### ISSUE TITLE
Azure__SignalR__StickyServerMode

### ISSUE THREAD

**Issue by Tommigun1980** [Azure/azure-signalr#1002]
Hi.

Should Azure__SignalR__StickyServerMode be turned on or off when using the SignalR service - https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-3.1#sticky-sessions says no, but the auto-generated app service keys have set "Azure__SignalR__StickyServerMode" to "Required".

If it is not required - what is the value to enter into "Azure__SignalR__StickyServerMode", is it "NotRequired" or what is it?

Thanks.

**Comment by vicancy** [comment]
For blazor apps it is `Required`, for other SignalR scenarios, it is not suggested.

**Comment by Tommigun1980** [comment]
> For blazor apps it is `Required`, for other SignalR scenarios, it is not suggested.

Thanks for the answer. So what is the value to enter into Azure__SignalR__StickyServerMode? Only "Required" is documented, but not its inverse. And I'd rather leave the key there to be explicit.

Thanks.

**Comment by vicancy** [comment]
Please check it here https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#serverstickymode

**Comment by Tommigun1980** [comment]
> Please check it here https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#serverstickymode

Thank you. There's lots of documents mentioning "Required" but I hadn't seen that one. It might make sense to combine the documents into one place at some point as the docs are extremely spread out atm.

One more question - the document you linked to says this of "Preferred": "This one can be useful when your scenario is send to connection". What does 'send to connection' mean? If I predominantly send to Groups, does it count as 'send to connection', which case the option "Preferred" would probably yield best performance?

Thanks again.

**Comment by Tommigun1980** [comment]
I don't know what the document means with send to connection as it's not mentioned anywhere else so it's not an established term. All messages go via a connection, or does it mean sending to a connection id (as opposed to a group for example)? In that case why would "Preferred" be better for that but not for groups? I'm so confused by the documentation.

But yeah, ultimately I just want to know if I mainly send messages to groups, where a group in my context is a single account (with all active devices in the same group), is "Preferred" or "Disabled" better?

Thanks.

**Comment by vicancy** [comment]
> send to connection

Yes, it is sending to a connection id specifically

> if I mainly send messages to groups, where a group in my context is a single account (with all active devices for an account in the same group), is "Preferred" or "Disabled" better? 

There is no difference for it, you actually don't need to set it, leave it as its default value is enough. 

Just curious, how you find out `Azure__SignalR__StickyServerMode` this variable since you are not using Blazor App?

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have any concerns about it.
