### ISSUE TITLE
ASP.NET SignalR Support

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-signalr#101]
This is an issue to track supporting ASP.NET SignalR as part of the SignalR Azure Service.

**Comment by vicancy** [comment]
- [ ] 1. Service side
  - [ ] Reconnect doesn’t work, we need to figure out what to do here. Do we indeed reconnect or do you return a non 200 status code so the client doesn’t reconnect.
  - [ ] We need to do message framing on the way in and on the way out (this one needs a bit more explanation)
  - [ ] Negotiate settings are hard coded, how do we want to handle the fact that settings set by the app isn’t propagated to the client (might require a SignalR change)
  - [ ] Do we copy all of the transport code from SignalR itself into the SDK to make this work? If the changes are in the core transport layer in SignalR. How is the service going to get these changes?

- [ ] 2. SDK side

**Comment by phil0007** [comment]
How is this issue tracking. What is the ETA for Azure SignalR support on .NET Framework?

**Comment by PinkPanda17** [comment]
Is there any update?

**Comment by vicancy** [comment]
We will have this feature public preview in Azure Service late this month. The announcement https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/ have some more details of the timeline.

**Comment by PinkPanda17** [comment]
Thanks For this :)

**Comment by vicancy** [comment]
2.4.0 preview for ASP.NET SignalR is released, which contains the support for Azure SignalR Service, please have a try.
https://blogs.msdn.microsoft.com/webdev/2018/10/04/announcing-asp-net-signalr-2-4-0-preview-1/
