### ISSUE TITLE
Support strongly typed Hub Clients

### ISSUE THREAD

**Issue by lfshr** [Azure/azure-signalr#1033]
### Is your feature request related to a problem? Please describe.
The Hub class allows for the use of a strongly typed Hub client. It would be great if the Azure SignalR service could also support the same! 

### Describe the solution you'd like
A new interface should be created to allow for this in `Microsoft.Azure.SignalR.Management`:
```
public interface IServiceHubContext<T> : IHubContext<Hub, T>
...
```

### Additional context
Source: https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.1#strongly-typed-hubs

Directly related to https://github.com/Azure/azure-functions-signalrservice-extension/issues/131

**Comment by lfshr** [comment]
Open branch here: https://github.com/lfshr/azure-signalr/tree/lfshr/strongly-typed-clients

Be happy for some early feedback. There's some duplication I'm not so keen about.
I'm away for a week so wont be any more work done this week.

**Comment by naster01** [comment]
It's a must feature in C# Blazor. Will look into your solution.

**Comment by Y-Sindo** [comment]
Will be supported in the next release.
