### ISSUE TITLE
Struggling to use Management SDK transient connection

### ISSUE THREAD

**Issue by lbargery** [Azure/azure-signalr#1041]
### Describe the bug
We've been using SignalR REST API for a long time, but just have some custom code (which I think was originally part of this project) to do this. We essentially take the connection string and split it into a URL and an access token then just use a normal http client to make the call. I've been wanting to switch to using the management SDK for a while, but when I turn it on in production (we have quite a high volume of calls) I get loads of exceptions coming out. 

### To Reproduce
Have linked a small github repo which just has the code required for the Azure function project in it [here](https://github.com/lbargery/signalr-function). Would prefer if possible to keep private and invite people to this though. At the moment I haven't even tried using persistent connection (which is what most of the code around semaphores is there to support). Current logic is that queue trigger picks up work and then broadcasts one of Rest API, transient or persistent connection. Not sure if this problem only occurs when large volumes of traffic are going through - we have around 1.4M invocations a day currently, each with multiple users -> multiple ASRS REST calls.

### Exceptions (if any)
I get a long aggregate exception like the one below with many URLs in it (all are valid Guids for our users, have checked this)
```
One or more errors occurred. (Unable to access SignalR service. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Please make sure the endpoint or DNS setting is correct. Request Uri: https://MYSIGNALR_URL.service.signalr.net/api/v1/hubs/practicehub/users/GUID) (Unable to access SignalR service. 
```

Further exceptions on Sentry:
```
Microsoft.Azure.SignalR.Common.AzureSignalRInaccessibleEndpointException
```
```
System.Net.Http.HttpRequestException
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

### Further technical details
- Tried to use management sdk 1.5

**Comment by vicancy** [comment]
Would you mind adding @wanlwanl and @vicancy (me) to the private repo?

**Comment by lbargery** [comment]
> Would you mind adding @wanlwanl and @vicancy (me) to the private repo?

Added both of you - let me know any issues or if the code doesn't make sense. Thanks!

**Comment by wanlwanl** [comment]
@lbargery Could you add a readme on how to run th app to trigger the error.

About "trasient" mode, management sdk doesn't establish a connection to ASRS (azure SignalR service), it simply sends http request to call ASRS's REST api. Only "Persistent" mode will establish websockets connections to ASRS, it's much more effecient.

**Comment by wanlwanl** [comment]
Could you email me your ASRS's resource ID to wanl [at] microsoft.com ? Could you also try the [sample](https://github.com/Azure/azure-functions-signalrservice-extension/tree/master/samples/simple-chat/csharp/FunctionApp) to see if your ASRS work or not?
> You can send messages using this [web page](https://github.com/Azure/azure-functions-signalrservice-extension/blob/master/samples/simple-chat/content/index.html)

**Comment by lbargery** [comment]
> wanl

Just emailed you this!

**Comment by lbargery** [comment]
> @lbargery
> About "trasient" mode, management sdk doesn't establish a connection to ASRS (azure SignalR service), it simply sends http request to call ASRS's REST api. Only "Persistent" mode will establish websockets connections to ASRS, it's much more effecient.

Have added a README to the repo which should make it clearer. With regards to above message, I'm aware the persistent should be better than transient in long run. However, my current problem is that I can't even switch transient on since it gives lots of errors. What I don't understand is that the transient code path should be very similar to my manual REST code.

You may not see an error with my repo though, since the volumes are very different...(unless you simulate 10,000s of items in the queue)

**Comment by wanlwanl** [comment]
I use this to enque messages
```
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Queue;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace signalr_function_queue
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var cloudStorageAccount = CloudStorageAccount.Parse("UseDevelopmentStorage=true");
            var devClient = cloudStorageAccount.CreateCloudQueueClient();
            var queueName = "signalr-items";
            var queue = devClient.GetQueueReference(queueName);
            await queue.CreateIfNotExistsAsync();


            await Task.WhenAll(from i in Enumerable.Range(0, 10000)
                               select Task.Run(async () =>
                                {
                                    await queue.AddMessageAsync(new CloudQueueMessage(@"
{
  ""Method"": ""Test"",
  ""Arguments"": [],
  ""UserIds"": [
    ""03192249 -AA47-4C3F-8FB4-8CC0CD3C3F54"",
    ""F2383F40 -05A8-431B-94A1-B5C51D0903E2""
  ]
}
"));
                                }));
        }
    }
}

looks normal locally. 
Could you reproduce again and provide the problem start time (including time zone) to me? I'm going to check your ASRS instance.
```

**Comment by lbargery** [comment]
The original problem happened at Aug 25, 2020 3:52:01 PM UTC. I can try and reproduce again today by changing the settings our function. Will let you know what happens later today

**Comment by wanlwanl** [comment]
Hi @lbargery have you reproduce the problem on your local machine instead of azure machine? I think the problem might be [intermittent outbound connection errors in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors), since azure function is rely on azure app service. If so, I think the workaround is to use persistent mode.

**Comment by lbargery** [comment]
> Hi @lbargery have you reproduce the problem on your local machine instead of azure machine? I think the problem might be [intermittent outbound connection errors in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors), since azure function is rely on azure app service. If so, I think the workaround is to use persistent mode.

I'm happy to try persistent mode and see what happens. This wouldn't explain why my ```LegacyServiceManager``` which uses the REST API works happily though with no errors. It should be that this code is largely exactly the same as the Transient connection yet the Management SDK does error (not for every call worth noting)

**Comment by lbargery** [comment]
I just now in production changed ```UseSignalRLibrary``` to true. Almost immediately got loads of errors of Sentry of

```
One or more errors occurred. (Unable to access SignalR service. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Please make sure the endpoint or DNS setting is correct.
```

**Comment by lbargery** [comment]
(Timestamp of error was 13:22 UTC and note not had a single error from the hand written REST API code all day)

**Comment by lbargery** [comment]
This is what I see in application insights from the working REST API code
![image](https://user-images.githubusercontent.com/48315337/93900948-e3f2a480-fced-11ea-9870-04f07075c855.png)

This is what I see when the transient connection errors
![image](https://user-images.githubusercontent.com/48315337/93901229-359b2f00-fcee-11ea-8815-ce71a80b2f02.png)

**Comment by wanlwanl** [comment]
@lbargery 

I found for Management sdk you are using `serviceHubContext.Clients.Users(userIds).SendCoreAsync(...)`
Since `Transient` mode, the sdk will only call the REST API [Broadcast a message to all clients belong to the target user](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#post-broadcast-a-message-to-all-clients-belong-to-the-target-user). We don't have a REST API for a list of multiple users. So the number of requests equals to the number of userIds.

And you retry for the whole user list if there's a fail in all these request. So, it probably make your requests much more than simply using REST API. 

I check ASRS log, I found during 13:22(+- 2min) UTC, in this 5 min, ASRS received 357400 request, therefore, about 901,786/second. Could you double check whether it's expected or not?

To the With/Without Management SDK the same, use `serviceHubContext.Clients.User(userIds).SendCoreAsync(...)` instead od `Users(...)`, and only retry for the failed one.

If you change to `Persistent` mode, you don't need to worry about it, since we use websockets in this mode, and a single message, that is, [`MultiUserDataMessage`](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Protocols/MulticastDataMessage.cs#L79), is used to send to ASRS. Therefore, `Persistent` mode is much better in your scenario.

**Comment by lbargery** [comment]
This makes sense - will try to update code today and see what happens

**Comment by lbargery** [comment]
Also would be interested to know if below code looks sensible for using the transient connection on the function. I create one instance of this class (so a static field) for the lifetime of the function app. My understanding is that I'd want to do this so that I don't have lots of Http Clients created. Would I ever need to call dispose? Again my understanding was that I don't with the transient connection.

```
    public class TransientServiceManager
    {
        private readonly SemaphoreSlim _semaphoreSlim = new SemaphoreSlim(initialCount: 1, maxCount: 1);
        private IServiceHubContext? _practiceHubContext;

        public async Task SendSafe(string connectionString, SignalRPushData myQueueItem)
        {
            if (_practiceHubContext == null)
            {
                try
                {
                    await _semaphoreSlim.WaitAsync();
                    if (_practiceHubContext == null)
                    {
                        var connectionBuilder = new ServiceHubContextBuilder(connectionString, ServiceTransportType.Transient);
                        _practiceHubContext = await connectionBuilder.GetPracticeHubContext();
                    }
                }
                finally
                {
                    _semaphoreSlim.Release();
                }
            }

            foreach (var userId in myQueueItem.UserIds)
            {
                await PerformSafe.PerformTask(async () =>
                {
                    var clientProxy = _practiceHubContext.Clients.User(userId);
                    await clientProxy.SendCoreAsync(myQueueItem.Method, myQueueItem.Arguments);
                }, "Failed to send message over transient connection");
            }
        }
    }
```

**Comment by wanlwanl** [comment]
No you don't need to call dispose. By the way, I'm wondering why you write your own `ServiceHubContextBuilder` `ServiceManager`? Looks like you can simply store the `IServiceHubContext` and send messages whenever you want.

**Comment by lbargery** [comment]
> No you don't need to call dispose. By the way, I'm wondering why you write your own `ServiceHubContextBuilder` `ServiceManager`? Looks like you can simply store the `IServiceHubContext` and send messages whenever you want.

I think that was just so I could do some unit testing - nothing more!

**Comment by lbargery** [comment]
It *seems* to be working okay now! I got a bunch of
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
```
when I first did the release but quiet since then. Will monitor for next day or so and then I think we can close this. Will aim to move to persitent connection after this. Thanks!

**Comment by lbargery** [comment]
Things are definitely better - have been using Management SDK since 4pm today without too many issues. Have had a few errors through:
Number 1 (some failed):
![image](https://user-images.githubusercontent.com/48315337/94203449-58c50a80-feb7-11ea-9fae-d7858e9ba283.png)
Number 2 (looks like all failed):
![image](https://user-images.githubusercontent.com/48315337/94203500-6bd7da80-feb7-11ea-9c5a-710a854a192d.png)

This is probably okay...But still slightly odd since saw almost 0 errors before with the hand written REST code. Any idea what could be causing this or if I should just add retry?

**Comment by wanlwanl** [comment]
Have count for the requests number? Are the number the same? When I checked the timestamp you provided, only 200+/second reuqests found, but the new one is 900K. So could you double check if the number of request are similar? Maybe it's due to the requests increasement.

It maybe the problem: https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors
You can try private link to solve this problem: https://docs.microsoft.com/en-us/azure/azure-signalr/howto-private-endpoints

**Comment by lbargery** [comment]
I think the request count is okay...I'm not sure why the outbound connections would be an issue though given the code I had before worked fine. It also seems like the new code has a memory leak

![image](https://user-images.githubusercontent.com/48315337/94259778-e855d200-ff26-11ea-9793-cd93abf72286.png)

Not quite sure how that's leaking memory from my code in: https://github.com/Azure/azure-signalr/issues/1041#issuecomment-698225616

**Comment by wanlwanl** [comment]
Since 5xx status code doesn't comes from ASRS. And your [symptom](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors#symptoms) looks like so, I recommend you create a ticket to azure function team in portal to let them verify it.

When the memory goes up, what's the graph of requests? Is it getting more and more?

**Comment by lbargery** [comment]
The memory leak *seems* to have disappeared with latest version of the package - realised I was using 1.4.3 and not 1.5.1

I can create a ticket with Azure...That doesn't explain why using my old REST code though I never got these exceptions and with the management SDK I do. I got an exception at 8pm last night when request rate is low.

**Comment by wanlwanl** [comment]
Hi @lbargery 
I made a test to use Management SDK v1.4.3 to send message repeatly. Check it out https://github.com/wanlwanl/AzureSignalR-samples/tree/wanl/1041/samples/Management/MessagePublisher.
You can add you connection string this way: `dotnet user-secrets set Azure:SignalR:ConnectionString "<Connection String>"`
Then debug the app in VS, and take a look at *Process Memory* in *Diagnostic Tools* windows.
It seems no memory leak in Management SDK for Transient mode.

**Comment by lbargery** [comment]
I can try and see if I can get diagnose it locally - it's definitely there though on 1.4.3 for my function in Azure and purely just the package upgrade fixed it so not too worried about this. Still getting exceptions at odd times of day where I didn't use to and traffic isn't too high

At 6:35 UTC got another

```
Microsoft.Azure.SignalR.Common.AzureSignalRInaccessibleEndpointException
Unable to access SignalR service. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Please make sure the endpoint or DNS setting is correct. 
```

I don't mind raising a ticket in Azure - but all the metrics on connection count etc look totally fine and given when I had the hand written REST code before I didn't get any exceptions I'm not sure this makes sense that it's the app service plan.

**Comment by lbargery** [comment]
Also I do see some memory increase locally on 1.4.3, not sure if this helps

![image](https://user-images.githubusercontent.com/48315337/94413612-39f29c80-0173-11eb-9274-d720f1c31de1.png)

**Comment by lbargery** [comment]
Actually, I am still seeing large memory footprint on 1.5.1

![image](https://user-images.githubusercontent.com/48315337/94414028-bf764c80-0173-11eb-82a1-161bb2999ab3.png)

That's 30 days worth of data

**Comment by wanlwanl** [comment]
What about the [project]( https://github.com/wanlwanl/AzureSignalR-samples/tree/wanl/1041/samples/Management/MessagePublisher) I provided? Did you see any memory leak there? If it doesn't leak memory, the problem is probably in your business logic.

**Comment by wanlwanl** [comment]
Can you update the repo you shared with us?  I need to get the latest code so that I can help. Would you mind schedule a remote meeting, what's your working hours (include time zone)?

**Comment by lbargery** [comment]
- Have updated the repo with the new code so you can see
- Trying to get memory dump out of azure portal too since this should be easier to see the problem
- Working hours are 8am-8pm British Summer time, happy to do remote meeting

**Comment by lbargery** [comment]
Interestingly I did a restart and since then the memory is quite steady. We have a surge of traffic on this function around 7-10am so it's almost like the increased traffic caused it to spike

![image](https://user-images.githubusercontent.com/48315337/94433502-53eea800-0190-11eb-9d06-8427289b5093.png)

**Comment by lbargery** [comment]
Okay - have found something interesting... When my exception goes off this morning at 7:35 BST, that's the exact same time the memory spikes to 1Gb above. This is the 

```
Unable to access SignalR service. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Please make sure the endpoint or DNS setting is correct. 
```

Is there some state/code path that changes when this exception goes off?

**Comment by lbargery** [comment]
I might be barking up the wrong tree..But in ```RestClient.cs``` you have this

```
var httpClient = HttpClientFactory.CreateClient();
            var request = BuildRequest(api, httpMethod, productInfo, methodName, args);
            HttpResponseMessage response;

            try
            {
                response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
            }
            catch (HttpRequestException ex)
            {
                throw new AzureSignalRInaccessibleEndpointException(request.RequestUri.ToString(), ex);
            }

            if (handleExpectedResponseAsync == null)
            {
                await ThrowExceptionOnResponseFailureAsync(response);
            }
            else
            {
                if (!await handleExpectedResponseAsync(response))
                {
                    await ThrowExceptionOnResponseFailureAsync(response);
                }
            }

            response.Dispose();
```

Why is the response.Dispose not inside a finally?

**Comment by lbargery** [comment]
Are there any possible memory leaks in RestClient.cs SendAsync?

**Comment by wanlwanl** [comment]
> it's almost like the increased traffic caused it to spike
Looks normal. I asked for it before "When the memory goes up, what's the graph of requests? Is it getting more and more?"

It seems that you think the Management SDK causes the problem, I suggest to use Management SDK to troubleshooting to isolate the impact from function runtime.

> Are there any possible memory leaks in RestClient.cs SendAsync?
Do you have any findings?

**Comment by lbargery** [comment]
So for the 1Gb memory peak in the morning, the number of request *does* go up. However, I would not expect it to go anywhere near 1Gb of memory and it never did before when using the code I'd written to call the ASRS REST API myself. I also find that just during the middle of the day, when the request count is steady, the memory goes up slowly (and you can see the GC running in the spikes)

![image](https://user-images.githubusercontent.com/48315337/94533285-ddf14c00-0236-11eb-933c-1f87335ea429.png)

The reason I think it's the SDK which is causing the issue is that the rest of my code (and using Azure function) has stayed the same, I've just swapped from my own code calling the REST API to the SDK's code (unless you see a problem with my TransientManager.cs class but I only create one static instance of this)

**Comment by wanlwanl** [comment]
![memory](https://user-images.githubusercontent.com/38236089/94547189-86c49900-0281-11eb-9be6-f087236f302d.png)
Looks stable for memory using your code locally with Mangement SDK in trasient mode

**Comment by lbargery** [comment]
So you think it's a specific Azure hosted function issue?

**Comment by wanlwanl** [comment]
At least the shared code running with stable memory. I still think ask azure function team to help is helpful.

**Comment by lbargery** [comment]
Am currently chasing with Azure support team. The function never seems to out of memory and crash like memory leaks I've had before, but does go to often go very high (1Gb) during the day. Even just now (when we have almost no usage of our product), it's varying a lot

**Comment by wanlwanl** [comment]
But the code you send me has a stable memory usage when I run it, you can also run it and use a perf monitor to monitor it on your PC. So I think you can troubleshoot on other parts except for the code you sent to me. Is your business code requires large memory? What's the comment for high memory usage from azure support team? Is it caused by function apps scaling?

**Comment by lbargery** [comment]
Latest from Azure team is that they see the large uses in memory as "free" objects. They say this is caused by objects being placed on the large object heap and then collected, but not compacted - so I end up with lots of "free" objects. Any idea how this could happen?

Still the memory profile as very erratic 
![image](https://user-images.githubusercontent.com/48315337/96586583-1be30c80-12d9-11eb-998f-ddc4defbc549.png)

And not related to function execution count at all
![image](https://user-images.githubusercontent.com/48315337/96586648-30bfa000-12d9-11eb-9790-6cc7b48ae5ea.png)

I've also still getting some of the exceptions I saw before happen every day at some point. Both

1.
```
Unable to access SignalR service. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Please make sure the endpoint or DNS setting is correct.
```

2.
```
Azure SignalR service runtime error.
```
