### ISSUE TITLE
AddAzureSignalR() extension methods allowing to change connection string are not working

### ISSUE THREAD

**Issue by matomato13** [Azure/azure-signalr#1048]
### Describe the bug
When using `AddAzureSignalR("<connection_string>")` or `AddAzureSignalR(o => o.ConnectionString = "<connection_string>")`, the connection string doesn't seem to be used and we get the exception below every few seconds. 

As a workaround, we added the connection string as `Azure:SignalR:ConnectionString` in the Azure configuration and used the `AddAzureSignalR()` method.

### To Reproduce
Use `AddAzureSignalR("<connection_string>")` or `AddAzureSignalR(o => o.ConnectionString = "<connection_string>")`.

### Exceptions (if any)
```
No connection string is specified. Skip scale operation.

Microsoft.Azure.SignalR.Common.AzureSignalRConfigurationNoEndpointException: No connection string was specified.
   at Microsoft.Azure.SignalR.ServiceEndpointManagerBase.GetValuableEndpoints(IEnumerable`1 endpoints)
   at Microsoft.Azure.SignalR.ServiceEndpointManagerBase.ReloadServiceEndpointsAsync(ServiceEndpoint[] serviceEndpoints, TimeSpan scaleTimeout)
```

### Further technical details
- Your Azure SignalR SDK version (1.5.1)
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR`  (3.1.8)
- Your SignalR Client SDK version (*)

**Comment by JialinXin** [comment]
@matomato13, you're triggering dynamic add/remove service endpoints at runtime, that when any configuration like appsettings or secret store has changes. Looks like some changes in your app triggered the process and the connection string set in `AddAzureSignalR` is not able to recognize in the reload process. It doesn't have any bad effect to your running app server, that the connections are still active.

We're able to repro this and will fix the issue. Thanks for reporting the issue.
