### ISSUE TITLE
How to generate accesstoken for SignalR Rest APIs

### ISSUE THREAD

**Issue by nebhagat** [Azure/azure-signalr#1066]
### Describe the bug
Hi,

I was redirected to these [samples](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless) from this [doc](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-rest-api#build-and-run-the-sample) for signalR REST Api reference.

This sample has deprecation warning stating not to generate access token by themselves, but to use `Management SDK`.
This SDK is only available in C# and my backend is in node.js.

I tried using signalR input binding in azure functions, [ref](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-input?tabs=javascript) and tried using access token generated by negotiation endpoint, but it threw authorization error.

What is the best way to generate access token for signalR Rest APIs in node js stack?

**Comment by vwxyzh** [comment]
Here is the [document](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#authentication).

> Should be the SAME as your HTTP request url, trailing slash and query parameters not included. For example, a broadcast request's audience should look like: https://example.service.signalr.net/api/v1/hubs/myhub.

**Comment by nebhagat** [comment]
Thanks @vwxyzh ,

This should solve my issue.
My worry was deprecation warning on github samples.
