### ISSUE TITLE
OnConnectedAsync randomly missing

### ISSUE THREAD

**Issue by Mimetis** [Azure/azure-signalr#1068]
### Describe the bug
When using Azure SignalR Services , sometimes Hub methods and even `OnConnectedAsync()` are not called, after a `connection.start()` is launched from the client.

![image](https://user-images.githubusercontent.com/4592555/95895264-b0ee7e80-0d8a-11eb-9975-dae29c39e5a4.png)

As a comparison, using SignalR *without* Azure SignalR Sercices, is working pretty well:

![image](https://user-images.githubusercontent.com/4592555/95895225-9fa57200-0d8a-11eb-88a3-ae4999dd4163.png)

### To Reproduce

The hub is pretty straightforward:

```
    public class JobHub : Hub
    {
        public JobHub()
        {

        }

        public override async Task OnConnectedAsync()
        {
            var user = Context.GetHttpContext()?.User?.GetObjectId();

            if (!string.IsNullOrEmpty(user))
                await Groups.AddToGroupAsync(Context.ConnectionId, user);

            Debug.WriteLine($"[{DateTime.Now}] Called OnConnected");
            await base.OnConnectedAsync();
            await this.Clients.Caller.SendAsync("feedback", "[SERVER] : OnConnectedAsync called");
        }

        public override async Task OnDisconnectedAsync(Exception exception)
        {
            var user = Context.GetHttpContext()?.User?.GetObjectId();

            if (!string.IsNullOrEmpty(user))
                await Groups.RemoveFromGroupAsync(Context.ConnectionId, user);

            Debug.WriteLine($"[{DateTime.Now}] Called OnDisconnected");
            await base.OnDisconnectedAsync(exception);
        }

    }
```
I'm just sending back to the `Caller` a signalr message for debugging purpose.
The javascript side is pretty straightforward as well:

```
<script>

    $(() => {

        let c = new console2($("#console"), $('div.docking-form'));

        let connection = new signalR.HubConnectionBuilder()
            .withUrl('/notifications')
            .withAutomaticReconnect()
            .configureLogging(signalR.LogLevel.Trace)
            .build();

        connection.onreconnecting(error => { c.log(error) });

        connection.on("feedback", (message) => c.appendWarning(message));

        c.log("Ready to deploy.")
        c.log("-----------------------")

        let startButton = $('#start');
        let stopButton = $('#stop');
        let clearButton = $('#clear');

        clearButton.click(async (evt) => {
            evt.preventDefault();
            await c.clearConsole();
        });


        startButton.click(async (evt) => {
            evt.preventDefault();

            if (connection.state == signalR.HubConnectionState.Connected) {
                await connection.stop();
                c.log("connection closed");
            }

            try {

                if (connection.state != signalR.HubConnectionState.Connected) {
                    await connection.start();
                    c.log("connection started");
                }

                connection.onclose(error => {
                    if (error && error.message) {
                        c.error(error.message);
                    }
                });

            } catch (err) {
                c.error(err.message);
            }
        });

        stopButton.click(async (evt) => {
            evt.preventDefault();
            if (connection.state != signalR.HubConnectionState.Disconnected) {
                await connection.stop();
                c.log("connection closed");
            }
        });

    });


</script>
```

### Exceptions (if any)

No exceptions are raised, everything seems to be normal in the browser console:

![image](https://user-images.githubusercontent.com/4592555/95895712-5c97ce80-0d8b-11eb-8769-858c0705c8ab.png)

### Further technical details
- Your Azure SignalR SDK version : Lastest version
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` : Latest version
- Your SignalR Client SDK version:  Latest version

It seems to be related with #115 but the issue seems to be closed and is pretty old, now

**Comment by vwxyzh** [comment]
How many app server instances when using Azure SignalR service?
Azure SignalR service will route the client to one of your app server instance by default.
That means if you have 2 app server connected to service (with the same hub name and same application name), then your instance will only get 1/2 clients.
You can use different hub name or application name to avoid this.
Or you can turn on [sticky](https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#serverstickymode).

**Comment by Mimetis** [comment]
Seems using Sticky session is working nicely.
BUT I have only one app server running (on my local machine, using visual studio and developing a new project)
So Sticky is OK, but I have only one app server.
