### ISSUE TITLE
Back-end loses connection with Azure SignalR-service

### ISSUE THREAD

**Issue by R-zr** [Azure/azure-signalr#1095]
### Describe the bug
In the last couple of days we experience a high amount of calls (send from our SignalR application) not ending up at our SignalR clients. The methods on the client never seem to get invoked even though the WS connection state is "Connected".

After having enabled more detailed logging we seem to understand a bit more about what is going on. Our (JS) clients seem to keep their websocket connection with the Azure SignalR-service but the connection between our back-end and the Azure SignalR-service itself drops or stalls.

SignalR JS-client <---WS---> Azure SignalR-service <---X---> .NET Core 3.1.* back-end

At some point the connection seems to restore itself only to disconnect later again. Could it be that when we run the following line in our back-end from instance "one":

`await this.context.Group("FooGroup").SendAsync("AddOrder", someObject)`

This might not arrive at the clients in group "FooGroup" when instance "one" has lost connection with the Azure SignalR-service? See the log below. This has serious impact in our trust of messages being delivered.

### Log entries
The following log has been created on our SignalR application.

Note that use auto-scaling on our Azure App-instances and we might vary between 1 and 15 instances. Here are some lines from our logs. This is one of our instances, I noticed the same errors also in the log of the other instances around the exact same times. A couple out of the ~15 instances had no issues.

`[ERROR] Microsoft.Azure.SignalR.ServiceConnection|Connection to '(Primary)https://xxx.service.signalr.net' was dropped, probably caused by network instability or service restart. Will try to reconnect after the back off period. Error detail: e686e9b2-87ec-4c6d-af29-be4b904178b7. Id: The remote party closed the WebSocket connection without completing the close handshake.. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..`

This happend at `2020-10-30 15:00:23.9607`

`[ERROR] Microsoft.Azure.SignalR.ServiceConnection|Service timeout. 30000.00ms elapsed without receiving a message from service. Id: 72bf96e6-4ee6-4b48-bc2c-850a76b11a68`

This happend at `2020-10-30 15:00:25.5991`.

It happend again ~20 minutes later:

`[ERROR] Microsoft.Azure.SignalR.ServiceConnection|Connection to '(Primary)https://xxx.service.signalr.net' was dropped, probably caused by network instability or service restart. Will try to reconnect after the back off period. Error detail: 2bbcb979-c84e-4f26-8bf7-6a766e9131d4. Id: The remote party closed the WebSocket connection without completing the close handshake.. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..`

`[ERROR] Microsoft.Azure.SignalR.ServiceConnection|Service timeout. 30000.00ms elapsed without receiving a message from service. Id: 291a6a6f-2ff3-4d41-b741-684737326233 |url: |action: `

### Further technical details
- Azure SignalR SDK version: `1.6.0`
- Your Server ASPNETCORE version or Assembly version of Microsoft.AspNetCore.SignalR: `3.1.9` (SDK .NET Core is `3.1.401`)
- Your SignalR Client SDK version: `3.1.9 (JavaScript @microsoft/signalr)`

**Comment by vicancy** [comment]
> This might not arrive at the clients in group "FooGroup" when instance "one" has lost connection with the Azure SignalR-service?

Yes, it is possible. `await this.context.Group("FooGroup").SendAsync("AddOrder", someObject)` should throw if it fails to send out. You can catch and retry when it throws. Do you see error logs containing `ServiceConnectionNotActiveException`?

> Microsoft.Azure.SignalR.ServiceConnection|Connection to '(Primary)https://xxx.service.signalr.net' was dropped, probably caused by network instability or service restart

As stated [here](https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#server_connection_drop), server connections may experience network connectivity issues, or, on a regular basis there are new version releases for the Azure SignalR Service, and sometimes the Azure wide OS patching or upgrades or occasionally interruption from our dependent services. The server connections have *Always Reconnect* strategy so that it can recover as soon as possible.

**Comment by vicancy** [comment]
Feel free to reopen the issue if there are any updates.
