### ISSUE TITLE
Azure SignalR autoscale

### ISSUE THREAD

**Issue by shankarmohannamakkal** [Azure/azure-signalr#1096]
### Is your feature request related to a problem? Please describe.
I am trying to identify a solution for Azure SignalR auto-scaling

### Describe the solution you'd like
SignalR service currently only supports 1000 concurrent connections per service instance per unit. If the number of concurrent SignalR connections exceed 1000, the service instances unit will have to be increased manually, and reduced manually as the users decrease.

Looking for the suitable solution to auto-scale (scale up and scale down) the SignalR service instances based on the demand.

Please give suggestions or ideas about this. Thanks.

**Comment by yjin81** [comment]
Here is a guidance about [how to scale an Azure SignalR Service instance](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-signalr). Is this what you need?

**Comment by shankarmohannamakkal** [comment]
I am looking for auto-scale up and down based on the user connections.

**Comment by vwxyzh** [comment]
Currently, scale-in/out will cause client connections drop, so we won't give auto-scale.
But we are working on smooth scale in/out, when it done, we will provide auto-scale.

**Comment by shankarmohannamakkal** [comment]
> Currently, scale-in/out will cause client connections drop, so we won't give auto-scale.
> But we are working on smooth scale in/out, when it done, we will provide auto-scale.

Ok

**Comment by mmulhearn** [comment]
We are also very interested in auto-scaling Azure SigR and understand the issue you face.  With that said, is it actively being worked on and/or on any sort of roadmap?

**Comment by zackliu** [comment]
@mmulhearn @shankarmohannamakkal We've already worked on it and overcome some critical issues. I can't give the ETA of auto-scaling but we can provide a smoother (no connection drops) scaling experience first.

**Comment by mmulhearn** [comment]
@zackliu when is that expected to release?

**Comment by zackliu** [comment]
If you want to try the new scaling experience, please create new resources in EastUS or WestUS2 and have a try. It's still in preview in limited regions and haven't been announced.
In the new scaling experience, the scaling is very fast even from unit 1 -> 100. Connections won't drop immediately during scaling. We can guarantee that we won't drop connections when you're in high server load. So if your service is reaching limit and scale up, the experience should be better. But if you're in very low server load, you may meet connection drops. The experience may change in future. We will try our best to avoid any connection drops.
Welcome any feedbacks on the new scaling experience.

**Comment by shankarmohannamakkal** [comment]
@zackliu Tried creating a new SignalR resource in EastUS. Is there an option for switch on the auto-scaling or by default this auto-scale will work?

**Comment by zackliu** [comment]
@shankarmohannamakkal No, there's no auto scaling now. What we have currently is a new scaling experience, which is smoother and faster. The auto scaling must base on a smoother scaling experience. Thus, we're testing the new scaling experience and add auto scaling feature once it's mature.

**Comment by hora7ce** [comment]
Any updates on this?  How is the preview going? any plans for GA?

**Comment by zackliu** [comment]
@hora7ce It's internal testing. We're integrating with [Azure Autoscale](https://docs.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-overview) and you can have a consistent autoscale experience among Azure. For the public preview date, I will keep updating here once I can give that.

**Comment by zackliu** [comment]
By the way, for the new scaling experience I mentioned before, we've enabled in all regions. For all the newly created resource, scaling is seamless. Which means no connection drop during scaling.

**Comment by wouterjanssens** [comment]
> By the way, for the new scaling experience I mentioned before, we've enabled in all regions. For all the newly created resource, scaling is seamless. Which means no connection drop during scaling.

Is re-creating our existing SignalR service the only way to get the smoother experience? If so we will need to plan a maintenance window for that. An upgrade script would be a better solution. Any idea on that?

**Comment by tonycoelho** [comment]
> @hora7ce It's internal testing. We're integrating with [Azure Autoscale](https://docs.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-overview) and you can have a consistent autoscale experience among Azure. For the public preview date, I will keep updating here once I can give that.

@hora7ce any updates on this? When is this expected to be in private or public preview?

**Comment by zackliu** [comment]
Q1 2022 is the estimated time for public preview.

**Comment by WilsonYesidRiveraCasas** [comment]
Hi, I wrote this solution https://dev.to/wilsonyesidriveracasas/auto-scaling-azure-signalr-units-4e94

**Comment by MarcusU** [comment]
@zackliu I just noticed this article about the auto scaling setting, which is great news! However it mentions it's only available on the "Premium" pricing tier that is currently in public preview, but I can't find anything in the portal about switching to that tier, I only still see "Free" and "Standard".

https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-autoscale

Was the doc released prematurely?

**Comment by WilsonYesidRiveraCasas** [comment]
@MarcusU , The free tier is limited, but there is a way to configure autoscaling in standard tier. [https://dev.to/wilsonyesidriveracasas/auto-scaling-azure-signalr-units-4e94](https://dev.to/wilsonyesidriveracasas/auto-scaling-azure-signalr-units-4e94)

**Comment by zackliu** [comment]
Premium tier is not public released yet. We're preparing for that. It's expected to be public in March.

**Comment by zackliu** [comment]
Azure SignalR is supporting autoscale in Premium Tier. 
Please refer to docs: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-autoscale
