### ISSUE TITLE
Unable to read Azure:SignalR:ConnectionString from Azure App Service Configuration Application Settings

### ISSUE THREAD

**Issue by JoshLefebvre** [Azure/azure-signalr#1097]
### Describe the bug
I  am working on an Azure SignalR application and everything is working fine on my local machine when I set the following section in my appsettings.json:
```
 "Azure": {
    "SignalR": {
      "ConnectionString": "XXXXX"
    }
  }
```
And then initialize in my startup.cs as follows:
`services.AddSignalR().AddAzureSignalR();
`

However when I create the same environment variable in my Azure App Service using App Service>Configration>ApplicationSettings:
![image](https://user-images.githubusercontent.com/22512098/98051220-626c5700-1e01-11eb-8703-4ffbdf646667.png)

My application is unable to start and I get the following application error:

> System.ArgumentException: Connection string missing required properties endpoint and accesskey. (Parameter 'connectionString')
>    at Microsoft.Azure.SignalR.ConnectionStringParser.Parse(String connectionString)
>    at Microsoft.Azure.SignalR.ServiceEndpoint..ctor(String connectionString, EndpointType type, String name)

It is very strange because:
- I can log my connectionstring and it does appear. 
- When I hardcore my connection string onto the AddAzureSignalR() connectionstring parameter and deploy everything works fine. 
- When I add the connection string to my applicationsettings.json directly everything works fine,

It would seem that azuresignalR is unable to pickup this environment variable, despite also being able to see it via the Kudo Appsettings page as Azure:SginalR:ConnectionString.

### Further technical details
- Microsoft.Azure.SignalR (1.5.1)

**Comment by JoshLefebvre** [comment]
When I deploy a sample SignalR service to an AppService directly from Visual Studio it automatically create the following Application Settings variables:
![image](https://user-images.githubusercontent.com/22512098/98051959-fb4fa200-1e02-11eb-9b75-bdf725ac65cf.png)

When I try to use these same application settings in my codebase and deploy via Az DevOps pipeline it doesn't work

**Comment by JoshLefebvre** [comment]
Possibly related to https://github.com/Azure/azure-signalr/issues/1048 as I also tried setting the connection string via ConfigOptions

**Comment by Y-Sindo** [comment]
ASP.NET Core uses [EnvironmentVariablesConfigurationProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.environmentvariables.environmentvariablesconfigurationprovider?view=dotnet-plat-ext-3.1) to load configuration from environment variables, from the reasons described [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables):
> The `:` separator doesn't work with environment variable hierarchical keys on all platforms. `__`, the double underscore, is:
> * Supported by all platforms. For example, the `:` separator is not supported by Bash, but `__` is.
> * Automatically replaced by a `:`

EnvironmentVariablesConfigurationProvider automatically replaces `__` with `:` . So when you configures connection string via environment variables, you should use `Azure__SignalR__ConnectionString` as the key. When you configures it via JSON file, you should use the origin key `Azure:SignalR:ConnectionString`.

**Comment by JoshLefebvre** [comment]
Yea that was it. I tried with the double underscore and worked! Thank you. First time I had tried it my connectionstring was malformed.
