### ISSUE TITLE
[QUESTION] Do I need to scale my Hub Server when scaling SignalR Service

### ISSUE THREAD

**Issue by RomanPavelko** [Azure/azure-signalr#1098]
Hi, I've been looking into Azure SignalR Service in order to solve our current issue where we exceeded available resources with thousands of active users on API that servers as SignalR Hub Server at the same time. It sounds like ASS is a good solution here due to its easy scaleability. I was able to integrate it in my dev environment. However without real volume testing and I want to understand the basics.

According to the documentation:
![image](https://user-images.githubusercontent.com/58891901/98055274-b166bc00-1e02-11eb-9287-ca69090a38c6.png)

If I scale my ASS to 2-3-10 units, how should my VM, where API is hosted, handle all those new websocket connections coming from multiple ASS units? Does it mean that I still need to scale my VM to multiple instances and ASS serves here as an orchestrator between them? Or ASS unit(s) have their own type of communication with Hub Server that doesn't necessarily matches amount of users?

**Comment by vicancy** [comment]
Traffic is multiplexed. Which means N client connections maps to 1 server connection. So whether or not scaling up the app servers depends on whether or not the current app servers can handle increased traffic, e.g. CPU usages for the app server can increase when more clients are connected. 

Here is a [performance guide for Azure SignalR Service](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-performance) FYI,

**Comment by RomanPavelko** [comment]
@vicancy thank you very much for this explanation. that is what I hoped it is doing.
