### ISSUE TITLE
Question: Read connection string from Azure KeyVault

### ISSUE THREAD

**Issue by mikesitch** [Azure/azure-signalr#1099]
All connections strings and keys are stored in AzureKeyVault and so I currently set the connection string via:

services.AddSignalR().AddAzureSignalR(options =>
{
    .... read connection string from key vault
    options.ConnectionString = connectionString;
});

My question is what is the recommended approach if the connection string can't be obtained, e.g. Key Vault is temporarily down?  Ideally I would like to be able to set the connection string when it is back up.  Of course, happy for SignalR to be disabled until that happens, i.e. degraded functionality.  Is this possible?

Only approach I see at the moment is to not use KeyVault for the connection string which would be a real shame as we store everything else there.

Appreciate any help.

**Comment by Y-Sindo** [comment]
Azure SignalR supports [reading configuration](https://github.com/Azure/azure-signalr/blob/1e362c25348d2c980ebdbd84acb40877a2d36f4f/src/Microsoft.Azure.SignalR/ServiceOptionsSetup.cs#L41) from different configuration provider, including Key Vault, JSON file and so on. Maybe you can [add Key Vault as a configuration provider](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#use-managed-identities-for-azure-resources) and also have your backup way. Configuration providers that are added later override previous key settings. The configuration is hot reload. I hope that this can help you.

**Comment by Y-Sindo** [comment]
FYI: [Azure Key Vault availability and redundancy](https://docs.microsoft.com/en-us/azure/key-vault/general/disaster-recovery-guidance)

**Comment by mikesitch** [comment]
Thank you will take a look.  

This question comes as recently our app service has been restarted overnight and the request to key vault has failed temporarily (other services show that this usually only lasts a few seconds or more).  As key vault isn't available the code currently throws an exception from AddAzureSignalR which means our app doesn't start up, hence we need to determine how we resolve this.

Hopefully hooking up the key vault as a configuration provider will work but this has to be resilient to key vault not being there, i.e. keep trying, if not we are no better off.

**Comment by Y-Sindo** [comment]
If I understand correctly, a retry logic for key vault client should help?

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have any concerns about it.

**Comment by vwxyzh** [comment]
BTW, you can also use msi, if your hub server is running in azure app service.
Followings are the samples of connection string with msi:
* System assigned:   `Endpoint=<your endpoint>;AuthType=aad;Version=1.0`
* User assigned:  `Endpoint=<your endpoint>;AuthType=aad;ClientId=<your client id>;Version=1.0`
