### ISSUE TITLE
Azure WebJob not sending message to Azure SignalR service

### ISSUE THREAD

**Issue by rachael-ross** [Azure/azure-signalr#1104]
### Describe the bug
I have an Asp.Net Core Api 3.1 and an Azure WebJob, both running on an Azure App Service. Both of them have a need to send notifications and neither will be receiving messages. To break it down:

 - I have a single instance of the Azure SignalR Service in the cloud that each app is pointed to.
   
  - The Hub class I've created is in a library that is referenced by both the Api and WebJob projects. 
   
  - Clients will only connect to the Hub via the Api.
   
  - Everything is working fine when the Api sends a message to connections, but the WebJob does not.

I **really don't** want to run the WebJob as a client because then I'd have to deal with auth. I just want it to run as another instance of the same Hub that will send messages to the same groups that the API does. Also, this WebJob is NOT a candidate to run as an Azure Function because it takes too long.

I'm missing something in how I'm configuring the WebJob as it appears it's not connecting to Azure SignalR. 

When the WebJob tries to send out a message, I get the following error: (I've not published yet to Azure so this is all happening on my local machine)

### To Reproduce
**WebJob Main:** 

    using System;
    using System.IO;
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using MyProject.Data;
    using MyProject.Hub;   
    using Microsoft.Azure.KeyVault;
    using Microsoft.Azure.Services.AppAuthentication;
    using Microsoft.Azure.Storage;
    using Microsoft.Azure.Storage.Blob;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.Extensions.SignalRService;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Configuration.AzureKeyVault;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using Microsoft.Extensions.Logging;

     public static IConfigurationRoot Configuration { get; protected set; }

        static async Task Main(string[] args)
        {    
            string buildConfig = "Development";           
            
            var builder = new HostBuilder()  
                .ConfigureWebJobs(b =>
                {
                    b.AddAzureStorageCoreServices();
                    b.AddTimers();                                     
                })
                .ConfigureAppConfiguration(config =>
                {                    
                    config.AddJsonFile($"appsettings.{buildConfig}.json", true, true);  
                    Configuration = config.Build();
                })                
                .ConfigureServices((hostContext, services) =>
                {                    
                    services.AddSignalR().AddAzureSignalR(options => 
                    {
                        options.ConnectionString = Configuration["Azure:SignalR:ConnectionString"];  
                    });            
                    
                    services.AddHostedService<ApplicationHostService>();                   
                    services.AddDbContext<MyDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("MyDatabase")));
                    services.AddScoped<MyDbContext>();     

               **// The NotificationService expects an injected MyDbContext and IHubContext<NotificationHub>**
                    services.AddScoped<INotificationService, NotificationService>();
                })
                .ConfigureLogging((context, b) =>
                {
                    b.AddConsole();
                });

            var host = builder.Build();
            using (host)
            {
                host.Run();
            }
        }
    }

**ApplicationHostService:**

    public class ApplicationHostService : IHostedService
    {
        readonly ILogger<ApplicationHostService> _logger;
        readonly IConfiguration _configuration;
        readonly IHostingEnvironment _hostingEnvironment;
        public ApplicationHostService(
            ILogger<ApplicationHostService> logger,
            IConfiguration configuration,
            IHostingEnvironment hostingEnvironment
            )
        {
            _logger = logger;
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            await Task.CompletedTask;
            _logger.LogWarning("Application Host Service started.....");           
        }

        public async Task StopAsync(CancellationToken cancellationToken)
        {            
            _logger.LogWarning("Application Host Service stopped.....");
            await Task.CompletedTask;
        }
    }

**WebJob trigger code:**

    public class MyImportTrigger
    {       
        private INotificationService _notificationService;        
      
        public MyImportTrigger(INotificationService notificationService)
        {
            _notificationService = notificationService;
        }

        
        public async Task Run([TimerTrigger("0 */1 * * * *" )] TimerInfo myTimer,  ILogger log)
        {
            ....bunch of non-relevant removed code for brevity....
            
            await _notificationService.CreateFundImportNotificationAsync(upload);
               
            ....bunch of non-relevant removed code for brevity....                  
        }
    }

**NotificationService:**

    using ProjectName.Auth;
    using ProjectName.Data;
    using ProjectName.Utils;
    using Microsoft.AspNetCore.SignalR;
    using SignalR.Mvc;
    using System;
    using System.ComponentModel;
    using System.Collections.Immutable;
    using System.Linq;
    using System.Threading.Tasks;
    
    
    namespace ProjectName.Hub
    {   
        public interface INotificationService
        {        
            FundPublishNotification CreateFundPublishNotification(short quarter, short year, string userName);        
        }
    
        public class NotificationService : INotificationService
        {
            MyDbContext _context;
            IHubContext<NotificationHub> _hubContext;
    
            public NotificationService(MyDbContext context, IHubContext<NotificationHub> hubContext)
            {
                _context = context;
                _hubContext = hubContext;
            }
    
          
            public async Task<FundImportNotification> CreateFundImportNotificationAsync(Upload upload)
            {
               *** removed: do some processing and db persistence to create an object called "notif" ***
                 
                **** THIS IS WHERE IT BOMBS WHEN CALLED FROM WEBJOB, BUT DOESN'T WHEN CALLED FROM API******                                   

                 ** the roles value is retrieved from the db and isn't dependent on a current user **

                 _hubContext.Clients.Groups(roles).SendAsync("NewNotification", notif);           
    
                return notif;
            }
        }
    }

**The Hub class:**

    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.SignalR;
    using MyProject.Auth;
    
    
    namespace SignalR.Mvc
    {
        [Authorize]    
        public class NotificationHub : Hub
        {
    
            public NotificationHub()
            { }
    
            public override async Task OnConnectedAsync()
            {
                await AddConnectionToGroups();
                await base.OnConnectedAsync();
            }
    
           
            public async Task AddConnectionToGroups()
            {
                var roles = Context.User.Roles();
                foreach (RoleValues role in roles)
                {
                    await Groups.AddToGroupAsync(Context.ConnectionId, role.ToString());
                }
            }
    
           
            public override async Task OnDisconnectedAsync(Exception exception)
            {
                await RemoveConnectionToGroups();
                await base.OnDisconnectedAsync(exception);
            }
    
            public async Task RemoveConnectionToGroups()
            {
                var roles = Context.User.Roles();
                foreach (RoleValues role in roles)
                {
                    await Groups.RemoveFromGroupAsync(Context.ConnectionId, role.ToString());
                }
            }
        }
    }

**appsettings.json:**

    {
     "Azure": {
        "SignalR": {
          "ConnectionString": "Endpoint=https://myproject-signalr-dev.service.signalr.net;AccessKey=removed-value-before-posting;Version=1.0;"
        }
      }
    }

### Exceptions (if any)
Microsoft.Azure.SignalR.ServiceLifetimeManager[100]
      Failed to send message (null).
Microsoft.Azure.SignalR.Common.AzureSignalRNotConnectedException: Azure SignalR Service is not connected yet, please try again later.
   at Microsoft.Azure.SignalR.ServiceConnectionManager`1.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.<>c__DisplayClass22_0`1.<WriteAsync>b__0(T m)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.WriteCoreAsync[T](T message, Func`2 task)

### Further technical details
```
  <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.1.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.23" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.2.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.8" />
```

**Comment by vicancy** [comment]
`AzureSignalRNotConnectedException` throws when there are no server connections connected to Azure SignalR. When the app starts to run, the SDK would try to start server connections to Azure SignalR, looks like that failed. There should be logs showing the detailed failure, could you share those logs, as similar to below:
```
info: Microsoft.Azure.SignalR.Connections.Client.Internal.WebSocketsTransport[1]
      Starting transport. Transfer mode:
```
Or:
```
fail: Microsoft.Azure.SignalR.ServiceConnection[2]
      Failed to connect to '(Primary)http://...', will retry after the back off period. Error detail: Unable to connect to the remote server. No connection could be made because the target machine actively refused it.. Id: c0c26bfd-8c90-4b0c-974e-1ab3e8c1faa9
```

**Comment by rachael-ross** [comment]
The WebJob isn't configured as a client though. It has an instance of the Hub.

warn: Microsoft.Azure.SignalR.ServiceLifetimeManager[100]
      Failed to send message (null).
Microsoft.Azure.SignalR.Common.AzureSignalRNotConnectedException: Azure SignalR Service is not connected yet, please try again later.
   at Microsoft.Azure.SignalR.ServiceConnectionManager`1.WriteAsync(ServiceMessage serviceMessage)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.<>c__DisplayClass22_0`1.<WriteAsync>b__0(T m)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.WriteCoreAsync[T](T message, Func`2 task)

**Comment by vicancy** [comment]
Yeah I understand that the WebJob is not a client but using the SDK and a Hub, so before this `Failed to send message (null).` log there should be some log starting with `info: Microsoft.Azure.SignalR.Connections.Client.Internal.WebSocketsTransport[1]`. The `Connections.Client` inside the logger name might be confusing, it is actually the SDK acts as a WebSocket client connecting to Azure SignalR to initiate the server connection. So why it `Failed to send message` is because no such server connections were successfully established. That's why I'd like to check the error log related to establishing the server connection. Hope it makes sense.

**Comment by rachael-ross** [comment]
Gotcha!  I ran it again to see if I had missed any logs and that's all it's emitting - there's nothing else being logged. I'm not sure what to do at this point. 

At what point is the connection made? In the API, we're configuring it into the pipeline, but also mapping an endpoint to the hub. In the WebJob, we're configuring it into the service collection only. Is there some initialization that I need to explicitly fire off?

Can you see anything in my configuration that jumps out at you or do you know of a good working example of a WebJob that is using Azure SignalR the way I am attempting to? I can't seem to find any that doesn't use servicebus or functions.

Thanks @vicancy !

**Comment by wanlwanl** [comment]
Hi @rachael-ross , your code only add AzureSignalR as a service into the service collection of the host. But you never actually connect to SignalR service. 

Looks like your scenario is suitable to use [SignalR service Management SDK](https://www.nuget.org/packages/Microsoft.Azure.SignalR.Management). You can get a `HubContext` easily to send messages.
For example:
```
var serviceManager = new ServiceManagerBuilder()
                    .WithOptions(option => 
                    {
                        option.ConnectionString = "<Your Azure SignalR Service Connection String>";
                    })
                    .Build();

try
{
    var hubcontext = await serviceManager.CreateHubContextAsync(hubName);

    // Broadcast
    hubContext.Clients.All.SendAsync(callbackName, obj1, obj2, ...);

    // Send to user
    hubContext.Clients.User(userId).SendAsync(callbackName, obj1, obj2, ...);

    // Send to group
    hubContext.Clients.Group(groupId).SendAsync(callbackName, obj1, obj2, ...);

    // add user to group
    await hubContext.UserGroups.AddToGroupAsync(userId, groupName);

    // remove user from group
    await hubContext.UserGroups.RemoveFromGroupAsync(userId, groupName);
}
finally
{
    await hubContext.DisposeAsync();
}
```

For more details, see [Quick Start](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#quick-start).
To get a sample for negotiation/publishingMessages, see [here](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management).

**Comment by rachael-ross** [comment]
Great! I'll try this when I have a chance to get back to this part in a couple of days.

**Comment by rachael-ross** [comment]
Using the ServiceManager worked great! Thank you!
