### ISSUE TITLE
Client doesn't receive UserGroup messages unless membership has TTL

### ISSUE THREAD

**Issue by BryceBarbara** [Azure/azure-signalr#1120]
### Describe the bug
Client who is a member of a UserGroup doesn't receive messages sent to UserGroups unless their membership has a TTL set.

We didn't see this behavior until we released to our production environment. It worked properly until the deployment.

This might be something we caused on ourselves but I've been unable to find any real documentation on SignalR Serverless UserGroups. It's been really hard diagnosing this and any suggestions for debugging techniques would be greatly appreciated.

#### Setup

* Use Azure SignalR in `Serverless` mode.
* Use `Microsoft.Azure.SignalR.Management` to manage hubs.
* Have a client already connected with the userId and listening for messages.
    ```c#
    return ServiceManager.GenerateClientAccessToken(hubName, userId);
    ```

#### Steps

1. Add user to UserGroup without specifying TTL.
    ```c#
    await hub.UserGroups.AddToGroupAsync(userId, groupName, ct);
    ```
1. Send message to Group.
    ```c#
    await hub.Clients.Group(groupName).SendCoreAsync(methodName, args, ct);
    ```
1. Client doesn't receive the message.

-------------------

**Note:** Setting a TTL in step 1 fixes the issue. Eg:
```c#
await hub.UserGroups.AddToGroupAsync(userId, groupName, ttl, ct);
```

### Further technical details
- `Microsoft.Azure.SignalR` v1.5.1
- `Microsoft.Azure.SignalR.Management` v1.5.1
- `@microsoft/signalr` v3.1.10

**Comment by vwxyzh** [comment]
@BryceBarbara 
I think it should be message out-of-order.
`AddToGroupAsync` only return 202 (Accept), the `AddUserToGroup` operation is still on the way, when you sending group broadcast.

There are two ways to fix the issue:
1. If you can know the connection id, use add connection to group, it will return 200 (OK), and ensure the operation is completed.
2. Still use `AddToGroupAsync`, but check user status by `IsUserInGroup`, and wait for `true`, then sending broadcast.

**Comment by BryceBarbara** [comment]
It turned out the problem actually did still remain even with the TTL set so I'll be closing this issue since it was invalid. I'll open a new one specific to this issue without assuming a solution.

@vwxyzh Thank you for your suggestion! I actually have a couple broadcasts going to the group every minute or so and none of them are received. If I understand you correctly, then the users should be receiving the later broadcasts but they aren't.

I think our production server is just unable to add users to groups... but I have no idea why? I don't know how to debug it since the Azure SignalR service is essentially a black box so I'm a bit at a loss.
