### ISSUE TITLE
Clients not receiving group messages, yet they're reported to be group members

### ISSUE THREAD

**Issue by BryceBarbara** [Azure/azure-signalr#1125]
### Describe the bug
We have a front-end web server that negotiates with SignalR for users and manages their group memberships. We also have a back-end service that is blindly firing events to various groups based on external events.

While everything is running, if I use the API to check if a test user is in a group that they should be in, SignalR says they are a member however they never receive messages sent to the group. But if I manually add the user using the [MessagePublisher](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management/MessagePublisher) sample project, the client automatically starts receiving messages properly.

Are there any situations where SignalR would say a user is a member and yet they wouldn't receive messages?

#### Setup
* Use Azure SignalR in `Serverless` mode.
* Use `Microsoft.Azure.SignalR.Management` to manage hubs.
* Have a client already connected with the userId and listening for messages.
    ```c#
    return ServiceManager.GenerateClientAccessToken(hubName, userId);
    ```
#### Steps

1. Add user to UserGroup.
    ```c#
    await hub.UserGroups.AddToGroupAsync(userId, groupName, ct);
    ```
1. Send message to Group from the backend.
    ```c#
    await hub.Clients.Group(groupName).SendCoreAsync(methodName, args, ct);
    ```
1. Client doesn't receive the message.

However, if I add the user to the group via a debug app or something else then the user starts receiving messages.

### Further technical details
- `Microsoft.Azure.SignalR` v1.5.1
- `Microsoft.Azure.SignalR.Management` v1.5.1
- `@microsoft/signalr` v3.1.10

**Comment by vicancy** [comment]
`UserGroups.AddToGroupAsync` is a `fire-and-forget` operation and `await` it does not guarantee the action is completed. If you need to do some thing right after the `AddToGroupAsync`, please use `Groups.AddToGroupAsync()` to add the connection to group.

@wanlwanl @vwxyzh I think we can re-implement `UserGroups.AddToGroupAsync` to spin-check if `UserGroups.IsUserInGroup` so that it completes only when the user is added to the group, thoughts?

**Comment by BryceBarbara** [comment]
No matter how long I wait, the clients will not receive messages. Also, the `IsUserInGroup` function _is_ returning true which is extra confusing.

**Comment by BryceBarbara** [comment]
I'm really at a loss for how to continue debugging this since there is so little insight into what is going on. 

Besides any suggestions for this issue at hand, do you have any general advice for how to debug issues with this management package and Azure SignalR in serverless mode? I haven't been able to find any real info. I've seen mentions of diagnostic clients but all the docs say is "TODO".

**Comment by vicancy** [comment]
> await hub.UserGroups.AddToGroupAsync(userId, groupName, ct);

When is this get called? Right after negotiation? 

I tried this [Management sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management) with [some minor changes](https://github.com/aspnet/AzureSignalR-samples/compare/master...vicancy:repro?expand=1#diff-c3178a931ca873dcff628082c9b120ffc633ee8168c9d0376a145e9aa5c05750R33) but failed to repro the issue, would you mind providing a minimum repro-able project?

My steps trying to repro but not:
1. Update the [NegotiationServer] with one more step before response to add the user to `group1`: 

```
 var hubContext = await _serviceManager.CreateHubContextAsync(hub);
 await hubContext.UserGroups.AddToGroupAsync(user, "group1");
```
https://github.com/vicancy/AzureSignalR-samples/blob/8232f3625598cc4cfb75b8e4419bf099c8f1537f/samples/Management/NegotiationServer/Controllers/NegotiateController.cs#L33

2. Follow the [instructions](https://github.com/vicancy/AzureSignalR-samples/tree/repro/samples/Management#run-the-sample) to start the NegotiationServer, the SignalRClient, and the MessagePublisher

3. In MessagePublisher, send to the group using: `send group group1 hello`

4. The client received the message successfully 
![image](https://user-images.githubusercontent.com/668244/100052797-a0392a00-2e59-11eb-8f3d-db2ce18dd5d5.png)

**Comment by wanlwanl** [comment]
Hi @BryceBarbara 

We just updated the [documentation for diagnostic logs](https://github.com/Azure/azure-signalr/blob/dev/docs/diagnostic-logs.md), you can find the doc for diagnostic client inside it.

To mark a client as diagnostic client, the current way is to use Microsoft.Azure.SignalR packge, you can make it as a negotiate server like this (workaround)  https://github.com/Azure/azure-signalr/issues/1115#issue-745419640,
Or please wait for a few days, I will make a preview version of Microsoft.Azure.SignalR.Management SDK to mark diagnostic client as soon as possible.

To troubleshoot, you can 
1. enable the message log
  * if you are in production environment, uncheck Messaging in diagnostic settings blade (enable collect-partial behavior), and use diagnostic client
  * if you are in development environement, check Messaging in diagnostic settings blade (enable collect-all behavior)
2. enable logging in Management SDK (pass `ILoggerFactory` to `Task<IServiceHubContext> CreateHubContextAsync(string hubName, ILoggerFactory loggerFactory = null, CancellationToken cancellationToken = default)`)
3. check logs
* if the particular user joins the particular group
* if the group message is sent to the right group
* if the particular user joins the particular group before sending group messages

If you still have other questions, please send you resource ID of SignalR service and problem start time and end time (it's better less than 10 minutes) to `wanl [at] microsoft.com`, I will help you to troubleshoot.

**Comment by BryceBarbara** [comment]
Repro repo: https://github.com/BryceBarbara/AzureSignalRUserGroupsIssue

The readme in the repo should walk you through how to reproduce this issue. While testing this on my end, I was only able to reproduce it when using our Prod Azure SignalR service which is on the Standard pricing tier. Our dev SignalR service on the Free tier did not display this odd behavior.

To summarize what I had to do to cause the issue:
* Switched NegotiationServer to using Persistent transport.
* NegotiationServer removes user from all groups prior to assigning groups
* Add an endpoint that manages groups after the client connects

**Comment by wanlwanl** [comment]
Thanks for your repo. For now, the operations about user join/leave group are fire-and-forget. Too soon operation of leave then join group will cause the wierd status of the user in/out of some group. For now the workaround is to to wait a little time (maybe one second) to between user-group action operations (user join/leave group) and wait a short time before sending message to group. We are trying to fix this issue. Another workaround is to use connection-group operations as @Liangying Wei<mailto:lianwei@microsoft.com> mentioned.

Thanks,
Wanpeng Li

________________________________

**Comment by wanlwanl** [comment]
Is it for the group name to contain “*”?

Thanks,
Liangying

________________________________

**Comment by wanlwanl** [comment]
No, in the repo, message publisher sends group message to "group1" "group2"...

Thanks,
Wanpeng Li

________________________________

**Comment by BryceBarbara** [comment]
I'm not really sure what the question is? I apologize

**Comment by wanlwanl** [comment]
Cleaning issues. Sorry there's no conclusion to this issue, but this issue is  too old, and the repro project is 404 now.
Please update the SDK to the latest one, it uses [ack message](https://github.com/Azure/azure-signalr/blob/master/src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs#L64) which will wait for the service confirm the message is handled.

If you still get this issue, please feel free to reopen it.

**Comment by neuro-sys** [comment]
Hi @wanlwanl,

> Please update the SDK to the latest one, it uses [ack message](https://github.com/Azure/azure-signalr/blob/master/src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs#L64) which will wait for the service confirm the message is handled.

Is the ack also added in .NET core version of SignalR?
