### ISSUE TITLE
Improve logs for server connection drop

### ISSUE THREAD

**Issue by vicancy** [Azure/azure-signalr#1173]
### Describe the bug
The server connections have client connections routed into them, and also are used to send data from server to client.
Server connections can drop due to network intermittent issues, or service maintenance. For now, every server connection drop reports an Error. However, some of these Errors actually have no business impact but worry customers because they are **Error** logs. 

Server connections drop with no business impact when:
1. Client->server side: the server connection has no clients routed to
2. Server->Client side: there are still server connections to the same HubServiceEndpoint available

Also, when the server connection having clients routed to drops, shall we make the log more user-friendly to include the impacted client count?

**Comment by NoahStahl** [comment]
This has been affecting us and would be great to see - errors ideally indicate actionable problems. I'm not sure if already intended, but also would be nice to de-duplicate the messages if logged, for example we see 5 instances of each disconnect message.
