### ISSUE TITLE
Microsoft.Azure.SignalR.Management incompatible with library that requires Microsoft.Extensions.Logging.Abstractions >= 3.0.0

### ISSUE THREAD

**Issue by furlongmt** [Azure/azure-signalr#1198]
I am using Microsoft.Azure.SignalR.Management 1.7.0 in a .NET 4.72 app that includes other libraries that require Microsoft.Extensions.Logging.Abstractions >= 3.0.0. When I run the application, I get this error:

```
 System.TypeLoadException: Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```
The Nuget gallery says the dependency is "Microsoft.Extensions.Logging.Abstractions (>= 2.1.0)", but it seems to actually requires version 2.x.x. 

Does anyone have any suggestions for workarounds, or can the `Microsoft.Extensions.Logging.Abstractions` package be updated to a later version (i.e. >= 3.0.0) for the SignalR.Management library?

Thanks!

**Comment by wanlwanl** [comment]
add this in your .csproj `    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.2" />` should work

**Comment by furlongmt** [comment]
That did the trick. Thanks for the help!
