### ISSUE TITLE
unable to call azure signalr hub method using azure signalr rest api

### ISSUE THREAD

**Issue by sonumalik1990** [Azure/azure-signalr#122]
I have created a sample .net core app with azure signalr service and hosted at local iis.

i) I am using below url in postman to call hub method: http://azuresignalr:5002/api/v1-preview/hub/:NotificationHub

ii) calling with postman with below body:

{ "Message": { "target": "BroadcastMessage", "arguments": [ "test method" ] } }

iii) My c# class :

public class NotificationHub:Hub {

public string TestConnection()
{
    return "connected";
}

[HttpPost]
public void BroadcastMessage([FromBody]object message)
{
    message = "Modified Message from Azure Signal R server " + message;

    Clients.All.SendAsync("broadcastMessage", message);

}
}
but I am getting 404 error "The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible." in postman.

Any help or document regarding its implementation is highly appreciated.

**Comment by xscript** [comment]
I think there are some misunderstanding about the use of REST API in Azure SignalR Service.

1. Only `HTTPS` is allowed to access the REST API.
2. You can only send message to clients through REST API. As I am seeing from your description, you are trying to invoke the hub method on your server.

**Comment by sonumalik1990** [comment]
Can you please provide some documentation or running demo to implement this.

**Comment by xscript** [comment]
You can refer to the [real-time sign-in sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/RealtimeSignIn), which describe the pattern of using Azure SignalR Service REST API.

**Comment by sonumalik1990** [comment]
Thanks

This link is really helpful.
 
in SignInFunction.cs

await signalR.SendAsync("signin", "updateSignInStats", stats.TotalNumber, stats.ByOS, stats.ByBrowser);

Can you please help me in understanding definition/use of "signin", "updateSignInStats", as I haven't found any hub "signin" with method  "updateSignInStats".

**Comment by sonumalik1990** [comment]
How we can fetch the sent message at client side??

Please suggest.

**Comment by sonumalik1990** [comment]
Its Done.

Thanks for your help.

**Comment by sonumalik1990** [comment]
@xscript 

Can you please help me in this.

https://github.com/Azure/Azure-Functions/issues/839

**Comment by sonumalik1990** [comment]
@xscript

Sorry for commenting in closed issue, but can you please suggest how unification(sending message to particular client not all client) of message can be done using rest api.

As upto now we broadcast the message to all client but if we have to send message to single client in a hub, how we can achieve that using azure signalR rest apis ??

Please suggest.

**Comment by xscript** [comment]
You can use [this API](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger.json#L8) to send message to a specific user.
You are required to provide a `NameIdentifier` claim when generating the access token for each client. Azure SignalR Service will use this claim to find the user you specify in the API.

**Comment by xscript** [comment]
Close this issue because there is no response for a week.

**Comment by jrmcdona** [comment]
@xscript how do we generate the name Identier claim in TypeScript with a Azure function negotiate function method?

**Comment by xscript** [comment]
> how do we generate the name Identier claim in TypeScript with a Azure function negotiate function method?

@JialinXin could you help answer this question?

**Comment by JialinXin** [comment]
Sure. @jrmcdona Answered in your issue #493.
