### ISSUE TITLE
Support standard https port (443)

### ISSUE THREAD

**Issue by chenkennt** [Azure/azure-signalr#123]
It may be more user friendly to expose SignalR service in standard HTTPS port (443), especially the client endpoint, considering some clients may have special network configuration (e.g. behind firewall).

**Comment by mariomeyrelles** [comment]
Yes, this is very important to be usable on corporate scenarios. I think this is urgent and should be prioritized.

**Comment by cyrilmestrom** [comment]
Very much needed here as well. Users opening our app on some public networks have no SignalR enabled

**Comment by gynet** [comment]
Also can azure-signalr support custom WebProxy? 

https://msdn.microsoft.com/en-us/library/system.net.webproxy(v=vs.110).aspx

**Comment by chenkennt** [comment]
Quick update for the progress so far:

Standard https port (443) will be supported in 1.0 (the release date is not finalized, hopefully in a month or two). This requires a major update in both SDK and service runtime. You'll need to upgrade to latest service SDK to use the new port. Service runtime will be automatically updated and no change to the client code.

Current port (5001/5002) will be retired, but there will be a transition period when both old and new ports are supported, after that old ports will be closed.

Feel free to let us know if there is any concerns/questions.

**Comment by xscript** [comment]
With the latest Service SDK and the new connection string format, all traffic will go through 443 port now.

**Comment by mahpour** [comment]
When will this new SDK be available to use on Azure SignalR services?

**Comment by chenkennt** [comment]
It's already released:
https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.0.2

**Comment by mahpour** [comment]
Yes released on Nuget not as a service in the portal. How do we use this latest version in the portal as a service?

**Comment by chenkennt** [comment]
Service is already updated to support port 443. Check out our GA announcement:
https://azure.microsoft.com/en-us/blog/azure-signalr-service-now-generally-available/

**Comment by mahpour** [comment]
I created multiple instances and still don’t see the new port in effect. Is there anything specific we should be doing to get the right one?

**Comment by mahpour** [comment]
As an update, I was able to use the service on port 443, the problem is that connectionInfo object provided is still showing port 5001 but I used port 443 and it worked.

**Comment by chenkennt** [comment]
The Azure function binding is still using the old port, we're working on an update right now. For now you can manually update the url before return the connectionInfo object.

**Comment by bmargula** [comment]
> The Azure function binding is still using the old port, we're working on an update right now. For now you can manually update the url before return the connectionInfo object.

Yeah, figured, the same problem here.

**Comment by JialinXin** [comment]
From January 2019, Azure SignalR Service is retiring 5001/5002 port and move to 443 completely. Please follow the steps below to ensure your service working normally.

## Azure SignalR Service SDK
Update to a newer SDK version = [v1.0.5](https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.0.5) and update Azure SignalR `ConnectionString` to latest version with `Version=1.0` assigned.

## Azure SignalR Service Function Extension
Update to a newer extension version = [v1.0.0-preview1-10025](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.SignalRService/1.0.0-preview1-10025) and update Azure SignalR `ConnectionString` to latest version with `Version=1.0` assigned.

## Self-build Rest API
Refer to swagger [v1](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.json) to build requests.
