### ISSUE TITLE
SendAsync not working on authenticated user

### ISSUE THREAD

**Issue by lovettchris** [Azure/azure-signalr#1233]
### Describe the bug
I have ASP.NET web site with authenticated user and a html client.  The html client receives SignalR messages if I use this method:
```
await _hubContext.Clients.All.SendAsync("broadcastMessage", message);
```
but **not** if I use this method:
```
_hubContext.Clients.User(User.Identity.Name).SendAsync("broadcastMessage", message);
```

### To Reproduce

See https://github.com/clovett/AspNetStreamingLogs

Change the "AzureAd" in appsettings.json and setup user-secret for your SignalR service.

Then run it and click the "Ping" button.  Notice nothing comes back.  Whereas the Broadcast button works fine.

### Exceptions (if any)
Can't find any exception in the sendAsync call even with just my code turned off.  I also took a look at this object:
```
var user = _hubContext.Clients.User(User.Identity.Name);
```
and it is non null, and contains non public member "_lifetimeManager" with a non-public member "_clientConnectionManager" which contains 1 connection and the key matches the connection.connectionId that I see on the Index.cshtml client page.  So it's a mystery why this isn't working?

### Further technical details
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` :  1.7.1
- Your SignalR Client SDK version:  https://cdn.jsdelivr.net/npm/@@microsoft/signalr@5.0.3/dist/browser/signalr.min.js

**Comment by Y-Sindo** [comment]
Hi @lovettchris, we have already reproduced your scenario successfully. We are actively working on the fix and will keep you updated.

**Comment by clovett** [comment]
Cool, thanks!

**Comment by Y-Sindo** [comment]
We finally concluded that this is not a bug with Azure SignalR Service, but the default behavior of SignalR not compatible with Microsoft Identity Web App. From the perspective of SignalR, you have two solutions:

##### Solution 1
Change from `_hubContext.Clients.User(User.Identity.Name)` to `_hubContext.Clients.User(User.FindFirst(ClaimTypes.NameIdentifier).Value)`

##### Solution 2 
Implement your customized [IUserIdProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.iuseridprovider?view=aspnetcore-5.0) like this and register it as an singleton.
```C#
    public class UserIdProvider : IUserIdProvider
    {
        public string GetUserId(HubConnectionContext connection)
        {
            return connection.User.FindFirst(ClaimConstants.PreferredUserName).Value;
        }
    }
```

**Comment by clovett** [comment]
Thanks so much, that works now!  Perhaps it should be added to some docs or samples someplace.

**Comment by Y-Sindo** [comment]
Here is a related doc:  [users-in-signalr](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-5.0#users-in-signalr). It is a topic of [SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-5.0), the underlying library of **Azure SignalR Service**. We will try to add a link to this doc in the Azure SignalR Service documents where appropriate.

**Comment by clovett** [comment]
Thanks I found my way to "[authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0)" since I figured it would be related to that, but alas that page says "_SignalR can be used with ASP.NET Core authentication to associate a user with each connection. In a hub, authentication data can be accessed from the HubConnectionContext.User property. Authentication allows the hub to call methods on all connections associated with a user._ " which gave me the impression things should "just work", which unfortunately, they didn't.  So adding a snippet after that paragraph would have solved it for me.

**Comment by BrennanConroy** [comment]
The next sentence in that paragraph links to the `users-in-signalr` doc.
>For more information, see [Manage users and groups in SignalR](https://docs.microsoft.com/aspnet/core/signalr/groups?view=aspnetcore-5.0). Multiple connections may be associated with a single user.

**Comment by lovettchris** [comment]
yep but I was already 3 pages deep in documentation, so I didn't explore deeper...  only so much one can read in a day... just a tiniest hint would have helped, "note: the userid is not User.Identity.Name" would have been enough.
________________________________

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have any concerns about it.
