### ISSUE TITLE
/poll requests spike when switching from self-hosted SignalR to Azure SignalR [AspNet]

### ISSUE THREAD

**Issue by bjqian** [Azure/azure-signalr#1236]
### Describe the bug
Azure SignalR SDK  returns 200 for SignalR path requests[ reconnect, poll... requests with valid token]. 
It should fail because those requests should be handled by SignalR service. 

### To Reproduce
1.	Use a **AspNet** SignalR Client to connect to a self-hosted SignalR server, setting the protocol to long-polling
2.	Stop the self-hosted SignalR server. Then the client would try reconnecting.
3.	Start the Azure SignalR app server (same host and port). Then the reconnect will succeed and the client would keep sending /signalr/poll to the server. 
![poll](https://user-images.githubusercontent.com/16233725/110426839-bbb30280-80e1-11eb-8c9e-5e9b5743e861.png)

### Further technical details
Azure SignalR SDK version <=1.7.1

**Comment by bjqian** [comment]
Fix PR:
https://github.com/Azure/azure-signalr/pull/1228

**Comment by vwxyzh** [comment]
Fixed in 1.8
