### ISSUE TITLE
"Message is incomplete" error

### ISSUE THREAD

**Issue by SqweeeRyan** [Azure/azure-signalr#124]
Hello! I just tried turning on the Azure SignalR Service and am running into an issue with large messages being sent from the server to the client. I am getting the following JS error message:

```
signalr.js:1616 Uncaught Error: Message is incomplete.
    at Function.TextMessageFormat.parse (signalr.js:1616)
    at JsonHubProtocol.parseMessages (signalr.js:3207)
    at HubConnection.processIncomingData (signalr.js:2158)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1934)
    at WebSocket.webSocket.onmessage (signalr.js:2761)
```

I added a console.log to that TextMessageFormat.parse method to see the input, and I see that it is a C# object that is being broken into half. That is, the first message is of length 2,049 characters. Then that exception is thrown. Then I immediately get the next message that is about the same length (2,046 characters), followed by the same exception.

My method of passing the data to the front-end, from the hub, follows:

```
await Clients.Client(Context.ConnectionId).SendAsync("FullRsvpListOfAttendees", attendees.Select(n => new
{
   AttendeeId = n.AttendeeId,
   FirstName = n.AttendeeFirstName,
   LastName = n.AttendeeLastName,
   IsMuted = n.IsMuted
}).ToList());
```

I have attached some logs generated from the client and server, if that is useful.

When I run this same code using the base AspNetCore.SignalR, it works without this error message.

Here's a longer copy/paste from the JS console:
```
Debug: Server handshake complete.
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 202.
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 41.
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 44.
signalr.js:1893 Trace: (WebSockets transport) sending data. String data of length 76.
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 186.
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 44.
signalr.js:1893 Trace: (WebSockets transport) sending data. String data of length 89.
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 2048.
signalr.js:1616 Uncaught Error: Message is incomplete.
    at Function.TextMessageFormat.parse (signalr.js:1616)
    at JsonHubProtocol.parseMessages (signalr.js:3207)
    at HubConnection.processIncomingData (signalr.js:2158)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1934)
    at WebSocket.webSocket.onmessage (signalr.js:2761)
TextMessageFormat.parse @ signalr.js:1616
JsonHubProtocol.parseMessages @ signalr.js:3207
HubConnection.processIncomingData @ signalr.js:2158
HubConnection.connection.onreceive @ signalr.js:1934
webSocket.onmessage @ signalr.js:2761
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 2046.
signalr.js:1616 Uncaught Error: Message is incomplete.
    at Function.TextMessageFormat.parse (signalr.js:1616)
    at JsonHubProtocol.parseMessages (signalr.js:3207)
    at HubConnection.processIncomingData (signalr.js:2158)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1934)
    at WebSocket.webSocket.onmessage (signalr.js:2761)
TextMessageFormat.parse @ signalr.js:1616
JsonHubProtocol.parseMessages @ signalr.js:3207
HubConnection.processIncomingData @ signalr.js:2158
HubConnection.connection.onreceive @ signalr.js:1934
webSocket.onmessage @ signalr.js:2761
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 2048.
signalr.js:1616 Uncaught Error: Message is incomplete.
    at Function.TextMessageFormat.parse (signalr.js:1616)
    at JsonHubProtocol.parseMessages (signalr.js:3207)
    at HubConnection.processIncomingData (signalr.js:2158)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1934)
    at WebSocket.webSocket.onmessage (signalr.js:2761)
TextMessageFormat.parse @ signalr.js:1616
JsonHubProtocol.parseMessages @ signalr.js:3207
HubConnection.processIncomingData @ signalr.js:2158
HubConnection.connection.onreceive @ signalr.js:1934
webSocket.onmessage @ signalr.js:2761
signalr.js:1893 Trace: (WebSockets transport) data received. String data of length 1176.
VM210868:1 Uncaught SyntaxError: Unexpected token , in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonHubProtocol.parseMessages (signalr.js:3211)
    at HubConnection.processIncomingData (signalr.js:2158)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1934)
    at WebSocket.webSocket.onmessage (signalr.js:2761)
```

Thank you!

[Server Log.txt](https://github.com/Azure/azure-signalr/files/2103727/Server.Log.txt)
[Client Log.txt](https://github.com/Azure/azure-signalr/files/2103728/Client.Log.txt)
[localhost.har.txt](https://github.com/Azure/azure-signalr/files/2103729/localhost.har.txt)

**Comment by xscript** [comment]
Thanks for reporting this issue. I am looking into it.

**Comment by xscript** [comment]
@SqweeeRyan I've tried to reproduce your issue from my side. So I sent some messages with length of ~10k. It works with no error.
I saw your connection is using `WebSockets` transport. Could you capture the problematic data frame and send it to me? My email address is `kevinzha_at_microsoft.com` (replace `_at_` with `@`).

**Comment by davidfowl** [comment]
We have to ensure that we’re sending full messages to the client. I’ll see if something stands out later tomorrow

**Comment by SqweeeRyan** [comment]
@xscript I just sent you an email to follow up...thanks!

**Comment by xscript** [comment]
@SqweeeRyan I have replied your email. Have your tried Chrome to get the problematic data frame?

**Comment by xscript** [comment]
Looks like the root cause is from [here](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs#L469-L475). A complete message is split into multiple service messages being sent to service. Digging more on it.

**Comment by stephenweaver** [comment]
It appears that I'm also running into this issue. Seems to be slitting the messages across several frames. Most of the frames are being slit at ~2048 bytes, but some are larger.

**Comment by davidfowl** [comment]
@xscript its likely on the service side as well. I have a simple fix in mind, but it means we won't be able to reuse the ConnectionDataMessage type here.

**Comment by davidfowl** [comment]
Actually the fix is easier than that, we just need to change ConnectionDataMessage to take a `ReadOnlySequence<byte>` instead of a `ReadOnlyMemory<byte>`. The multi writing can happen in side of the ServiceProtocol implementation itself.

**Comment by xscript** [comment]
@davidfowl Yes, i was thinking about the same.
The only concern is `ConnectionDataMessage` will not be consistent with the other service message types because the payload type is not the same. But I didn't find any API to convert from `ReadOnlySequence<T>` to `ReadOnlyMemory<T>` without breaking into segments.
As `ConnectionDataMessage` is only used internally now, I think we can live with the inconsistency.

**Comment by davidfowl** [comment]
@xscript I sent a PR. Writing a few tests now.

**Comment by davidfowl** [comment]
The SDK side fixes are in, we still need to fix the service itself.

**Comment by davidfowl** [comment]
Actually there might not need to be any fix on the service side at all.

@SqweeeRyan and @stephenjordan would you be willing to try out a ci build of the SDK to help us verify this fixes your applications?

**Comment by stephenweaver** [comment]
@davidfowl do we know if the service needs to be updated? Not sure if you meant to tag the other stephen or not, but I'd be happy to test it out a CI build. What's the package source? (I checked aspnetcore-dev and netcore-dev to see if it was there, but I didn't the package there.)

**Comment by xscript** [comment]
I've tested that this issue is fixed with the current service runtime. You can double confirm with your application.
You can use this feed https://www.myget.org/feed/azure-signalr-dev/package/nuget/Microsoft.Azure.SignalR . The latest version is `1.0.0-preview1-10012`.
