### ISSUE TITLE
Message size over 32 KB will cause server connection closed

### ISSUE THREAD

**Issue by xscript** [Azure/azure-signalr#125]
Same issue as https://github.com/aspnet/SignalR/issues/2483 . Azure SignalR Service use the default transport buffer size setting.
For now we should document this limitation. Maybe we can make it configurable when provisioning a new service instance, but definitely need more discussion and testing before making any decision.

**Comment by davidfowl** [comment]
Upgraded to bug

**Comment by xscript** [comment]
Fix has been deployed to all instances.

**Comment by johnjbateman** [comment]
@xscript @davidfowl So when you say this has been deployed to all instances and closed the bug, exactly how can we change the default transport buffer size in Azure SignalR?

In SignalR Core, we could do this:

```
app.UseSignalR(routes =>
            {
                routes.MapHub<DocumentNavigationHub>("/documentNavigationHub", options =>
                {
                    options.ApplicationMaxBufferSize = 2650 * 1024;
                });
```

In Azure SignalR, there are no "options" available.  Can you help?

```
app.UseAzureSignalR(routes =>
            {
                routes.MapHub<DocumentNavigationHub>("/documentNavigationHub", options =>
                {
                    options.ApplicationMaxBufferSize = 2650 * 1024;
                });
```
![image](https://user-images.githubusercontent.com/34578771/51993241-66c14e80-247c-11e9-87a5-8138ff6e365c.png)

**Comment by davidfowl** [comment]
What exactly are you trying to change? This issue was about sending data between the server and service. The client still can’t send more than 32K today to the service. There’s currently no workaround for that (as there at security implications). 

There’s need to be an option on the portal to increase the limit.

**Comment by johnjbateman** [comment]
We were trying to increase the ApplicationMaxBufferSize so that we can send documents back and forth.  However, we just refactored our code to not send the doc data through SignalR.  So we worked around the limitation.

> There’s need to be an option on the portal to increase the limit.

This would be great!  Would love to be able to toggle that.

**Comment by davidfowl** [comment]
@johnjbateman I'd suggest opening another issue on that. We're also adding support for client streaming in the next version of SignalR.
