### ISSUE TITLE
Missing release tag for 1.8.0

### ISSUE THREAD

**Issue by NoahStahl** [Azure/azure-signalr#1257]
Nuget is showing a new package version of 1.8.0 but there is no associated tagged release with change notes in this repo. Please add so users can evaluate upgrading.

It would also be nice if a CHANGELOG file were added to consolidate change history for the same purpose.

**Comment by vicancy** [comment]
Thanks for pointing this out. https://github.com/Azure/azure-signalr/releases/tag/v1.8.0
