### ISSUE TITLE
Consider adding `ConnectionStrings` in the fallback path when loading default connection string from environment

### ISSUE THREAD

**Issue by xscript** [Azure/azure-signalr#126]
Azure Web App has a "Connection Strings" section specifically for secret connection strings. We should consider adding it into the fallback path when loading default connection string from environment, to optimize the experiences in Azure Web App.

**Comment by davidfowl** [comment]
There’s a pattern we infer for this, take a look at the environment variable configuration provider

**Comment by xscript** [comment]
@davidfowl are you talking about [AddEnvironmentVariables() API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.environmentvariablesextensions.addenvironmentvariables?view=aspnetcore-2.1#Microsoft_Extensions_Configuration_EnvironmentVariablesExtensions_AddEnvironmentVariables_Microsoft_Extensions_Configuration_IConfigurationBuilder_System_String_)?
What I mean is we may search for `ConnectionStrings:Azure:SignalR:ConnectionString` from environment since Azure Web App supports it. Of course the naming should be further discussed. What do you think?

**Comment by davidfowl** [comment]
Yes https://github.com/aspnet/Configuration/blob/2177cdf37ab22b766f70e6f0dbf3a486a0955fb4/src/Config.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs#L21

I believe we read the environment variables from app service and we project them as a ke.
