### ISSUE TITLE
Troubleshoot Dropped Connections

### ISSUE THREAD

**Issue by higginsddh** [Azure/azure-signalr#1261]
I'm having SignalR clients frequently drop and hoping I could get some guidance on how to troubleshoot.

My application server is on ASP.NET Core v5 and hosted on an App Service.  I'm using Azure SignalR set to Default mode.  

We've gotten reports from our users that real time updates are frequently breaking for them.

From our client side logging, we're seeing connections frequently close.  We're determining this through logging in connection.oncclose.  The code does try to reconnect but often gets disconnected again a few minutes later.

These disconnects correspond to SignalR connectivity log entries that say "Connection aborted. Reason: Application server closed the connection."  However, the documentation doesn't give much detail on that other than "App server triggers the abortion. It can be considered as an expected abortion."  Given that it happens so frequently, it's surprising that it would be an expected abortion.  The application server seems to be running fine and not restarting or logging any errors during that time.

Has anyone run into a similar issue or have suggestions on where else to look to figure out the problem?

Thanks!

**Comment by BrennanConroy** [comment]
Are your users using Chrome and putting the tab with the signalr connection in the background?

**Comment by higginsddh** [comment]
@BrennanConroy At least some of the users reporting it are using Chrome but not sure about all of them.  Also not sure if they've put the tab in the background but I could add logging to see if that's happening based on page visibility toggling.  

Is it expected that the signalr connection is dropped when the tab is in the background?

Thanks for the suggestion!

**Comment by BrennanConroy** [comment]
Chrome recently added "timer throttling" which is causing the server to close clients after a few minutes if the chrome tab isn't active.

We're currently exploring fixes in the client library to workaround this.

**Comment by higginsddh** [comment]
That makes sense.  There may some changes I can do on my reconnection logic to workaround it as well.  Appreciate the info!

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have any concerns about it.

**Comment by nikunj231991** [comment]
Any update on the fix? because I am facing the same issue.
