### ISSUE TITLE
SignalR Emulator adds \u001e character to messages sent to upstream endpoint

### ISSUE THREAD

**Issue by npalmiusfutr** [Azure/azure-signalr#1262]
### Describe the bug

The SignalR Emulator appears to be adding a `\u001e` character to the end of the body sent to the configured upstream endpoint. This causes issues with JSON parsing of the body data. Logging out incoming message bodies, they appear as follows, where the `{ ... }` is the expected body:

```
{ ... }▲
```

The extra character is included in the `Content-Length` header.

This was first reported by @mmulhearn in #969, but appears to be in the current version of the emulator so raising a separate bug.

### To Reproduce

Send any json content to the SignalR Emulator across an opened socket and observe the data sent to the upstream endpoint. Note that @mmulhearn suggests that this may be transparently handled by some function bindings, however we are working with Node functions running Express that do not handle this correctly.

### Exceptions (if any)

N/A.

### Further technical details
- Azure SignalR Emulator package version 1.0.0-preview1-10719.

**Comment by vicancy** [comment]
Should be fixed in https://github.com/Azure/azure-signalr/commit/ed87e3096a1ecbae3c419d7ef34af611a0c0d48c

**Comment by npalmiusfutr** [comment]
That's great, many thanks @vicancy! I will test this later on today and get back to you.

**Comment by npalmiusfutr** [comment]
Apologies for the delay in gettting back to you @vicancy - all working perfectly now, thank you again for getting this fixed so quickly.

More generally, I also want to say just how useful this emulator is to have, so thank you for all your work on it!
