### ISSUE TITLE
Azure SignalR Service is not connected yet, error many times for blazer app

### ISSUE THREAD

**Issue by swiftinitdotcom** [Azure/azure-signalr#1264]
Azure SignalR Service is not connected yet, error many times for blazer app

### Further technical details
- Your Azure SignalR SDK version
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 
- Your SignalR Client SDK version

**Comment by vicancy** [comment]
Is it a persistent error or a transient error?
`Azure SignalR Service is not connected yet` means the blazer app is not connected to the service, here contains detailed info and troubleshooting guidance for such error: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#500-error-when-negotiate-azure-signalr-service-is-not-connected-yet-please-try-again-later

**Comment by swiftinitdotcom** [comment]
Its for few days now, before it was working nicely, now I had to move to onpremise because of this... until this gets resolved

**Comment by swiftinitdotcom** [comment]
Strange thing is same published app works just fine on on premise and when I publish on azure this signal r error....

**Comment by vicancy** [comment]
Consistently repro? Any exceptions from the app server side? Can it be reproed from localhost?

**Comment by swiftinitdotcom** [comment]
yes it posts back and does not behave like blazer app in azure due to signarr error, works just fine on server iis

**Comment by vicancy** [comment]
If it can be repro-ed consistently from localhost, could you try this: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#troubleshooting-guide

**Comment by vicancy** [comment]
Please feel free to reopen the issue if there are further updates.
