### ISSUE TITLE
Use Azure SignalR with MVC 5

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-signalr#127]
Hi, 

I would like to use Azure SignalR with .net framework / mvc 5. How can I specify the connection string / secrets?

**Comment by xscript** [comment]
You mean you want to host your hubs in MVC 5?
Right now Azure SignalR Service only support [ASP.NET Core SignalR](https://github.com/aspnet/signalr). #101 is tracking the support of [ASP.NET SignalR](https://github.com/signalr/signalr). Working is in progress.

If you app is already using ASP.NET SignalR. You can follow up on #101 .
If you plan to start using SignalR, we recommend to migrate to .NET Core and use ASP.NET Core SignalR.

**Comment by davidfowl** [comment]
Closing this as there's another issue tracking the work
