### ISSUE TITLE
System.MissingMethodException : Method not found: 'Microsoft.Azure.SignalR.Management.IInternalServiceHubContext Microsoft.Azure.SignalR.Management.IInternalServiceHubContext.WithEndpoints(System.Collections.Generic.IEnumerable`1<Microsoft.Azure.SignalR.ServiceEndpoint>)'.at async

### ISSUE THREAD

**Issue by mpalese** [Azure/azure-signalr#1275]
When i call in the Azure function 
await signalRMessages.AddAsync(
                    new SignalRMessage()
                    {
                        Target = "Broadcast",
                        Arguments = new[] { msg }
                    });
i receive System.MissingMethodException : Method not found: 'Microsoft.Azure.SignalR.Management.IInternalServiceHubContext Microsoft.Azure.SignalR.Management.IInternalServiceHubContext.WithEndpoints(System.Collections.Generic.IEnumerable`1<Microsoft.Azure.SignalR.ServiceEndpoint>)'.at async Microsoft.Azure.WebJobs.Extensions.SignalRService.AzureSignalRClient.InvokeAsync(ServiceEndpoint[] endpoints,Func`2 func)at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)at Microsoft.Azure.WebJobs.Extensions.SignalRService.AzureSignalRClient.InvokeAsync(ServiceEndpoint[] endpoints,Func`2 func)at async Microsoft.Azure.WebJobs.Extensions.SignalRService.SignalRAsyncCollector`1.AddAsync[T](T item,CancellationToken cancellationToken)at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at async

```javascript
public async Task Run([IoTHubTrigger("messages/events", Connection = "EventHubConnectionAppSetting")] EventData message,
            [SignalR(HubName = "SignalRTestHub", ConnectionStringSetting = "AzureSignalRConnectionString")] IAsyncCollector<SignalRMessage> signalRMessages,
            ExecutionContext exeContext, ILogger log)
        {
                   string msg = Encoding.UTF8.GetString(message.Body.ToArray());
                  await signalRMessages.AddAsync(
                    new SignalRMessage()
                    {
                        Target = "Broadcast",
                        Arguments = new[] { msg }
                    });
}
```

    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.4.0" />
    <PackageReference Include="Microsoft.Azure.Devices" Version="1.32.0" />
    <PackageReference Include="Microsoft.Azure.EventGrid" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.8.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.3.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

**Comment by Y-Sindo** [comment]
We're sorry that "Microsoft.Azure.WebJobs.Extensions.SignalRService" 1.3.0 are not compatible with "Microsoft.Azure.SignalR.Management" 1.8.1. A workaround is downgrade "Microsoft.Azure.SignalR.Management" to 1.8.0.  We will release a new function extension version to fix this problem.

**Comment by Y-Sindo** [comment]
`Microsoft.Azure.WebJobs.Extensions.SignalRService` v1.4.0 has been released and could be used with "Microsoft.Azure.SignalR.Management" v1.8.1.
