### ISSUE TITLE
Many errors while starting connections concurrently

### ISSUE THREAD

**Issue by elias-rod** [Azure/azure-signalr#1282]
**DESCRIPTION**
We know about Crankier but we created a custom tool to test our platform with SignalR on loads that we expect to have. When we try to start the connections for 2.4k clients there are at least two kinds of exceptions for 30% of the requests and we need to connect up to 4k clients. We configured the service with 5 units and our tool is a NET 5 worker that we intend to run in containers.

Are we doing something wrong or is it that Azure SignalR can't handle so many connections simultaneously?

**EXCEPTIONS**
The server disconnected before sending a handshake response
![image](https://user-images.githubusercontent.com/12984787/119144484-168ca280-ba1f-11eb-8805-ca469e1ea301.png)

System. Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests) .
![image](https://user-images.githubusercontent.com/12984787/119144601-33c17100-ba1f-11eb-9647-dde986a83734.png)

**REPRO PROJECT**
This a [small repro project](https://github.com/elias-rod/signalrtestingtool) where we removed everything related to our complete project and these are the configurable settings in appsetings.json:
  

-   "SignalRConcurrentConnections": 2,
-   "ListeningWaitingMs": "10000",//Time when the loggings gather the final results
-   "SignalREndpoint": "",
-   "SignalRToken": ""

_Our server_ is hosted in a separated API with the following code (abstract):
Startup.cs>ConfigureServices

    services.AddSignalR().Services.AddSingleton(new ServiceManagerBuilder()
        .WithOptions(configure => configure.ConnectionString = "x")
        .Build());

SignalRService.cs

    public class SignalRService : ISignalRService
    {
        private readonly IServiceManager _serviceManager;

        public SignalRService(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public Dictionary<string, string> GetClientConnectionData(string hubName)
        {
            var connectionData = new Dictionary<string, string>()
            {
                { "clientEndpoint", _serviceManager.GetClientEndpoint(hubName) },
                { "accessToken", _serviceManager.GenerateClientAccessToken(hubName) },
            };
    
            return connectionData;
        }

        public async Task PublishMessage<T>(string hubName, string topic, T message)
        {
            var hubContext = await _serviceManager.CreateHubContextAsync(hubName);

            await hubContext.Clients.All.SendAsync(topic, message);
        }
    }
**SDK**
"Microsoft.AspNetCore.SignalR.Client" Version="5.0.6"

**Comment by vicancy** [comment]
1. The server disconnected before sending a handshake response
    This one looks like your app server-side failed to return back the handshake response. Could you check your app server side CPU usage during that time?

2. System. Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests) .
    What is the request per second for the client to start the connections? For Unit5, the service allows 400 concurrent "start connection" requests **per second **

**Comment by elias-rod** [comment]
Thanks for your answer! Regarding the 429 (Too Many Requests) error, we didn't find any documentation about that limitation and the [closest one](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-performance) didn't mention that. Where can we find more information about that 400 concurrent start connection request limitation?

About the handshake error, we are getting the URL and token from Azure SignalR through a single, one-time call and then reusing those credentials by all the clients on starting the connection. The flow we are using is the following:

1. Client requests the URL and token from our server hosted in a custom API
2. Custom API, in turn, requests those from IServiceManager (SignalR)
3. Client receives those credentials from our custom API to create the 3k connections with SignalR service
4. The connections start listening for messages sent by SignalR

When I saw that the server disconnected before sending a handshake, I understood it meant the Azure SignalR server as we don't have coded any other interaction between the client and our server except for getting the credentials (and indirectly by broadcasting the messages from the server to the clients through SignalR). Could you throw some light on this?

I've included the code related to the GetClientConnectionData method within SignalRService.cs abstract (from our server) in the issue description from above.

**Comment by vicancy** [comment]
> Where can we find more information about that 400 concurrent start connection request limitation?

Here is a doc mentioning that behavior but yes we need to improve the doc to include the algorithm detail. https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#too-many-negotiate-requests-at-the-same-time

> When I saw that the server disconnected before sending a handshake, I understood it meant the Azure SignalR server as we don't have coded any other interaction between the client and our server except for getting the credentials

Actually, when your app server starts, it starts several server connections to the service. When the client connects to Azure SignalR and sends out the handshake request to the service, the service acts as a data proxy and forwards the request to your app server. Your app server then returns back the handshake response to the client through the service. Could you check if your app server is heavily loaded during that period? When the app server is heavily loaded, it might fail to send back the handshake response, and the Azure SignalR would close the client connection if it hasn't detected the handshake response within 15 seconds.

**Comment by elias-rod** [comment]
Thanks! That troubleshooting guide is excellent, we will investigate our API behavior more thoroughly although we haven't seen peaks in that period in a shallow inspection.
Regarding the limitation, do the other tiers have different concurrent start-connection limitations? If so, would you please share them with us? This is because we are planning to scale the service even further.

**Comment by vwxyzh** [comment]
@elias-rod
| unit size | connections per second* | time for connecting all connections |
|:--:|:--:|:--:|
| Free | 20 | 1 second |
| 1 ~ 10 | 400 | 2.5 seconds ~ 25 seconds |
| 20 | 600 | 33.3 seconds |
| 50 | 2000 | 25 seconds |
| 100 | 8000 | 25 seconds |

\* we might scale the instance automatically, sometime the limitation will exceed this value.

**Comment by elias-rod** [comment]
Awesome, with these numbers you provided we can properly configure the service for our next events, thanks!
