### ISSUE TITLE
Migrate from AppAuthentication to Azure.Identity

### ISSUE THREAD

**Issue by aelij** [Azure/azure-signalr#1288]
The `AppAuthentication` library has been superseded by `Azure.Identity` (see [notice](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication)), which provides a much wider range of auth provides.

I think the `ServiceEndpoint` class should just expose a `TokenCredential` property instead of relying on connection string parsing. It also provides better discoverability for auth properties.

**Comment by terencefan** [comment]
We'll consider adding a constructor for `TokenCredential` in the future release.

Thank you for mentioning us.
