### ISSUE TITLE
to provision Azure singalR service using ARM templates in Visual studio

### ISSUE THREAD

**Issue by sonumalik1990** [Azure/azure-signalr#134]
Can any one please help me in creating/deploying  Azure singalR service using ARM templates with VSO.

I am not getting much help from google.

**Comment by juniwang** [comment]
Hi @sonumalik1990,  please read this [post](https://docs.microsoft.com/en-us/azure/vs-azure-tools-resource-groups-ci-in-vsts?toc=%2fazure%2fazure-resource-manager%2ftoc.json) as a reference about how to deploy service to Azure using ARM with VSO.   And you can find example ARM templates for Azure SignalR service in this [repository](https://github.com/juniwang/azure-signalr-arm-example/tree/master/standard).

**Comment by chenkennt** [comment]
So you're looking for a way to programmatically get connection string? Then you can use Azure CLI, some samples can be found here:
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-cli-samples

**Comment by juniwang** [comment]
I believe these is no way that one resource can read the output of another resource in single ARM deployment. That means you cannot read the SignalR connection string and apply it to Function in the ARM.  You have to read and apply the connection string in other ways than ARM.   

You can deploy SignalR and Azure Function(with default or blank SignalR connection string) in one ARM, then configure Azure function to update its app settings using cli/powershell.  For VSO, the [azure cli](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/azure-cli?view=vsts) task might help.  Make sure azure cli is installed on your build/release agents. 

Following scripts exemplifies how to configure the Functions apps(note that SignalR extension for Azure cli must be installed):
```
az extension add -n signalr
az signalr key list --name <SignalRServiceName> --resource-group <ResourceGroup>
az functionapp config appsettings set --name <FunctionAppName> --resource-group <FuncAppGroup> --settings <name>=<value>
```

**Comment by sonumalik1990** [comment]
@juniwang / @chenkennt 

Can we get "primaryKey" connection string inside ARM template, actually I am using single ARM to deploy both SignalR service and Azure function. I am using below line in appsetting section of Azure function:

 "SignalRServiceUrl": "[reference(resourceId('Microsoft.SignalRService/SignalR', parameters('serviceName'))).primaryKey]"

**Comment by juniwang** [comment]
I'm sorry you cannot.  For security reasons,  connection string/access keys operations must be separated APIs. They won't be included in SignalR service meta.

**Comment by sonumalik1990** [comment]
azure cli is not installed on my build/release agents, So can I use powershell code to perform above operation.

Please suggest as I am not getting much help from google regarding reading signalR service connection string from powershell.

**Comment by sonumalik1990** [comment]
When I am using below command on VSO agent's task, then every time it told to execute "az login" to set up account.
az signalr key list --name <SignalRServiceName> --resource-group <ResourceGroup>

How its possible to set up an account while running task on VSO agent.

On local, I can do that by putting code in browser and start executing the commands.

Please suggest.

**Comment by xscript** [comment]
Close old issue.
@sonumalik1990 Feel free to reopen it if you have further questions.

**Comment by sonumalik1990** [comment]
Its Done 

Thanks

Sorry for commenting in close issue, 

Can you please help me in syncing azure search with Azure sql db.

I have done this using SQL Integrated Change Tracking Policy, but it updates the azure search in some time for ex 3 to 4 minutes.

In my scenario, I have to update Azure search asap(without manual running of indexer).

Is it possible to update automatically in few seconds, if yes then how??

**Comment by xscript** [comment]
@sonumalik1990 I am afraid we don't have the expertise in Azure SQL Server or Azure Search. You may leave you questions at Azure SQL or Azure Search's documentation page at https://docs.microsoft.com/azure. Then the document owners will follow up with you.

**Comment by surabhshah** [comment]
@sonumalik1990 ,

In case you are still stuck with getting SignalR access key in ARM template, you can get the primary key as below.

````
listKeys(resourceId('Microsoft.SignalRService/SignalR', parameters('name')), providers('Microsoft.SignalRService','SignalR').apiVersions[0]).primaryKey
````

Complete template could be found [here](https://github.com/surabhshah/ARMTemplates/blob/master/SignalRDeploy.json)

Hope it helps!

Surabh

**Comment by juniwang** [comment]
@subbarayudukamma Good to learn that!

**Comment by Aluui** [comment]
@sonumalik1990 can you please post your full solution for us? or link to the ARM template you used in creating your
1. SignalR service
2. Azure function for SignalR
3. connecting the azure function to the signalR service

**Comment by Zenuka** [comment]
For anybody who gets here from google; I used surabhshah's [answer above](https://github.com/Azure/azure-signalr/issues/134#issuecomment-403728843) to fetch the connection string like this:
```
[listKeys(resourceId('Microsoft.SignalRService/SignalR', variables('signalrName')), providers('Microsoft.SignalRService','SignalR').apiVersions[0]).primaryConnectionString]
```
Documentation about the return object of `listkeys`: https://docs.microsoft.com/en-us/rest/api/signalr/signalr/listkeys
