### ISSUE TITLE
Question : Multiple Instances of Azure Signal R

### ISSUE THREAD

**Issue by Dewaldf** [Azure/azure-signalr#1345]
Hi, 
Reading through the [documentation ](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-multi-instances) on scaling the azure signal r service to more than one instance, we require this because we are looking at supporting > 100k users .

My understanding of the documentation is I just add an additional connectionstring. 
```
services.AddSignalR()
        .AddAzureSignalR(options => 
        {
            options.Endpoints = new ServiceEndpoint[]
            {
                // Note: this is just a demonstration of how to set options.Endpoints
                // Having ConnectionStrings explicitly set inside the code is not encouraged
                // You can fetch it from a safe place such as Azure KeyVault
                new ServiceEndpoint("<ConnectionString0>"),
                new ServiceEndpoint("<ConnectionString1>", type: EndpointType.Primary, name: "east-region-a"),
                new ServiceEndpoint("<ConnectionString2>", type: EndpointType.Primary, name: "east-region-b"),
                new ServiceEndpoint("<ConnectionString3>", type: EndpointType.Secondary, name: "backup"),
            };
        });
```

Do I have to implement a custom router, or will the default router handle this for me (if yes, how ?) ? Ideally I do not want to be sharding based on user location etc.

If there is any more documentation around scaling past 2 instances it would really help.

**Comment by Y-Sindo** [comment]
> By default, the SDK uses the DefaultEndpointRouter to pick up endpoints.

The default router handles this for you. The [document](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-multi-instances#default-behavior) already contains a section about the behaviour of the default router. Do you have more detailed questions about the routing behaviour?

**Comment by vicancy** [comment]
Please feel free to reopen it if there are any updates.
