### ISSUE TITLE
Failing to connect via WebSockets from SPA (Firefox & Safari)

### ISSUE THREAD

**Issue by mikesitch** [Azure/azure-signalr#135]
Hi,

We use Azure SignalR service from our angular SPA (using node package @aspnet/signalr) client, server is a DotNetCore 2.1 app using NuGet package 1.0.0-preview1-10011.

Everything works fine in Chrome and Edge and we connect to AzureSignalR service using WebSockets.  However we get a 401 from Firefox and Safari (latest versions) and so fall back to server sent events.

Is this a known issue.

Thanks for the help.

**Comment by xscript** [comment]
It shouldn't happen. Could you capture a HAR file from Firefox?

**Comment by xscript** [comment]
@mikesitch Confirm this is a bug in service run-time. We will fix it and deploy in the coming deployment,

**Comment by mikesitch** [comment]
Thanks for confirming.  Will wait for Preview1.

**Comment by xscript** [comment]
We have planned a release next week. But it is not guaranteed because a lot of changes are going on. Will update here once the deployment is done.
BTW, which region are you in?

**Comment by mikesitch** [comment]
Good news.  West Europe (until UK South becomes available).

**Comment by xscript** [comment]
@mikesitch Fix has been deployed to all instances. Please try again to double confirm.
