### ISSUE TITLE
Seemingly random failures

### ISSUE THREAD

**Issue by carlbm** [Azure/azure-signalr#1356]
### Describe the bug
I have a blazor server app hosted on an Azure App Service, using Azure SignalR, and also a SignalR client running.
This has been working fine for about 8 months. This morning I'm getting random connection issues with SignalR.
The response from the server is 500, and digging into the Azure diagnostics this is the only thing that looks relevant

![image](https://user-images.githubusercontent.com/2923969/126135989-ee1a0fe4-91ff-4347-b948-62a8f12f048a.png)

I've restarted the SignalR service, but the connection errors are still present.

What do NoAvailableServerConnection and ServerConnectionClosed mean? And how do I prevent them from happening?

### Further technical details
- Your Azure SignalR SDK version
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` Microsoft.AspNetCore.SignalR.Client - 5.0.2
- Your SignalR Client SDK version 1.7.0

**Comment by vicancy** [comment]
Is the issue persistent?

Could you email me `lianwei(at)microsoft.com` your instance id and the time stamp when the error happened for me to take a look?

`NoAvailableServerConnection ` and `ServerConnectionClosed ` generally mean the app server side fails to connect to the Azure SignalR Service. It can be a transient network issue, or sometimes Azure SignalR service doing its regular maintenance, or app server-side is doing maintenance or auto-scale and shut down some app instances. Server connections always "reconnect" so usually, such `ServerConnectionClosed` exception has little impact on the application layer.

**Comment by vicancy** [comment]
Please feel free to reopen it if there are any updates.
