### ISSUE TITLE
EndpointMetrics.ClientConnectionCount and Name fields don't show correct values

### ISSUE THREAD

**Issue by yigitgursoy** [Azure/azure-signalr#1367]
### Describe the bug
endpoint.EndpointMetrics.ClientConnectionCount and endpoint.Name fields don't return correct values.

### To Reproduce

```csharp
public class TestRouter : EndpointRouterDecorator
{
	private readonly Logging.Abstractions.ILogger<TestRouter> _logger;

	public TestRouter(Logging.Abstractions.ILogger<TestRouter> logger)
	{
		_logger = logger;
	}

	public override ServiceEndpoint GetNegotiateEndpoint(HttpContext context, IEnumerable<ServiceEndpoint> endpoints)
	{
		var endpoint = endpoints
			.OrderBy(p => p.EndpointMetrics.ClientConnectionCount)
			.FirstOrDefault(p => p.Online && p.EndpointType == EndpointType.Primary);

		if (endpoint == null)
		{
			throw new AzureSignalRNotConnectedException();
		}

		_logger.Log(LogLevel.Information,
			$"EndpointMetrics.ClientConnectionCount: {endpoint.EndpointMetrics.ClientConnectionCount}, Endpoint: {endpoint.Name}", Guid.Empty);

		return endpoint;
	}
}
```

I've opened 100 connections to the hub and I can see 100 lines in Application Insights logs.
However, incorrect values are logged as shown in the image below:

![Logs](https://i.imgur.com/cRwWQ6K.jpeg)

### Exceptions (if any)
No exceptions

### Further technical details

- Your Azure SignalR SDK version

Nugets:
Microsoft.Azure.SignalR v1.8.2
Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson v5.0.7

- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 

Project Sdk -> Microsoft.NET.Sdk.Web
TargetFramework -> netcoreapp3.1
RuntimeIdentifier -> win-x64

The application is hosted on Azure.

- Your SignalR Client SDK version

Javascript client

**Comment by JialinXin** [comment]
The `Name` property is coming from the `ServiceEndpoint`. It's decided by how you set the endpoints. 

From the snapshot, it seems the **aux** and **base** are set like
```
new ServiceEndpoint("<ConnectionString1>", type: EndpointType.Primary, name: "aux")
```
And the empty ones are set like this without `Name` assigned and regard as empty name, which probably comes from some default secret stores you doesn't aware, like secret.json or appsettings.json.
```
new ServiceEndpoint("<ConnectionString1>")
```

Another easy way to get endpoint information is directly use `endpoint.ToString()` where we've override the `ToString()` method to provide endpoint information. So you can further check what endpoints are using.

**Comment by yigitgursoy** [comment]
@JialinXin thanks for pointing that out. However, I still don't see ClientConnectionCount being updated for every connection request. Please check the image below:

![Logs](https://i.imgur.com/GL0G3NX.png)

**Comment by JialinXin** [comment]
The delay is expected because the value is get updated by round-trip pings between server-service whose interval is 10 seconds.

**Comment by yigitgursoy** [comment]
Thanks @JialinXin
