### ISSUE TITLE
In using ASRS Migration Feature I found that Context?.GetHttpContext()?.Features?.Get<IConnectionMigrationFeature>() object is always null

### ISSUE THREAD

**Issue by junedans** [Azure/azure-signalr#1374]
### Describe the bug
While testing the migration feature of ASRS I always find that Context?.GetHttpContext()?.Features?.Get<IConnectionMigrationFeature>() object is null

### To Reproduce
Create 2 sample Hub with Azure SignalR SDK that supports migration feature. Have them both connect to same ASRS endpoint. Connect a client to hub1 and hit ctrl+c to initiate shutdown for hub1 and see the client migrate and connect to hub2 and now put a debug point there. When debugging you will see that the features object is always null

**Comment by terencefan** [comment]
#1373

**Comment by junedans** [comment]
Thanks for the quick turn around!
