### ISSUE TITLE
SignalR Service Message Limit Error 

### ISSUE THREAD

**Issue by f9analytics** [Azure/azure-signalr#1411]
### Describe the bug
Getting a message error limit on message size 199kb. Azure SignalR Services explicitly states no message limit.

Please explain?

**Comment by f9analytics** [comment]
{"type":3,"invocationId":"1","error":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:c2518331-0002-0085-7039-993277000000\nTime:2021-08-24T22:43:30.3745938Z\r\nStatus: 400 (Bad Request)\r\nErrorCode: PropertyValueTooLarge\r\n\r\nContent:\r\n{\u0022odata.error\u0022:{\u0022code\u0022:\u0022PropertyValueTooLarge\u0022,\u0022message\u0022:{\u0022lang\u0022:\u0022en-US\u0022,\u0022value\u0022:\u0022The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\\nRequestId:c2518331-0002-0085-7039-993277000000\\nTime:2021-08-24T22:43:30.3745938Z\u0022}}}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nTransfer-Encoding: chunked\r\nServer: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: c2518331-0002-0085-7039-993277000000\r\nx-ms-client-request-id: a1895b3d-80c9-4269-bca6-a93e7767f699\r\nx-ms-version: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nPreference-Applied: REDACTED\r\nDate: Tue, 24 Aug 2021 22:43:29 GMT\r\nContent-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8\r\n"}

**Comment by f9analytics** [comment]
[https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-messages-and-connections#:~:text=Azure%20SignalR%20Service%20has%20no%20size%20limit%20for,splitting%20and%20assembling.%20No%20developer%20efforts%20are%20needed.](url)

**Comment by f9analytics** [comment]
> Message size
Azure SignalR Service has no size limit for messages.

**Comment by Y-Sindo** [comment]
The error is not returned from Azure SignalR and is the method invocation result. I searched "PropertyValueTooLarge" error and found similar result from Azure Storage Table. Do you use it?

**Comment by f9analytics** [comment]
> The error is not returned from Azure SignalR and is the method invocation result. I searched "PropertyValueTooLarge" error and found similar result from Azure Storage Table. Also I found `Server: Windows-Azure-Table` in your response. So I guess it is a message from Azure Storage Table.

That is correct. We noticed it after the post. Thank you.
