### ISSUE TITLE
Run Code clean up on these projects

### ISSUE THREAD

**Issue by genifycom** [Azure/azure-signalr#1441]
It would be really nice if code clean up was run on these github projects to remove all of the useless using statements.

Using statements provide developer guidance on dependencies that are ACTUALLY used.

In Visual Studio it is a one step process. Select the solution and use Analyze and Code Cleanup.

It makes source code smaller and more relevant.

Please!

**Comment by terencefan** [comment]
#1444

**Comment by genifycom** [comment]
Does this mean that it will get done? Or it is to be ignored?
