### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by genifycom** [Azure/azure-signalr#1442]
Please can someone explain why they would write 4 lines of code instead of one?

Example:

        if (keepAlive == null || !metadata.Connection.SupportsKeepAlive)
            {
                return false;
            }

This is 4 lines, an if clause, an open block, a return clause and a close block.

This should be a single readable statement i.e. an if and a single simple result.

        if (keepAlive == null || !metadata.Connection.SupportsKeepAlive) return false;

This makes it easier to read, easier to understand and is more concise. 

The only argument I have heard is "well you might want to add additional statements to the result". My answer is that in that case ADD A BLOCK! Blocks should be for more than one statement i.e. a COMPOUND statement. When a diff is performed, it will be clear to the reader that this if statement was converted from the simple statement to a compound statement and we expect to see multiple actions.

This is not Javascript this is C#

"To have more than one statement execute after an if statement that evaluates to true, use braces, like we did with the body of the main function. Anything inside braces is called a compound statement, or a block. When using if statements, the code that depends on the if statement is called the "body" of the if statement."

https://www.cprogramming.com/tutorial/c/lesson2.html

**Comment by terencefan** [comment]
The link is for C, C and C# are not the same, thus they followed different coding conventions.

[C# layout conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#layout-conventions)
