### ISSUE TITLE
New TransportManager type proxiedWebSockets?

### ISSUE THREAD

**Issue by genifycom** [Azure/azure-signalr#1443]
I need to add a new TransportManager and I am looking for some ideas for naming.

This transport manager will receive an HTTP request which includes the message and the WebSocket connection id.

KeepAlive will be false.

The response will be a PostToConnectionAsync (an AmazonApiGatewayManagementApiClient function).

This is currently specific to the AWS environment where the HTTP requests are proxied through the AWS WebSockets API Gateway (see https://gavinlewis.medium.com/getting-started-with-websockets-on-api-gateway-with-net-and-the-serverless-framework-9065f37d06e0 for how this works). The WebSockets API Gateway manages the connections (like the Azure SignalR service).

I expect that with better load balancing this will be a future trend and this is a requirement to use SignalR in an AWS Serverless environment. The aim is to get Blazor Server-Side working in AWS.

How would proxiedWebSockets sound?

**Comment by genifycom** [comment]
Perhaps in Transportmanager

`        /// <summary>
        /// Initializes a new instance of <see cref="TransportManager"/> class.
        /// </summary>
        /// <param name="resolver">The default <see cref="IDependencyResolver"/>.</param>
        [SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Justification = "Those are factory methods")]
        public TransportManager(IDependencyResolver resolver)
        {
            if (resolver == null) throw new ArgumentNullException("resolver");

            Register("foreverFrame", context => new ForeverFrameTransport(context, resolver));
            Register("serverSentEvents", context => new ServerSentEventsTransport(context, resolver));
            Register("longPolling", context => new LongPollingTransport(context, resolver));
            Register("webSockets", context => new WebSocketTransport(context, resolver));
            Register("proxiedWebSockets", context => new ProxiedWebSocketTransport(context, resolver)); //TODO
        }`

**Comment by vicancy** [comment]
This sounds more SignalR related instead of Azure SignalR related. Could you try opening a design proposal in aspnetcore repo https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=design-proposal&template=40_design_proposal.md instead?

**Comment by vicancy** [comment]
A SignalR frame is not necessarily a WebSocket frame, so one challenge for a serverless scenario is that how you guarantee message stickiness to your backend "serverless" app.

**Comment by genifycom** [comment]
Hi Vicancy,

In AWS, the Websockets API Gateway manages the sticky connection for us. We only have to deal with the connection id passed by the API Gateway.

Now the AWS Websockets API Gateway only manages Websockets, so yes there would be no backdown to long polling or SSE.

**Comment by genifycom** [comment]
I have create the design doc. Thanks for the info :)

**Comment by vicancy** [comment]
> In AWS, the Websockets API Gateway manages the sticky connection for us. We only have to deal with the connection id passed by the API Gateway.

So you have to make sure messages for one connection id always go to your same backend server otherwise your backend server might receive a partial message frame and failed to parse it using SignalR protocol
