### ISSUE TITLE
Microsoft.Azure.SignalR.Management has dependency on AspNetCore

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-signalr#1476]
I created a .net 5.0 console app, it uses the SDK to send messages to SignalR clients(Serverless Mode). After added Microsoft.Azure.SignalR.Management to project, the target runtime was changed to Microsoft.AspNetCore.App automatically, I got following error while running.
```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - No frameworks were found.
```
Anyway to use the SDK in console app without AspNetCore runtime?

**Comment by vicancy** [comment]
Failed to repro. 

The commands trying to repro:
```
dotnet new console
dotnet add package Microsoft.Azure.SignalR.Management
dotnet build
```

The project is built successfully without Project SDK auto-changed.

**Comment by zhiweiv** [comment]
@vicancy 
The problem is at [xxx].runtimeconfig.json under bin\Debug\net5.0, after you added this package the content of  runtimeconfig.json will be changed 

from 
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "5.0.0"
    }
  }
}
```
to
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "5.0.0"
    }
  }
}
```

**Comment by zhiweiv** [comment]
In .net 6.0, the content is below after added this package 
```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "6.0.0"
      }
    ]
  }
}
```

**Comment by vicancy** [comment]
Thanks for the explanation, yes, reproed. I think the root cause is https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj#L35. @Y-Sindo could you check if we can get rid of this FrameworkReference?

**Comment by zhiweiv** [comment]
Any update?

**Comment by Y-Sindo** [comment]
@zhiweiv I don't think we can remove the framework reference as we depend on ASP.NET Core framework. However, you might want to try to publish your app as self-contained so that it doesn't depend on ASP.NET Core runtime even the .NET runtime. See [Publish self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) for more details.

**Comment by Y-Sindo** [comment]
@vicancy `Microsoft.AspNetCore.SignalR` is also in the list that are no longer published. I think `<FrameworkReference>` is the only way to reference API in ASP.NET Core API. 
> [With the release of .NET Core 3.0, many ASP.NET Core assemblies are no longer published to NuGet as packages. Instead, the assemblies are included in the Microsoft.AspNetCore.App shared framework, which is installed with the .NET Core SDK and runtime installers.](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio#use-the-aspnet-core-shared-framework)

**Comment by zhiweiv** [comment]
> @zhiweiv I don't think we can remove the framework reference as we depend on ASP.NET Core framework. However, you might want to try to publish your app as self-contained so that it doesn't depend on ASP.NET Core runtime even the .NET runtime. See [Publish self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) for more details.

In my use case, I referenced this library in our common library, any project in our company which uses the common library will be forced to run under asp.net core runtime, even if it doesn't use the SignalR part. There are a few solutions to avoid this, but all tricky.

Anyway since it is can't be fixed in this library, I will close this issue, thanks for the information.
