### ISSUE TITLE
Azure SignalR client disconnect with error - Message rate reaches limit.

### ISSUE THREAD

**Issue by AjitBhosale** [Azure/azure-signalr#149]
Using Azure SignalR service.

Message rate - 1 messages per 100 milliseconds.

Getting error in C# client which send message to Azure SignalR service.

connected successfully and able to receive and send messages but after some time(5 seconds) getting error on sender side continuously - "The server closed the connection with the following error: Message rate reaches limit."

Trying to reconnect in OnClose event but getting same error continuously after 5 seconds.

The Azure SignalR receiver client work properly without disconnect but getting issue in sender client.

From Azure SignalR metrics is there any way to see it's message limits or per second limit?

It work properly if i host asp.net core SignalrR in web app instead of using Azure SignalR.

This issue occur with both Azure SignalR Free and Standard(Paid) Tier.

**Comment by xscript** [comment]
What's the size of your message? I guess they are over 10 KB?

**Comment by xscript** [comment]
Use this issue to track the work of updating message rate limit. The fix is ready and will be rolled out in the next deployment.

**Comment by xscript** [comment]
@AjitBhosale  We have removed the message rate limit in production. Please help check from your side.

**Comment by xscript** [comment]
Close this issue as there is no response for over a week.
