### ISSUE TITLE
Can not get request headers in Hub(Context.GetHttpContext) using Azure SignalR

### ISSUE THREAD

**Issue by dreamofmaks** [Azure/azure-signalr#1495]
I am using Azure SignalR, and i can not get request headers in my hub class. I was trying to do that using Context.GetHttpContext() method. but it was not successful. Can anyone help me? Thank you.

**Comment by vicancy** [comment]
It should be in `Context.GetHttpContext().Request.Headers`.
![image](https://user-images.githubusercontent.com/668244/141729326-1aa2d8cb-a3d5-48b7-847c-f3574810856f.png)

Which header do you want? Are you using AspNetCore SignalR or AspNet SignalR?

**Comment by MaxxDelusional** [comment]
I am seeing this too. I set custom headers when creating my hub connection in my Blazor WASM app.

```
hubConnection = new HubConnectionBuilder()
    .WithUrl(Nav.ToAbsoluteUri("/hub"), (conn) =>
    {
        conn.Headers.Add("headerName", "headerValue");
    })
    .Build();
```
But this custom header is not present in `Context.GetHttpContext().Request.Headers`.

**Comment by vicancy** [comment]
@MaxxDelusional I did a quick try and the headers are included in `Context.GetHttpContext().Request.Headers`. 
C# client (tried both Microsoft.AspNetCore.SignalR.Client 3.1.25 and 6.0.5)
![image](https://user-images.githubusercontent.com/668244/169939186-96617d90-8869-45ac-a2c9-5a3746a22b04.png)
And server hub can get the custom header through `Context.GetHttpContext().Request.Headers`
![image](https://user-images.githubusercontent.com/668244/169939110-31331d98-db11-4aad-a3f5-b4937a6e459c.png)

Could you provide me with a minimum project that can repro the issue you described?

**Comment by MaxxDelusional** [comment]
@vicancy where are you reading the headers in your hub? Are they available in OnConnectedAsync?

I believe the problem might be caused by web sockets. I am not sure that web sockets support custom headers.

**Comment by vicancy** [comment]
@MaxxDelusional It's indeed in OnConnctedAsync, but I am using a normal SignalR project instead of a blazor WASM project though. A minimum project that can repro the issue is very much appreciated.

**Comment by jiaming0708** [comment]
I am also using the SignalR in Blazor WASM, add custom header on client, in my expection, there should have `jimmy` in the header, unfortunate there have any custom header, do you have any idea to resolve?

my code
![image](https://user-images.githubusercontent.com/8855285/188583365-53c15c7f-8f78-4f49-92a4-9b68fdd8f893.png)

network request
![image](https://user-images.githubusercontent.com/8855285/188584340-0d5275ff-e185-40a1-a5fd-35179b4dea31.png)

**Comment by BrennanConroy** [comment]
You can't set headers on WebSocket requests in the browser. This is a limitation of the browser and not something SignalR can fix. See https://github.com/whatwg/websockets/issues/16 if you're passionate about browsers supporting this.

**Comment by jiaming0708** [comment]
> You can't set headers on WebSocket requests in the browser. This is a limitation of the browser and not something SignalR can fix. See [whatwg/websockets#16](https://github.com/whatwg/websockets/issues/16) if you're passionate about browsers supporting this.

Thanks for your information, I think I should set the data on sending.
