### ISSUE TITLE
WebSocket connection gets disconnected

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-signalr#150]
I'm trying to connect to Azure Signalr directly using WebSockets with Java (as the Java client is not ready yet), I manage to get a WebSocket connection with a successful handshake but after a few seconds the server closes the connection (error code: 1000). During the time the connection is open, if I send a message (to the same hub) using the REST API I receive an InternalServerError as a response, after the WebSocket connection is closed, the REST API works as expected.

For the webSocket connection I'm using "org.java-websocket" lib (https://github.com/TooTallNate/Java-WebSocket) connection to wss://MY_HOST_URI:5001/client/?hub=testhub and sending the JWT Bearer token header (created with https://MY_HOST_URI:5001/client/?hub=testhub as audience, trying to roughly follow the "Serverless" sample client's code).

Is this the expected behaviour or maybe direct WebSocket connection is ready to use yet or I'm just not connecting following the right steps/using the right credentials?

**Comment by xscript** [comment]
@pizerg Could you provide more details to help us troubleshoot? For example, the frames going through the WebSocket connection.

The `InternalServerError` might be another issue. We have fixed it and the fix is being deployed across all regions. Is it convenient for you to provide your instance name so that we can confirm from our side?

**Comment by pizerg** [comment]
@xscript Here's the log when I enable DEBUG mode on the websockets lib:

```
write(517): {GET /client/?hub=testhub HTTP/1.1
Authorization: Bearer TOKEN_HERE
Connection: Upgrade
Host: MY_HOST_URI:5001
Sec-WebSocket-Key: WS_KEY
Sec-WebSocket-Version: 13
Upgrade: websocket

}
process(183): {HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Date: Wed, 01 Aug 2018 07:28:49 GMT
Server: Kestrel
Upgrade: websocket
Sec-WebSocket-Accept: WS_ACCEPT

}
open using draft: Draft_6455 extension: DefaultExtension protocol: 
Connection lost timer started
Connected to https://MY_HOST_URI:5001/client/?hub=testhub
process(4): {��}
afterDecoding(2): {�}
matched frame: Framedata{ optcode:CLOSING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:2], payload:�}code: 1000
send frame: Framedata{ optcode:CLOSING, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:2], payload:�}code: 1000
afterEnconding(2): {�}
write(8): {��%�*&�}
Connection lost timer stopped
Connection Closed code: 1000  remote: true
```

Regarding the instance name, provide me with an email or something to send it privately

**Comment by xscript** [comment]
You can send your instance name to `kevinzha<at>microsoft.com` (replace `<at>` with `@` ). Thanks!

**Comment by pizerg** [comment]
@xscript I managed to connect and send/receive messages, thank you for your help! Also I can confirm that the InternalServerError seems to be gone.

I'm closing the issue.
