### ISSUE TITLE
Getting "Azure SignalR Service is not connected yet, please try again later." when upgrading Microsoft.AspNetCore.Http.Connections.Client to 6.0.0.0

### ISSUE THREAD

**Issue by chrfin** [Azure/azure-signalr#1503]
### Describe the bug
I have a classic ASP.NET MVC project targeting .NET 4.7.1 using SignalR and `Microsoft.Azure.SignalR.AspNet`.
If I upgrade `Microsoft.AspNetCore.Http.Connections.Client` from 5.0.12.0 to 6.0.0.0 I get the following error with status code 500 when the client calls `/negotiate`:
> Azure SignalR Service is not connected yet, please try again later.

### To Reproduce
Create a classic ASP.NET MVC project and use the packages mentioned above.

### Exceptions (if any)
I do not get any exceptions, just the mentioned 500 during negotiation.

### Further technical details
I'm using 1.13.0 of the `Microsoft.Azure.SignalR.AspNet` package and when I enable logging like described [HERE ](https://github.com/Azure/azure-signalr/blob/c764ee716b0b6079d4085c1c68d02c29be3c8aea/docs/tsg.md#500_error_when_negotiate)I get the following log entry:
> Microsoft.Azure.SignalR Error: 0 : [Microsoft.Azure.SignalR.AspNet.ServiceConnection]Failed to connect to '(Primary)https://MY-SERVICE.service.signalr.net', will retry after the back off period. Error detail: Method 'get_Features' in type 'Microsoft.Azure.SignalR.WebSocketConnectionContext' from assembly 'Microsoft.Azure.SignalR.Common, Version=1.13.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.. Method 'get_Features' in type 'Microsoft.Azure.SignalR.WebSocketConnectionContext' from assembly 'Microsoft.Azure.SignalR.Common, Version=1.13.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.. Id: a23d8224-6c1d-4ef7-bbe0-5f150a299275

I guess there was a property changed with v6 of the `Microsoft.AspNetCore.Http.*` classes.
If you can't reproduce with the given information, please tell me and I will create a repro-repo 🤓.

**Comment by vicancy** [comment]
Looks causing by https://github.com/dotnet/aspnetcore/issues/32307 that in 6.0 [ConnectionContext](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Connections.Abstractions/src/BaseConnectionContext.cs#L26) this `IFeatureCollection Features` is considered to be in assembly `Microsoft.Extension.Features`
![image](https://user-images.githubusercontent.com/668244/144812243-b78966d5-8704-4c77-b27e-b086bdc0066f.png)

However `WebSocketConnectionContext` implements `Features` in assembly `Microsoft.AspNetCore.Http.Features`
![image](https://user-images.githubusercontent.com/668244/144812445-c2ed4acc-a829-403e-8b13-975556d9018c.png)

As a result, it believes `get_features` is not implemented. 

Hi David @davidfowl, do you have insights on how to handle such breaking changes?

**Comment by vicancy** [comment]
There is an on-going effort to fix this issue as tracked in https://github.com/dotnet/aspnetcore/issues/38699

**Comment by chrfin** [comment]
Update, as I just hit the same error again trying to update some dependencies:

The following three packages are required to be kept below v6.\*:  
\* Microsoft.AspNetCore.Connections.Abstractions  
\* Microsoft.AspNetCore.Http.Connections.Common  
\* Microsoft.AspNetCore.Http.Connections.Client

The newest v5.\* as to date is 5.0.17 and does still work.

**Comment by chrfin** [comment]
@vicancy / @davidfowl Any update on this? v5.0.17 is now deprecated and v8.0.2 still does not work...

**Comment by jaydgus** [comment]
> @vicancy / @davidfowl Any update on this? v5.0.17 is now deprecated and v8.0.2 still does not work...

Did you get the latest assemblies to work?

**Comment by ionelr** [comment]
> > @vicancy / @davidfowl Any update on this? v5.0.17 is now deprecated and v8.0.2 still does not work...
> 
> Did you get the latest assemblies to work?

I just tried with those 3 packages versions 8.0.2 and 8.0.5 (latest), they DO NOT work
5.0.17 (deprecated) works
issue still present

**Comment by jaydgus** [comment]
> The following three packages are required to be kept below v6.*:
> * Microsoft.AspNetCore.Connections.Abstractions
> * Microsoft.AspNetCore.Http.Connections.Common
> * Microsoft.AspNetCore.Http.Connections.Client
> 
> The newest v5.* as to date is 5.0.17 and does still work.

This is still an issue. I updated our nugets and it broke the client-side signalR negotiation. I had to roll these 3 back to 5.0.17 to get it to work.

**Comment by jaydgus** [comment]
Did this get resolved or just closed? Did this package's support end?

**Comment by vicancy** [comment]
The code fix is in. We will release a stable version of the package after validation cycle. Please allow me to update the package status once its released.

**Comment by vicancy** [comment]
https://www.myget.org/feed/azure-signalr-dev/package/nuget/Microsoft.Azure.SignalR.AspNet contains the preview version containing the fix, we will release a stable version after validation workflow.

**Comment by vicancy** [comment]
1.28.0 https://www.nuget.org/packages/Microsoft.Azure.SignalR.AspNet containing the fix is released.

**Comment by jaydgus** [comment]
Awesome, thanks for the update!

**Comment by chrfin** [comment]
👍 I can confirm it works now, thanks 😎

**Comment by marafiq** [comment]
I am hitting this error after I upgraded to use Microsoft.Extensions.* 9.0.0.2 packages due to dependency from Azure App Configuration. Did anyone tried it with 9.x packages.

**Comment by Y-Sindo** [comment]
> I am hitting this error after I upgraded to use Microsoft.Extensions.* 9.0.0.2 packages due to dependency from Azure App Configuration. Did anyone tried it with 9.x packages.

@marafiq Look like a new issue. Could you please open a new issue, providing a minimal reproducible project, or any error message during runtime that you believe is related to the failure?
