### ISSUE TITLE
web socket connection not working  for long query string

### ISSUE THREAD

**Issue by nithinkd-geon** [Azure/azure-signalr#151]
we are facing  similar issue in azure signalr service that is referenced below
https://github.com/aspnet/SignalR/issues/1747

when we try to connect with smaller query string by reducing hub name length it start working in wss in other cases it downgraded to sse

**Comment by vicancy** [comment]
Thanks for reporting the issue. We will take a look and get back to you.

**Comment by vwxyzh** [comment]
@nithinkd-geon how large is you request line?
Is it limited by browser (IE is 2K, [see most browsers URL length limit](https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string))?
We will increase the [max request line size](https://github.com/aspnet/KestrelHttpServer/blob/release/2.2/src/Kestrel.Core/KestrelServerLimits.cs#L92) to 16K (current limit is 8K), is it enough for your case?
And please make sure your app server can handle these requests.

**Comment by nithinkd-geon** [comment]
@vwxyzh  
currently we are using serverless method mentioned in the below example https://github.com/aspnet/AzureSignalRsamples/tree/master/samples/Serverless

building the hub url  from service and passes that into javascript client then client makes the connection

**Comment by vwxyzh** [comment]
@nithinkd-geon how large is your request line in web socket?
For web socket, your hub name and claims are parts of query string. 8k is enough for normal case, but if your hub name is very long, or your client has many claims, the request line will be exceeded.

**Comment by xscript** [comment]
We have increased the limit of request line size from 8 KB (default value) to 12 KB. It will be deployed soon.

**Comment by nithinkd-geon** [comment]
thank you..!

Regards.
*Nithin KD*

**Comment by xscript** [comment]
Fix has been deployed to all regions. Close this issue.

**Comment by dazinator** [comment]
This appears to remain an issue for "app service for windows containers." - where my application is running in a windows container under kestrel, but the azure IIS reverse proxy (not within my control) is imposing its default limit on query string size and rejecting signal-r websocket connections before they reach the container..
