### ISSUE TITLE
[serverless] - AddToGroup is failing when using transient to init ServiceManagerBuilder

### ISSUE THREAD

**Issue by shatsu8** [Azure/azure-signalr#1528]
### Describe the bug
getting an exception when calling `hub.Groups.AddToGroupAsync(id, groupName);` after creating the HubContext.

`var serviceManager = new ServiceManagerBuilder().WithOptions(option =>
{
option.ConnectionString = *******
option.ServiceTransportType = **ServiceTransportType.Transient;**

}).WithLoggerFactory(LoggerFactory.Create(builder => builder.AddConsole())).Build();`

### To Reproduce
when using ServiceTransportType.Transient getting the exception below. when I switched the ServiceTransportType to **Presistent** everything works as expected.

### Exceptions (if any)
System.NullReferenceException:
at Microsoft.Azure.SignalR.PayloadMessageContent+d__5.MoveNext (Microsoft.Azure.SignalR.Common, Version=1.14.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

### Further technical details
`<PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.14.0" />`

**Comment by Y-Sindo** [comment]
This is a known issue, fixed by #1519. Please wait for 1.15.0  release.
