### ISSUE TITLE
Unable to deliver messages to end users with Persistent connection configured

### ISSUE THREAD

**Issue by samushenkov** [Azure/azure-signalr#1539]
Hey there!

### Describe the bug
We are using Azure SignalR service (serverless mode) in combination with Azure Functions (isolated process). Also we have a standalone service that uses ServiceManager to send some realtime information for end users. Clients do not receive any messages if ServiceManager is configured to use **ServiceTransportType** in **Persistent** mode. Switching it back to Transient solves an issue.

### Further technical details
- Microsoft.Azure.SignalR.Management: 1.15.0
- @microsoft/signalr: 6.0.0

Do we need to make some extra configuration for persistent mode?

**Comment by Y-Sindo** [comment]
Is your client using MessagePack hub protocol?  Currently the message sent from Management SDK is in JSON format, and in `Transient` mode JSON is translating to MessagePack in Azure SignalR service side, but `Persistent` mode is more like server mode and doesn't have such a feature.

**Comment by samushenkov** [comment]
Thank you, @Y-Sindo! Disabling MessagePack on client side indeed solved an issue. Do you have any plans guys to make both these features work together? Didn't manage to find any information about such an incompatibility.

**Comment by Y-Sindo** [comment]
We will update the docs to remind users of the incompatibility. 

We do have plans to support MessagePack in `Persistent` mode, but we are still considering the design. Do you think you will need to customize MessagePack serialization later? Your feedback is important to our decision. Thank you very much.

**Comment by samushenkov** [comment]
In our case we are planning to have a pretty big stream of realtime updates (quotes / orders / positions / balances and so on...). That is why we decided to use binany protocol (MessagePack) + dto serialization (protobuf). Looks like SignalR service sends our binary data as base64 string and it doesn't depend on used protocol (MessagePack vs JSON). So disabling MessagePack increases messages only by size of metadata (payload is the same base64 string). We don't need to customize MassagePack serialization but it would be great to have a way to send bytes array as trueish binary message.

**Comment by Y-Sindo** [comment]
Hi @samushenkov ,  now MessagePack is also supported in the persistent mode. You could update your SDK to the latest version and follow [the guide here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#message-pack-serialization) to enable MessagePack in the persistent mode.
