### ISSUE TITLE
Set StatusCode on HttpRequestException

### ISSUE THREAD

**Issue by skystedt** [Azure/azure-signalr#1543]
Today Azure SignalR creates HttpRequestException where it writes the status code as a part of the exception Message.

Since .NET 5, the HttpRequestException has a property for StatusCode.

I would propose the StatusCode property of HttpRequestException should be set. To allow for easier access to the status code.
To avoid having to do string parsing on the Message.

For example here: https://github.com/Azure/azure-signalr/blob/master/src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs#L99

To be able to write code like below

```
[FunctionName("SendMessage")]
public static async Task SendMessage(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
    [SignalR(HubName = "chat")] IAsyncCollector<SignalRMessage> signalRMessages)
{
    try
    {
        await signalRMessages.AddAsync(
            new SignalRMessage
            {
                Target = "newMessage",
                Arguments = new[] { message }
            });
    }
    catch (AzureSignalRException ex) when (ex.InnerException is HttpRequestException httpException && httpException.StatusCode == HttpStatusCode.TooManyRequests)
    {
        // Status Code 429
        // Wait some time before trying again
    }
}
```

**Comment by vicancy** [comment]
> To avoid having to do string parsing on the Message

In which case would you do string parsing to which Message?

> Today when we create an HttpRequestException,

Could you describe more about when would you create an HttpRequestException when using Azure SignalR?

**Comment by skystedt** [comment]
I updated the post, providing more information and a use case
