### ISSUE TITLE
Empty `IHubContext<THub, T>.Clients.Users(userIds)` `userIds` array throws `Argument cannot be null or empty. (Parameter 'userIds')`

### ISSUE THREAD

**Issue by brbarnett** [Azure/azure-signalr#1544]
We run built-in SignalR locally, and Azure SignalR when deployed to Azure. Configuration:
```
var signalRServiceBuilder = builder.Services.AddSignalR();
if (builder.Environment.IsProduction())
{
    // only run Azure SignalR in higher-level environments
    signalRServiceBuilder.AddAzureSignalR(builder.Configuration.GetConnectionString("AzureSignalR"));
}
```

Calling `IHubContext<THub, T>.Clients.Users(userIds).Method` locally with an empty `userIds` array succeeds. When called after `AddAzureSignalR` (like we do in our cloud environments), it throws a `Argument cannot be null or empty. (Parameter 'userIds')` exception. 

I would expect that passing an empty array would not throw an exception, but really I think both APIs should match regardless of whether the empty array should throw.

**Comment by wanlwanl** [comment]
Hi @brbarnett the bug is fixed, please try https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.15.1

**Comment by brbarnett** [comment]
Thank you, @wanlwanl!
