### ISSUE TITLE
Azure Function V4 in .NET 6.0 does not seem to be working with the emulator

### ISSUE THREAD

**Issue by arashcomsense** [Azure/azure-signalr#1552]
### Describe the bug
Clone[ this repo](https://github.com/aspnet/AzureSignalR-samples/blob/main/samples/DotnetIsolated-BidirectionChat/Functions.cs) and configure the local.settings.json file to communicate with the emulator.  Nothing is working but the negotiation.

**Comment by Y-Sindo** [comment]
It works well when I test. Do you initialize the emulator upstream settings with `asrs-emulator.exe upstream init`?

**Comment by arashcomsense** [comment]
@Y-Sindo Yes I did initialize it. This is how the settings looks like:

```json
{
  "UpstreamSettings": {
    "Templates": [
      {
        "UrlTemplate": "http://localhost:7071/runtime/webhooks/signalr",
        "EventPattern": "*",
        "HubPattern": "*",
        "CategoryPattern": "*"
      }
    ]
  }
}
```

**Comment by Y-Sindo** [comment]
What is the transport type you use? `Persistent` type doesn't work for emulator.

**Comment by arashcomsense** [comment]
@Y-Sindo Yes, the transport type is `Persistent` per the following configuration:

```json
"AzureSignalRServiceTransportType": "Persistent",
```
Apparently that's why and we cannot use the emulator. Therefore the best way would be to use ngrok to have the SignalR Service's webhook divert the traffic to the local machine.

**Comment by Y-Sindo** [comment]
> Apparently that's why and we cannot use the emulator. Therefore the best way would be to use ngrok to have the SignalR Service's webhook divert the traffic to the local machine.

You could also try [Azure Relay](https://docs.microsoft.com/en-us/azure/service-bus-relay/relay-what-is-it#hybrid-connections) with this [local client tool](https://github.com/OfficeDev/microsoft-teams-tunnelrelay), which costs little and provides better GUI experience.

FYI: https://techcommunity.microsoft.com/t5/microsoft-teams-blog/introducing-tunnel-relay/ba-p/149990
