### ISSUE TITLE
"Request headers must contain only ASCII characters" in console when connecting to Azure SignalR Service

### ISSUE THREAD

**Issue by jojoman2** [Azure/azure-signalr#1555]
### Describe the bug
When I try to run an ASPNET Core project using Azure SignalR on my local machine, I get the following message:
fail: Microsoft.Azure.SignalR.ServiceConnection[2]
      Failed to connect to '(Primary)https://xxx.service.signalr.net', will retry after the back off period. Error detail: Unable to connect to the remote server. Request headers must contain only ASCII characters.. Id: d63dc5d6-898f-4adb-a960-c6e26f68e137
This also stops the Azure SignalR Client from connecting
It works on other machines.

I was able to check out this repo and reference it in my project and found the bug
![image](https://user-images.githubusercontent.com/2865861/154046676-36579e52-fbf4-4499-8692-9e2a19dfd8fa.png)
The X-ARS-Server-Id header was not ASCII because my machine's name contains a non ascii character. You should probably clean up non-ascii characters in that header

### To Reproduce
Try setting your computers name (Environment.MachineName) so that it contains non-ascii characters

### Exceptions (if any)
See above

### Further technical details
- Your Azure SignalR SDK version: 1.15.0
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 6.0
- Your SignalR Client SDK version N/A

**Comment by gavinbarron** [comment]
I just encountered this same error message when using SignalR in serverless mode with Azure Functions.

When a user with the character é in their given name, which is inside the jwt used as the access token I see logging in the Live Trace tool as : 
```json
{
  "time": "2023-05-10T17:32:42.9009282Z",
  "logLevel": "Warning",
  "eventName": "HttpInvocationFailed",
  "message": "Failed invoking 'https://<function-app-name>azurewebsites.net/runtime/webhooks/signalr?code=x' for 'hub:<hub-name>,event:disconnected,type:sys,category:connections,requestType:<request-type>'.",
  "exception": "Request headers must contain only ASCII characters."
}
```

This renders any processing of messages sent by these users via the function app non-functional as the function app is never called.

**Comment by Y-Sindo** [comment]
This error message "Request headers must contain only ASCII characters." doesn't come from our service, but a general limitation 
 of `HttpClient`.  
> In general, non-ASCII characters are disallowed by the RFC in header values. https://github.com/dotnet/runtime/issues/32482#issuecomment-587590210
