### ISSUE TITLE
Unable to connect, No server available

### ISSUE THREAD

**Issue by xscript** [Azure/azure-signalr#156]
Copied from https://github.com/aspnet/SignalR/issues/2772

**Comment by xscript** [comment]
@DibranMulder After looking at our backend logs, we've identified it was caused by intermittent connection issues to the Redis backplane. It should happen very rare. We are working on a fix right now.
The work around for now is to restart the the problematic app server to re-establish connections between your app server and SignalR Service.

**Comment by DibranMulder** [comment]
Ok thanks for the information. Please keep me posted with release schedules etc..

**Comment by xscript** [comment]
Fix has been deployed to all regions. Close this issue.
