### ISSUE TITLE
can a blazor wasm client connect to azure signalr 

### ISSUE THREAD

**Issue by dkboon01** [Azure/azure-signalr#1560]
I know this will work if I put the hub class either in .net core application or in blazor server application or in azure function.  My question  can  a the blazor wasm client  connect directly  to azure signalr service?  Is there an example?

**Comment by vicancy** [comment]
I think the way how a Blazor WASM client uses Azure SignalR service sounds the same as how a normal C# client uses the service. You can either have a hub server to host your hub logic or use the "serverless" mode of the Azure SignalR service, depending on your user scenarios.

**Comment by davidfowl** [comment]
Yes it can, just like the JS Client.
