### ISSUE TITLE
Does azure-signalrs support WebProxy?

### ISSUE THREAD

**Issue by gynet** [Azure/azure-signalr#162]
Does azure-signalrs support WebProxy and How?

**Comment by vicancy** [comment]
Hi @gynet, with WebProxy, are you talking about https://docs.microsoft.com/en-us/dotnet/api/system.net.webproxy?redirectedfrom=MSDN&view=netcore-2.1 specifically or https://en.wikipedia.org/wiki/Proxy_server in general?

Also, would you mind giving us a more detailed description on your needs and user scenarios using WebProxy?

**Comment by gynet** [comment]
Hi Vicancy, 

Yes, I am talking about https://docs.microsoft.com/en-us/dotnet/api/system.net.webproxy?redirectedfrom=MSDN&view=netcore-2.1

Does the SDK support webproxy for the ws connection between clients and Azure? 

https://docs.microsoft.com/en-us/previous-versions/aspnet/web-frameworks/jj918125(v=vs.111)

We have customers have very restricted networking environment and they want to use a proxy for all their connects.

**Comment by gynet** [comment]
@vicancy

**Comment by gynet** [comment]
Usually, an SDK should expose a WebProxy as configuration for customization settings

**Comment by gynet** [comment]
Thank you Vicancy. I will have a try

**Comment by gynet** [comment]
I tried to set up a proxy and looks like the traffic for Azure went through the proxy server.

**Comment by xscript** [comment]
@gynet Looks like everything works. Can we close this issue?

**Comment by gynet** [comment]
I tried and it works, closed
