### ISSUE TITLE
[RCA]Azure SignalR ServerLoad inaccurate [Resolved]

### ISSUE THREAD

**Issue by bjqian** [Azure/azure-signalr#1633]
### The impact
Customer may find the [Server Load metrics](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-performance#quick-evaluation-using-metrics) remains high even other metrics are showing the traffic is decreasing. This will impact the auto-scaling functionality if Server Load is used as a dimension. **The metrics will recover after several hours.**

### In what situation it will happen
This happens when the SignalR instance exits **abnormally**. The abnomal exit might be caused by OOM, sudden traffic spike. 

### The root cause
When the SignalR instance exits abnormally, the instance leaves a dirty record in the metrics. It should be cleaned up quickly. But an internal bug delays the cleaning up for **several hours**. This makes the metrics inaccurate.

### The fix
We will do the fix in next release. It will be done within **3 week**s.
> ⚠️ If the customer hopes to recover the metrics immediately, they could do a restart. **Be careful as this will disconnect all the existing connections!**

**Comment by jcbrooks92** [comment]
@bjqian did the deployment reach Azure Government yet?

**Comment by bjqian** [comment]
@jcbrooks92 Not yet. The estimated time for ff will be this weekend

**Comment by bjqian** [comment]
The release has finished
