### ISSUE TITLE
Guidance on upstream settings for an azure containerized function 

### ISSUE THREAD

**Issue by RbsTechOnline** [Azure/azure-signalr#1644]
Due to operational constraints, we need to run the upstream function inside a container on AKS.

*Environment* 
- Net 6
- Isolated
- Signalr Serverless mode
- Upstream
- Azure Containerized function 
- AKS with workflow identity, 
- Container has its own service principle. 

The only thing i am unsure about is the upstream URL and its code

`<host>/runtime/webhooks/signalr?code=<API_KEY>`

The host is fine.
I can access that route from postman  `/runtime/webhooks/signalr` though unauthorized, which is a good start. 

I am wondering if its possible to hook up the api-key ?

Are containerized upstream functions supported? or is there a work around?

**Comment by Y-Sindo** [comment]
Are you using [Azure Functions on Kubernetes with KEDA](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda)?

**Comment by RbsTechOnline** [comment]
@Y-Sindo Yeah the upstream singalr azure function is running in a container on AKS. the problem i am having in particular is the secret used in the upstream setting in the azure signalr service

http://host/runtime/webhooks/signalr?code=<secret>

I have progressed a little and figured that secret for  signalr is actually a system key which is found and backed by the AzureWebJobsStorage connectionstring in the azure function environment variables. 

Now i am just on a learning curve, of how to create and or allow the containerized function to use similar storage, to obtain a the system key, so the upstream setting of the azure signalr service can authenticate with that particular function system key. 

I.e i assume if i get this right, i should be able to call http://host/runtime/webhooks/signalr?code=<secret> from postman, and have it not return 401 or 500. 

Anyway, that is my working hypothesis for now, which makes this likely not a azure signalr serverless question. and more a azure containerized function on AKS question :/ 

However any help would be appreciated

**Comment by Y-Sindo** [comment]
If you confirm that you're using [KEDA](https://docs.microsoft.com/azure/azure-functions/functions-kubernetes-keda), then SignalR trigger is not supported according to [Supported triggers in KEDA](https://docs.microsoft.com/azure/azure-functions/functions-kubernetes-keda#supported-triggers-in-keda).

Implementing an HTTP trigger to handle SignalR requests might be a workaround, as the SignalR trigger is an HTTP trigger actually. You can refer to [serverless protocol](https://docs.microsoft.com/en-us/azure/azure-signalr/concept-upstream#serverless-protocols) for more details. But there is another concern that HTTP trigger seems to need more effort to auto-scale according to the [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda#http-trigger-support)

**Comment by RbsTechOnline** [comment]
@Y-Sindo thanks for your help, yeah, i think i am pushing this too far up hill, for little benefit
