### ISSUE TITLE
Failed to connect to '(Primary)https://<name>.service.signalr.net', will retry after the back off period. 

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-signalr#1650]
### Describe the bug
After a full day of successful operation, two of my three environments started throwing the following exception in multitude with my SignalR instance:

```
Failed to connect to '(Primary)https://<name>.service.signalr.net', will retry after the back off period. Error detail: Unable to connect to the remote server. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
```

### To Reproduce
Not sure if I could if I wanted to. It just started happening and would not stop.

Some notes:
- I was able to access `https://<name>.service.signalr.net` from my local environment without issue.
- Creating a new SignalR instance and pointing my connection string to that instance worked.  Maybe a DNS issue?

### Exceptions (if any)

Message:

```
Unable to connect to the remote server. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

### Further technical details
- Your Azure SignalR SDK version 1.4.0
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` net6.0
- Your SignalR Client SDK version 6.0.7

**Comment by Mike-E-angelo** [comment]
> Creating a new SignalR instance and pointing my connection string to that instance worked. 

So this worked for one of the broken environments, but when I deployed the new connection string to the other environment, they both started throwing errors.  Looks like a namespace issue of some sort.  So weird because it was working just fine all day.

Additionally, the two environments having the trouble are on the same AppService in different slots: Staging and Production.  The environment that works without issue (along with my local development environment) is on a different AppService altogether.

For further context, I have 10 Hubs and I've been using Standard instances.  I guess I should say I *had* 10 Hubs, as I am getting the feeling that if I consolidated everything into one hub that will address somehow help to address this issue. :P

**Comment by vicancy** [comment]
1. Does restart the app server work?
2. Any VNET/NSG settings in your app server
3. Any hints from your app server portal => "Diagnose and solve problems" => "Availability and Performance"?

**Comment by Mike-E-angelo** [comment]
HI @vicancy thank you for your review into this matter.

I spent some time complaining about this on Twitter and subsequently getting more information:
https://twitter.com/Mike_E_angelo/status/1553849819340410890

The excessive connections are apparently due to the number of hubs I have, of which there appears to be 5 created per hub.  That's 50 per environment which far exceeds the Free tier for testing.  Note that my hubs are categorized by feature and there are one-two methods per call.  As designs tend to be more "micro" these days I am sure I will not be the only developer running into this issue as time goes on.

As for the primary failure: 

1. Restarting the server was one of the first things I tried.  That did not work, unfortunately.  
2. I do have VNet applied for all my AppService resources
3. I will look into this to see if I can get the Free account working on Testing/Staging
4. This was one of the first places I looked but did not (and still do not) see anything obvious

So this appears to be a namespacing issue.  This is a rough sketch of my setup:

AppService1.azurewebsites.net -> my.service.signalr.net:
- Hub1
- Hub2
- Hub3
AppService1-staging.azurewebsites.net  -> my.service.signalr.net:
- Hub1
- Hub2
- Hub3

My guess is that it seems the hub names get registered twice with the same Azure SignalR server and these errors start to throw.  Using two separate servers solves this issue for now.

**Comment by vicancy** [comment]
So when you have different environments connecting to one Azure SignalR, you can configure different [ApplicationName](https://github.com/Azure/azure-signalr/blob/dev/docs/run-asp-net-core.md#applicationname) for different environments for them to share the same Azure SignalR instance.

Back to the issue described here "Unable to connect to the remote server.", it should not be related to the different environment though. Hub is a logic concept and there is no "register" needed. When app servers from different environments connect to the same Azure SignalR with the same hub name, Azure SignalR treat them as different instances of the same app server, so your production client traffic might be routed to your staging app server, which means they are not isolated.

If you have NSG or route tables to control the traffic flow, please further check the NSG(outbound rules) and route tables to check if connectivity to the target has been granted or not. A quick test is to disable NSG or route table and check if the web app could reach the target.

**Comment by Mike-E-angelo** [comment]
> so your production client traffic might be routed to your staging app server, which means they are not isolated.

Yes, there is a lovely Azure AppService limitation that ensures this to be the case:
https://github.com/MicrosoftDocs/azure-docs/issues/32922


> So when you have different environments connecting to one Azure SignalR, you can configure different [ApplicationName](https://github.com/Azure/azure-signalr/blob/dev/docs/run-asp-net-core.md#applicationname) for different environments for them to share the same Azure SignalR instance.

I will configure this to see if I can get this working and/or if it makes a difference for this issue.  Also please consider my experience here where I had everything simply "just work" with Blazor Server-side but now here after upgrading to Azure SignalR there are tons of bells/whistles/configurations (or at least feels that way after 3 days of grief).  I've had zero problems with SignalR until integrating this product.

> If you have NSG or route tables to control the traffic flow, please further check the NSG(outbound rules) and route tables to check if connectivity to the target has been granted or not.

I do not as far as I know.  Everything is default configuration to keep my traffic private off of the interweb.  I see the following on all my subnets:

![image](https://user-images.githubusercontent.com/2931376/182316571-28ea0c88-2c9e-4def-aa23-53ee66da7d71.png)

**Comment by vicancy** [comment]
> so your production client traffic might be routed to your staging app server, which means they are not isolated.

I mean from Azure SignalR's perspective of view, your production client traffic might be routed to your staging hub server. You can consider Azure SignalR as a proxy that routes messages from the client to your multiple server instances. 

> Also please consider my experience here where I had everything simply "just work" with Blazor Server-side but now here after upgrading to Azure SignalR there are tons of bells/whistles/configurations

This is a nice catch, @Jialin shall we consider applying the Environment variable as the ApplicationName for Blazor apps (but sounds a breaking change), or maybe add some documentation for such a scenario?

**Comment by vicancy** [comment]
For the network connectivity issue I would suggest follow the Web App TSG https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#troubleshooting to narrow down the issue。

**Comment by Mike-E-angelo** [comment]
I appreciate your continued dialogue here @vicancy 🙏

> I mean from Azure SignalR's perspective of view, your production client traffic might be routed to your staging hub server. You can consider Azure SignalR as a proxy that routes messages from the client to your multiple server instances.

This issue wouldn't be nearly as bad for me if there was something that returned with the search results.  This seems like an obvious issue that should return results, but the results were empty, so I had to create an issue and spend 3 days (now) exploring it.  We're at the point now with this that hopefully, it will help others running into the same issue with pointers.

> For the network connectivity issue I would suggest follow the Web App TSG https://docs.microsoft.com/en-us/azure/app-service/overview-vnet-integration#troubleshooting to narrow down the issue.

I have a sneaking suspicion that setting ApplicationName will address this.  I will update the configuration and let you know accordingly. 👍

**Comment by Mike-E-angelo** [comment]
Hi @vicancy does the `Azure:SignalR:ApplicationName` setting work?  I am attempting to set it in configuration and it does not seem to apply.  Checking here before I open another issue.  Thank you for any continued assistance.

**Comment by vicancy** [comment]
looks like there is a bug when reading from config... try using `Azure:SignalR:ApplicationName:`

**Comment by Mike-E-angelo** [comment]
Small victories, @vicancy that worked.  Is the same for `Azure:SignalR:ConnectionCount`?  It's unclear to me ATM where connections are created/emitted to verify.

**Comment by vicancy** [comment]
I don't think ConnectionCount is settable directly from Configuration though.

**Comment by Mike-E-angelo** [comment]
Doh @vicancy guess we're 1/2 there.  I have opened #1652 to track.

Setting `ConnectionCount = 1` solved my testing/staging problems so I can use the Free tier there for those two environments. 
 I have also added Application names to my testing/staging environments for good measure, while production stays `null`/default.  

So, really this issue is no longer a concern for me, nor do I want to spend any more time tracking this down.  I am pretty sure there were namespacing issues with the `ApplicationName` but that is a hunch and not backed by evidence.  

We can keep this issue open if you wish and think you can reproduce it, but I have no problem closing it.

In any case, I appreciate you taking the time to play the role of tech support while I get situated here. It is very much appreciated!

**Comment by vicancy** [comment]
Do you have different configuration for PROD and Staging VNET settings? I would very much appreciate it if you could share with me your VNET setting steps and let me try to see if I can repro. Or if you could provide me with your web app instance names (through email) so that I could involve our web app support engineers to help check the network issue?

**Comment by Mike-E-angelo** [comment]
Sure thing @vicancy anything for the cause. :)  Note that I am not an Azure engineer and really plowed through the settings as default as possible to get things working.  My only intention was to get "a private network in the cloud" so nothing fancy (unless by mistake which is totally possible).

I see your email in your GitHub profile and I will contact you there with the requested information.

**Comment by Mike-E-angelo** [comment]
FWIW I have encountered this issue again this morning @vicancy

Interesting to note that this time the error message includes the hub name:

```
Failed to connect to '(Primary)https://<name>.service.signalr.net(hub=<hub>)', will retry after the back off period. 
```

This has been working without issue for several days now and then all of the sudden these exceptions.

Resetting my environment resolved the errors this time, however.  This did not happen last time and the errors continued.  So no big deal, but still worth mentioning.

**Comment by vicancy** [comment]
Please feel free to open new issues or email me (`lianwei(at)microsoft`) the resource name, time stamp when the issue happens and your server side logs if available during that time when you encounter such issue and there were no network issues/deployments/abnormal events identified in your server side.
