### ISSUE TITLE
Azure Signalr Service - reducing claims impacts Blazor AuthorizeView 

### ISSUE THREAD

**Issue by jassent** [Azure/azure-signalr#1661]
The issue of the JWT size being too large in Azure SignalR Service is documented under [#249](https://github.com/Azure/azure-signalr/issues/249):

The proposed solution in the issue is to reduce the number of claims. For example:
```
services.AddSignalR().AddAzureSignalR(options =>
            {                
                options.ClaimsProvider = context => context.User.Claims.Where(x => x.Type != "groups");                
            });
```

The problem with this approach is that it breaks Blazor AuthorizeView components:
```
<AuthorizeView Policy="MemberOfGroupX">
<p>Confirmed! You are a Member Of Group X</p>
</AuthorizeView>
```

As well as ClaimsPrincipal checks such as:
```
@if (_claims.Where(x => x.Type == "groups" && x.Value == "MemberOfGroupX").Any())
{
    <p>Confirmed! You are a Member Of Group X</p>
}
```

I have tried the following:
1. IClaimsTransformation - This is where I am adding the custom claims. Any custom claims added in IClaimsTransformation are removed by the "options.ClaimsProvider = context => context.User.Claims.Where(x => x.Type != "groups");" filter.

2. Adding the custom claims using the OpenIdConnectEvent() - The claims are added but also removed by the  "options.ClaimsProvider = context => context.User.Claims.Where(x => x.Type != "groups");" filter.
```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(options =>
                    {
                        Configuration.Bind("AzureAd", options);
                        options.Events ??= new OpenIdConnectEvents();
                        options.Events.OnUserInformationReceived += OnUserInformationReceivedFunction;
                        options.Events.OnTokenValidated += OnTokenValidatedFunction;
                        options.Events.OnAuthorizationCodeReceived += OnAuthorizationCodeReceivedFunction;
                        options.Events.OnTokenResponseReceived += OnTokenResponseReceivedFunction;
                    })               
                .AddInMemoryTokenCaches();
```

If I remove the  "options.ClaimsProvider = context => context.User.Claims.Where(x => x.Type != "groups");" filter all of the AuthorizeView policies work as expected.

One other odd part...I am using Blazor Server with Azure Signalr Service in render-mode="ServerPrerendered". When a page loads, upon the first page load the AuthorizeView Policy works as expected and various components are show (the page flickers with the various components effected by the policies being quickly shown). However, upon the second page load the AuthorizeView Policy does not work as expected because the claims have been removed. Switching to render-mode-"Server" causes AuthorizeView Policy to not work because the claims are removed before the page is rendered.

Is it a general limitation of using Azure Signalr Service that custom claims and therefore custom AuthorizationOptions / AuthorizationPolicies must be kept small so that the JWT send to/from the Azure Signalr Service is less than 4k?

**Comment by vicancy** [comment]
Looks like you need to still preserve your custom claims needed by your AuthorizeView policies. 

Is such claim `(groups:MemberOfGroupX)` expected by your AuthorizeView or some other claims are also needed? Looks like `options.ClaimsProvider = context => context.User.Claims.Where(x => x.Type != "groups");` preserves such `groups `claim.

**Comment by jassent** [comment]
> preserves such `groups `claim.

Thank you for your response and assisting with this. 

Did you mean _removes_ such `groups` claim? The Where clause keeps every claim that isn't (!=) a `groups`.

I have an IClaimsTransformation that loads the custom claims from the database.  Sorry, I should have added this before. 

The custom claims are added by IClaimsTransformation during each page/component load and then removed by options.ClaimsProvider before <AuthorizeView Policy="MemberOfGroupX"> is checked. 

I would think the expected behavior is that IClaimsTransformation adds the claims --> then AuthorizeView Policies are checked for the claims --> then the options.ClaimsProvider removes the custom claims before communicating with Azure Signalr Services.

It seems odd that options.ClaimsProvider is removing the claims for the entire application and not just the communication back and forth between the app and Azure Signalr Service. Likewise, I am also using an authenticated downstream api and the claims are also being removed from the calls to the authenticated downstream api. 

I know for certain the IClaimsTransformation is working because if I adjust the options.ClaimsProvider then the AuthorizeView Policies work as expected. 

Here is the missing IClaimsTransformation code:

```
public class UserClaimsTransformation : IClaimsTransformation
    {
         /// <summary>
        /// Transform claims by either re-using or loading from database. Executed with each page load.
        /// </summary>

        public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {

            _logger.LogInformation("UserClaimsTransformation TransformAsync {Name}", principal.Identity.Name);

           ClaimsIdentity claimsIdentity = new ClaimsIdentity();
           claimsIdentity.AddClaim("groups","MemberOfGroupX");
           principal.AddIdentity(claimsIdentity);           
           return Task.FromResult(principal);
         }
}
```

**Comment by vicancy** [comment]
Sorry my bad. I mean you still need to preserve the `groups` claims. Internally Azure SignalR receives the claims and reconstruct the HttpContext for your components when the connection is established.

**Comment by jassent** [comment]
> Sorry my bad. I mean you still need to preserve the `groups` claims. Internally Azure SignalR receives the claims and reconstruct the HttpContext for your components when the connection is established.

Ahh...Then this is my misunderstanding of how it works. Thank you for reviewing and explaining. I will re-think using claims to control access to components. I changed the title of this issue to avoid future confusion.
