### ISSUE TITLE
Azure SignalR Service Management SDK IsServiceHealthy returns true when the connection string is no longer valid

### ISSUE THREAD

**Issue by gagwithgaffer** [Azure/azure-signalr#1662]
### Describe the bug
Hello,

I'm using the Azure SignalR Service Management SDK and trying to setup a mechanism whereby if the connection string has been changed *after* the hub connection has been initialized, then I want to perform an IConfigurationRoot)!.Reload() in order to pull the updated connection string down from Azure KeyVault into .NET Core

I've tired imlementing a .NET Polly Policy, as well as testing the ServiceManager.IsServiceHealthy(token) option, but once the hub has been initialized, sending any subsequent messages still go through to Azure SignalR, even if I've reaplced the connection string, or have even disabled the connection string from Azure KeyVault.

It seems that once the Hub has been initialized, the static instance of that hub remanins active, so nothing can influence the status of that hub unless I re-start the running application. I was kinda expecting some form of exception to throw when the SDK tries to send a message to the hub once the connection string is no longer valid, but nothing is caught in my try/catch block so am rather perplexed whats going under the hood.

It might be prevelant to mention that I'm using a persistant TransportType, but really this is the preferred route since my environement will be sending lots of messages frequently. So its important that I can detect as quickly as possible when a connection string has ultimately changed in order that I can poll Azure KeyVault and grab the latst/updated connection string.

### To Reproduce

My code sample is shown below. I created a SignalService class in which i call the method InitAsync when the app first starts up.
The InitAsync method basically creates a static instance of each HubContext. Then later, when I want to send a message, I simply ref the class from somewhere else in my app and call the SendMessage methods.

What I ultimately need know is how the ServiceManager.IsServiceHealthy is supposed to work and why it always returns true, even if the connection string is no longer valid during the app lifetime.

Youll see in the method SendMessageToGroup() I have tried two different approaches to try and make the SDK fail when it tries to send a message to the hub using a connection string that is invalid, but I still receive the messages to Azure which is not what i would expect.

```
public class SignalRService
{
	private ServiceHubContext? _hubContext;
	private readonly IServiceScopeFactory _serviceScopeFactory;

	public SignalRService(
		IServiceScopeFactory serviceScopeFactory)
	{
		_serviceScopeFactory = serviceScopeFactory;
	}

	private static string? LogData { get; set; }

	private static ServiceManager? ServiceManager { get; set; }
	private ServiceTransportType ServiceTransportType { get; set; }

	public static ServiceHubContext? EventsMonitorHubContext { get; private set; }
	public static ServiceHubContext? IntegrationDataMonitorHubContext { get; private set; }
	public static ServiceHubContext? IntegrationStatusHubContext { get; private set; }
	public static ServiceHubContext? IotDeviceStatusHubContext { get; private set; }

	/// <summary>
	/// Method called in program.cs file during startup. See bottom of the file.
	/// </summary>
	/// <param name="connectionString"></param>
	/// <returns></returns>
	public async Task InitializeSignalRHubs()
	{
		// Dispose the DbContext instance when the task has completed. 'using' = dispose when finished...
		using var scope = _serviceScopeFactory.CreateScope();
		var _configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();
		var _connectionString = _configuration.GetSection("AzureSignalR").GetValue<string>("ConnectionStringTest220820222143");

		// See private method at the bottom...
		if (EventsMonitorHubContext == null)
		{
			EventsMonitorHubContext = await InitAsync("EventsMonitorHub", _connectionString);
		}
		if (IntegrationDataMonitorHubContext == null)
		{
			IntegrationDataMonitorHubContext = await InitAsync("IntegrationDataMonitorHub", _connectionString);
		}
		if (IntegrationStatusHubContext == null)
		{
			IntegrationStatusHubContext = await InitAsync("IntegrationStatusHub", _connectionString);
		}
		if (IotDeviceStatusHubContext == null)
		{
			IotDeviceStatusHubContext = await InitAsync("IotDeviceStatusHub", _connectionString);
		}
	}

	public async Task SendMessageToAllClients(ServiceHubContext? hubContext, string methodName, object message)
	{
		// Dispose the DbContext instance when the task has completed. 'using' = dispose when finished...
		using var scope = _serviceScopeFactory.CreateScope();
		var _logExtension = scope.ServiceProvider.GetRequiredService<ILogExtension>();
		var _configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();
		var _connectionString = _configuration.GetSection("AzureSignalR").GetValue<string>("ConnectionStringTest220820222143");

		try
		{
			// If statement required when calling the hub before 
			// it's initialized i.e. during early stages of startup.
			if (hubContext != null & _configuration != null)
			{
				var retryPolicy = Policy.Handle<HubException>()
					.RetryAsync(2, async (ex, count, context) =>
					{
						(_configuration as IConfigurationRoot)!.Reload();
						_connectionString = _configuration.GetSection("AzureSignalR").GetValue<string>("ConnectionStringTest220820222143");
						await UpdateConnectionString(_connectionString);
					});
				await retryPolicy.ExecuteAsync(async () =>
				{
					await hubContext!.Clients.All.SendAsync(methodName, message);
				});
			}
		}
		catch(HubException ex)
		{
			LogData = "IotHubs-Message-Server encountered an exception when sending a SignalR message to all clients. SignalR returned an error with message: [" + ex.Message + "]";
			await _logExtension.WriteLogEvent<SignalRService>("Error", "SignalR Service", "Send Message", "All Clients", LogData, ex);
		}
	}

	public async Task SendMessageToGroup(ServiceHubContext? hubContext, string methodName, string groupName, object message)
	{
		// Dispose the DbContext instance when the task has completed. 'using' = dispose when finished...
		using var scope = _serviceScopeFactory.CreateScope();
		var _logExtension = scope.ServiceProvider.GetRequiredService<ILogExtension>();
		var _configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();
		var _connectionString = _configuration.GetSection("AzureSignalR").GetValue<string>("ConnectionStringTest220820222143");

		try
		{
			// If statement required when calling the hub before 
			// it's initialized i.e. during early stages of startup.
			if (hubContext != null & _configuration != null)
			{
				// -----------
				// Not Working
				// -----------
				//var retryPolicy = Policy.Handle<Exception>()
				//    .RetryAsync(2, async (ex, count, context) =>
				//    {
				//        Console.WriteLine("OLD Connecton String " + _connectionString);
				//        (_configuration as IConfigurationRoot)!.Reload();
				//        _connectionString = _configuration.GetSection("AzureSignalR").GetValue<string>("ConnectionStringTest220820222143");
				//        Console.WriteLine("NEW Connecton String " + _connectionString);
				//        await UpdateConnectionString(_connectionString);
				//    });
				//await retryPolicy.ExecuteAsync(async () =>
				//{
				//    await hubContext!.Clients.Group(groupName).SendAsync(methodName, groupName, message);
				//});

				if (ServiceManager != null)
				{
					var cancellationTokenSource = new CancellationTokenSource();
					var token = cancellationTokenSource.Token;
					var healthly = await ServiceManager.IsServiceHealthy(token);
					
					// This always returns true, even if the connection string had changed to an empty string. 
					if (healthly == true)
					{
						await hubContext!.Clients.Group(groupName).SendAsync(methodName, groupName, message);
					}
					else
					{
						(_configuration as IConfigurationRoot)!.Reload();
						_connectionString = _configuration.GetSection("AzureSignalR").GetValue<string>("ConnectionStringTest220820222143");
						await UpdateConnectionString(_connectionString);
						await hubContext!.Clients.Group(groupName).SendAsync(methodName, groupName, message);
					}
				}
			}
		}
		catch (Exception ex)
		{
			LogData = "IotHubs-Message-Server encountered an exception when sending a SignalR message to a Group with name [" + groupName + "]. SignalR returned an error with message: [" + ex.Message + "]";
			await _logExtension.WriteLogEvent<SignalRService>("Error", "SignalR Service", "Send Message To Group", groupName, LogData, ex);
		}
	}

	private async Task UpdateConnectionString(string connectionString)
	{
		// Dispose the existing hub instances.
		if (EventsMonitorHubContext != null)
		{
			await EventsMonitorHubContext.DisposeAsync();
		}
		if (IntegrationDataMonitorHubContext != null)
		{
			await IntegrationDataMonitorHubContext.DisposeAsync();
		}
		if (IntegrationStatusHubContext != null)
		{
			await IntegrationStatusHubContext.DisposeAsync();
		}

		// Re-initialize the hubs
		EventsMonitorHubContext = await InitAsync("EventsMonitorHub", connectionString);
		IntegrationDataMonitorHubContext = await InitAsync("IntegrationDataMonitorHub", connectionString);
		IntegrationStatusHubContext = await InitAsync("IntegrationStatusHub", connectionString);
	}

	private async Task<ServiceHubContext?> InitAsync(string hubName, string connectionString)
	{
		// Dispose the DbContext instance when the task has completed. 'using' = dispose when finished...
		using var scope = _serviceScopeFactory.CreateScope();
		var _logExtension = scope.ServiceProvider.GetRequiredService<ILogExtension>();
		var _configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();
		var _transportType = _configuration.GetSection("AzureSignalR").GetValue<string>("TransportType");

		if (string.IsNullOrEmpty(connectionString))
		{
			return null; // Abort the method and return null!
		}

		if (string.IsNullOrEmpty(_transportType))
		{
			// Set the default transport type
			ServiceTransportType = ServiceTransportType.Persistent;
		}
		else
		{
			// Set the default transport type from configuration.
			ServiceTransportType = Enum.Parse<ServiceTransportType>(_transportType, true);
		}

		// Create a service manager instance.
		ServiceManager = new ServiceManagerBuilder().WithOptions(option =>
		{
			option.ConnectionString = connectionString;
			option.ServiceTransportType = ServiceTransportType;
			option.UseJsonObjectSerializer(new JsonObjectSerializer(new JsonSerializerOptions
			{
				// VERY IMPORTANT --> Set to null otherwise Azure SignalR will
				// automatically set the first character to lowercase for each
				// log event property when serializing the string for transportation.
				// See https://github.com/Azure/azure-signalr/blob/dev/docs/advanced-topics/json-object-serializer.md
				PropertyNamingPolicy = null
			}));
		})
		// Uncomment the following line to get more logs
		//.WithLoggerFactory(LoggerFactory.Create(builder => builder.AddConsole()))
		.BuildServiceManager();

		try
		{
			_hubContext = await ServiceManager.CreateHubContextAsync(hubName, default);
			return _hubContext;
		}
		catch (Exception ex)
		{
			LogData = "IotHubs-Message-Server encountered an exception when initializing a SignalR Hub with name [" + hubName + "]. SignalR returned an error with message: [" + ex.Message + "]";
			await _logExtension.WriteLogEvent<SignalRService>("Error", "SignalR Service", "Initialize Hub Connection", hubName!, LogData, ex);
			throw;
		}
	}
}
```

### Further technical details
- Your Azure SignalR SDK version = Microsoft.Azure.SignalR.Management 1.18.1
- Your Server ASPNETCORE version  = .NET Core 6.0 Worker App

**Comment by Y-Sindo** [comment]
For `SendMessageToAllClients` method, `UpdateConnectionString(..)` won't be executed if `await hubContext!.Clients.All.SendAsync(methodName, message)` inside `retryPolicy.executeAsync` successfully sends the message. **Unless you make the SignalR Service instance that the `hubContext` connects to not working (such as deleting the resource)**, the `UpdateConnectionString(..)` would never be executed. 

For `SendMessageToGroup` method, the retry policy is not working for the same reason I explained before, and the `ServiceManager` is not updated, and you're calling `IsHealthy` on the original `ServiceManager`. As long as the SignalR service behind the original `ServiceManger` is healthy, it will always return healthy.

If I understand right, you want to get notified when the connection in Key Vault changes and then update the `hubContext`. First of all, our SDK can detect the change in `IConfiguration` (by the `IChangeToken` in `IConfiguration`) in `Persistent` mode. You should make sure the connection string is placed on `IConfiguration["Azure:SignalR:ConnectionString"]`, then initialize the hub context as follows:
```cs
var serviceManager = new ServiceManagerBuilder()
      .WithConfiguration(_configuration)
      .WithOptions(o => o.ServiceTransportType = ServiceTransportType.Persistent)
      .BuildServiceManager();
var hubContext = await serviceManager.CreateHubContextAsync("hub", default);
```
Then whenever the connection string in `IConfiguration` changes and the SDK detects that the endpoint changes, it will drop the old connections and establish new connections. You don't need to change the reference to the hub context. 

Please note that the `IsHealthy` API itself cannot respond to the configuration change. It would always check the health of the initial SignalR instance. 

Now the problem comes to how to get notified when the Key Vault changes and then call `IConfigrationRoot.Reload()`. That's out of my scope. You might want to combine with [EventHub](https://docs.microsoft.com/en-us/azure/key-vault/general/event-grid-logicapps) to achieve that. 

You might also want to read the following docs:
* [Multiple Azure SignalR Service Instances Support in Azure Functions](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/docs/sharding.md#configuration-method) Although the title is for Functions, but it also applied to management SDK.
* [Resiliency and disaster recovery in Azure SignalR Service](https://docs.microsoft.com/azure/azure-signalr/signalr-concept-disaster-recovery)

**Comment by gagwithgaffer** [comment]
Hello, thank you for your reply.

Sideline observation,  through my testing I found that changing the connection string sometime after the hubContext was already intilaized, the messages still go through to Azure. I'm wandering whether that is somthing to do with using websockets i.e. until the websocket has closed then the current connection will keep firing messages through the pipe, depsite the fact that the connecton string had actually changed against the SignalR Service. Although this would allow the app to continue working until such times it has a retstart (in which case it would then reload the keys from (KeyVault)) this pattern still wouldnt comply with anyone wanting to forcefully change the connection on demand over to the new connection string for security reasons.

Acknowledge your tip about inserting the .WithConfiguration(_configuration) into the ServiceManagerBuilder() I'll give that a test but agree yes we still have a conumdrum in how to trigger the IConfigrationRoot.Reload() to forcefully request the app to reload the keys from KeyVault.

mmm i'll have to think how to get around this...

**Comment by Y-Sindo** [comment]
> Sideline observation, through my testing I found that changing the connection string sometime after the hubContext was already intilaized, the messages still go through to Azure. 

That shouldn't be the case. In the code you provided, the `UpdateConnectionString` is never called as long as the original SignalR service is healthy. Even if `UpdateConnectionString` is called, the `hubContext` you use is still the one passed as a method parameter, see
```
// UpdateConnectionString updates the "_hubContext" variable, but you're using "hubContext" without underscore to send the message.
if (healthly == true)
{
await hubContext!.Clients.Group(groupName).SendAsync(methodName, groupName, message);
}
```

The code sample cannot prove that changing connection string is not working. It might be different with the actual code you run, if you're sure about your observation, please provide a minimal reproducible project.

**Comment by gagwithgaffer** [comment]
Hi, I created another, more simpler Net Core 6.0 Console app for some more tests. To keep things simple I configured the connection string first, then started up the app. So without trying to modify the connection string whilst its running, I've discovered that I can set a random access key and no errors are thrown when the app runs.

{
  "Azure": {
    "SignalR": {
      "ConnectionString": "Endpoint=https://myhubreference-signalr.service.signalr.net;AccessKey=123456789123456789=;Version=1.0;"
    }
  }
}

I then experiemted further by utilising serviceManager.IsServiceHealthy() but looking at the docs, it seems to only check the endpoint portion of the connection string which explains why I can configure a random non-valid access key. 

If the serviceManager.IsServiceHealthy() doesnt like the connection string depending on what is set, then it will throw an exception. 

This exception throws upon two scenraios I tested:
1 - If the endpoint url portion of the connection string is invalid
2 - If the access key has too few characters, setting it to 123456789123456789 didn't cause any issues.

Without the exeption being thrown, the messages appear to go through to Azure, I just don't receive the messages in my other client app for the obvious reason the access key is not valid.

I havent noticed anything in the docs that says we need to wrap the serviceManager.IsServiceHealthy() in a try/catch block? kinda thought the "health" boolean value returned was what we are supposed work with?

Anyhow, for my particular environment,  even If I had updated the connection string in KeyVault, the endpoint portion of the connection string is not going to change, only the access key part. So I'm not sure how the app using this SDK to send messages would ever know there was an issue when trying to use an outdated connection string, it woud keeep sending the messages but they would no longer reach their intended destination.

**Comment by Y-Sindo** [comment]
Ah I thought the invalid connection string was because of bad format or invalid endpoint. Invalid access key with correct format does not affect the `IsServiceHealthy` API, because this API only tests if the SignalR Service is healthy, rather than if the connection to the SignalR Service is healthy. 
And there is another note that passing `IConfiguration` cannot detect the change of access key currently.

>I found that changing the connection string sometime after the hubContext was already intilaized, the messages still go through to Azure.
Rotating the access key won't stop the existing connections. It just affects the newly created connections. Do you mean that you want to stop all the previous connections and reestablish new connections when you rotate the key? If so, you need to restart the SignalR Service instance so that all the previous connections are dropped.

**Comment by gagwithgaffer** [comment]
Hi, yes that would ultimately be my aim, to stop all the previous connections and re-establish new connections when I rotate the key. As you advised in a previous comment that there is no magic way for the service to restart and adopt the new key by itself, I'd have to figure out the most practical way in doing this.

At least I understand better now what we have on the table to play with. Thanks for your inputs, much appreciated.
