### ISSUE TITLE
Cannot deploy serverless signalR and upstream function app from pipeline

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-signalr#1664]
### Describe the bug
Using a devops pipeline to deploy a serverless signalR resource with an associated upstream function app.  SignalR extension key not created in the Function App so cannot extract from function app and feed it into upstream rule in SignalR.

### To Reproduce
Use the SignalR bidirectional serverless sample in the samples repo.  Create a Azure Devops AzureCLI pipeline task that executes a BICEP script to create the Function App and SignalR resource.  Create a subsequent pipeline 'AzureFunctionApp' task that deploys the code to the function app:

The code is deployed, but the 'signalr_extension' System Key is not created.  This prevents the creation of the upstream setting in SignalR.

### Further technical details
Pipeline deployment YML file attached.
BICEP file attached
[main.bicep.txt](https://github.com/Azure/azure-signalr/files/9446221/main.bicep.txt)
[release.yml.txt](https://github.com/Azure/azure-signalr/files/9446225/release.yml.txt)

**Comment by zackliu** [comment]
`signalr_extension` is generated when functions that contain `SignalRTrigger` are successfully deployed to the Function app. So can you confirm whether it's successfully deployed? Sometimes the deployment fails so that the key is not generated.

**Comment by vicancy** [comment]
Please feel free to reopen the issue if there are updates.
