### ISSUE TITLE
The connection count on Azure Portal is Incorrect

### ISSUE THREAD

**Issue by gynet** [Azure/azure-signalr#167]
I just use 2 clients locally for testing, started and stopped them multiple times, but the portal logged the connection number as around 55 which is definitely incorrect.

**Comment by gynet** [comment]
Since the count number is incorrect, it will cause issues with the costing

**Comment by zackliu** [comment]
Where did you see the connection count number, in overall page or in metrics(preview) page. If in metrics page, you need to make sure `Time granularity = 1 minute`. It's just a bug of showing metrics and the background statistics is accurate.

**Comment by gynet** [comment]
I saw that on the overall page.

**Comment by gynet** [comment]
Also, it's having issues on the metrics page, if I chose the default granularity, it goes above 1k+, even if I chose granularity as 1 minute, it still shows around 55.

**Comment by gynet** [comment]
Synced with your team offline, I think this issue can be closed now
