### ISSUE TITLE
Unable to write message to endpoint

### ISSUE THREAD

**Issue by co-dax** [Azure/azure-signalr#1685]
Hi. I am following [this ](https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core) tutorial and I am getting the following exception when I try to send a message:

> Microsoft.Azure.SignalR.Common.FailedWritingMessageToServiceException: 'Unable to write message to endpoint:...

I am running .net core 6 on Windows and the  Microsoft.Azure.SignalR 1.18.3.

What could it be?

Thanks.

**Comment by vicancy** [comment]
What is the inner message for `Unable to write message to endpoint`?

**Comment by co-dax** [comment]
Inner excepion is null.
Below is the list of relevant exception details available.

Source: Microsoft.Azure.SignalR.Common
StackTrace:    at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.<WriteSingleEndpointMessageAsync>d__12.MoveNext()
   at Microsoft.Azure.SignalR.MultiEndpointMessageWriter.<WriteMultiEndpointMessageAsync>d__11.MoveNext()
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.<WriteCoreAsync>d__29`1.MoveNext()
   at 
TargetSite: {Void MoveNext()}
Data: [empty list]



Thanks.

**Comment by vicancy** [comment]
Any other logs? For example, logs related to the service endpoint?

**Comment by co-dax** [comment]
@vicancy I eventually found it didn't work as in the past I had set "skipNegoriation: true" on the fontend but negotiation now is needed so that the frontend can be redirected to Azure SignalR server. After that I had to further configure cors but that is not related to the initial issue.

Thanks for responding promptly.
