### ISSUE TITLE
How to get authenticated user id from negotiate endpoint to use in Azure Function having Service bus input trigger binding and  Azure SignalR Service Output binding

### ISSUE THREAD

**Issue by Chays21** [Azure/azure-signalr#1688]
can you help with below questions, I am looking for some guidance

1)  [question1](https://stackoverflow.com/questions/73664850/how-to-get-authenticated-user-id-to-use-in-azure-function-with-azure-signalr-ser)
2) When to use this SDK if I could already follow the traditional model (Azure function bindings) of creating negotiate, other functions to send messages to clients.

_Originally posted by @Chays21 in https://github.com/Azure/azure-signalr/issues/1640#issuecomment-1253924727_

**Comment by JialinXin** [comment]
Whom(user-id) do you want to send to in the function?

1. Service bus message trigger user -> you may attach the user-id part of the message or from service bus trigger properties(see [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#message-metadata)).
2. A list of users that you've some flags to filter -> the authenticated user list need to be cached somehow(in storage or some places) during negotiation function so when in the message function you can find required user-ids.

**Comment by JialinXin** [comment]
About Q2, management SDK provides similar functionality comparing with function bindings. Management SDK is a lightweight server that can be hosted in app service/functions. I think you can choose either one to work with.

Basically for output bindings, they both works on the [REST API(transient mode)](https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-reference-data-plane-rest-api). The benefit of management SDK is that it provides better returns than output bindings. For example, if you need to call [`CheckUserExistence`](https://learn.microsoft.com/en-us/azure/azure-signalr/swagger/signalr-data-plane-rest-v1#check-if-there-are-any-client-connections-connected-for-the-given-user), then suggest to use Management SDK in the function.

And for input bindings, management SDK helps less on reading the request.

- If the trigger is a service bus message, work with `ServiceBusTrigger`, alternatively `HttpTrigger`.
- If the trigger is a client message on websocket, work with `SignalRTrigger`, alternatively `HttpTrigger`.
- If the trigger is a function exposed API call, work with `HttpTrigger`.

**Comment by Y-Sindo** [comment]
In reply to https://github.com/Azure/azure-signalr/issues/1640#issuecomment-1255990273:
> > How do I know what all function bindings are available with SDK to use? are there any limitations?
> > I am not sure if I understand your first question. Do you mean that you want to find all the functionalities/features provided by the management SDK? You can see this doc https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md for more details.
> 
> I can not figure out the what `names of bindings are there to use? Can you list down the names of bindings that can be used from sdk.

You can find [docs](https://learn.microsoft.com/azure/azure-functions/functions-bindings-signalr-service?tabs=in-process&pivots=programming-language-csharp) of Azure SignalR bindings here. There are also some bindings not listed there, which are for multiple endpoint cases. You can find those specific bindings [here](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/docs/sharding.md#configuration-method)

> 
> 
> > This is not true. ASP.NET Core SignalR refers to the server-side technique you're using. For the client side, you could choose the proper JS library according to your server-side technique. For JS client, you should use @microsoft/signalr library.
> > [ASP.NET Core SignalR JS client](https://learn.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-6.0&tabs=visual-studio)
> > [Differences between ASP.NET SignalR and ASP.NET Core SignalR](https://learn.microsoft.com/aspnet/core/signalr/version-differences?view=aspnetcore-6.0)
> 
> but I see the below note, here https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md.
> 
> > Azure SignalR Service Management SDK
> > NOTE
> > Azure SignalR Service only supports this SDK for ASP.NET CORE SignalR clients.
> 
> This means I can only use this SDK to manage asp.net core signalr clients from my server side code not the reactjs signalr clients. is this understanding correct? other way the question is can I use this SDK to implement negotiate, processupdate functions instead of Azure function bindings to work with ReactJs signalr client?

"Azure SignalR Service only supports this SDK for ASP.NET CORE SignalR clients." This sentence is a little bit confusing. It still means the SignalR client whose server-side technique is ASP.NET Core SignalR. Will improve the doc.

**Comment by Chays21** [comment]
I am really looking to see below statement, much needed correction. Thanks a lot for your clarification and patience.

**You can use this SDK instead of Azure function bindings to work with ReactJS client.**
