### ISSUE TITLE
StartAsync() returns 404 from Azure SignalR Service

### ISSUE THREAD

**Issue by cnlogistics** [Azure/azure-signalr#169]
Please see all details there:

https://github.com/aspnet/SignalR/issues/2791#issuecomment-413609478

**Comment by vicancy** [comment]
Thanks @cnlogistics for reporting the issue. I will take a look from the service side and get back to you.

**Comment by vicancy** [comment]
@cnlogistics as your log screenshot indicates, the timestamp is *Local Time*, could you provide the *UTC time* for the *Local Time* `2018-08-15T12:07:28` for me to narrow down the log?

With a first glance, it looks like the `WebSockets` connection fails to start, according to the log.
![image](https://user-images.githubusercontent.com/668244/44253010-b72b5380-a230-11e8-8bac-4134e5861162.png)
![image](https://user-images.githubusercontent.com/668244/44253024-c3171580-a230-11e8-8530-fa47aacebf97.png)

**Comment by ericbrunner** [comment]
Just subtract 2 hours than you are on UTC time. UTC+2 is my local time in Vienna / Austria.
![image](https://user-images.githubusercontent.com/6480047/44254132-305f8200-a202-11e8-9c96-175d6b684f4a.png)

**Comment by ericbrunner** [comment]
@vicancy If helpful here the AI Analytics query from 5 minutes before the 404 and 5 minutes after and the new CSV as ZIP

```
union (traces), (requests), (pageViews), (dependencies), (customEvents), (availabilityResults), (exceptions)
| extend itemType = iif(itemType == 'availabilityResult',itemType,iif(itemType == 'customEvent',itemType,iif(itemType == 'dependency',itemType,iif(itemType == 'pageView',itemType,iif(itemType == 'request',itemType,iif(itemType == 'trace',itemType,iif(itemType == 'exception',itemType,"")))))))
| where ((itemType == 'request' or (itemType == 'trace' or (itemType == 'exception' or (itemType == 'dependency' or (itemType == 'availabilityResult' or (itemType == 'pageView' or itemType == 'customEvent')))))) and (timestamp >= datetime(2018-08-16T20:11:21.046Z) and timestamp <= datetime(2018-08-16T20:21:21.046Z)))
| top 101 by timestamp desc
```

[query_data (1).zip](https://github.com/Azure/azure-signalr/files/2296401/query_data.1.zip)

**Comment by vicancy** [comment]
1. Client side: on `2018-08-15T10:07:28.753Z` 404 response with SSE request `?hub=hubname&id=xGk...`
2. Service side: on `2018-08-15T10:07:28.7598884Z` an Handshake error occurs:
```
Microsoft.Azure.SignalR.HandshakeFailedException: Handshake failed: Connection closed before handshake complete.
```

This error happens when the `HttpConnectionContext.Transport.Input` `IsCompleted` before handshake request message completed. Code logic similar to 
```cs
var connection = CreateConnection(connectionId);
while (true) {
   var result = await HttpConnectionContext.Transport.Input.ReadAsync();
   var buffer = result.Buffer;
   if (TryParseHandshakeRequest(ref buffer, out _)) {
      return;
   }
   if (result.IsCompleted) {
      // This is where it runs into
       throw new HandshakeFailedException();
   }
}
```
![image](https://user-images.githubusercontent.com/668244/44256567-1fcbfd80-a23c-11e8-9100-d42a7650f5dc.png)

As the log shows, the connection is connected, however during handshake, the Pipe input is completed somehow. (creating the connection and handshake happens in the same service instance)

So @anurse , is it possible that the underlying HttpConnectionContext made it happen somehow?

**Comment by ericbrunner** [comment]
@vicancy maybe related to that https://github.com/aspnet/SignalR/issues/2791#issuecomment-413790378

**Comment by ericbrunner** [comment]
@vicancy Regarding

> Service side: on 2018-08-15T10:07:28.7598884Z an Handshake error occurs:
> Microsoft.Azure.SignalR.HandshakeFailedException: Handshake failed: Connection closed before handshake com

Where can I see that Azure SignalR Service log messages. Would somehow help. Even help you when I could provide that with an issue? I Azure Portal I see only that, but it is not ready and shows wrong metrics.

![image](https://user-images.githubusercontent.com/6480047/44257923-ce0c7e80-a20d-11e8-86a2-66ecc3e69cf4.png)

**Comment by vicancy** [comment]
@ericbrunner Currently Azure SignalR Service log messages are not exposed to the portal. We are considering publishing error/warning logs to portal, however that would be after GA. cc @chenkennt For now, you can provide the time range and your instance ID, and we can help getting service logs for you.

**Comment by davidfowl** [comment]
@ericbrunner I was looking at your azure function and it looks like you're initializing a shared instance of the hubConnection (it's static) without locking. That might explain some of the weird behaviors you're seeing.

**Comment by ericbrunner** [comment]
@davidfowl you are propably right. I will surround my own SendAsync method invocation with a SemaphoreSlim wait lock (only 1 concurrent invocation allowed) or what's much better than locks, I start the hubConnection only ONCE and invoke hubConnection.StartAsync ONCE. Only in case of an exception that occurs on hubConnection.SendAsync I would attempt to invoke hubConnection.StartAsync until it succeeds. Either way works for me.

**Comment by ericbrunner** [comment]
@davidfowl  Maybe you consider making StartAsync and StopAsync thread safe in future. Analog to HttpClient thread safe methods

**Comment by davidfowl** [comment]
The client is thread safe but that’s not your issue. You start and stop the connection from overlapping requests. You have a shared state problem.

Why do you stop the connection after sending?

**Comment by ericbrunner** [comment]
You can close that issue. I described 2 way of code improvements above. Why I close? Well that was the first code draft and playing around with Az Fx and SignalR.
