### ISSUE TITLE
support for CloseOnAuthenticationExpiration

### ISSUE THREAD

**Issue by standsed** [Azure/azure-signalr#1690]
### Is your feature request related to a problem? Please describe.
It seems that feature added in SignalR for closing expired connections is not implemented in Azure SignalR.
https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet#advanced-http-configuration-options
Option: CloseOnAuthenticationExpiration
Implemented in: https://github.com/dotnet/aspnetcore/pull/32431

There is related change for Azure https://github.com/dotnet/aspnetcore/issues/35544
but seems its about sending config options, but not actually supporting them in Azure.

### Describe the solution you'd like
Ideally support for CloseOnAuthenticationExpiration in Azure SignalR.

### Additional context
I would appreciate any suggestions for workaround to support authentication expiration from server side, i.e., I would like to avoid sending message to clients to initiate disconnect.
I found https://github.com/dotnet/aspnetcore/issues/5283#issuecomment-797446519
but context.GetHttpContext().Abort(); does not work when using Azure SignalR
context.Abort(); closes the connection, but it disallows for client to reconnect.

**Comment by Y-Sindo** [comment]
The support of the feature is not released in the runtime side, I'll notify you once it's ready to use it.

**Comment by Y-Sindo** [comment]
The runtime is ready for the feature.
