### ISSUE TITLE
[Design proposal] Implement close on authentication expire

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-signalr#1694]
Feature request: #1690

Proposal:

* Service runtime:
    * Rresponsible for closing the expired connections so that we can also support the feature in serverless mode. Uses the "exp" field of JWT as the expiration time.
    * Like dotnet/aspnetcore/pull/32431 does, runtime will scan all the client connections every seconds and close the expired connections.
    * When closing an expired connection, send close message to SDK which indicates the client is closed for auth expires. (Requires protocol changes), send close message to client which allows reconnect.
 
* SDK
    * Uses claim to indicate whether the client should be closed on auth expires.
    * Provides hooks for server to be notified when client is closed on auth expires in the same way as dotnet/aspnetcore/pull/32431 does.
    * Questions: currently SDK provides an option `ServiceOptions.AccessTokenLifetime` to set the access token lifetime. The option is shared among all hubs and all clients. Do we have a need for specifying the value for a hub or for a client?

**Comment by vicancy** [comment]
1. Is `exp` too general? Shall we use another custom claim for this feature? Looks like this feature can be OFF.
2. `ServiceOptions.AccessTokenLifetime` change => maybe not

**Comment by Y-Sindo** [comment]
> 1. Is `exp` too general? Shall we use another custom claim for this feature? Looks like this feature can be OFF.

We will use one more custom claim to indicate whether the client will be closed on auth expires. The `exp` decides when the auth expires.

> 2. `ServiceOptions.AccessTokenLifetime` change => maybe not

I think it would be better to automatically detect the authentication expiration time like self-hosted SignalR, but it seems not easy to do so. We can set it aside now.

**Comment by Y-Sindo** [comment]
Move to #1695
