### ISSUE TITLE
Connection closed with an error. Unknown error

### ISSUE THREAD

**Issue by ToniaDemchuk** [Azure/azure-signalr#172]
Web socket connection to Azure services returns error after trying to connect from several browser tabs:
```
{"type":7,"error":"Connection closed with an error."}
```
Several tabs succeed to connect to sockets and receive mesages, but most of connections returned this type of error. I have no clue what is going wrong because no error description returned.

I am using Azure services on Free plan, but dashboard shows that all is under the message/connection limits (max 18 connections):
![image](https://user-images.githubusercontent.com/19282629/44460048-5e82fe80-a614-11e8-8b6a-f5760f3bd274.png)

I have tried to configure signalR options EnableDetailedErrors, but with no result - no error description.
Startup.cs:
```
services.AddSignalR(conf =>
{
    conf.HandshakeTimeout = TimeSpan.FromSeconds(300);
    conf.EnableDetailedErrors = true;
})
.AddAzureSignalR(configure => 
{
    configure.ConnectionString = connString;
    configure.ConnectionCount = 1;
    configure.AccessTokenLifetime = TimeSpan.FromHours(24);
});
```
```
app.UseAuthentication();
app.UseMvc();
app.UseFileServer();              

app.UseAzureSignalR(routes =>
{
    routes.MapHub<ChatHub>("/hub/chat");
});
```
Javascript client:
```
var connection = new HubConnectionBuilder()
      .withUrl('/hun/chat', { accessTokenFactory: () => this.authService.getAccessToken() })
      .build();
connection.serverTimeoutInMilliseconds = 300000;
connection.start();
```

Microsoft.AspNetCore.SignalR: 1.0.2
Microsoft.Azure.SignalR: 1.0.0-preview1-10015

**Comment by xscript** [comment]
Could you send your service instance name to me via email? My email address is `kevinzha<at>microsoft.com` (change `<at>` to `@`).

**Comment by xscript** [comment]
@ToniaDemchuk I didn't see any unusual errors in our backend logs. But I do noticed that quite a lot of connections are closed right after receiving the handshake request.
Have you turned on `debug` log in your server code? I want to confirm whether server code is closing the client connection.

**Comment by xscript** [comment]
It is not normal. Each client connection shouldn't have impact on the others. It sounds like the underlying connection between your server and SignalR service is broken. Then all client connections running on top are closed too.
Could you share more details such as debug logs from your app?

**Comment by xscript** [comment]
@ToniaDemchuk Is this still an issue?

**Comment by ToniaDemchuk** [comment]
Thank you for reply. 
I cannot reproduce it anymore. Debug logs don't show any suspicious items.

**Comment by xscript** [comment]
Then it is probably just intermittent network issue.
I will close this issue for now. Feel free to reopen it or create another issue if you have further questions.
