### ISSUE TITLE
Assembly reference error after upgrading to 1.19.0

### ISSUE THREAD

**Issue by ilya-scale** [Azure/azure-signalr#1720]
### Describe the bug

After updating to 1.19.0 the following code is throwing an exception:

```csharp
  public async Task SendMessageToGroup(string groupName, string target, IEnumerable<object> arguments)
  {
      await HubContext.Clients.Group(groupName).SendCoreAsync(target, arguments.ToArray());
  }
```

>   SignalRServiceClient.cs(52, 26): [CS0012] The type 'IHubClients' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.SignalR.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### To Reproduce

Have the following code and try to update to 1.19.0, it is not compiled anymore. I did try with net6 and net7.

### Further technical details
- Your Azure SignalR SDK version: 1.19.0
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 
- Your SignalR Client SDK version

**Comment by JialinXin** [comment]
Would you provide a small project to repro?
Which framework version are you using?

Normally the SignalR dependency should be able to resolve from server sdk. It seems there's some mismatch reference packages in your project that triggered by our latest dependency clean-up. It would be helpful if you could provide more details.

**Comment by ilya-scale** [comment]
I am not sure unfortunately I can just share the whole project, but maybe csproj and package.lock.json is enough? They do not contain any secret information, how can I send it non-publicly?

I have just switched to the newly released .Net 7, but I tried reverting back and it seems there was the same issue

**Comment by cygnim** [comment]
I'm experiencing this issue as well and I have created a (contrived) example repo that displays the problem. 

https://github.com/cygnim/signal-r-issue

Referencing: `<PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.18.3" />` and the project builds and works correctly. Updating this package reference to `<PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.19.0" />` and compilation will fail with the following build errors:
```
error CS0234: The type or namespace name 'SignalR' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
error CS0234: The type or namespace name 'SignalR' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)
error CS0246: The type or namespace name 'HubMessage' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by JialinXin** [comment]
Thank @cygnim for sharing the project. I'm investigating.

**Comment by JialinXin** [comment]
It's caused by a reference movement in latest SDK. We'll release a new package for the fix.

For short work-around, you can update the project reference as below to work.
```xml
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.19.0" />
</ItemGroup>
```

**Comment by JialinXin** [comment]
> I am not sure unfortunately I can just share the whole project, but maybe csproj and package.lock.json is enough? They do not contain any secret information, how can I send it non-publicly?
> 
> I have just switched to the newly released .Net 7, but I tried reverting back and it seems there was the same issue

@ilya-scale Is you issue in `Microsoft.Azure.SignalR.Management` or `Microsoft.Azure.SignalR`? You can send the project to jixin[at]microsoft.com for your convenience.

**Comment by ilya-scale** [comment]
Sorry, it seems I have pasted the wrong library, it is indeed "Microsoft.Azure.SignalR.Management" meaning that you already figured out what is wrong, right?

**Comment by JialinXin** [comment]
> Sorry, it seems I have pasted the wrong library, it is indeed "Microsoft.Azure.SignalR.Management" meaning that you already figured out what is wrong, right?

Yes, we have a fix #1723 and will release a new package soon. Sorry for the break and appreciate your immediate reporting! Suppose you can work with the `v1.19.1` including the fix in a day or two.

Besides, add the framework reference yourself also fix the issue.

```xml
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```

**Comment by ilya-scale** [comment]
Thanks for the quick fix, I can manage with the previous version so far, so I will just wait for the release :)

**Comment by JialinXin** [comment]
@ilya-scale Quick update that v1.19.1 is released. Please update and check.

**Comment by ilya-scale** [comment]
The build seems to work, thank you for a quick fix!
