### ISSUE TITLE
SignalR started sending 502 and 504 error codes overnight

### ISSUE THREAD

**Issue by TechnoCompetences** [Azure/azure-signalr#1727]
### Describe the bug
We have a very small Blazor project hosted on Azure, using an Azure SignalR service. Everything worked fine, until the SignalR service stopped working overnight, without any change in the code. It now returns 502 or 504 error codes, about which I could not find much useful information online.

### To Reproduce
This would require setting up an entire project stack, including an instance of SignalR on Azure, and I am not sure how you would gain access to it. However, any basic fuction of Blazor that requires SignalR for communication between the client and the server (basically everything) is broken at the moment, without any change in the code since the last working version. I would of course be happy to provide any information about the project that would help solve the problem.

### Exceptions (if any)
Several error messages appear while attempting to run the server. These include, in order of apparition : 

"warn: Microsoft.Azure.SignalR.ServiceConnection[27]
      Connection 71a0be04-7353-46b2-bb2a-cafc2f7d9fec received error message from service: Connection ping timeout."

"fail: Microsoft.Azure.SignalR.ServiceConnection[23]
      Error receiving handshake response. Id: f1846f91-f75e-403d-8dd3-42d25d3ac97d
      System.InvalidOperationException: Service disconnected before sending a handshake response.
         at Microsoft.Azure.SignalR.ServiceConnectionBase.ReceiveHandshakeResponseAsync(PipeReader input, CancellationToken token)
         at Microsoft.Azure.SignalR.ServiceConnectionBase.HandshakeAsync(ConnectionContext context)"

"crit: Microsoft.Azure.SignalR.ServiceConnection[24]
      Service returned handshake error: Service disconnected before sending a handshake response.. Id: f1846f91-f75e-403d-8dd3-42d25d3ac97d"

"fail: Microsoft.Azure.SignalR.ServiceConnection[2]
      Failed to connect to '(Primary)https://applicationimt-server.service.signalr.net', will retry after the back off period. Error detail: The server returned status code '502' when status code '101' was expected.. The server returned status code '502' when status code '101' was expected.. Id: 63e31cf1-60a1-49d7-b572-238206ca8cf8"

"fail: Microsoft.Azure.SignalR.ServiceConnection[2]
      Failed to connect to '(Primary)https://applicationimt-server.service.signalr.net', will retry after the back off period. Error detail: The server returned status code '504' when status code '101' was expected.. The server returned status code '504' when status code '101' was expected.. Id: ea015dc5-fd9d-490d-b483-4591604a1f62"

### Further technical details
This issue arises whether the application is deployed locally through Visual Studio or published on Azure, both of them using the same Azure SignalR instance. 
I would like to add that I started doing web dev and using Blazor / Azure / SignalR a couple months ago, and therefore lack a lot of the technical knowledge. It should however be noted that the whole stack worked perfectly fine and that the error started occurring without any change in the code. Therefore, I suspect that an update somewhere in SignalR broke it. 

I am using the .NET Standard SDK for Azure SignalR, version 1.4.0.
I am not entirely sure how to get the version of SignalR on our server, since it is hosted on Azure and all of this is pretty new to me.

Thanks in advance for your help !

**Comment by wanlwanl** [comment]
Hi @TechnoCompetences , I found you restart the instance at 11-17-2022 14:45:13 UTC. So 5xx is expected during restart. Is it possible that the issue happened during the restart?
Can you provide problem start time (including time zone) please if you need further help?

**Comment by TechnoCompetences** [comment]
Hello @wanlwanl and thanks for your answer.
Indeed, we restarted the instance as an attempt to solve the issue. We also attempted shutting down the web app, to test only with the local debug version (the debug version also uses the Azure SignalR instance).

It started happening prior to that, at an unknown point during wednesday night (let's say, between 22:00 UTC on november 16th and 14:00 UTC on november 17th), and keeps occurring to this time, so the restart doesn't seem to be the issue. I would add that I could not find anything out of the ordinary on the Azure control panel for SignalR, everything looks fine on Azure's end. But then again, I could have missed something important due to my lack of experience.

**Comment by TechnoCompetences** [comment]
Hello,
Another update : it seems that, after a nice weekend of cooling off, everything got back in order, and our app is working again. However, since both the breaking and the fixing were out of our hands (or so it seems), it could be useful to understand the source of the issue. That way, we could have a better understanding if it happens again, and options other than wait for it to be fixed.

Regardless, thanks for your assistance !

**Comment by wanlwanl** [comment]
@TechnoCompetences  Thanks for the update. 
applicationimt-server is a free tier resource. Due to VM patch in East US, Free resources of SignalR service may get impacted, and encounter 502 error or connection drop issue in last week. We have fixed the issue. Please use standard or premium tiers for SLA. Free resource is only for developing and debugging, and has no SLA.

If you need any help, please open ticket on azure portal, support engineer will be assigned to help you resolve your issue.
