### ISSUE TITLE
Breaking changes updating Microsoft.Azure.SignalR.Management to 1.19.0

### ISSUE THREAD

**Issue by paulhickman-a365** [Azure/azure-signalr#1728]
In a netstandard 2.1 class library project, when updating the Microsoft.Azure.SignalR.Management package from 1.18.3 to 1.19.0, the types of some of the properties of the ServiceHubContext class become undefined - e.g. IHubClients

I tried adding a reference to the package Microsoft.AspNetCore.SignalR.Core and that fixed the compile time issue but at runtime I get a file not found loading the assembly "Microsoft.AspNetCore.SignalR.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"

**Comment by Y-Sindo** [comment]
Seems to be a duplicate issue #1720. We will release 1.19.1 to fix the problem soon.

**Comment by Y-Sindo** [comment]
Update: 1.19.1 is released.
