### ISSUE TITLE
Getting "Invalid Target" response when trying to send a message from Postman

### ISSUE THREAD

**Issue by Mishu** [Azure/azure-signalr#173]
Hey guys,

I have this setup:
1. ASP.Net Core web app 
    - using package Microsoft.Azure.SignalR to enable SignalR
    - I have the service defined in Azure
    - I have a hub class defined in the Web App
    - sending messages from the web app hub works perfectly
2. I have an Azure Worker Role I want to send message to the web app by it's SignalR connection id.
To do this, I've built a class to send the messages using the REST API, but it doesn't work. I moved to test the REST API in Postman. There, after generating the server access token, I get the "Invalid target" response. If I use the same URL and same access token in code, the response is 202, but the message is never delivered. Are there any logs for this API in Azure to investigate?

Another thing that may be relevant is that in order to get a connection Id in Javascript I have to invoke a method on the hub to get it (`return Context.ConnectionId`. The property on the Javascript object used to initialize the SignalR connection is always set to 0.

The target that I'm using in the message is the Javascript name I've given when initializing the connection with SignalR in the web app. For example:
```
var receiveMessageCallback = function(someData) {
};
connection.on('receiveMessage', receiveMessageCallback);
```
The Postman payload is this:
```
{
	"message":{
		"target":"receiveMessage",
		"arguments":["test from Azure Worker Role"]
	}
}
```
What am I doing wrong, or am I missing something?

**Comment by chenkennt** [comment]
Which API are you using? We currently only support send to hub/group/user in REST API.

**Comment by Mishu** [comment]
Yeah, sorry about that I forgot to add the REST API call...

`https://{endpoint}.service.signalr.net:5002/api/v1-preview/hub/{hub}/user/{connectionId}`

**Comment by xscript** [comment]
Could you try to put your payload in below format?
```json
{
    "Target": "receiveMessage",
    "Arguments": ["xxxx"]
}
```

**Comment by Mishu** [comment]
Thanks for you reply, @xscript !

Now it says `202 Accepted` but the message still doesn't get delivered to the client. 
I've added `Message` object because of an error received when using Postman from the SignalR Azure Server...

**Comment by xscript** [comment]
When sending to a specific use, you need to:
- Add a `nameid` claim (`ClaimTypes.NameIdentifier` in C#) in the access token of each client, so that SignalR Service knows to which how to find each user.
- In the REST API call, use the same value of `nameif` claim as the user id. In your case, you are using `connectionId`, which is not right. Because `connectionId` and `userId` is not the same.

**Comment by Mishu** [comment]
I've added the `nameid` claim type and it is the same as the `userid` parameter. 
How can I get the user Id? 
If I use `Context.UserIdentifier` instead of `Context.ConnectionId` I get a `null` value.

Also when sending messages from the Web App hub I'm using the `connectionId`. 
I'm using the method `T Client(string connectionId);` from the `IHubContext<T>` instance which works fine.

**Comment by xscript** [comment]
Do you have a custom `IUserIdProvider` implementation? The default implementation of `IUserIdProvider` will get the `NameIdentifier` claim as `UserIdentifier` (see [here](https://github.com/aspnet/SignalR/blob/release/2.2/src/Microsoft.AspNetCore.SignalR.Core/DefaultUserIdProvider.cs#L17)).

**Comment by xscript** [comment]
@Mishu Is your issue resolved? Can we close this issue?

**Comment by Mishu** [comment]
@xscript I'm sorry I didn't got the time to test this yet... I'll get on it tomorrow (my time). 
Thank you for your assistance!

**Comment by Mishu** [comment]
@xscript I've updated the code to include a custom implementation (get a custom claim)... the response is 202 but I don't get any messages in the client. When using this approach I don't get messages even if I send them from the web api where the hub is defined... Any thoughts on that? (the client is an Angular 6 app, using @angular/signalr library)

**Comment by xscript** [comment]
Where did you put the `nameid` claim? It should be included in each client's access token like described [here](https://github.com/Azure/azure-signalr/blob/kevinzha/doc/docs/rest-api.md#user-related-rest-api).

**Comment by Mishu** [comment]
I’m using Azure Converged Application to get users logged in into the angular app, I’m using the acquiretTokenSilent method to get a token for signalR hub and backend web api. I’m using the `preferred_name` claim to get the user UPN from Azure Ad. Is that correct or should I use the `nameid` claim? I’m sending the token when creating the connection, I’m using `accessTokenFactory`. Am I on the right track? Or I’m missing something? 
Thanks for the help so far!

**Comment by xscript** [comment]
You should add a `nameid` claim with the value of each client's user id. This is the claim SignalR Service will use to identify each connection.

**Comment by Mishu** [comment]
@xscript Yes it works! I was setting the incorrect value when using the SignalR API... The Azure AD JWT token has a `nameidentifier` claim. 

👍 for Azure SignalR service! Very nice how you can send messages from the API!

Thank you for all the help!

**Comment by xscript** [comment]
Glad to help. Can we close this issue now?
