### ISSUE TITLE
[Emulator] Getting forbidden error in emulator when it gets triggered

### ISSUE THREAD

**Issue by Power-Maverick** [Azure/azure-signalr#1733]
### Describe the bug
I am running a local emulator for SignalR and whenever the emulator is triggered it throws following error:

```
fail: Microsoft.Azure.SignalR.Emulator.HubEmulator.HttpServerlessMessageHandler[0]
      The response for {hub}=signalrhub,{event}=connected,{category}=connections is unexpected: Forbidden.
```

### To Reproduce
- Start the emulator
- Start the Azure Function app locally that contains SignalR triggers
- Start the web app that will negotiate with the locally running SignalR instance (emulator's connection string)
  - Follow the prompts on the web app
- This does a successful negotiation and then invoked OnConnected - which throws the error described above.

### Exceptions (if any)

```
fail: Microsoft.Azure.SignalR.Emulator.HubEmulator.HttpServerlessMessageHandler[0]
      The response for {hub}=signalrhub,{event}=connected,{category}=connections is unexpected: Forbidden.
```

I am using the default Upstream settings as:

```
{
  "UpstreamSettings": {
    "Templates": [
      {
        "UrlTemplate": "http://localhost:7071/runtime/webhooks/signalr",
        "EventPattern": "*",
        "HubPattern": "*",
        "CategoryPattern": "*"
      }
    ]
  }
}

```

**Comment by vicancy** [comment]
Forbidden means your local azure function returns 403 Forbidden, do you see any trace in your azure function side?

**Comment by agravity-philipp** [comment]
Hi @vicancy ! I have the same issue. No trace in my function. I am using version '1.1.0' of Microsoft.Azure.SignalR.Emulator.

**Comment by agravity-philipp** [comment]
Oh.. just saw I have a different error:
`fail: Microsoft.Azure.SignalR.Emulator.HubEmulator.HttpServerlessMessageHandler[0]
      The response for {hub}=local,{event}=disconnected,{category}=connections is unexpected: NotFound.`

**Comment by vicancy** [comment]
Please feel free to reopen the issue if there are updates
