### ISSUE TITLE
Unable to run the emulator on Mac OS

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-signalr#1739]
### Describe the bug
I was able to install the emulator successfully per the documentation but issuing the following command does not run the emulator:

```
asrs-emulator upstream init
```
The error message reads as **zsh: command not found: asrs-emulator**. I don't think if this issue has anything to do with the M1 or Intel processors. The dotnet version is 6.0.403.

@vicancy

**Comment by vicancy** [comment]
looks like the tool path is not recognized.
Could you try 
```
export PATH="$PATH:$HOME/.dotnet/tools/"
```

**Comment by Arash-Sabet** [comment]
I am skipping this change as I'm unsure about the possible consequences. I use ngrok to divert traffic to my local machine.
