### ISSUE TITLE
Using MessagePack protocol in the context of serverless Azure SignalR services mutes receiving events/messages

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-signalr#1741]
### Describe the bug
The following code works fine with my Azure SignalR Services (serverless mode), and I can receive messages/events successfully.

```cs
var connection = new HubConnectionBuilder()
            .WithUrl(connectionInfo.NegotiationUrl!, options =>
            {
                options.Headers.Add("x-ms-signalr-userid", "myuserid");
                options.Headers.Add("x-functions-key", "mykey");
            })
            .WithAutomaticReconnect(new[] { TimeSpan.Zero, TimeSpan.Zero, TimeSpan.FromMilliseconds(5) })
            .Build();
        connection.Closed += excecption =>
        {
            return Task.CompletedTask;
        };
        connection.On("onMsg", (Action<object>)(message =>
        {
                    Console.WriteLine(message)
        }));
```
### To Reproduce
I referenced the [.NET MessagePack NuGet package for SignalR](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Protocols.MessagePack/6.0.12) and invoked `AddMessagePackProtocol()` extension method in the hub connection builder per the code below but stop receiving messages from SignalR.

```cs
var connection = new HubConnectionBuilder()
            .WithUrl(connectionInfo.NegotiationUrl!, options =>
            {
                options.Headers.Add("x-ms-signalr-userid", "myuserid");
                options.Headers.Add("x-functions-key", "mykey");
            })
                        .AddMessagePackProtocol()
            .WithAutomaticReconnect(new[] { TimeSpan.Zero, TimeSpan.Zero, TimeSpan.FromMilliseconds(5) })
            .Build();
```
### Exceptions (if any)
n/a

### Further technical details
n/a

**Comment by Y-Sindo** [comment]
Are you using persistent mode? Currently MessagePack is only supported in transient mode. See https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#summary-of-serialization-behaviors-of-the-arguments-in-messages

**Comment by Arash-Sabet** [comment]
@Y-Sindo Thanks for the reply. Yes, I am using the persistent mode, so I am closing this issue.

**Comment by Y-Sindo** [comment]
Hi @Arash-Sabet , now MessagePack is also supported in the persistent mode. You could update your SDK to the latest version and follow [the guide here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#message-pack-serialization) to enable MessagePack in the persistent mode.

**Comment by Arash-Sabet** [comment]
Awesome! Thanks for sharing this info.

**Comment by Arash-Sabet** [comment]
@Y-Sindo How does this enhancement apply to Azure SignalR Services and Azure Function Apps? We usually do not have `ServiceManagerBuilder()` in the function apps.

**Comment by Y-Sindo** [comment]
Hi @Arash-Sabet, please update your Microsoft.Azure.WebJobs.Extensions.SignalRService package to 1.10.0 and see  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/samples/Sample04_MessagePack.md for enabling MessagePack.
