### ISSUE TITLE
Mechanism for deployment

### ISSUE THREAD

**Issue by Bhaney44** [Azure/azure-signalr#1753]
### Is your feature request related to a problem? Please describe.
One big problem using Azure is that there is no existing way to deploy SignalR applications. The process for creating a SignalR applications is relatively straightforward locally. However, there is no way to deploy the local application via the cloud. 

When you click on `SignalR` under Azure services and `Create SignalR` in the [Azure portal](https://login.microsoftonline.com/trutradeproton.onmicrosoft.com/oauth2/v2.0/authorize?redirect_uri=https%3A%2F%2Fportal.azure.com%2Fsignin%2Findex%2F&response_type=code%20id_token&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2Fuser_impersonation%20openid%20email%20profile&state=OpenIdConnect.AuthenticationProperties%3DWMRNHHQVzMbTW9N2rnMIZrBYuAu-2BPbzeH4ysYRQxDZUPt57-9wgWJj0cSBCn1ZuBr9iPg8UqZajgJALJqTfGmsReO06Nxw-uDSNAaMx3rjoM4_DbnCy5YR9-7vpWoKUBKoRpLiqoT5dEmS9caCsW7Z0NX78dES4UJxhAuvuHJOWQJCn-MFxi9sTTiSjC39H_Ab0HNindcElc8LTLspTQYk7FC5CL9NrbvmVzUqO1UUV6EeG-kaZMIrdkOYqYoVyGleS1niyb9Du8-QP3GJdx6f8WmEs0YQGdBQiLa3qMtVIEg6dhP9P-Nf05GbSYMRoHQOCLXrrA1sBE5dj4J-PSpWrTU3J-tEyW0yMrZ5tOxIETgf1Jcyb2-lR7LmULYMhgTqNDdZ3Nrqzkb5gryUSFxeplccgvrKbNTIJ2vQBFZCsiof9jVzZRt4bXRfWcsNor9apZeZP4JUG6-NA6YXXahHMZ0rNrNMyRl-hGQODugc2zPneTVIv4qr24GLBGQsLjzXVuZ56QBIB5s73Hsk8abJCdtdmpIPfXKfXgjojl8&response_mode=form_post&nonce=638094110468298721.MmY1MzlhMTUtYTg2Zi00OWE3LTlhZDMtODk1ZGE3Mjc0OGU2MmMyNmU0OWYtOTM2MC00ZDQxLTg3MmUtYTZjMWFmMzBlOGY1&client_id=c44b4083-3bb0-49c1-b47d-974e53cbdf3c&site_id=501430&client-request-id=b6555a25-1efd-4605-96fc-5c64ad0a81fb&x-client-SKU=ID_NET472&x-client-ver=6.22.1.0), there is no way to connect the software to a GitHub repository. This is extremely strange because presumably, the Azure team would want people to be able to deploy SignalR applications. So, it is unclear, why they would essentially create a worthless software to prevent users from being able to deploy on their platform.

### Describe the solution you'd like
I would like to be able to deploy my SignalR application on Azure. 

### Additional context
The problem is it isn't clear whether the Azure team wants people to use their software. If they did, they would in theory make a method for deploying the application on the cloud. But, I know a lot of times the incentives within organizations are such that the individuals within those organizations are motivated to do the exact opposite of their stated purpose, which seems like it may be the case here.

<img width="1007" alt="Screenshot 2023-01-15 at 12 29 49 PM" src="https://user-images.githubusercontent.com/43055154/212565490-814cdae2-ef01-4740-bd8c-acba793db2b5.png">

**Comment by Bhaney44** [comment]
So, I decided I need to use a different software platform for this because Azure is far too convoluted to work with and there is no service provided. It feels like a scam to steal credit card numbers than an actual product and software services offering. I am not able to delete my payment data from my account, even though I have canceled my subscription. If anyone has any advice on how to proceed, it would be much appreciated. Thank you.

**Comment by Bhaney44** [comment]
This is actually incredibly frustrating because I cancelled all my subscriptions, but it still won't let me delete my credit card. The Azure Portal refers me to support, which directs me to a bot that generates a solution. The problem is the solution doesn't work. So, there is a bug in Azure software that prevents users from deleting their credit card information. This is a blatant violation of the privacy policy and federal law, particularly Title 18 of the United States Code. Horrible service.

**Comment by vicancy** [comment]
SignalR application is similar to other web apps and you could deploy them to Azure Web App. VSCode extensions can help simplify the workflow. Here is a sample sharing how to deploy your app to Azure https://learn.microsoft.com/azure/azure-signalr/signalr-tutorial-build-blazor-server-chat-app#publish-to-azure
