### ISSUE TITLE
Incorrect prompt on Azure SignalR Portal when navigating away.

### ISSUE THREAD

**Issue by BrettStyles** [Azure/azure-signalr#1792]
There is a bug when navigating away from 'Monitoring' on SignalR. A prompt says 'Your unsaved edits will be discarded.' but there is nothing to save, I am just viewing data.

**Comment by vicancy** [comment]
Hi @BrettStyles, by "Monitoring" could you share more about the repro steps? Which blade under "Monitoring"? 
![image](https://github.com/Azure/azure-signalr/assets/668244/4d384bda-e91a-422d-b486-dbcbcc458b9a)

**Comment by vicancy** [comment]
Thanks for reporting the issue, the fix will be online in the next release.
