### ISSUE TITLE
Upgrade dependency on Microsoft.Rest.ClientRuntime to Azure.Core

### ISSUE THREAD

**Issue by timjansenortec** [Azure/azure-signalr#1818]
### Describe the bug
Microsoft.Azure.SignalR and Microsoft.Azure.SignalR.Management packages depend on Microsoft.Rest.ClientRuntime.
This package is now deprecated: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/
Microsoft.Rest.ClientRuntime will no longer receive security fixes after September 2023.
The dependency should probably be updated to Azure.Core.

### Further technical details
- Your Azure SignalR SDK version
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 
- Your SignalR Client SDK version

**Comment by timjansenortec** [comment]
I was checking if we are supposed to use a different package, but 'Get started' documentation is still guiding to use Microsoft.Azure.SignalR.
see https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core#add-azure-signalr-to-the-web-app

**Comment by Y-Sindo** [comment]
@vicancy We uses `Microsoft.Rest.ClientRuntime` package for generated REST client, which is only used for health check API. Should we remove the generated client and roll back to the hand-written client?

**Comment by vicancy** [comment]
> @vicancy We use `Microsoft.Rest.ClientRuntime` package for generated REST client, which is only used for health check API. Should we remove the generated client and roll back to the hand-written client?

sounds good enough using a simple httpclient

**Comment by JapNolt** [comment]
any progress on removing this deprecated dependency??
