### ISSUE TITLE
Query active connections using the REST API

### ISSUE THREAD

**Issue by gerb0n** [Azure/azure-signalr#1826]
### Problem
I have a signalr-client (let's call it broadcasterclient), which is responsible for generating messages inside a message-group. It does so by doing a http-request to an azure function. The function broadcasts the message to other clients inside this specific message-group.

However I would like to add logic to the 'broadcasterclient' to only generate messages once there are actually other clients inside the same group. Else the 'broadcasterclient' would be generating messages while there are no other clients listening, which would be a waste of resources.

I would like the 'broadcasterclient' to be able to query the REST API the amount of active connections inside a group. That way the broadcasterclient could determine if there are more than one clients connected that it should start generating messages.

PS: I know I can use the `connected` and `disconnected` events and keep track of active clients inside the messagegroup. But the broadcasterclient might have connection interruptions and thus missing connects and disconnects from other clients. Which makes it unreliable to keep track of the active connections. Querying the Azure SignalR service would be the correct entity to maintain the active connections, in my opinion.

### Solution
I would like to be able to query the REST API with a `HTTP-GET` on the following URL:
`api/v1/hubs/myhub/groups/randomgroup/connections`

For the response a simple 'count' would suffice for me. But I can imagine that for other use-cases it would be nice to have a list of currently active connectionids within the response.

**Comment by vicancy** [comment]
I understand the scenario described, but Azure SignalR generally follows the SignalR protocol, and providing the list of connections in a group is not in the feature plan. Azure SignalR only charges for outbound traffic, so if you are sending messages to a group excluding your only connectionId in that group, the actual outbound traffic is 0 and there will be no cost. I hope that could reduce your concern about resource waste a little bit.

**Comment by gerb0n** [comment]
That does indeed reduce my concern about resource usage. For me that resolves my problem but I can imagine the feature might still be useful for others. It's up to you guys to put this on the longlist of future features or just close it this issue.

**Comment by vicancy** [comment]
Thanks for the confirmation, since providing lists of connections is not in our feature plan, I am closing the issue. Please feel free to commentit if you have any concerns.
