### ISSUE TITLE
Stateful Reconnect Support? [net8]

### ISSUE THREAD

**Issue by VincentH-Net** [Azure/azure-signalr#1878]
[Stateful reconnect](https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-8.0&tabs=dotnet#configure-stateful-reconnect) was added to SignalR in .NET 8.

[Feedback](https://github.com/dotnet/aspnetcore/issues/46691#issuecomment-1605770566) on this feature (for e.g. Blazor applications) was
> This feature is amazing and a must have

Multiple questions about support for this feature in Azure SignalR Service were [answered](https://github.com/dotnet/aspnetcore/issues/46691#issuecomment-1760220750) in the AspNetCore SignalR repo with
> Azure SignalR Service requires explicit support.

I could not find documentation / confirmation on whether this is supported.

# Ask
Is stateful reconnect officially supported in Azure SignalR Service?

**Comment by vicancy** [comment]
We are actively working on the support.

**Comment by vwxyzh** [comment]
* [x] Support negotiation version 1.0 (Released)
* [x] Support stateful reconnect for serverless (Released)
* [x] Support stateful reconnect for default (Deploying)
     * SDK version >= 1.26, Target framework >= .Net Standard 2.0 (Released)
     * Service runtime (Deployed)

**Comment by VincentH-Net** [comment]
@vwxyzh great to see this is coming. Is the `Support negotiation version 1.0 (Releasing)` enough to use stateful reconnect from an AspNetCore 8 service hosted in Azure Container Apps, or does that also require `Support stateful reconnect for default (Pending)`?

Also, where can progress on this be tracked - this issue or somewhere else?

Thanks for your support!

**Comment by vwxyzh** [comment]
@VincentH-Net Yes, it is required. Here is the document about [negotiation version 1](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md#version-1)
And you can track the progress in this issue.

**Comment by vwxyzh** [comment]
Blazor app requires SDK version >= 1.26.1

**Comment by SmartlyGit** [comment]
Hi, any news here? We were trying to set up Stateful reconnect with Azure signalr with this settings:
```
services.AddSignalR(hubOptions => {
    hubOptions.EnableDetailedErrors = false;
    hubOptions.KeepAliveInterval = TimeSpan.FromSeconds(3);
    hubOptions.HandshakeTimeout = TimeSpan.FromSeconds(10);
    hubOptions.ClientTimeoutInterval = TimeSpan.FromSeconds(15);
    hubOptions.MaximumParallelInvocationsPerClient = 1;
    hubOptions.MaximumReceiveMessageSize = 32 * 1024;
    hubOptions.StreamBufferCapacity = 10;
    hubOptions.StatefulReconnectBufferSize = 100000;
}).AddAzureSignalR(options =>
{
    options.ServerStickyMode = Microsoft.Azure.SignalR.ServerStickyMode.Required;
    options.AccessTokenLifetime = TimeSpan.FromDays(1);
    options.GracefulShutdown.Timeout = TimeSpan.FromSeconds(10);
    options.GracefulShutdown.Mode = Microsoft.Azure.SignalR.GracefulShutdownMode.MigrateClients;
    options.AllowStatefulReconnects = true;
});
```
and _Host:
```
configureSignalR: function (builder) {
    builder.withServerTimeout(15000).withKeepAliveInterval(3000).withStatefulReconnect({ bufferSize: 100000 });
}
```

Everything seems to be working, but we haven't seen any real change in production. However, uploading files larger than a few dozen KB is not working. I know that there is some bug related to this setting MaximumParallelInvocationsPerClient = 1; that affects file uploads, but this parameter remained in default in our case. We only tried to set up the StatefulReconnect.
[53951](https://github.com/dotnet/aspnetcore/issues/53951)

**Comment by vwxyzh** [comment]
@SmartlyGit if the issue is still there, please open a new issue and send me (zhyan at microsoft.com) the resource id and issue time. or open a case in azure support.
this issue should be closed now.

**Comment by jonas-nordtorp** [comment]
If this has been resolved, the docs should probably be updated to reflect it
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-9.0#azure-signalr-service-with-stateful-reconnect

They still redirect to this issue
