### ISSUE TITLE
Azure App Service with Authentication/Authorization enabled failed because of redirect response 

### ISSUE THREAD

**Issue by birynk** [Azure/azure-signalr#189]
We are using Azure SignalR and SignalR js library (1.0.0) in the client.  

The backend is a ASP.Net Core Web APP deployed in a Azure App Service with Authentication/Authorization activated and configured to use the Azure AD for validation.  We have deactivated CORS configuration in the AZURE portal as found here [https://github.com/aspnet/SignalR/issues/2095](https://github.com/aspnet/SignalR/issues/2095). The negociation process is working when the Authentication/Authorization is deactivated. But is not working when it is activated.

The request being sent from localhost against the Web APP in Azure:
OPTIONS https://app_host/hubName/negotiate HTTP/1.1
Host: app_host
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:5001
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Access-Control-Request-Headers: authorization,x-requested-with
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

We get back a redirect:
HTTP/1.1 302 Redirect
Content-Length: 607
Content-Type: text/html; charset=UTF-8
Location: https://login.microsoftonline.com/redirect_uri
Set-Cookie: Nonce=...; path=/; secure; HttpOnly
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=...;Path=/;HttpOnly;Domain=app_host

When the Authentication/Authorization is deactivated we get the correct response and the further negotiation is working:

HTTP/1.1 204 No Content
Vary: Origin
Server: Kestrel
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: authorization,x-requested-with
Access-Control-Allow-Origin: http://localhost:5001
Request-Context: appId=app_id
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=..;Path=/;HttpOnly;Domain=app_host

This is how we use the JS client.
`    var connection = new signalR.HubConnectionBuilder()
                .withUrl('https://app_host/hub_name', { accessTokenFactory: () => validjwtToken})
                                        .build();
`
 The jwt token will be fetched by a separated request and is a valid Azure AD token.   

Is there a way to fix the issue with the Authentication/Authorization sandbox? Or do we have to do the whole JWT validation logic in the backend application?

**Comment by vicancy** [comment]
Hi @birynk,
According to your 302 response:
```
HTTP/1.1 302 Redirect
Location: https://login.microsoftonline.com/redirect_uri
```
It looks like the token is not working and it fails login. Is `validjwtToken` fetched and contain valid value when calling `var connection = new signalR.HubConnectionBuilder() .withUrl('https://app_host/hub_name', { accessTokenFactory: () => validjwtToken}) .build();`?

To help us narrow down the issue, could you help to check if Authentication works well when you are not using Azure SignalR Service but the core SignalR following https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1? There should be no additional work for client side to make authentication work when switching from the core SignalR to Azure SignalR service.

**Comment by birynk** [comment]
Hi @vicancy, 

The token is valid.

I have tried also with the core SignalR in the Web APP and the same behaviour happens with Redirect for OPTIONS call.

On a second look, I believe the reason why it is failing on our side is the OPTIONS request send before POST /negotiate. POST /negotiate contains the token and is accepted by the Azure Auth Layer. But the OPTIONS does not contain the token thus the layer responds with a redirect.  

I do not understand why OPTIONS is send before the POST /negotiate is send. I haven't identifies why POST /negotiate matches the requirements of preflight requests described here https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests. 

Our SPA does something special and redirects the user to login.microsoftonline.com as soon the page is opened in the browser and before any request is send to the backend. Then all the requests to the backend contain the token.  The backend, with the Authentication/Authorization layer activated, only validates the jwt token if the request contains the token.

**Comment by vicancy** [comment]
I am closing the issue as it is now work with Azure SignalR Service properly.
