### ISSUE TITLE
Preserve client IP address in Context.HttpContext

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#191]
How can I see client remote IP address?

`Context.GetHttpContext().Connection.RemoteIpAddress` is null

In asp.net Core SignalR it worked.

**Comment by xscript** [comment]
For now, you can't. When using Azure SignalR Service, the `HttpContext` is not the `"real"` one but a logical one.
The `"real"` HttpContext is maintained in SignalR Service. The one you can access is rebuilt in your app with limited information.

Could you elaborate more how you'd like to use the client IP? We want to understand more about your scenario.

**Comment by davidfowl** [comment]
@xscript yep, I didnt mean roundtrip from the application, it would be sent like how we handle headers.

**Comment by alexiordan** [comment]
Maybe is related to this: https://github.com/Azure/azure-signalr/issues/25

**Comment by xscript** [comment]
With the latest Service SDK (1.0.0), remote IP address is available.
Close this issue.
