### ISSUE TITLE
MapHub configureOptions

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#192]
In asp.net Core SignalR MapHub method provides means for configuration:
```
MapHub<THub>(PathString path, Action<HttpConnectionDispatcherOptions> configureOptions)
```

Azure SignalRService only has
```
 MapHub<THub>(PathString path)
```

So one cannot state which transport protocols to be binded for each hub like it used to be an asp.net Core version:
```
MapHub<Hub>(new PathString("/mypathToHub"), options => options.Transports = HttpTransportType.ServerSentEvents | HttpTransportType.LongPolling);
```

How can transports be specified for each Hub in Azure SignalR Service?

**Comment by alexiordan** [comment]
Free, Shared and Basic App Service plans have a finite number of websocket connections. Therefore if one needs to limit those to specific areas that configuration was a possibility.

However, if client requests a specific transport the server will honour that, right?

**Comment by xscript** [comment]
>Free, Shared and Basic App Service plans have a finite number of websocket connections (https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits). Therefore if one needs to limit those to specific areas that configuration was a possibility.

When you use Azure SignalR Service, client doesn't establish persistent connection (ws/sse/long-polling) with your app server. Client will only establish connection with Azure SignalR Service. Is that what you worried about?

>However, if client requests a specific transport the server will honour that, right?

Yes, you can force a client to use a specified transport. Refer to [here](https://github.com/aspnet/SignalR/blob/release/2.2/src/Microsoft.AspNetCore.SignalR.Client/HubConnectionBuilderHttpExtensions.cs#L48).

**Comment by alexiordan** [comment]
I thought that since websocket connections are limited on some plans it is higher value resource (TCP connection) and therefor could be more wisely used.

SignalR Service has no limitations regarding  this (similar with one's from App Service plans)?

**Comment by alexiordan** [comment]
OK. One more question:
Can more than 1 App use a SignalR Service?

**Comment by xscript** [comment]
Yes. You can have multiple app service instances connected to the same Azure SignalR Service.

**Comment by alexiordan** [comment]
And they can be sepparate AppServices with different hubs, right?
Thank you!

For the initial issue I only see the reason for providing means to specify transport as an easy transition to/from in-AppService SignalR hosting to SignalR Service.

**Comment by xscript** [comment]
>And they can be sepparate AppServices with different hubs, right?
Yes.

> For the initial issue I only see the reason for providing means to specify transport per-hub as an easy transition to/from in-AppService SignalR hosting to SignalR Service.

You can also limit the available transport types in [`AddSignalR`](https://github.com/aspnet/SignalR/blob/release/2.2/src/Microsoft.AspNetCore.SignalR/SignalRDependencyInjectionExtensions.cs#L49). That is a global setting for all hubs. It won't impact the use of Azure SignalR Service.

**Comment by davidfowl** [comment]
> For the initial issue I only see the reason for providing means to specify transport per-hub as an easy transition to/from in-AppService SignalR hosting to SignalR Service.

We should document these gotchas

**Comment by xscript** [comment]
Documented at [here](https://github.com/Azure/azure-signalr/blob/2929468848954e1561e5692c376e9456f739479a/docs/faq.md#configure-transports).

**Comment by xscript** [comment]
#217 is merged. Close this issue.
