### ISSUE TITLE
How does AzureSignalR handle multiple instances of Azure Web App service ?

### ISSUE THREAD

**Issue by prohith14** [Azure/azure-signalr#1952]

**Comment by vwxyzh** [comment]
@prohith14, if you are using same hub (both name and application name are same), Azure SignalR Service will assume they are different instances for same hub, it will try to balance clients to all of your instances.
for example, if server A handle 1000 clients, and server B handle 500 clients, the services will try to route new clients to server B in much probability.
but if you enable sticky server in your server side, it always routes client to the server which client negotiated.
