### ISSUE TITLE
Connection close error is not readable.

### ISSUE THREAD

**Issue by JialinXin** [Azure/azure-signalr#1956]
### Describe the bug
improve error message on connection close.

Bad case:
`Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.`

**Comment by vicancy** [comment]
The error message is from signalr application layer, and prefixes are defined in the js signalr code https://github.com/dotnet/aspnetcore/blob/98c4546ddccfe2f62c4dc239fabd0c92848b255d/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L643
