### ISSUE TITLE
SignalR emulator returns 404

### ISSUE THREAD

**Issue by mojtabacazi** [Azure/azure-signalr#2018]
### Describe the bug
Running `asrs-emulator` locally, any request to the localhost:8888 comes back with 404. The backend code error is as follows:

```
Microsoft.Azure.SignalR.ServiceConnection[2]
      Failed to connect to '(Primary)http://localhost:8888(hub=CommentHub)', will retry after the back off period. Error detail: The server returned status code '404' when status code '101' was expected.. The server returned status code '404' when status code '101' was expected..
```

### To Reproduce
* Install `asrs-emulator v1.1.0`
* run `asrs-emulator upstream init`
* run `asrs-emulator start`
* replace signalr connection string with the output of `asrs-emulator`
* try to connect to the endpoint

### Further technical details
- `asrs-emulator v1.1.0`
- .net core sdks installed:  8 and 6 (6 is required for asrs-emulator)

**Comment by vicancy** [comment]
Emulator supports only serverless mode. The log shows that you are using Azure SignalR SDK which is using default(proxy) mode of Azure SignalR. You don't need the emulator when you are using Azure SignalR SDK, if you want to test locally, you could directly use self-host signalr.
