### ISSUE TITLE
Why does APIMS cause CORS issue for Socket Negotiate

### ISSUE THREAD

**Issue by Shaieb524** [Azure/azure-signalr#2054]
I have an APIMS that is connected to a web API that enables CORS and Websocket connections.

When I connect my Angular client directly to the API everything works fine, but when I connect, is to the APIMS I get CORS error for negotiating requests.

![image](https://github.com/user-attachments/assets/1d532af6-8953-48c6-ad28-934b49b595da)

When I tried to connect my Angular client app directly to my Backend Azure App Serivce, everything was fine (I had to check the Enable Access-Control-Allow-Credentials) and it worked even with wildcard domains for the client.

But now I can't do the same for APIMS.

I added Inbound CORS policy for APIMS for this API (All Operations) but still get the same error.

What am I missing? And is there any step to be done between the APIMS and the Web API other than the regular links (BTW all HTTP requests are working fine)?

**Comment by vicancy** [comment]
Here is a doc integrating with APIM FYI https://learn.microsoft.com/azure/azure-signalr/signalr-howto-work-with-apim

**Comment by Shaieb524** [comment]
Solved, the issue was i had to remove **<base />** line from the All operations CORS policy because it was overwritten by the inherited global policy (this is what <base /> means)
and to check the current policy you can hit the Calculate effective policy 
<img width="517" alt="image" src="https://github.com/user-attachments/assets/e11bb22a-f007-4b4e-b88c-6952f448c307">
