### ISSUE TITLE
No Connection on 1.0.0-preview1-10200  (stateless service, service fabric) 

### ISSUE THREAD

**Issue by mike7ang1rdz** [Azure/azure-signalr#212]
we are  currently working with (service fabric 6.3.162.9494) and with the previous version (**1.0.0-preview1-10015** )  working fine with stateless service. with the update to the version (1.0.0-preview1-10200) it stopped working.  

It seems that the connection is well stablished  (no errors) but  if  we override the onconnected method it doesn't connect

**Comment by vicancy** [comment]
Thanks for reporting a issue. Could you share more details about how you **override the onconnected method**, a minimum code snippet to repro the issue would be appreciated.

**Comment by vicancy** [comment]
Hi @mike7ang1rdz any updates?
