### ISSUE TITLE
Same hub name in multiple AppServices behavior

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#221]
AppService no. 1 - Hub name: "myHub"
AppService no. 2 - Hub name: "myHub"

If both AppServices share the same SignalR Service, which seems to be a supported scenario: https://github.com/Azure/azure-signalr/issues/192#issuecomment-419804810 , AppService no.2 does not receive its own messages, but receives AppService no.1's :-)

Maybe in the mapping service AppService address could be taken into consideration also...

**Comment by vicancy** [comment]
No, it is not supported. We do consider using hub’s FullName as the unique hub name in the future, however for now, we are using hub’s type Name as the unique identity for that hub, that is to say, if there are same hub names in multiple app servers, we consider them as same hub with multiple instances. So if the same hub name is shared by different app servers, the result is undetermined.

We recommend you generate two different endpoints for the two different app servers if they have the same hub name.

**Comment by vicancy** [comment]
Hi @alexiordan I am closing the issue, if you have any other concerns, feel free to reopen it.
