### ISSUE TITLE
NameClaimType not honored

### ISSUE THREAD

**Issue by NArnott** [Azure/azure-signalr#223]
I have a sample ASP NET Core web app that I'm hooking up to Azure SignalR. For authentication, I'm using an existing Identity Server. When the initial login authentication occurs, the claim type for the user's name is "name" (the JWT claim type name). When adding AddOpenIdConnect, I set x.TokenValidationParameters.NameClaimType = "name";

This works, and when I call HttpContext.SignInAsync(User), the User.Identity.Name is correct.

However, once a call makes it into the Hub class, Context.User.Identity.Name is null, and I discovered that the NameClaimType is no longer "name", but has reverted to "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

I removed the AzureSignalR specific calls in Startup.cs and the NameClaimType is persisted as "name". so it seems to be a bug with the Azure implementation of SignalR. Is there some extra configuration I am missing, or is this really a bug?

**Comment by vicancy** [comment]
I believe this is a bug that `x.TokenValidationParameters.NameClaimType` info is not passed through service to server and when creating the `User` the `NameClaimType` is reset to default https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionContext.cs#L53
