### ISSUE TITLE
'System.IO.InvalidDataException' in Microsoft.AspNetCore.SignalR.Protocols.Json.dll

### ISSUE THREAD

**Issue by jamesatgithub** [Azure/azure-signalr#226]
the signalr service hub works ok with js client, but when I tried to connect with a .net client, no message received and with this output:
Exception thrown: 'System.IO.InvalidDataException' in Microsoft.AspNetCore.SignalR.Protocols.Json.dll

also it seems once this .net client connected, the hub seems in a wrong state and the js client cannot receive message till the .net client disconnected

the .net client uses below code:
```
public ChatHubClient(string hubUrl, string token)
        {
            _connection = new HubConnectionBuilder()
                .WithUrl(hubUrl)
                .Build();

            _connection.Closed += async (error) =>
            {
                await Task.Delay(new Random().Next(0, 5) * 1000);
                await _connection.StartAsync();
            };
        }

        public async Task Connect(string roomName)
        {
            _connection.On<string,string,string,int>("said", (user, message, avatar, speakerId) =>
            {
                Console.WriteLine($"{user} said: {message}");
            });
            await _connection.StartAsync();
            await _connection.InvokeAsync("joinRoom", roomName);
        }
```

**Comment by vicancy** [comment]
Could you share the detailed stacktrace of your `'System.IO.InvalidDataException'`? Is it working when you are not using Azure SignalR service but using self-hosting SignalR? Looks like your .net client is not sending out valid hub messages.

**Comment by jamesatgithub** [comment]
problem resolved:
1. signalr client version should match to server version
2. the hub method name is case-sensitive
