### ISSUE TITLE
What counts toward connections?

### ISSUE THREAD

**Issue by Zaixer** [Azure/azure-signalr#234]
In metrics there are server connections and client connections listed. When is each of these types of connection made? I'm trying to predict how many units will be needed.

**Comment by zackliu** [comment]
When you start your app server, each hub will start 5 server connections by default. And client connection will be made after it negotiate with app server and redirect to service.

**Comment by Zaixer** [comment]
Ok thanks! So each app server in a server farm will start five connect per hub and each client will start one connection per hub?

**Comment by steve-79** [comment]
I have one single hub, but each time I start my program in visual studio, Azure SignalR uses 20 server connections.  Then if I stop debugging and try to debug again, this number jumps to 30 and maxes out the free plan, so then I receive the "Connection count reaches limit."

I have to completely exit visual studio and close all of the tabs I'm debugging in and wait a couple minutes to restart visual studio for the Azure Signal R server count to go back to 0....am I doing something wrong?  My client connections are always at 0, or match what they should be but it looks like the server connection count is adding in increments of 20 and I can't find any way to shut them all when they max out at 30 without exiting visual studio and re-opening it.  It's like I'm missing a server close hub method for when I stop debugging.

**Comment by Zaixer** [comment]
Nice, I close this then.

**Comment by kedzior-io** [comment]
We use paid tier for production and free tier for staging with with 1 app service and 2 hubs which automatically takes 20 connections on the start (5 per hub, both are asp.net so another 5 per hub)

We made a suggestion to increase that maximum limit of 20 connections. If you guys think it's a good idea and have some spare votes: 
https://feedback.azure.com/forums/915436-azure-signalr-service/suggestions/38952187-increase-free-tier-signalr-connection-limit
