### ISSUE TITLE
Access token no longer includes user claims

### ISSUE THREAD

**Issue by jeremywww** [Azure/azure-signalr#235]
After updating to 1.0.1, none of my claims are being included in the access token that is generated in the negotiate request. Here's the token I'm getting now:
```json
{
  "asrs.s.aut": "AuthenticationTypes.Federation",
  "nbf": 1539897555,
  "exp": 1539901155,
  "iat": 1539897555,
  "aud": "https://(removed).service.signalr.net/client/?hub=(removed)"
}
```

With 1.0.0 the access token would contain all of my claims, with the only difference being an additional `aud` pointing to the SignalR service.

**Comment by Jos1k** [comment]
I think after this change new bug appear, currently I'm using JWT token as auth mechanism for my SignalR and also using aud claim for internal purposes (I'm setting it to All). So internal validation passed and negotiate request to Azure Service has merged version of claims with 2 aud claims ('All' and with requestUrl)

previously (in version 1.0.1) was only one aud, and no error on negotiate request.

bellow I will attach 2 negotiate requests to Azure, one is working (1.0.1) and one is not (1.0.2). No changes from my side, only updating package version.

https://www.diffnow.com/?report=m2z70

**Comment by vicancy** [comment]
Thanks @Jos1k for reporting the issue. Yes, that is a regression we should fix. For your case, are you expecting `aud` `All` get passed to server? When using SDK 1.0.1, `aud`= `All` is overwritten by ours, is that OK for your auth mechanism?

**Comment by Jos1k** [comment]
Thx for fast response @vicancy, for me it's OK, our auth mechanism tolerates multiple aud claims.

In fact bigger issue in personal my case was a restriction in header length. I described it at this [comment](https://github.com/Azure/azure-signalr/issues/249#issuecomment-436273466), down to the [issue ](https://github.com/Azure/azure-signalr/issues/249)
