### ISSUE TITLE
Receiving 429 - Connection count reaches limit.

### ISSUE THREAD

**Issue by cyrilmestrom** [Azure/azure-signalr#241]
Connection count:
Server: 30 - Client: 0

Even when scaling up..

**Comment by zackliu** [comment]
When you scale up, there is a DNS cache pointing to the old free tier service. So, wait a few time and then the quota will change.

**Comment by cyrilmestrom** [comment]
That didn't help but last Friday afternoon this suddenly stopped and all was working again.
