### ISSUE TITLE
Add support for configuring multiple SignalR service instances

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-signalr#243]
This solves a couple of problems:
- Ability to increase the scale by adding more Azure SignalR instances and distribute messages across those instances
- Ability to support multi-region fan out 
 
There are 2 major pieces to this:
- Supporting multiple connection strings
- Selecting a single connection string on negotiate based on the incoming request (user extensible)

The negotiate payload will by default round robin and select a single end point that the client will connect to. Instead of opening N connections to a single service instance, we'll be opening N connections to M service instances. Each outgoing message should be sent to a single connection on each service instance (see https://github.com/Azure/azure-signalr/blob/25bcc7bd4b3fcd7209578d8138ff053e88490276/src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionManager.cs#L30)

A couple of services need to be tweaked to no longer assume a single connection string (like `IServiceEndpointProvider`) and we need to change the IServiceConnectionManager implementation to fan out to all servers.

**Comment by robynt34** [comment]
Is there an update on this feature?

**Comment by robynt34** [comment]
Thank you!

**Comment by vicancy** [comment]
Official instruction on this is here https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-scale-multi-instances
