### ISSUE TITLE
Support client ping message in serverless mode

### ISSUE THREAD

**Issue by chenkennt** [Azure/azure-signalr#244]
ASP.NET Core 2.2 version of SignalR starts sending ping message from client. This will break service in serverless mode as there is no server to handle the message. Need to add some special logic at service side to handle ping messages when no server is connected.

**Comment by davidfowl** [comment]
@chenkennt Any ideas when this will be implemented?

**Comment by vwxyzh** [comment]
Service has supported ping message.
