### ISSUE TITLE
The connection was aborted

### ISSUE THREAD

**Issue by cyrilmestrom** [Azure/azure-signalr#245]
We noticed many _The connection was aborted_ exceptions, and getting reports from clients there were no updates. All this when having 250 connections and 5 standard units. When scaling out to 10 the connections instantly moved to 481..
Now still seeing these exceptions...

**Comment by davidfowl** [comment]
What's the exception message you see?

**Comment by cyrilmestrom** [comment]
All seems fixed with a new instance
