### ISSUE TITLE
Failing negotiate request with 403 when JWT token is too long

### ISSUE THREAD

**Issue by Jos1k** [Azure/azure-signalr#249]
I think fixing [this issue](https://github.com/Azure/azure-signalr/issues/235) caused new bug.

Currently I'm using JWT token as auth mechanism for my SignalR and also using aud claim for internal purposes (I'm setting it to All). So internal validation passed and negotiate request to Azure Service has merged version of claims with 2 aud claims ('All' and with requestUrl)

due to [documentation ](https://github.com/Azure/azure-signalr/blob/5fad27b1892c0cc1388e53d42becfd8aa8e4d5e3/docs/rest-api.md) aud "Should be the SAME as your HTTP request url", but looks like it was changed in [this ](https://github.com/Azure/azure-signalr/pull/237/commits/72dca932fb9017728ea379066b9cd68e2c247d22) commit

previously (in version 1.0.1) was only one aud, and no error on negotiate request.

bellow I will attach 2 negotiate requests to Azure, one is working (1.0.1) and one is not (1.0.2). No changes from my side, only updating package version.

https://www.diffnow.com/?report=m2z70

**Comment by Jos1k** [comment]
Ok, after investigation, was found, that problem appears not because of multiple aud, but because of too long JWT token. After reaching some length - it's just returns 403 net::ERR_CONNECTION_CLOSED

Is there any way to increase the max length of headers?

**Comment by vicancy** [comment]
How long is the token when it returns 403? Is it happening when `/negotiate` with token inside the header? What is the total size of your header?

**Comment by Jos1k** [comment]
@vicancy it's about 6kb. Yes, it's happening during /negotiate request with the header inside.

So full scenario looks like that -> my web App using JWT auth, so after auth token validation passed, it creates an identity with claims (we are saving role access in claims, so it could be up to 100 key-value pairs). As I see,  azure signalR SDK sends my claims from identity + own ones (like aud, asrs.s.uid, asrs.s.aut, etc.). As a result - I'm receiving 403 error for the user who has "bigger list of roles" than some another users.

As a temporary solution, I've implemented simple middleware to remove roles claims before negotiate request, so JWT token will be short all the time, but be honest, from my perspective it would be great if SDK client can configure such things.

**Comment by vicancy** [comment]
There is a [ClaimsProvider](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/ServiceOptions.cs#L38) for you to customize the claims you want to pass into service then to server.

```
services.AddSignalR()
        .AddAzureSignalR(options =>
            {
                options.ClaimsProvider = context => context.User.Claims;
            });
```

**Comment by Jos1k** [comment]
Thanks, this is a more elegant way to reduce the length of my headers ;)

Still, maybe it's great to mention somewhere about this "headers length restriction".

**Comment by vicancy** [comment]
We've added check when the authorization header is too long.

**Comment by alexeystrakh** [comment]
@vicancy I'm having the (same issue)[https://github.com/dotnet/aspnetcore/issues/25262) and the AccessToken header size is around 1k (well below 4k). Do you think it's a related issue?

**Comment by vicancy** [comment]
Hi @alexeystrakh  It looks related, the exception is thrown from here https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Common/Auth/AuthUtility.cs#L74 when the generated token > 4K. It's not the AccessToken for your incoming request, but the token generated based on your user claims to access Azure SignalR.

Try to filter out unnecessary claims with the ClaimsProvider as shown here https://github.com/Azure/azure-signalr/issues/249#issuecomment-436601882 to see if it helps.

**Comment by PTC-JoshuaMatthews** [comment]
@vicancy I believe I am running into this issue with my .net framework application. Do you have any suggestion for how to filter claims in .net framework signalr?

**Comment by vicancy** [comment]
@PTC-JoshuaMatthews try this:
```csharp
services.MapAzureSignalR(GetType().FullName, options =>
            {
                // pick up necessary claims
                options.ClaimsProvider = context.Authentication?.User.Claims.Where(...);
            });
```
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#solution

**Comment by jaydgus** [comment]
> @PTC-JoshuaMatthews try this:
> 
> ```cs
> services.MapAzureSignalR(GetType().FullName, options =>
>             {
>                 // pick up necessary claims
>                 options.ClaimsProvider = context.Authentication?.User.Claims.Where(...);
>             });
> ```
> 
> https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#solution

@vicancy
What if we are still getting this error despite setting the claims to an empty array?

`app.MapAzureSignalR(GetType().FullName, new HubConfiguration { EnableDetailedErrors = true }, options =>
{
    options.ClaimsProvider = context => new Claim[] { };
});`

How would we trim the header size to the /signalr/negotiate request if the headers are still too large because of the cookies?
![image](https://github.com/Azure/azure-signalr/assets/3278145/a353e10e-5a4c-4e67-96ab-656104a4b79d)

**Comment by vicancy** [comment]
Cookies are not included when generating the negotiate response.

**Comment by jaydgus** [comment]
> Cookies are not included when generating the negotiate response.

~~Ok, I think they are included on the negotiate request. When I click on the request in firefox dev tools, you're seeing the request headers previously posted. Some internet searching suggests that cookies are included in ajax calls to the same domain.  Do you know how to prevent the passing of cookie data in ajax? I tried setting connection.withCredentials to false, but that did nothing.~~

~~If it is not Cookies and not Claims, then what is making the request so large? Or, how can we increase the 4K limit?~~

Thanks.

Edit: new info in follow up post.

**Comment by jaydgus** [comment]
@vicancy It could very well be passing Cookie data to the negotiate endpoint, but that is not where the problem is occurring. I downloaded the source and stepped through the code to see what is actually going on. The Claims are being included in the JWT building despite the attempt to reduce them via `options.ClaimsProvider = context => new Claim[] { };`. We have an OAuth server and our app is using `UseOpenIdConnectAuthentication`.

Edit: it turns out duplicate code resulted in the second attempt to edit Claims being ineffective.
