### ISSUE TITLE
Microsoft.Azure.SignalR.ServiceConnection

### ISSUE THREAD

**Issue by sandipbhavsar** [Azure/azure-signalr#251]
Microsoft.Azure.SignalR.ServiceConnection|ERROR|Service timeout. 30000.00ms elapsed without receiving a message from service.

**Comment by vicancy** [comment]
I am closing this issue as it contains little information for us to trouble shoot the issue. Could you please update the issue in detail inside https://github.com/Azure/azure-signalr/issues/250 for us to investigate?
