### ISSUE TITLE
ASP.NET Core client InvokeAsync throws exception - The server closed the connection with the following error: No server available

### ISSUE THREAD

**Issue by Simke11** [Azure/azure-signalr#253]
We have an ASP.NET Core API where we create Azure SignalR client on API startup. The client invokes Hub method to subscribe to a group. Our code looks like:

```csharp
string azureSignalRClientUrl = SignalRHelper.GetAzureSignalrClientUrl(config, "messaginghub");
HubConnection connection = new HubConnectionBuilder().WithUrl(azureSignalRClientUrl, option =>
{
	option.AccessTokenProvider = () =>
	{
		return Task.FromResult(SignalRHelper.GenerateAccessToken(azureSignalRClientUrl, "APIClient", config));
	};
}).Build();
connection.Closed += async (error) =>
{
	await Task.Delay(new Random().Next(0, 5) * 1000);
	await connection.StartAsync();
};
connection.On<MessageData>("receiveMessage", (message) =>
{
	var subject = message.Subject;
	var content = message.Content;
});
connection.StartAsync().Wait();
connection.InvokeAsync("Subscribe", "TESTGROUP").Wait();
```

Code to generate client URL and access token is based on [https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless)

We have a webhook which when request is received send a message to the group specified above -
`
_hubContext.Clients.Group("TESTGROUP").SendAsync("receiveMessage", myMessage).Wait();
`
The Hub looks like
```csharp
public class MessagingHub : Hub
{
	public Task Subscribe(string groupName)
	{
		return Groups.AddToGroupAsync(Context.ConnectionId, groupName.ToUpper());
	}
}
```

This has been in use for the couple of months or so while Azure SignalR was still in preview, and has been working fine, up until 3-4 weeks ago, when we started getting intermittent issues with InvokeAsync, which then completely stopped working in the last few days.

`
connection.InvokeAsync("Subscribe", "TESTGROUP").Wait();
`
has been throwing an error "The server closed the connection with the following error: No server available".

Just as I'm writing this, it has started working again. Any ideas why this is happening?

Our Azure SignalR service instance is in Standard pricing tier (we moved it from Free tier thinking that maybe Free tier was having issues)

On a (un)related note, Message Count graph on Azure Portal is not showing any messages being sent (connection graph show connections fine). We have our API deployed to azure, and when sending a message from Azure deployed API, local API running on dev machine gets the message, so it must be going via Azure SignalR service, but this does not seem to be reflected on Message Count graph.

**Comment by vicancy** [comment]
Message count sampling rate is per 100 messages, so if you are sending less than 100 messages, it is not shown on the metrics.

*No server available* can be caused by: 

https://github.com/Azure/azure-signalr/blob/dev/docs/faq.md#no-server-available.

Any server side log available during that period, were server connections disconnected at that moment?

**Comment by Simke11** [comment]
Thanks for your quick reply.

We are sending less than 100 messages, so that explains it.

As for logs, do you mean signalr logs on azure? In our use case, client initialization is the very first thing that happens, as it is part of our api Startup() pipeline.

Also issue is specifically with line
`
connection.InvokeAsync("Subscribe", "TESTGROUP").Wait();
`
If that is removed there are no client connection errors and a message can be sent successfully to all clients instead of a specific group. In this scenario there is at least a few seconds delay between client starting the connection and a message being sent to clients.

Should we be adding a delay of couple of seconds between StartAsync() and InvokeAsync()?

**Comment by vicancy** [comment]
Just noticed that you are using "serverless" mode. In Serverless mode, client are in **LISTEN** mode and is now by design **NOT** allowed to send messages to service. Please refer to https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#serverless for details.

**Comment by Simke11** [comment]
Meaning that Invoke() should not be working at all now? Are there any code samples for ASP.Net Core client that don't use serverless mode? This was the only example of ASP.NET Core client that I could find.

**Comment by Simke11** [comment]
Also, looking at C# client example for Core SignalR [https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1)

Connection is intialized with internal server URL, like
```csharp
connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:53353/ChatHub")
                .Build();
```
And in our example instead of using our web API url, we use url of our Azure SignalR service instance.

**Comment by vicancy** [comment]
Here is the server side change for enabling Azure SignalR https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoom

The **only** change required to switch from self-host SignalR to Azure SignalR is the **server side** change. **No change** needed for C# client. So you are still initializing the connection with your web app server URL, e.g. `http://localhost:53353/ChatHub`. 

Under the hook, with `AddAzureSignalR` added to your server, it returns a redirect `URL` to the client with client `negotiate` request and SignalR client initiates another negotiate call to Azure SignalR. Here https://github.com/Azure/azure-signalr/blob/dev/docs/internal.md#client-connections describes the workflow in detail.

**Comment by Simke11** [comment]
Ok, so the question is - if I use the URL https://our_azure_signalr_instance.service.signalr.net/client/?hub=messaginghub as a paramter to `.WithUrl()`, should `InvokeAsync()` work or not? 
As I'm understanding it, using this URL would mean we are running in serverless mode, and as such doing `InvokeAsync()` on client should NOT work? 
Behavior I'm seeing at the moment is the opposite - this is currently working - I can connect using `.WithUrl("https://our_azure_signalr_instance.service.signalr.net/client/?hub=messaginghub")` (and pass credentials) and I can InvokeAsync() successfully to subscribe to a group. I can also successfully send a message to the said group.

So is the behavior I was seeing until yesterday where I was getting error "No server available" on InvokeAsync() correct, and the fact that it is working now is actually a bug in Azure SignalR?

The issue I'm having is that I am not seeing consistent behavior. Documentation says that what I'm doing should **NOT** work, yet I'm seeing it **WORKING** now.

**Comment by Simke11** [comment]
Also, in our use case we have to create a client in our API startup pipeline. Trying to use API url as parameter to `.WithUrl()` throws 'Task was cancelled' error on trying to `.StartAsync()`, presumably due to timeout as it sits there for a while before failing.

I have moved client connection to after `UseAzureSignalR()` to make sure hub route is set up (even though we don't want new client connection being created on every request, but just to test and make sure all Azure SignalR setup has been run prior).

Is there anything else that needs to happen for this connection to internal URL be successful?

```csharp
public class Startup
{
	public Startup(IConfiguration configuration)
	{
		Configuration = configuration;
	}

	public IConfiguration Configuration { get; }

	// This method gets called by the runtime. Use this method to add services to the container.
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

		services.AddSignalR().AddAzureSignalR();

		//SubscribeAzureSignalR(Configuration);
	}

	// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
		}

		app.UseAzureSignalR(routes =>
		{
			//routes.MapHub<MessagingHub>("/hubs/messaging");
			routes.MapHub<MessagingHub>("/messaginghub");
		});

		SubscribeAzureSignalR(Configuration);

		app.UseMvc();
	}

	private static void SubscribeAzureSignalR(IConfiguration config)
	{
		HubConnection connection = new HubConnectionBuilder()
			.WithUrl("http://localhost:62123/MessagingHub")
			.Build();
		connection.Closed += async (error) =>
		{
			await Task.Delay(new Random().Next(0, 5) * 1000);
			await connection.StartAsync();
		};
		connection.On<MessageData>("receiveMessage", (message) =>
		{
			var subject = message.Subject;
			var content = message.Content;
		});
		connection.StartAsync().Wait();
		connection.InvokeAsync("Subscribe", "TESTGROUP").Wait();
	}
}
```

**Comment by vicancy** [comment]
I think you misunderstand the SignalR usage and your code above shows that you are mixing SignalR server and client together.

So for SignalR we have **server side** and **client side**, the concept is the same as a normal web app https://developer.mozilla.org/en-US/docs/Learn/Server-side/First_steps/Introduction#What_is_server-side_website_programming. *App server* is where you have your logic to handle request, *client* is what your customer uses to initiate request to your server.

So for SignalR, the methods such as `.AddSignalR().AddAzureSignalR()` and `UseAzureSignalR` are the server side logic. With these methods, your app server is able to handling requests to `/signalr`.

And methods such as `HubConnection connection = new HubConnectionBuilder()` are the **client side** logic, it should be inside **another** C# client app. https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1 SignalR supports different languagues for client, you can have C# client, you can also have JavaScript clients, JAVA clients...

Back to your original question, you mentioned that 
> We have a webhook which when request is received send a message to the group specified above -
> _hubContext.Clients.Group("TESTGROUP").SendAsync("receiveMessage", myMessage).Wait();
> The Hub looks like
> ```
> public class MessagingHub : Hub
> {
> 	public Task Subscribe(string groupName)
> 	{
> 		return Groups.AddToGroupAsync(Context.ConnectionId, groupName.ToUpper());
> 	}
> }
> ```

`Hub` is a concept for SignalR server https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1. So where do you have the Hub logic? The place you have the hub logic is the ** server side** of your SignalR.

**Comment by Simke11** [comment]
In our scenario, our Web API is both server and the client.

Hub logic is in the API.
Webhook that receives a request which triggers sending of messages to the client is a controller in the API.
The client which receives messages is instantiated in the Startup() pipeline of the API, and listens for messages for as long as the API is running.

We use Azure SignalR for system-level messaging in our API.

To give you an idea of what we are doing:
- An event message is sent to Azure Event Grid
- API webhook is set up as subscriber and receives event grid message
- Webhook then broadcasts a message to azure signalr  clients
- Because we'll have our API sitting behind load balancer, that means there will be multiple instances of the API sitting behind the balancer, and we use Azure SignalR to send a message to all instances that are running.

Hope this explains better what we are trying to achieve and why the API needs to act both as a server and the client.

**Comment by vicancy** [comment]
The latest 1.0.5 SDK mitigated the issue, please have a try.

**Comment by vicancy** [comment]
Hi @Simke11 sorry for the late reply. 

I reviewed all your response and I believe the root cause is as follows:

When your app server starts, `UseAzureSignalR` tries to establish *server connection* to ASRS, while the client side `new HubConnection` also tries to connect to ASRS and it connects so quickly that none of the *server connections* are yet established. So ASRS take this client connection into **serverless** mode which does not allow client->server traffic. 

By chances, if the client connects later then one *server connection* connects, this issue does not occur.

The ASRS has a `Service Mode` settings, if you switch it to `Default`, client side `hubConnection.StartAsync` will throw when no server is connected. In this way, you can retry `StartAsync` until the server connections are established.

![image](https://user-images.githubusercontent.com/668244/50393987-f5172600-0794-11e9-9a7b-b63026dd40d0.png)

**Comment by vicancy** [comment]
Please reopen it if https://github.com/Azure/azure-signalr/issues/253#issuecomment-449699588 does not solve your issue.
