### ISSUE TITLE
Server connection count vs client connection count

### ISSUE THREAD

**Issue by steve-79** [Azure/azure-signalr#254]
What is the max number of client connections I could have with 1 unit?  I know it says 1000 connections, but how does that work with the server connection count?

In other words, will the automatic 5 server connections per hub sustain more than 5 client connections?  Or do I have to make changes to my code to enable a single hub (with the 5 server connections) to serve 1000 client connections.

My goal is to have a single hub and 1000 users (clients) connected to serve real time data to a very large team.

**Comment by zackliu** [comment]
First, the quota contains the server connections and client connections, so if you need to guarantee 1000 client connections, 2 units is a better choice. 
Then, one hub with 5 server connections can handle 1000 client connections. But please note, one client connection will be routed to a specific server connection, and once the server connection abort somehow, all client connections routed to this server connection will be terminated at once.

**Comment by steve-79** [comment]
That sounds great thank you for your response!  Also, what constitutes a message in the message count?  Because I'm sending a JSON object which seems to be counted as around 100 messages.  Is there a better way I could package this to be a smaller number of messages?  Because right now with only about 10 clients connected, I've hit 152k messages in the span of a few hours.

**Comment by steve-79** [comment]
#299
