### ISSUE TITLE
Groups management issue

### ISSUE THREAD

**Issue by Harween64** [Azure/azure-signalr#256]
Hi,

We are using signalr core and azure signalr service in a data synchronization scenario between user devices (ios, android, desktop, etc...) to notify user devices to initiate a synchronization process.
To avoid unnecessary code on clients to exclude his own notification, we decide to use groups combined with user id, and notify all **other** devices that they can synchronize.

The asp.net core app containing the signalr hub is deployed on two deployment slots, expose a rest api to achieve synchronization, and is connected to azure signalr service (one instance).

Here is the code of the hub:
```C#
[Authorize]
public class SynchronizationHub : Hub
{
  public async Task NotifyOtherDevicesSynchroIsNeeded()
  {
    try
    {
    	await Clients.OthersInGroup(Context.UserIdentifier).SendAsync("SynchroIsNeeded").ConfigureAwait(false);
    }
    catch (Exception ex)
    {
    	Trace.WriteLine("SignalR NotifyOtherDevicesSynchroIsNeeded Method error : " + ex.Message);
    	throw;
    }
  }
  public override async Task OnConnectedAsync()
  {
    await Groups.AddToGroupAsync(Context.ConnectionId, Context.UserIdentifier).ConfigureAwait(false);
    await base.OnConnectedAsync().ConfigureAwait(false);
  }
  public override async Task OnDisconnectedAsync(Exception exception)
  {
    await Groups.RemoveFromGroupAsync(Context.ConnectionId, Context.UserIdentifier).ConfigureAwait(false);
    await base.OnDisconnectedAsync(exception).ConfigureAwait(false);
  }
}
```

Everythings is working perfectly... 
**except with one user (for the moment)**. 
This is really the only thing that is changing on clients. We log in with this specific user, and notifications does not work.

With this user particularly :
- We have set some debug snapshot break points to see what happens on the hub (on server side), and a break point in all the clients code in the SynchroIsNeeded callback method.
	- OnConnectedAsync, OnDisconnectedAsync, NotifyOtherDevicesSynchroIsNeeded seems to be called normally.
	- On server Context.UserIdentifier is correct (the guid of the user).
	- On all other clients, the "SynchroIsNeeded" call back method is **not** called.
		
- If we the remove usage of azure signalr service (only using signalr core on one deployment slot), everything is working well.

- We have found a workaround by not using groups but user in the hub. The problem is that the caller is called back and I don't know how to exclude it.
Here is the workaround code:
```C#
[Authorize]
public class CloudSynchronizationHub : Hub
{
  public async Task NotifyOtherDevicesSynchroIsNeeded()
  {
    try
    {
    	await Clients.User(Context.UserIdentifier).SendAsync("SynchroIsNeeded").ConfigureAwait(false);
    }
    catch (Exception ex)
    {
    	Trace.WriteLine("SignalR NotifyOtherDevicesSynchroIsNeeded Method error : " + ex.Message);
    	throw;
    }
  }
}
```

- Can you please explain me if I missed something with groups management ?
- Can I maybe have a better workaround ? (maybe with a random tag parameter generated by caller, but I need to update clients)
- It is possible to add a "Send to User except connection id" api or extension api in the IHubClients Api ?

**Comment by vicancy** [comment]
* Your usage looks good to me
* cc @davidfowl how about a "Send to User except connection id" api? 

For this specific `Context.UserIdentifier`,
1. what happens when `Clients.Group(Context.UserIdentifier).SendAsync("SynchroIsNeeded")`? Is it working?
2. Does the issue persist when `Context.ConnectionId` changes?

**Comment by Harween64** [comment]
Hi @vicancy,

We have published app today with the code back to the groups usage, and guess what? now it is working well for everyone.
I really don't understand why this happens with this user and not others...
Maybe a publish issue, but I suspect deployment slot issue: To search the issue, we have scaled out down our app to one instance, and later scaled out to two instances. So we had a new fresh deployment slot...

Anyway, I will respond your answers:

1. It is really hard to say, but I can tell you that no exceptions were catched.
   Regarding Snapshot details, in LifeTimeConnectionManager instance , there was only the caller's connectionId.
   But both clients was able to call "Notify" hub method.
   
2. If you mean if I disconnect/reconnect clients, yes the issue was persisting.
   I don't know how to force a refresh of connectionId, and how to track it.

I think you can close this issue.
I will make another one if needed.
Thank you for your time.
