### ISSUE TITLE
Asp.net Azure SignalR Service- server responded with a status of 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by ramjbe27** [Azure/azure-signalr#257]
Hi ,

I tried to use azure signalR Service in Asp.net Mvc application and for that i have created a SignalR service in Azure and tried to use from the code as told in the code sample  **AzureSignalR-samples-master\aspnet-samples\ChatRoom** .
But i found that auto generated  SignalR hub script is not created and it is throwing error as attached in the image. 

![asp net mvc - azure signalr service](https://user-images.githubusercontent.com/44195398/48207232-3c3c8980-e396-11e8-98be-f01102269109.png)

And my web.config screenshot is also attached. And i also had a doubt like where to use the key 
name="Azure:SignalR:ConnectionString" which in the connection string in web config file .
![web config](https://user-images.githubusercontent.com/44195398/48207434-a2291100-e396-11e8-989c-0aa4c823fd11.png)

**Comment by vicancy** [comment]
Can you share your MVC `Routing` code? SignalR first requests for `<your server url>/signalr/hubs` to get the proxy file but looks like it fails. It hasn't yet talk to Azure. Is it working when not using AzureSignalR?

Your web.config looks good to me.

**Comment by vicancy** [comment]
500 means server throws error. Could you break when CLR exceptions throw and also disable "Just My Code" (Debug=>Options) to see what throws? Doubt if it is assembly version related issues. 
![image](https://user-images.githubusercontent.com/668244/48250219-87a77400-e438-11e8-8e32-1b364f6c0c26.png)

![image](https://user-images.githubusercontent.com/668244/48250126-30a19f00-e438-11e8-9cc8-b224c04a161d.png)

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
