### ISSUE TITLE
Connection lost on Docker container

### ISSUE THREAD

**Issue by unsafecode** [Azure/azure-signalr#264]
We're running a ASP.NET Core 2.1 Web API which proxies outbound notifications to Azure SignalR, running on a Docker Container on AKS.

Sometimes throughout the day, we get the following exception:

```
fail: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[15]
      Error while sending a message.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completi
ng the close handshake. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values
```

And then the only way to recover is to kill the container and restart it.

**Is there a way to make the HubContext recover and reconnect automatically?**

**Comment by gidifede** [comment]
Same issue here.
Anyone can help?

**Comment by vicancy** [comment]
What is your version of the SDK? 
The latest SDK changes the behavior to always reconnect https://github.com/Azure/azure-signalr/releases/tag/v1.0.3
Please have a try and let us know if there are any issues/concerns/suggestions

**Comment by unsafecode** [comment]
@vicancy Thanks, we'll look into take and update this issue ASAP

**Comment by unsafecode** [comment]
Looks like the latest release was at least beneficial, since we are not noticing so many exceptions.
