### ISSUE TITLE
Consider extend the default JWT token's lifetime

### ISSUE THREAD

**Issue by vicancy** [Azure/azure-signalr#274]
Currently the default value of JWT token's lifetime is 1 hour.
For ASP.NET Core SignalR, when it is using WebSocket transport type, it is OK.
For ASP.NET Core SignalR's other transport type, SSE and longpolling, this means the connection can at most persist for 1 hour.

For ASP.NET SignalR, the client sends a `/ping` KeepAlive request to the service from time to time, when the `/ping` fails, the client aborts the connection and never reconnect. This means, for ASP.NET SignalR, the default token lifetime makes the connection lasts for at most 1 hour for all the transport type.

We shall consider a better user experience:
1. Make the default token lifetime much longer, for example, 1 day
2. Consider a way to renew the token?

**Comment by AndyDalton** [comment]
We've just ran in to this problem with ASP.NET SignalR. It would be great if there was a way the token would auto-renew as our usage means connections will be open for long periods of times and we really want to migrate To Azure SignalR.

**Comment by tehmas** [comment]
We are using ASP.NET SignalR with Azure SignalR. We are facing the same problem. Maybe a way to determine if the token is valid can remedy the problem.

**Comment by choronz** [comment]
You can set the claim for 'exp' in the JWT token directly if you are using the 
[Rest Api](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#using-rest-api) to send messages.

**Comment by vicancy** [comment]
For security concerns, extend TTL is not encouraged. We have a detailed explanation and suggested solution in https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#solution-2
