### ISSUE TITLE
Error response from Azure SignalR Service with too large of header

### ISSUE THREAD

**Issue by rhux** [Azure/azure-signalr#275]
I don't know if this is the right forum for this potential bug.

We've noticed that when we are trying to connect to the Azure SignalR service with an access token that is 14k (don't ask) the XhrRequest response returns an error.  It appears to work with access tokens that are 5k or less.  We know that access tokens are not supposed to be that large, but we are dealing with a legacy system and user who just happens to have a large token.

The response from the server with the large request when in a web browser fails with a "cors" error.  But works fine when sending through fiddler (fails also when sending through postman).

We are using the 1.0.4 client, and the call fails on the https://XXXXXX.service.signalr.net/client/negotiate?hub=XXXXX&asrs.op=%2Fhubs%2Fnotifications POST call.

In googling around it looks like Apache has a default limit of 8k and IIS has a default limit of 16k. Is the Azure SignalR Service by any chance running on Apache?

**Comment by vicancy** [comment]
For HTTP/2, the max length for a single header is 4K, so if you are using browser to access Azure service, you will encounter this limitation with `ERR_CONNECTION_` error.

For HTTP/1.1, or c# clients, the max URI length is 12K, max header length is 16K. 

So in general, we suggest the access token under 4K.

There is a [ClaimsProvider](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/ServiceOptions.cs#L38) for you to customize the claims you want to pass into service then to server.

```
services.AddSignalR()
        .AddAzureSignalR(options =>
            {
                options.ClaimsProvider = context => context.User.Claims;
            });
``` 
If it is not applicable for your case, please let us know so that we can consider increasing the limit.

**Comment by rhux** [comment]
Hi, sorry for the long delay.  We've tried limiting the claims in the ClaimsProvider, for example doing the following:
`.AddAzureSignalR(options =>
            {
                options.ClaimsProvider = context => new[]
                                  {
                                      new Claim(ClaimTypes.NameIdentifier, context.User.Claims.Single(c => c.Type == "sub").Value)
                                  };
            });`

And while the user is able to correctly negotiate with AzureSignalR, all messages are now being broadcast to all users.  
Are we doing something wrong? Does the claims that are attached to the ClaimProvider have to match on both the Server and the Client (ie js client in `signalR.HubConnectionBuilder().withUrl("", {accessTokenFactory: () => access_token})`

Thank you

**Comment by vicancy** [comment]
`new Claim(ClaimTypes.NameIdentifier, context.User.Claims.Single(c => c.Type == "sub").Value` means the user is using `sub` claim as its user id. 
You can check if it works as expected inside `OnConnectedAsync`:
```cs
public override Task OnConnectedAsync()
        {
            var id = Context.UserIdentifier;
            return base.OnConnectedAsync();
        }
```

> all messages are now being broadcast to all users

Could you provide more information about it? Is `SendToUser` sending message to all the users?

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by mmulhearn** [comment]
Hi, we just ran into this as well.  We need to validate the JWT against a public key we have, so I'm not sure limiting claims being sent will work as that would invalidate the validation of the JWT as a whole.

**Comment by vicancy** [comment]
@mmulhearn 
>  validate the JWT against a public key we have

It should be the validation steps for your own app server, instead of the JWT used to talk to Azure SignalR, so claim length check only impact the JWT token sent to Azure SignalR and it should not affect your own authentication flow.
