### ISSUE TITLE
ASP.Net "No server available" error

### ISSUE THREAD

**Issue by tomasmcguinness** [Azure/azure-signalr#279]
I have a simple SignalR setup on ASP.Net (.Net 4.6.2). When using a local SignalR server, my JS client connects without issue. 

However, when I change from app.MapSignalR() to app.MapAzureSignalR(GetType().FullName) I can't seem to get my JS client connected at all. Here is a screenshot of the output from console.

![image](https://user-images.githubusercontent.com/302741/49088237-b901ab80-f250-11e8-9bfa-f80a1b3b24db.png)

I'm not doing anything more than trying to connect.

I'm using Microsoft.AspNet.SignalR 2.4.0-preview2-20181018-02

How can I fix this issue?

**Comment by vicancy** [comment]
"No server available" indicates that your app server has trouble connecting to Azure service. You can enable tracing from the app server side with the following to see if any error throws.
```
GlobalHost.TraceManager.Switch.Level = SourceLevels.Information;
```
A sample here: https://github.com/Azure/azure-signalr/blob/dev/samples/AspNet.ChatSample/AspNet.ChatSample.SelfHostServer/Startup.cs#L19

If you are local debugging the server side, you can also uncheck "Just My Code" and break when any CLR exception throws:
![image](https://user-images.githubusercontent.com/668244/49123286-fe76b500-f2f2-11e8-908b-4b7bcb0508c3.png)
![image](https://user-images.githubusercontent.com/668244/49123306-13534880-f2f3-11e8-80b6-576a3c10bfc8.png)

**Comment by tomasmcguinness** [comment]
Thanks for the quick reply. I've debugged locally and caught some exceptions when opening the webpage with the SignalR client.

Here are the ones I caught:

System.Security.Authentication.AuthenticationException: "A call to SSPI failed, see inner exception."
     - (inner) "The function requested is not supported"

System.ObjectDisposedException: 'Safe handle has been closed'

System.Net.WebException: 'The request was aborted: Could not create SSL/TLS secure channel.'

System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server'
	- (inner) WebException: The request was aborted: Could not create SSL/TLS secure channel.

The AuthenciationException is the one that occurs the most frequently.

Does this help shed any light on the issue?

**Comment by vicancy** [comment]
Azure Service only support TLS1.2 for security concerns. 
Please add following code to your Startup:
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by tomasmcguinness** [comment]
Thank! I tried that myself and it has solved it.

I thought ..NET 4.6 defaulted to TLS 1.2, so I got that wrong.

Thanks!

**Comment by spooky** [comment]
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

does this switch the protocol type system wide? if so, is there a way to limit this switch just for signalr?

**Comment by spooky** [comment]
targeting .net 4.7 in web.config also works and doesn't require forcing TLS 1.2 in code (provided that it can be negotiated)
related link: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-net-framework-47-or-later-versions
