### ISSUE TITLE
Microsoft.Azure.SignalR.ServiceConnectionManager`1.WriteAsync(ServiceMessage serviceMessage) Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by martindjerf** [Azure/azure-signalr#294]
Net Core version: 2.2
Microsoft.Azure.SignalR : 1.0.4
Application type: Web API

Hi, we are experiencing a strange scenario when we are using Azure SignalR 1.0.4. We have different groups that we create for different types of messages that needs to be sent out to the clients that subscribe to these groups. They usually get them but then some times they stop getting the messages but we can still see that our SendAsync method is called. We are also seeing a few exceptions that show up regularly saying:

> Microsoft.Azure.SignalR.ServiceConnectionManager`1.WriteAsync(ServiceMessage serviceMessage)
> 
> Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index

We have tried a few different approaches that has been mentioned in other issues that have revolved around clients not reciving messages but with no luck. Hopefully you can help us out.

**Comment by vicancy** [comment]
Could you share how you use the Azure SDK? Could you provide some pseudo code?
Have you customized the `ConnectionCount` in [ServiceOptions](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/ServiceOptions.cs#L32]?

**Comment by vwxyzh** [comment]
Do you get the instance of `HubLifetimeManager<WorkerHub>` from DI context (e.g. Controller) then send messages?

**Comment by martindjerf** [comment]
Yes, except I am using the `IHubContext<WorkerHub>` and not the `HubLifetimeManager`

**Comment by vwxyzh** [comment]
@martindjerf in controller?

**Comment by martindjerf** [comment]
@vwxyzh I have followed the example given in this example:
https://github.com/aspnet/AzureSignalR-samples/blob/master/samples/FlightMap/FlightControl.cs

**Comment by vwxyzh** [comment]
We find a defect for this case, we will fix it soon.
Thank you for your report this issue.

**Comment by martindjerf** [comment]
Great! Thank you. Will you let me know when it has been fixed?

**Comment by vwxyzh** [comment]
@martindjerf we will release the fix in next Friday.

**Comment by vicancy** [comment]
1.0.5 contains the fix, please have a try.

**Comment by brread** [comment]
I'm confused by the resolution of this issue. It looks like the code change that @vwxyzh  pushed in just gives a more descriptive error message.

What does "The Service Connection Is Not Connected" mean? 

Is this related to using DI on the `IHubContext`? (Or the `HubLifetimeManager`). Does something about this method affect the Service connection?

**Comment by vicancy** [comment]
@brread For this issue, it happens when server does not yet connected to Azure SignalR Service however DI gets the `IHubContext` and tries to send message to Azure SignalR Service, so it is a right behavior to throw an exception in such case.
