### ISSUE TITLE
Negotiation net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by Mishu** [Azure/azure-signalr#298]
Hello,

I have a recent issue with Azure SignalR. I'm getting this error `net::ERR_CONNECTION_CLOSED` when it's sending a negotiation request to the Azure SignalR service.
The OPTIONS request works with no issue.
I'm using Microsoft.Azure.SignalR 1.0.4 in the .Net Core 2.1 Web Api project and on client side Angular 6 with "@aspnet/signalr": "^1.1.0". 
The negotiation link is `https://<azureSignalRService>.service.signalr.net/client/negotiate?hub=<webApiHubName>&asrs.op=%2F<webApi_MapHubName>`.

Also, before the error I get a `Warning: Error from HTTP request. 0: .` from in `XhrHttpClient.js:73`.

Note, if running from Postman the request is ok and I get back a connection Id and the available transports.

**Comment by vicancy** [comment]
Probably caused by long access token. see https://github.com/Azure/azure-signalr/issues/275#issuecomment-441961901

**Comment by Mishu** [comment]
Yeah, that was the issue, I've added the user's group membership from ADAL and the token was way bigger.
Thanks!
