### ISSUE TITLE
Question - How is the message count determined?

### ISSUE THREAD

**Issue by steve-79** [Azure/azure-signalr#299]
Thank you for the great work you've done - I just have a question on what determines the message count in Azure?

It seems like I'm having a very high message count (like 152 thousand messages) in a span of just a few hours with a very small number of connections (less than 20).  I just want to make sure I can optimize my code to have a smaller number of messages sent/received if possible because I'm sending entire data objects through the Azure SignalR hub which I think is causing this high count.

Thanks again in advance for your help.

**Comment by zackliu** [comment]
We only count the outbound messages and ignore the ping messages between clients and servers. Any message that larger than 2KB will be counted as multiple messages of 2KB.
E.g. You have 3 clients and 1 app server. One client send one message to let server broadcase and each message is 4KB. The message count will be 8 (1 from service to app server and 3 from service to clients, and each message will be counted as 2)

**Comment by steve-79** [comment]
That's perfect, thank you!
