### ISSUE TITLE
MapHub exception "Type T contains generic parameters"

### ISSUE THREAD

**Issue by lilraft** [Azure/azure-signalr#310]
I'm getting "Type T contains generic parameters" exception when trying to register a hub with generic method and parameter T. Using Microsoft.Azure.SignalR 1.0.4 and Microsoft.AspNetCore.SignalR 1.0.4 . Is there any way to use generic methods in the hub?

**Comment by zackliu** [comment]
Could you give an example how did you use generic method.
I tried the code below
```
public class Chat<T> : Hub
{
     public void BroadcastMessage(string name, T message)
     {
         Clients.All.SendAsync("broadcastMessage", name, message);
     }
}
public class Person
{
     public string Name { get; set; }
}
```
And register with
```
app.UseAzureSignalR(routes =>
            {
                routes.MapHub<Chat<Person>>("/chat");
            });
```
And seems it doesn't throw exceptions

**Comment by lilraft** [comment]
I'm trying to use generic method

`public class Chat : Hub
{
     public void BroadcastMessage<T>(string name, T message)
     {
         Clients.All.SendAsync("broadcastMessage", name, message);
     }
}`

**Comment by zackliu** [comment]
Generic method is not supported in SignalR as far as I know

**Comment by BrennanConroy** [comment]
We have an issue tracking making the error nicer https://github.com/aspnet/AspNetCore/issues/6949

**Comment by vicancy** [comment]
Closing this as it sounds like a SignalR issue.
