### ISSUE TITLE
Azure SignalR Service Connection is not active - 1.0.0-preview1-10264

### ISSUE THREAD

**Issue by YoupHulsebos** [Azure/azure-signalr#324]
I updated our signalr packages from 2.4.0 and added RunAzureSignalR instead of RunSignalR. Added this code in de Startup.cs

`app.Map("/signalr", map =>
{
    var hubConfiguration = new HubConfiguration
    {
        EnableDetailedErrors = true
    };
    map.RunAzureSignalR(typeof(Startup).FullName, hubConfiguration, options =>
    {
        options.ConnectionString = AppApiSettings.SignalRServiceConnectionString;
    });
});`

But when I try to send a message to the hub I get an exception:
> The connection is not active, data cannot be sent to the service.

Can't find any reason this would happen or why the service would not run. When I use RunSignalR (self hosted) everything runs great.

Any help would be greatly appreciated.

**Comment by vicancy** [comment]
Could you enable trace as similar to
https://github.com/Azure/azure-signalr/blob/ea2823c0897289e33fe2b3b3059194bf156e5101/samples/AspNet.ChatSample/AspNet.ChatSample.SelfHostServer/Startup.cs#L21
to see if any error reported when establishing server connections?

**Comment by YoupHulsebos** [comment]
Sure thing. The complete log is attached here: [log.txt](https://github.com/Azure/azure-signalr/files/2735440/log.txt)

Seems it does error on making the connection to the signalr service:
Failed to start connection. Error starting transport 'WebSockets'.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Error: 11 : Exception thrown: 'System.Net.WebSockets.WebSocketException' in Microsoft.Azure.SignalR.AspNet.dll

**Comment by YoupHulsebos** [comment]
Thanks! Turns out it was the exect same error: TLS2.1 was not enabled on my .net472 solution. The same solution in that ticket fixed my issue. Maybe an idea to add this to the docs as an reminder for people on .net framework.
