### ISSUE TITLE
Allow UUID as a group name

### ISSUE THREAD

**Issue by ebashmakov** [Azure/azure-signalr#345]
UUIDs should be allowed to be used as a group name since it's a very common scenario.

The current [limitation](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1-preview.json#L143) is the following:

> should start with alphabetic characters and only contain alpha-numeric characters or underscore

_source_: https://github.com/MicrosoftDocs/azure-docs/issues/20988

**Comment by vwxyzh** [comment]
We will change the limitation to less than 256, allow any character, like space, emoji.
* Following cases are invalid:
  * *Empty*
  * LongLong...LongString (>256)
* Following cases are valid
  * `1234`
  * *GUID*
  * `1 2 3`
  * `123-456`
  * `~!@#$%^&*()_+=[]{}\|;:'",./<>?`
  * :smile: *emoji*

If your group name contains spiecal characters, for rest API, you should encode the group name (like [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)).

It will be release by service.

**Comment by ebashmakov** [comment]
@vwxyzh great news! I'm looking forward to it. Do you have ETA? What do you mean by "It will be release by service."?

**Comment by vwxyzh** [comment]
About 11 March, release to all regions may be one week.
This limit is in SignalR service side, we will update service, so no SDK changes.

**Comment by jraristi** [comment]
Is there an official documentation page where we can track this?
