### ISSUE TITLE
Use app name as a prefix to hub so that different apps with same hub name can share the same Azure SignalR

### ISSUE THREAD

**Issue by vicancy** [Azure/azure-signalr#348]
Quote from our user:
> I would like to understand what app name does and if I can use it for different environments. 
>
> Eg. In the code below environment would be ‘staging’, ‘prod’, ‘dev’
> map.RunAzureSignalR("DrTalkSignalR" + environment, new HubConfiguration()
>
> Would this work and be fully isolated?

**Comment by kroymann** [comment]
A feature like this would be extremely useful to me.  Our service has multiple different parallel environments (prod, test, staging, etc.).  In the prod environment we use Azure SignalR to handle connection capacity, but none of the other environments have enough concurrent users to warrant paying the additional money for each one to have it's own dedicated Azure SignalR instance.  Given that we can't currently isolate the different environments from each other within a shared Azure SignalR instance, this forces us to only use Azure SignalR in production, which raises the chances of encountering bugs that only repro in production. :(

I envision something simple like this with the AppName getting prepended to each of the HubNames internally:

```
services
    .AddSignalR()
    .AddAzureSignalR(opts =>
    {
        opts.ConnectionString = azureSignalRConnectionString;
        **opts.AppName = $"{appName}_{envName}"**;
    });
```

**Comment by nmehlei** [comment]
I would find this also very useful, for the same reasons as @kroymann already described. According to #192 , it's already possible to re-use the same Azure SignalR Service for different App Services (and thus environments) as long as the hub names are different. With a setter for a prefix (or something similar) this could be improved upon.

**Comment by steverash** [comment]
I needed this, so have done the work and created a pull request.   

#449 

Works in the way that @kroymann describes.

**Comment by vicancy** [comment]
Already supported
