### ISSUE TITLE
Split claimprovider for server and SignlarR Service

### ISSUE THREAD

**Issue by ferronsw** [Azure/azure-signalr#376]
Hello,

I've seen multiple issues regarding the length of the bearer token like #275 and #249.
I'm using some claim values within the SignalR Hub OnConnect and OnDisconnect methodes.
In certain scenarios the claim is to big to be used for the SignalR service. 

These custom claims (claim-identity) are not required for the SignalR Service, but I can't specify a ClaimsProvider for the Hub (within my own app) and one for the service.  Because the claims are specified in two different claim-identities it's easy to split these. Is it possible to implement such feature?

**Comment by vicancy** [comment]
`ClaimsProvider` are for Hubs only. You can consider Service as a proxy and it just pass the claims inside `ClaimsProvider` to your Hub.
