### ISSUE TITLE
Is there a SDK available to use AzureSignalR in Node.JS Express App?

### ISSUE THREAD

**Issue by RamYadlapalli** [Azure/azure-signalr#378]
All the examples and samples talk about using Azure SignalR with .net core and .net apps, is there a SDK available for Node.JS Express application to user this service?

**Comment by vicancy** [comment]
When using AzureSignalR, there are 2 parts, client and server.
For server which specifies `RunAzureSignalR`, it only supports .net core and .net apps.

For client, the SignalR client can be seamlessly used. Current SignalR client supports multiple languages, such as JavaScript, TypeScript, Java, .net, please refer to https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-2.1

**Comment by ekaram** [comment]
Hi Vicancy, would you be able to tell us whether nodejs server is on the roadmap?  If so, the ball park timeline?  thanks in advance

**Comment by vicancy** [comment]
HI @ekaram, no, nodejs server is not in our support plan. Could you share more about your user scenario? How about the serverless approach https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript?
