### ISSUE TITLE
When using a custom protocol, a client receives a message from a hub a multitude of times, and the server doesn't receive messages at all.

### ISSUE THREAD

**Issue by daltonks** [Azure/azure-signalr#379]
I am attempting to write my own `IHubProtocol` that uses Protobuf for `InvocationMessages`.

The problem is that in my test projects, the client receives a multitude of the same message from the server (when it is only sent once upon connecting), and the server is not receiving a message from the client (which is invoked right after `StartAsync`).

I tried updating `Microsoft.AspNetCore.SignalR.Client` to `3.0.0-preview-19075-0444`, but that only resulted in an exception `"Method 'get_MinorVersion' in type 'Unofficial.SignalR.Protobuf.ProtobufProtocol' from assembly 'Unofficial.SignalR.Protobuf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."`.

[Here](https://github.com/daltonks/Unofficial-SignalR-Protobuf) is the solution that attempts to do this. You can give it a try by putting a connection string in [SignalR Connection String.txt](https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf.Test.Server/SignalR%20Connection%20String.txt) and running the server and client.

Since there is no documentation on how to create a custom `IHubProtocol`, I looked at how a decompiled `JsonHubProtocol` is created and used. Based on this, I created [these extension methods](https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf/SignalRBuilderExtensions.cs) to add my [ProtobufProtocol](https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf/ProtobufProtocol.cs) to an `ISignalRBuilder`.

Server
- [Startup](https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf.Test.Server/Startup.cs)
- [Hub](https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf.Test.Server/TestHub.cs)

Client
- [Program](https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf.Test.Client/Program.cs)

**Comment by BrennanConroy** [comment]
Very cool! Glad you're trying out your own protocol.

One thing I noticed by glancing at the code is that you never modify the `ref input` in `ParseMessages`. https://github.com/daltonks/Unofficial-SignalR-Protobuf/blob/master/Unofficial.SignalR.Protobuf/ProtobufProtocol.cs#L125

You need to modify it up to the point you've used it otherwise the outer loop that is calling `ParseMessages` will keep sending you the same sequence of bytes over and over again.

```csharp
// example
input = input.Slice(consumedBytes);
```

**Comment by daltonks** [comment]
Thank you for taking a look @BrennanConroy !
Oh wow, I never would have thought to do that. I will give that a try 🙂

**Comment by daltonks** [comment]
Spot on, that was exactly the issue. I am now receiving one message on the client and one message on the server.

You are a godsend, thank you.

**Comment by BrennanConroy** [comment]
I'll make a note on the docs issue that that is something to point out when we write a doc.
