### ISSUE TITLE
Hourly disconnects across all clients

### ISSUE THREAD

**Issue by dmitrysamuylovpharo** [Azure/azure-signalr#381]
We are seeing consistent disconnects almost on the dot every hour across multiple clients (windows desktop apps). I saw there were some issues with load-balancing that were affecting all azure signalR instances as mentioned here [Issue# 283](https://github.com/Azure/azure-signalr/issues/283) Could this still be affecting our Azure SignalR instance as well? Same as the person in Issue # 283, we have re-connect logic in place and it is working correctly and successfully re-connecting after a few seconds after the disconnect, but seeing the disconnects with such high frequency very much not expected, what can we do to fix this? Any help would be highly appreciated.

Error we see in the client when disconnected:
`The remote party closed the WebSocket connection without completing the close handshake.`

**Comment by vicancy** [comment]
Such frequent disconnects are not expected. Could you email me your instance name and subscription id for me to check from the service side?

**Comment by dmitrysamuylovpharo** [comment]
@vicancy thank you for the reply, emailed the info to your Microsoft email

**Comment by vicancy** [comment]
The service side log shows that, for some client requests, the client initiated the request and established connection with the service, however the service didn't received any handshake messages from client for 15 seconds time out and so service cancelled the connection after the timeout.

What version of SignalR client are you using? Is it possible for you to repro the issue and capture the client payloads?

**Comment by dmitrysamuylovpharo** [comment]
@vicancy There are some client connections that fail sometimes after trying to reconnect, I see these failures after 15 seconds and our application logic re-tries to reconnect and eventually successfully connects. This is not the issue I am trying to track down and resolve. After the initial connection is made by a client, the server disconnects that client after exactly 1 hour, all subsequent re-connects are also disconnected after exactly 1 hour of the connection staying alive. This leads me to to suspect some kind of configuration setting somewhere, just not exactly sure where.

The SDK I was using was Microsoft.Azure.SignalR v1.0.4, I see the latest available is v1.0.7, I am going to update to the latest and give it a try again, hopefully it fixes this problem.

**Comment by vicancy** [comment]
It sounds like the token expires. https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#403-returned-for-client-requests

**Comment by dmitrysamuylovpharo** [comment]
@vicancy yes! this sounds EXACTLY like what is happening, thank you! I will try this out but I already am almost 100% sure this is the issue. I'll update here once I've confirmed this workaround fixes my issue. Thanks again.

**Comment by dmitrysamuylovpharo** [comment]
@vicancy I added the configuration change to increase the lifespan of the token to `options.AccessTokenLifetime = TimeSpan.FromDays(6);` and updated the `Microsoft.Azure.SignalR` Nuget package to version 1.0.7, but I see no change in the disconnect behavior, it still consistently disconnects exactly 1 hour after the connection is established on the client. Anything else you could think of that could be responsible for this? Is there anything in the client library that can affect this?

Thanks again for your attempts to help.

**Comment by vicancy** [comment]
Any special configs from your app server side? Are there any events logged in the Azure Website, e.g. website restart? Are there any abnormal messages logged in the client side when it disconnected?

I checked your service side log, it shows no error with the websocket connections, the last-for-1-hour websocket connections are just closed normally without error. Looks like it is the client that closed the connection normally.

**Comment by dmitrysamuylovpharo** [comment]
The `ConfigureServices` looks like this but i don't see anything that should be affecting this that stands out to me:

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddSignalR()
                    .AddAzureSignalR(options =>
                    {
                        options.ConnectionString = "Endpoint=https://name.service.signalr.net;AccessKey=keyhere;Version=1.0;";
                        // extend the TTL
                        options.AccessTokenLifetime = TimeSpan.FromDays(6);
                    })
                    .AddHubOptions<BroadcastHub>(options =>
                    {
                        options.EnableDetailedErrors = true;
                    });

            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(options => {
                options.Authority = "okta.com";
                options.Audience = "api://default";         
            });
        }

I enabled the error logging on the asp.net core web service that implements the signalR hub and I don't see any errors, just see the re-connection of the websocket after the connection is lost. 

On the client I profiled using fiddler and don't see any other traffic either other than the re-connect requests after the connection is lost.

**Comment by vicancy** [comment]
Noticed that your client requests are going through a proxy. Could you try the client without the proxy to see if the connections are influenced by the proxy?

Some proxies might have issue supporting WebSocket, *since WebSocket connections are long lived, as opposed to the typical short‑lived connections used by HTTP, the proxy needs to allow these connections to remain open, rather than closing them because they seem to be idle.*

**Comment by dmitrysamuylovpharo** [comment]
@vicancy that's a great suggestion, we arrived at the same suspicion a day ago and tried disabling the proxy for client requests connecting to our signalR instance and these hourly disconnects went away, what a crazy wild goose chase, but glad we finally figured it out, thank you for all your help in trying to figure this out!
