### ISSUE TITLE
Allow group names longer than 64 characters

### ISSUE THREAD

**Issue by adamra-msft** [Azure/azure-signalr#387]
The group name length limitation of 64 characters is somewhat restrictive. For example, ideally we would like to use group names an order of magnitude larger (say 512-1024 chars), or else we have to resort to hashing to reduce the size of group names.

In addition, it would be nice if there were additional allowed characters in the group names. Right now, there are only 63 distinct characters allowed (case-sensitive alphanumeric plus underscore) which means we cannot base64 encode the IDs that go into group names.

**Comment by vwxyzh** [comment]
#345

**Comment by vwxyzh** [comment]
Service was updated, group name was up to 1024 characters.
