### ISSUE TITLE
SignalR Service client cannot receive messages after re-connect

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#396]
I have a strange behavior that I don't know what to do next..

I have a SignalRService connected to my appservice.
I also have several clients (UWP app) that connect to SignalRService.

From those clients ~one~ **some** have this strange behavior.
After the restart of the appservice, it succesfully connects to SignalRService and receives all the _application messages_ sent by appservice.
But if it reconnects to SignalRService, then from appservice it doesn't receive any _application messages_ sent to it.
However it receives ping messages and is also capable of sending _application messages_

Message are sent like this:
`
await m_Hub.Clients.Group(clientId).SendAsync("ServerToClientMessage", jsonSerializedMessage);
`

Please help!

**Comment by alexiordan** [comment]
In server logs it seems I can only see received messages, not sent ones, except from ping ones. 
If this is incorrect, please advice on how cand I find the message requested by appservice to be sent to the clients.

**Comment by alexiordan** [comment]
@vicancy , Would you please take a look?

**Comment by vicancy** [comment]
By default, SignalR Service switches to Serverless mode when no app server connected. So in your case, it might be that in that moment when all server connections were dropped, the client connected to SignalR service automatically fallback to Serverless mode and not connected to the app server.

You can change the behavior to `Default` mode to enforce Azure SignalR to disable Serverless mode. When the Azure SignalR is in `Default` mode and all server connections dropped, during that period, clients trying to connect to Azure SignalR will fail.
![image](https://user-images.githubusercontent.com/668244/52987363-c4223d00-3435-11e9-946d-3ef9a3c69065.png)

**Comment by alexiordan** [comment]
It is set to Default.
However is the client that when reconnects no longer receives messages. Appservice was not restarted in this interval.
To be more clear here are the steps below:
1. Restart AppService to be o a fresh ground.
2. Connect UWP Client
3. UWP Client is connected and everything works well.
4. Restart the UWP Client (or just reconnect)
5. UWP Client no longer receives _application messages_. However it sucessfuly receives {"type":6} messages. It also succesfully send _application messages_ and _infrastructure messages_ ({"type":6}) .

**Comment by alexiordan** [comment]
UPDATE no. 2
It still happened soI decided to toggle the Service Mode.

- From Default to Serverless
- From Serverless to Classic
Now I don't encounter the issue anymore.

However I am deeply worried about this silent way of not working... AppService restart did not fix it.
1. Would you please take a look and see why this happened?

2. Regarding ServerMode: Default means Classic I presume, right?

**Comment by vicancy** [comment]
We have a not-yet-fixed display bug in portal that the initial state of "Default" behaves like "Classic". So you need to toggle ServiceMode to another and then toggle it back to "Default" to make it work.

**Comment by alexiordan** [comment]
OK, but please take a look at what happened there. Because my client did not received any messages. Besides it didn't know it need to reconnect. Given somehow reconnects, still did not fix the issue...

**Comment by vicancy** [comment]
> My understanding is that toggling restarted the SignalR Service that "fixed" the issue...

No, toggling ServiceMode is a hot reload that it does not restart the SignalR Service.

> UWP Client no longer receives _application messages_. However it sucessfuly receives {"type":6} messages. It also succesfully send _application messages_ and _infrastructure messages_ ({"type":6}) .

This only happens when the client enters Serverless mode, and the client should still be able to receive "broadcast" messages from server using `m_Hub.Clients.All.SendAsync`. Is that true in your case? Group broadcast messages are not able to be received by this client who entered Serverless mode because this client did not enter the server logic to join a group, so that's why `await m_Hub.Clients.Group(clientId).SendAsync` not work for this client.

> * From Serverless to Classic"  Now I don't encounter the issue anymore.

I am not sure if is this toggling fixed the issue or it is that the client just reconnect with all server connections connected so that the client reconnects to Proxy mode successfully and did not repro the issue. I would suggest toggling the ServiceMode to "Default" and have a retry.

**Comment by alexiordan** [comment]
1. It is still unclear to me if the Default is one of the other 2 or not. I do not understand why you suggest to put it back on Default. Classic mode isn't what I need (since I use an appservice)? 
2. Is the client informed that will be connected to a serverless instance? How can I track that?

**Comment by vicancy** [comment]
> It is still unclear to me if the Default is one of the other 2 or not. I do not understand why you suggest to put it back on Default. Classic mode isn't what I need (since I use an appservice)?

No, Classic mode is actually a mixed mode. You need 'Default' mode which prevents the Service from switching automatically to Serverless mode.

> Is the client informed that will be connected to a serverless instance? How can I track that?

No. "Default" mode helps to prevent that silent switch.

**Comment by alexiordan** [comment]
@vicancy, it happened again.
Client report that connected. Server reported client connected.
However client doesn't receive any commands from the server.
What could cause the server to switch again to the _non-Default_ state?

**Comment by vicancy** [comment]
If *Server reported client connected*, then client is connected to the server, it does not enter `serverless` state.

**Comment by alexiordan** [comment]
This kind of commands did not reach the client:
```
 await myHub.Clients.Group(someId).SendAsync("methodName", JsonConvert.SerializeObject(message));
```

**Comment by vicancy** [comment]
Where is the join Group take place? Is it just before the group.SendAsync? In current implemenation, group related messages should happen in the same app server to guarantee the order, a general practice is similar to:
```cs
            await Groups.AddToGroupAsync(Context.ConnectionId, groupName);
            await Clients.Group(groupName).SendAsync("echo", "_SYSTEM_", $"{name} joined {groupName} with connectionId {Context.ConnectionId}");
```

**Comment by alexiordan** [comment]
1. AddToGroupAsync is called on Hub.OnConnectedAsync();
2. Then the connectionId is stored for further refence until OnDisconnectedAsync() occurs from that connection. At that moment the connection is RemoveFromGroupAsync().
3. Whenever application needs (can be any time afterwards: 30 minutes, 2 hours etc.) calls SendAsync on that group.

Calls are in the same appserver.
However, I believe the logic is correct since it works most of the time.

 Just every now and then, this kind of error occurs that are hard to spot from my side since I have no control over the logs of the SignalR Service. This is why I rely very much on your support.

**Comment by alexiordan** [comment]
@vicancy , It is happening right now on one of my clients. 

Server receives data from client, but it doens't receive data from server.

Could you please take a look if you spot something server side?

I'll get to you via e-mail with Azure instance and connection details .

**Comment by hempe** [comment]
Started seeing the same. 
Clients can still send messages to the server, but don't receive any.
My SignalR Services are set to Default.
Tried to send messages with User(userId) and Client(connectionId). Both just "stop" working.

**Comment by vicancy** [comment]
@hempe 
1. any logs from your app server side? How you invoke `User(userId)` and `Client(connectionId)`? 
2. Do all clients meet the issue or some?
3. By "Clients can still send messages to the server", does the server receive the message successfully?

**Comment by hempe** [comment]
@vicancy I found the issue with "Client(connectionId)" i think, I used version **1.0.11** (so sending to clients connected to the same back-end worked, but to "others" did not. I think it should be OK with **1.0.12**, but haven't tested it yet. right?

As for sending to User(userId):
1. I send with something like this, where the hubContext `IHubContext<MyHub>` is injected:
```
await this.hubContext.Clients.User(deviceId).SendAsync("MethodName", new SomeDto { });
```
2. What kind of logs? From the app server side everything looks ok. Is there a way to get asrs internal logs?
3. Yes messages are received successfully.

I think I'll have to create a new issue, because it also seems to happen without a reconnect, the clients just stop receiving messages. (but still can send to the server).

I'll try to see if I can reproduce it with a simple example project and create a new issue.

**Comment by vicancy** [comment]
@hempe  thanks for looking into the issue. However, I am not aware of any such issue in SDK 1.0.11. Please open an issue if you find anything.

**Comment by TingtingAn** [comment]
@hempe   any luck?  I got same issue with you.

**Comment by vicancy** [comment]
@TingtingAn latest version?

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by fscavo** [comment]
I'm having the same issue. After reconnecting the hub is no longer able to send message to javascript client with
await this.hubContext.Clients.Client(this.connectionId).SendAsync(m.EventName, data);

**Comment by SimonOrdo6** [comment]
@vicancy  Same issue, I think.  

I have an Azure Function upstream hub server with a Serverless Azure SIgnalR instance fronted by a JS client.  

`connection.send(method, ...args); ` works fine after initial connection is made (i.e. the command is received by Hub Server).  Then, I manually kill the network connection which induces a disconnect.  Once network is re-established the client reconnects automatically.  AFter that, `connection.send(method, ...args); ` fail to arrive at the upstream server.

**Comment by vicancy** [comment]
> I'm having the same issue. After reconnecting, the hub is no longer able to send message to javascript client with await this.hubContext.Clients.Client(this.connectionId).SendAsync(m.EventName, data);

How you reconnect? The client connectionID changes if you are not using [stateful reconnect](https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-9.0&tabs=dotnet#configure-stateful-reconnect)
