### ISSUE TITLE
Server frequently loses Azure SignalR connection [Azure SignalR Service is not connected yet Error]

### ISSUE THREAD

**Issue by tehmas** [Azure/azure-signalr#404]
My ASP.NET Web API (target framework: .NET Framework 4.6.2) project frequently loses connection with Azure SignalR service (**free tier**). I have followed the example as shown in **aspnet** ‘chatroom’ [example][1].

My client application is based on Angular JS. Messages are being sent to the clients but after a few hours, the server connection with Azure SignalR service is lost and is not established again.

As far as I understand from the MS Azure SignalR Internals [documentation][2]:

> If a server connection is disconnected for network issue,
> 
>  - the server connection starts reconnecting **automatically**.

The following error is returned back in response:

> Azure SignalR Service is not connected yet, please try again later

![50b742fb-fbbd-491c-b8ae-2957e3e2f9c5 png](https://user-images.githubusercontent.com/9120583/53298590-07274a80-3852-11e9-89e8-ef307fea7968.jpg)

However, this does not seem to be happening i.e. server connection with Azure SignalR service is not established again. 

![5e878734-6613-49cc-9b2a-f5ff63bd6686 png](https://user-images.githubusercontent.com/9120583/53298611-3d64ca00-3852-11e9-9357-b7ef83a35f28.jpg)

`nuget` packages:

 - Microsoft.AspNet.SignalR v2.4.0
 - Microsoft.AspNet.SignalR.Core v2.4.0
 - Microsoft.AspNet.SignalR.SystemWeb v2.4.0
 - Microsoft.Azure.SignalR.AspNet v1.0.0-preview1-10317
 - Microsoft.Azure.SignalR.Protocols v1.0.6

  [1]: https://github.com/aspnet/AzureSignalR-samples/blob/master/aspnet-samples/ChatRoom/Startup.cs
  [2]: https://docs.microsoft.com/bs-latn-ba/azure/azure-signalr/signalr-internals

**Comment by tehmas** [comment]
Just to add, Azure SignalR service is in North Europe.

**Comment by vicancy** [comment]
We've identified an issue for ASP.NET that SDK does not reconnect after disconnect. There is a nightly build that contains a fix to this problem:
`install-package Microsoft.Azure.SignalR.AspNet -Version 1.0.0-preview1-10325 -Prerelease -Source https://www.myget.org/F/azure-signalr-dev/api/v3/index.json`

The fix is planned to be released this week.

**Comment by tehmas** [comment]
Thanks, @vicancy. I'm also interested in why the service is frequently disconnecting from the server in the first place. Is there a document available regarding this?

**Comment by vicancy** [comment]
"Frequent disconnecting" is not expected. There should be either something wrong inside the service, or exceptions from the app server side. Can you see any abnormal logs/CPU usage from app server side?

**Comment by vicancy** [comment]
The latest v1.0.0-preview1-10330 version of ASP.NET should fix the issue.

**Comment by tehmas** [comment]
Thanks, @vicancy for the fix. I would like to report that the connections were successfully being established for a longer period of time. However, after this, the following error is frequently occurring on the client side:

![image](https://user-images.githubusercontent.com/9120583/53474364-b51f3880-3a8e-11e9-80fb-87bd8a4af37a.png)

Logged error stack:
![image_2019_02_27t06_47_21_470z](https://user-images.githubusercontent.com/9120583/53471233-c283f500-3a85-11e9-8004-6aa3d8a2fcdb.png)

![image](https://user-images.githubusercontent.com/9120583/53474316-91f48900-3a8e-11e9-8e53-7475bf649b65.png)

### Error Gone After An Hour:
After an hour of this error frequently occuring, the error itself is gone (without doing any changes or redeployment), the client is able to connect but is not receving any messages. Please note that I am using groups as well. There doesn't seem to be any kind of abnormal logs on web server.

### Restarting API:
Not being able to receive any messages, I restarted the API. Messages are now being received.

### Lazy Initialization:
Also using lazy initalization for connecting with hub from a controller:

```
Lazy<IHubContext> hub = new Lazy<IHubContext>(
    () => GlobalHost.ConnectionManager.GetHubContext<THub>()
);
protected IHubContext Hub
{
    get { return hub.Value; }
}
```

### 6 hours overview of Azure SignalR service:
![image](https://user-images.githubusercontent.com/9120583/53473983-b9972180-3a8d-11e9-82ea-297f419fdcd9.png)

### nuget packages:
- Microsoft.AspNet.SignalR 2.4.0
- Microsoft.AspNet.SignalR.Core 2.4.0
- Microsoft.AspNet.SignalR.SystemWeb 2.4.0
- Microsoft.Azure.SignalR.AspNet 1.0.0-preview1-10330
- Microsoft.Azure.SignalR.Protocols 1.0.7

**Comment by tehmas** [comment]
**Update**

This again occurred after a deployment today:
![image](https://user-images.githubusercontent.com/9120583/53497079-31cd0980-3ac5-11e9-8663-15dc38a7eafb.png)

**Comment by vicancy** [comment]
Hi @tehmas From the connection metrics, there was no server connection from 11AM to 12AM, is it expected? Are there any error logs from service side about connection failures?

"Azure SignalR Service is not connected yet" error happens when there is no app server connected to the Azure Service. As the metrics shows, the error should happen between 11AM and 12AM.

The client side error should be related to https://github.com/SignalR/SignalR/pull/4320/files
