### ISSUE TITLE
Azure SignalR Service is ignoring custom AuthorizeAttribute

### ISSUE THREAD

**Issue by anilrp** [Azure/azure-signalr#419]
I am using **`.Net Framework 4.7.1`** " and **NOT .Net Core**

```
public class AuthorizeClaimsAttribute : Microsoft.AspNet.SignalR.AuthorizeAttribute
{
        public override bool AuthorizeHubConnection(Microsoft.AspNet.SignalR.Hubs.HubDescriptor hubDescriptor, IRequest request)
        {
              ///some authorization code on bearer token provided by user
        }
}
```

Following is written in owin startup.cs file - 

```
            var hubConfiguration = new HubConfiguration();
            hubConfiguration.EnableDetailedErrors = true;
            hubConfiguration.EnableJavaScriptProxies = false;

            app.MapAzureSignalR(GetType().FullName, hubConfiguration);
```

`MapAzureSignalR` method is coming from `Microsoft.Azure.SignalR.AspNet`

And hub is having authorize attribute - 
```
    [AuthorizeClaimsAttribute]
    public class NotificationHub : Hub
    {
    }
````

.net Client code is here which trying connect to signalr hub - 

```
          _connection = new Microsoft.AspNet.SignalR.Client.HubConnection(url);
          _connection.Headers.Add("Authorization", string.Format("Bearer {0}", bearerToken));
```

Azure SignalR Service is ignoring `AuthorizeClaimsAttribute` on Hub and connecting client without authorizing it

**Comment by vicancy** [comment]
Reproed, should be a bug in https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs#L135 that when `Authorize` fails, it throws and thus fails to close the client connection.
![image](https://user-images.githubusercontent.com/668244/53630760-c5c8dd80-3c4b-11e9-934a-91be8aa7b362.png)

@JialinXin Would you mind taking a look?

**Comment by JialinXin** [comment]
Sure. Will take this.
