### ISSUE TITLE
Possible to get an ETA on stable version of Microsoft.Azure.SignalR.AspNet?

### ISSUE THREAD

**Issue by Rtalos** [Azure/azure-signalr#425]
Hello

I don't know if this is the right channel to ask; but I was wondering if there is a possibility to get an ETA on when there might be a stable version of Microsoft.Azure.SignalR.AspNet?

**Comment by vicancy** [comment]
We are actively working on improving the stability of the AspNet support. We plan to make AspNet SignalR support generally available on April.

**Comment by vicancy** [comment]
1.0.0 is released.
