### ISSUE TITLE
Username and role claims name is changed

### ISSUE THREAD

**Issue by marcin-dardzinski** [Azure/azure-signalr#429]
I'm having trouble making authenticated requests to Azure SignalR. I have my role and name claim names set as in https://github.com/Azure/azure-signalr/issues/223. 
```
services.AddAuthentication()
                .AddJwtBearer(cfg =>
                {
                    cfg.TokenValidationParameters.RoleClaimType =  "role";
                    cfg.TokenValidationParameters.NameClaimType = "sub";
                });
```

The access token issued for my client app looks like this:
```
{
  "asrs.s.uid": "685e9974-4c4a-4ac9-bb27-a42c05597e61",
  "asrs.s.aut": "AuthenticationTypes.Federation",
  "asrs.s.nt": "sub",
  "asrs.s.rt": "role",
  "nbf": 1552374807,
  "exp": 1552378407,
  "iss": "http://api.local.lncd.pl/auth",
  "aud": [
    "http://api.local.lncd.pl/auth/resources",
    "https://signalr-for-local-dev.service.signalr.net/client/?hub=chathub"
  ],
  "client_id": "optitruck/web",
  "sub": "685e9974-4c4a-4ac9-bb27-a42c05597e61",
  "auth_time": 1552319791,
  "idp": "local",
  "role": "business_owner",
  "company_id": "82ff842c-f297-4e62-91c1-717a01a05b94",
  "scope": [
    "openid",
    "offline_access"
  ],
  "amr": "pwd",
  "asrs.s.id": "bnX87lwAAAA=",
  "iat": 1552374807
}
```

The token contains `sub` and `role` claims. However, in the hub, my claims principal looks like this.

![debug](https://user-images.githubusercontent.com/25584335/54194683-1ac2ea00-44bd-11e9-8bc9-df22b0db5b19.png)

It looks like my custom claim names have been substituted with default ones. As a result I cannot have role base authentication in my hubs. Note that it all works fine, when I use regular SignalR and don't connect to Azure SignalR Service. Is this a bug or some kind of misconfiguration on my part?

**Comment by vicancy** [comment]
Probably related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/550, JWT has a default [ClaimTypeMapping](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/ClaimTypeMapping.cs#L50) to transform incoming claims to long standard claims, so when your request comes into Azure SignalR Service, we use this standard library and the claims are automatically transform. 

We will fix the issue by disabling the transforming and deploy it to Azure in the upcoming week.

In the mean while, you can workaround the issue, by providing a custom claim type not in the mapping, for example:

```cs
services.AddAuthentication()
                .AddJwtBearer(cfg =>
                {
                    cfg.TokenValidationParameters.RoleClaimType =  "rolect";
                    cfg.TokenValidationParameters.NameClaimType = "subct";
                });
```

**Comment by vicancy** [comment]
We are not able to roll out the fix as this breaks currently working scenario. Meanwhile, in our SDK, we enabled outbound ClaimTypeMapping, which means long claim types will be automatically transformed to short claim types when communicating with Azure Service, so we rely on this auto-transforming to make users using old SDK work.

**Comment by vicancy** [comment]
We plan to fix this issue by adding back the original claims if it has been converted, and in the meanwhile keep backward compatibility. 

So if your incoming claims are: 

```json
{
  "sub": "685e9974-4c4a-4ac9-bb27-a42c05597e61",
  "role": "business_owner"
}
```

The claims you receive from hub will be:

```json
{
  "sub": "685e9974-4c4a-4ac9-bb27-a42c05597e61",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "685e9974-4c4a-4ac9-bb27-a42c05597e61",
  "role": "business_owner",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "business_owner"
}
```
@marcin-dardzinski Do you have any concerns with this fix?

**Comment by marcin-dardzinski** [comment]
No, thank you very mucb

**Comment by vicancy** [comment]
Already fixed
