### ISSUE TITLE
Question: Do you have to use ARR Affinity for wss to work reliable?

### ISSUE THREAD

**Issue by Hypnobrew** [Azure/azure-signalr#430]
We are experience 404 occasionally when the client is trying to connect to the SignalR Service via websockets. Negotiating works fine and downgrading to long polling seems fine.

We are not using ARR Affinity because we have a completely stateless application. 

Do we have to use ARR Affinity for stickyness somehow for websockets to work reliable?

**Comment by vicancy** [comment]
Could you check https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#random-404-returned-for-client-requests to see if it covers your scenario? If not, could you email me one HAR file when 404 took place?

**Comment by Hypnobrew** [comment]
Yes, most likely we experience this issue: https://github.com/Azure/azure-signalr/issues/346

We do send an `access_token` to authenticate a user against our backend.
Would it solve the problem if we use another key instead of `access_token`?
Is it possible to set at specific name for this token using `accessTokenFactory` in javascript?

**Comment by Hypnobrew** [comment]
Hmm, does not look like I can change the key when using a `accessTokenFactory`: https://github.com/aspnet/AspNetCore/blob/095c1c1759daef34e18a94c86236e4f02644ebe9/src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts#L44

Guess I just have to wait for the fix in the issue https://github.com/Azure/azure-signalr/issues/346 ?

**Comment by vicancy** [comment]
You can also workaround it by not using `access_token` for your app auth.

**Comment by Hypnobrew** [comment]
That is not an option at the moment. We will await the enhancement in #346 .
Thank you!
