### ISSUE TITLE
Add method Groups.RemoveFromAllGroupsAsync(string connectionId)

### ISSUE THREAD

**Issue by ntrpnr** [Azure/azure-signalr#444]
Would it be possible to implement a method which takes the connection id as parameter, and removes the client from all groups?

The alternative is to keep track of assigned groups in the hub, but if you have multiple connections to your Azure SignalR back plane, this becomes much harder.

If we can just remove all groups from a connection globally in Azure SignalR it would be great.

**Comment by realwanpengli** [comment]
Hi @ntrpnr we published an [Azure SignalR Service Management](https://www.nuget.org/packages/Microsoft.Azure.SignalR.Management). You can use it to remove a user from all groups. You can also call [REST API](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#remove-user-from-all-groups) to remove it. 
You can mark the client connection with a user name, then you can use this feature.
