### ISSUE TITLE
Calling Signalr Rest Api endpoint form postman

### ISSUE THREAD

**Issue by ernestotw85** [Azure/azure-signalr#466]
I am calling https://[myaccount].service.signalr.net/api/v1/hubs/[myhub] endpoint from postman, the request and response seems to be fine because it's getting 202 Accepted http status code. The problem is that any client connectred to the hub in Azure SignalR Service do not  receive the message.

this is the data about my request

url POST https://[myaccount].service.signalr.net/api/v1/hubs/[myhub] 

headers 

Authorization Bearer [token]
Content-Type :  application/json
body

{
    "Target": "broadcastMessage",
    "Arguments": [
        "server",
        "hello from server"
    ]
}

Response
Status Code : 202 accepted

Date →Thu, 28 Mar 2019 14:00:53 GMT
Content-Length →0
Connection →keep-alive
Strict-Transport-Security →max-age=15724800; includeSubDomains

**Comment by realwanpengli** [comment]
Is the client method named "broadcastMessage", and receives 2 strings?

**Comment by realwanpengli** [comment]
By the way, [Management SDK](https://github.com/Azure/azure-signalr/tree/dev/src/Microsoft.Azure.SignalR.Management) just released for Azure SignalR Service. It can be used in serverless environment. You can use this SDK to manage your SignalR clients connected to your Azure SignalR Service directly such as broadcast messages. samples can be found [here](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management).

**Comment by ernestotw85** [comment]
@realwanpengli I am going to check all your suggestions. below my client side code

<script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
    </script>

**Comment by realwanpengli** [comment]
@ernestotw85  Since you get 202, your messages should be sent successfully. You can use this [chatroom](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoom) sample to verify that messages sent successfully so that clients can receive messages. 

You should double check your client side code.

p.s. Hub name is "chat" in chatroom sample.

**Comment by ernestotw85** [comment]
I am using Chatroom sample. I opened two clients and the communication between these clients works fine . I can see the messages in both sides. then I created a POST request to send a message to both client using REST API endpoint from Azure SignalR service using Postman. If I go to one of the clients and inspect the objects this is the results

![Capture](https://user-images.githubusercontent.com/37849715/55183210-bfa02100-5165-11e9-9709-6b42bdfc00b5.PNG)

But I can't see the message that I am sending from Postman trough the SignalR REST API.

**Comment by realwanpengli** [comment]
[Azure SignalR REST API](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#rest-api-in-azure-signalr-service) only support ASP.NET **CORE** SignalR applications.

You are using the asp.net chat room sample. 

You can use this [asp.net core chat room sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoom) instead.

**Comment by ernestotw85** [comment]
Thank you @realwanpengli
