### ISSUE TITLE
IServiceManager.CreateHubContextAsync throws ArgumentNullException when loggerFactory is null

### ISSUE THREAD

**Issue by Jun2014** [Azure/azure-signalr#474]
We are using Microsoft.Azure.SignalR.Management.1.0.0-preview1-10351.

We have below code:

            IServiceManager _serviceManager = new ServiceManagerBuilder()
                .WithOptions(option =>
                {
                    option.ConnectionString = connectionString;
                    option.ServiceTransportType = ServiceTransportType.Persistent;
                })
                .Build();
            IServiceHubContext _hubContext = _serviceManager.CreateHubContextAsync(hubName, null).ConfigureAwait(false).GetAwaiter().GetResult();

Basically we pass in null logFactory when CreateHubContextAsync(). It throws exception: Value cannot be null. Parameter name: implementationInstance.

In IServiceManager definition, we expect loggerFactory could be null.
    public interface IServiceManager
    {
        Task<IServiceHubContext> CreateHubContextAsync(string hubName, ILoggerFactory loggerFactory = null, CancellationToken cancellationToken = default(CancellationToken));
    }

In code https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, line 51, we expect loggerFactory is not null.

**Comment by realwanpengli** [comment]
It is a bug, will be fixed in next release. You can use [Microsoft.Extensions.Logging.LoggerFactory](https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging/LoggerFactory.cs) to workaround for now.
