### ISSUE TITLE
Randomly see HttpClientException 404 Not Found

### ISSUE THREAD

**Issue by Jun2014** [Azure/azure-signalr#477]
We randomly see our C# client connects to app server, and see below exception randomly.

```
Microsoft.AspNet.SignalR.Client.HttpClientException: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  Date: Fri, 05 Apr 2019 04:02:45 GMT
  Content-Type: text/plain
}'



            _hubConnection.Start().GetAwaiter().GetResult();
        }
```

**Comment by vicancy** [comment]
Could you send me your instance name and the time when 404 happened for me to have a check? There are several cases when 404 can happen, please see https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#random-404-returned-for-client-requests

**Comment by Jun2014** [comment]
Can't repro now, closing this issue.
