### ISSUE TITLE
Signalr service outage and App server not auto-reconnect

### ISSUE THREAD

**Issue by Jun2014** [Azure/azure-signalr#485]
We have .net core signalr app (hooked with signalr service) running in app service environment. It's running pretty well for almost 2 days, and we see an issue yesterday night, and want to seek your help to further investigate.

From app server, the first weird event shown in app insight starting at 4/12/2019, 5:53:55 AM PST.
![image](https://user-images.githubusercontent.com/8303320/56055295-036e5b00-5d0e-11e9-955e-de3101f55aa6.png)
and we see spike of http error in app server:
![image](https://user-images.githubusercontent.com/8303320/56055404-3e708e80-5d0e-11e9-9328-9f2bde24104a.png)
However, I don't see any other error from signalr on app server.

Below is connections on signlar service side:
![image](https://user-images.githubusercontent.com/8303320/56055527-87284780-5d0e-11e9-87fe-a0501fbf8b1b.png)

Here I have a few questions:
1. How can we further investigate this without involve your team in future?
2. The outage lasted for half an hour, and recovered itself. The recovering seems take too long.

The environment we're on:
app server: Microsoft.Azure.SignalR 1.0.8. Running on 1 instance of S1 app service plan.
signalr service: 1 Unit Standard.

Please let us know if you need more info to investigate this issue. thanks.

**Comment by vicancy** [comment]
Hi Jun2014, for such incidents, you can open a ticket in Azure portal to get Azure support team involved to take a look at the incident. Or you can email me your instance name and the exact time range of the issue for me to take a look if there were any events during that time.

**Comment by vicancy** [comment]
There was an incident during that time and it was then recovered.
