### ISSUE TITLE
[Error]Connection "..." to the service was dropped

### ISSUE THREAD

**Issue by johnjbateman** [Azure/azure-signalr#497]
This is related to [this](https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#️todoclient-side-connection-drop) link:

We have been seeing this error:

`Connection "[guid]" to the service was dropped.`

All Exceptions in the stack [here](https://gist.github.com/johnjbateman/bd3cb662c95d6fad6144d76006c2c243)

I have checked the app logs and it was during random times, but most occurred without activity (overnight) and no app restarts at that time.

Platform:

Azure Kubernetes Service (AKS) cluster
Ubuntu 16.04.5 LTS pods connecting to Azure SignalR Service
ASP.NET Core 2.2

(Will email timestamps and resource names)

**Comment by johnjbateman** [comment]
Timestamps and resource names: [link](https://gist.github.com/johnjbateman/fd51738c5f584c5a5d76db19a0f7b3d9)

**Comment by johnjbateman** [comment]
@vicancy Also experiencing this issue similar to #420.  I emailed you just now information.

**Comment by cmxl** [comment]
has this ever been resolved?
we experience the same issue with asp.net core 3.1

**Comment by vicancy** [comment]
Quote from https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#server_connection_drop

> As the connections between the app server and SignalR Service are persistent connections, they may experience network connectivity issues. In the Server SDK, we have Always Reconnect strategy to server connections. As the best practice, we also encourage users to add continuous reconnect logic to the clients with a random delay time to avoid massive simultaneous requests to the server.
On a regular basis there are new version releases for the Azure SignalR Service, and sometimes the Azure wide OS patching or upgrades or occasionally interruption from our dependent services. These may bring in a very short period of service disruption, but as long as client-side has the disconnect/reconnect mechanism, the impact is minimal like any client-side caused disconnect-reconnect.
