### ISSUE TITLE
Asp.net (4.6.1) client doesn't receive messages when they are not sent from the server serving the web site

### ISSUE THREAD

**Issue by stebbo** [Azure/azure-signalr#498]
Messages sent directly to Azure SignalR Service (e.g from Functions / Console Apps) are not delivered to connected Asp.net clients

**Steps to reproduce**

- Open the ChatRoom Asp.net sample (not Asp.net Core)
- Configure your Azure SignalR connection string and run the sample.
- Open the Serverless sample and configure the Server to connect to the same Azure SignalR Hub as the ChatRoom
- Run the server and send a broadcast message to the hub.

**Expected behavior**
The broadcast message sent from the Serverless Server should be presented in the chat window

**Actual behavior**
Crickets

I can see from the logs that a connection with Azure SignalR Service is successfully established, I get the ping messages and the OnConnected method gets called on my Hub object. So everything *seems* fine.

I have tested this scenario with the Asp.net Core samples and that works just fine, i.e. messages arrive as expected.

Any ideas?

Thanks in advance!

**Comment by vicancy** [comment]
Please not that serverless/or REST API does **NOT** support ASP.NET SignalR as Serverless only support the ASP.NET Core SignalR data protocols.

If you'd like the serverless functionality, please use the new ASP.NET Core SignalR clients.

**Comment by stebbo** [comment]
Ok, sad to hear that. It wasn't obvious in the docs.
And to be crystal clear, the only serverless component in my scenario is the Console App that sends the message. The *intended* reciever of that message is **NOT** serverless. I thought this would be supported, either by having Azure SignalR sending the message directly to the browser through the web sockets connection that was just established, or by relaying via the application server (i.e. the server serving the HTML)

If not, what does Azure SignalR do here? Is it merely keeping track of connected clients on behalf of the application server?

Any plans on supporting serverless on ASP.NET?

**Comment by vicancy** [comment]
It is claimed in the REST API document, https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#rest-api-in-azure-signalr-service.

For now, we don't have plan to support REST API/serverless for ASP.NET
