### ISSUE TITLE
Build error when adding with Nunit test project

### ISSUE THREAD

**Issue by laurence-accurx** [Azure/azure-signalr#500]
I'm getting this error when I add an NUnit test project and point it to my asp net core (2.2) application using Azure SignalR:

_Assembly 'WebApplication4' with identity 'WebApplication4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.AspNetCore.SignalR.Core, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.SignalR.Core' with identity 'Microsoft.AspNetCore.SignalR.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'_

I've proven this out with a super simple project too. Steps to repro:
1. Add AspNetCore MVC application to solution
2. Reference AzureSignalR 1.0.8
3. Add blank "MessageHub" which inherits from Hub
4. Add "services.AddSignalR().AddAzureSignalR();" in Configure Services
5. Map message hub in Configure
6. Add Nunit test project
7. Reference the MVC application
8. Add test which references MessageHub
9. Observe build error above

I can fix this at the moment by adding a hard reference from my test project to AspNet.SignalR.Core and an assembly binding re-direct in code in my test project but it's not ideal. Is this being caused by Azure SignalR using AspNetCore.SignalR 1.0.0 instead of 1.1.0? Thanks in advance

**Comment by vicancy** [comment]
Thanks for reporting this. Yes, this is because we are using `1.0.0` version SignalR, and we need to keep it as `1.0.0` so that the Service SDK can work for all versions of SignalR. Please use assembly rebinding to solve the issue.

**Comment by laurence-accurx** [comment]
Thanks - have added this as a fix locally. Why does this work okay with just the web application project but when you add an Nunit test project the build error occurs?

**Comment by paulpce** [comment]
We have this issue as well but with an xUnit test project and I'm not seeing a way forward.  Can you please explain how assembly rebinding would work in this instance? Have tried a [couple](https://stackoverflow.com/a/46120907) of [things](https://stackoverflow.com/a/44382926) and they didn't work, it appears that .Net Fx assembly rebinding is not supported in .net standard and core any more. How do we move forward with this?

**Comment by laurence-accurx** [comment]
What has fixed it so far for me is explicitly referencing "Microsoft.AspNetCore.SignalR.Core" package version 1.1.0 in my test assembly and then in my Nunit one time set up which runs before any code I've got this 

```public static void FixSignalRBinding()
        {
            var bindingRedirect = new BindingRedirect("Microsoft.AspNetCore.SignalR", "adb9793829ddae60", "1.0.0.0");

            ResolveEventHandler handler = null;

            handler = (sender, args) =>
            {
                var requestedAssembly = new AssemblyName(args.Name);

                if (requestedAssembly.Name != bindingRedirect.ShortName)
                {
                    return null;
                }

                var targetPublicKeyToken = new AssemblyName("x, PublicKeyToken=" + bindingRedirect.PublicKeyToken).GetPublicKeyToken();
                requestedAssembly.Version = new Version(bindingRedirect.RedirectToVersion);
                requestedAssembly.SetPublicKeyToken(targetPublicKeyToken);
                requestedAssembly.CultureInfo = CultureInfo.InvariantCulture;

                AppDomain.CurrentDomain.AssemblyResolve -= handler;

                return Assembly.Load(requestedAssembly);
            };

            AppDomain.CurrentDomain.AssemblyResolve += handler;
        }
```
