### ISSUE TITLE
After Upgraded to Azure Signalr from Asp.Net Signalr still not working 

### ISSUE THREAD

**Issue by AbhisheNandika** [Azure/azure-signalr#514]
I had followed the steps as mentioned in the below url
https://devblogs.microsoft.com/aspnet/announcing-asp-net-signalr-2-4-0-preview-1/

First message when I call the send method from client side it's working but second message on wards  it's not working.

Kindly help me to fixed this issue

**Comment by vicancy** [comment]
Is it reproduce-able? Is it possible for you to provide a simple project that can reproduce the issue? Any detailed error messages shown when the message failed to be sent?

**Comment by AbhisheNandika** [comment]
By mistake I closed this issue. I will get back to you on Thursday.

**Comment by AbhisheNandika** [comment]
Hi Vicancy,
Thanks for your reply,

I am trying to upgrade from Asp.net Signalr to Azure Signalr in Asp.net MVC5 project. 

By three simple steps we upgraded to Azure Signalr  using below link
https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md

we saw using the browser networking, It was connected with the new service. 

It's calling to onconnected in Hub class later we didn't saw send function call. there are ajax calls to save the messages and in success we call hub to   

Note : We made as default from ServerLess in AzureSignalr settings.

Please let me know if you need any information.

Correct me if I am wrong.

**Comment by vicancy** [comment]
Is it possible for you to provide a simple project that can reproduce the issue?
