### ISSUE TITLE
Add Streaming Support to Azure SignalR

### ISSUE THREAD

**Issue by TobySanders** [Azure/azure-signalr#516]
Currently the signalR streaming feature is available in AspNetCore signalR but not in signalR service. according to [this article](https://devblogs.microsoft.com/aspnet/azure-signalr-service-now-supports-asp-net/) it is unavailable for compatibility reasons however it's an incredibly useful feature and would add a lot of value to the signalR service; are there plans to implement this in the future?

**Comment by davidfowl** [comment]
ASP.NET SignalR isn't getting any new features (aka streaming), the support in the server is mostly compatibility with existing applications. All future investment is in ASP.NET Core SignalR.

**Comment by TobySanders** [comment]
Thank you for the reply, David, that's definitely understandable; in which case (although this may be a separate issue) are there any plans to make ASP.NET Core SignalR usable on Azure SignalR Service or will it always remain as ASP.NET

**Comment by davidfowl** [comment]
Azure SignalR supports both.

**Comment by TobySanders** [comment]
Yeah looking back through the documentation I definitely missed that, apologies.
At the risk of going on a tangent could I explain my scenario and potentially be pointed in the right direction?

I have an ASP.NET Core 2.2 web application which has initialises SignalR in the startup as
```
 services.AddSignalR()
       .AddAzureSignalR();
```

` app.UseAzureSignalR(routes => routes.MapHub<StreamHub>("/streamhub"));`

nuget packages are:

- Microsoft.Azure.SignalR (1.1.0-preview1-10404)
- Microsoft.AspNetCore.SignalR(1.1.0) (I have tried with and without this package and got the same results)

I then have my Hub logic in a .NET standard 2.0 Class Library

nuget packages are:
- Microsoft.AspNetCore.SignalR(1.1.0)


I'm trying to use the client to server streaming capabilities of SignalR so the hub code is 

```
    public class StreamHub : Hub
    {
        public async Task UploadStream(ChannelReader<string> stream)
        {
            while (await stream.WaitToReadAsync())
            {
                while (stream.TryRead(out var item))
                {
                    // do something with the stream item
                    await Clients.Others.SendAsync("Input", item);
                }
            }
        }
   }
```
I managed to get this working with Self hosted SignalR and that was working great, but as soon as I moved to Azure signalR I started getting this exception whenever I try and start the stream


```
System.IO.InvalidDataException: Invocation provides 0 argument(s) but target expects 1.
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JArray args, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher:Error: Received unsupported message of type 'Microsoft.AspNetCore.SignalR.Protocol.StreamItemMessage'.
Microsoft.AspNetCore.SignalR.HubConnectionHandler:Error: Error when processing requests.

System.NotSupportedException: Received unsupported message: StreamItem { InvocationId: "0", Item: X: 232Y: 122 }
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DispatchMessageAsync(HubConnectionContext connection, HubMessage hubMessage)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

The client code for this example is the JS client taken from the samples repository 3.0 folder

**Comment by BrennanConroy** [comment]
Client to Server streaming is a new feature in 3.0. So the only way you will be able to use it is if you use the 3.0.0-preview builds of AspNetCore.

**Comment by BrennanConroy** [comment]
>like the rest of SignalR

Not sure what you mean here. The only parts of SignalR that target .net standard are things used by the client.

I'm curious as to why you are putting your Hub in a library?

**Comment by TobySanders** [comment]
I guess it's a symptom of habit, the hub was moved to a library to separate out business logic which, at the time, we considered SignalR to be. Based on the responses here I'm getting the impression that SignalR should instead be used on the same level as a controller

Closing this due to my misunderstanding, Thank you for the help
