### ISSUE TITLE
this.hubConnection.on("UpdatedMissions"..  is firing many times

### ISSUE THREAD

**Issue by jrmcdona** [Azure/azure-signalr#526]
Hello, I am using Azure SignalR REST API to send message to the client.  My client is an Angular app.    We have a Azure SignalR service.   From our backedn service we issues Rest API call to the user.
Like so:

```
 public async Task SendUpdatedMissions(string userId)
        {
            _defaultPayloadMessage = new PayloadMessage
            {
                Target = "UpdatedMissions",
                Arguments = new[] {
                    userId
                }
            };

            string url = GetSendToUserUrl(userId);

            if (!string.IsNullOrEmpty(url))
            {
                var request = BuildRequest(url);

                var response = await Client.SendAsync(request);
                if (response.StatusCode != HttpStatusCode.Accepted)
                {
                    Console.WriteLine($"Sent error: {response.StatusCode}");
                }
            }
        }
```

I have three different methods I am listening for and two are working well, however,  when I fire UpdatedMissions from the REST API.  The client receives the message many times.
```
 this.hubConnection.on("UpdatedMissions", () => {
          // this.missionsService.refreshMissionsFromService();
          console.log('received UpdatedMissions');
        });
```

Here is the rest of the code where I start SignalR connection on client:
```
public startSignalRConnection() {
    this.getSignalRConnection().subscribe(con => {
      console.log('SignalR con: ' + con);
      const options = {
        accessTokenFactory: () => con.accessToken
      };
      this.hubConnection = new SignalR.HubConnectionBuilder()
        .withUrl(con.url, options)
        .configureLogging(SignalR.LogLevel.Information)
        .build();

        this.hubConnection
        .start()
        .then(() => {
          this.addSignalRListener();
        console.log('Connection started');
        })
        .catch(err => console.log('Error while starting connection: ' + err));
    //  this.hubConnection.start().catch(error => console.error(error));
    });
  }

  public addSignalRListener = () => {
    this.hubConnection.on("UpdatedProfile", () => {
      this.profileService.refreshStatsFromService();
    });

    this.hubConnection.on("UpdatedMissions", () => {
      // this.missionsService.refreshMissionsFromService();
      console.log('received UpdatedMissions');
    });

    this.hubConnection.on("BroadcastLeaderboardUpdate", () => {
      this.leaderboardService.refreshLiveLeaderboardFromSignalR();
    });
  }
```
When I put a breakpoint in there it just keeps firing one after another and I am unable to figure out why.  

You can see here it logged 16 times.  The REST API is definitely not getting called 16 times.

![image](https://user-images.githubusercontent.com/4327773/57493604-4e3aae80-728b-11e9-83e4-247a8139f6bb.png)

**Comment by realwanpengli** [comment]
Is the same send-to-user rest api used for `UpdatedProfile` and `UpdatedMissions`. If so, they are equivalent. If `UpdatedProfile` works well, `UpdatedMissions` should works well too.

Could you tell me how many times the listener `UpdatedMissions` is registered for one hub connection?
Assume that you call rest api for 1 time, if you always get 16 times for each message, you might register 16 times for `UpdatedMissions` for each hub connection.

**Comment by realwanpengli** [comment]
You can try our new [Management SDK](https://www.nuget.org/packages/Microsoft.Azure.SignalR.Management) to send messages in your backend service. 
You don't have to build the request. The interface is almost the same with `IHubContext` and more efficient to use `Persistent` mode which establish a websocket connection to communicate with SignalR service. 
[Introduction to this SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#create-and-use-servicehubcontext).

**Comment by jrmcdona** [comment]
@realwanpengli  Let me take a look.  This morning it seems to be working as expected which is weird, because all day yesterday it was not.   I will monitor it and also take a look at the Management SDK.

**Comment by realwanpengli** [comment]
Great to hear that it worked. Close the issue due to no more comments for more than 1 week.
