### ISSUE TITLE
Can't connect in Xamarin.Forms Android

### ISSUE THREAD

**Issue by andrekiba** [Azure/azure-signalr#529]
I'm trying to connect to Azure SignalR Service from a Xamarin.Forms app that targets only Android for now. I use an Azure Function with SignalR binding (negotiate) to retrieve the correct url and token. The fuction returns the correct data with a status 200.
But then during `hubconnection.StartAsync()` i always receive this error:
**"Unable to connect to the server with any of the available transports"**
I use Microsoft.AspNetCore.SignalR.Client version 1.1.0 (preview 3 doesn't work for other reasons... :-( )
The connection is built in this way:
`hubConnection = new HubConnectionBuilder().WithUrl("myurl").Build();`
where "myurl" is the address to reach the negotiate function

**Comment by realwanpengli** [comment]
> where "myurl" is the address to reach the negotiate function

"myurl" should be the Url in the body of negotiate response rather than the address of the negotiate function

**Comment by realwanpengli** [comment]
"myurl" should be the hub url.
For example, if your negotiate function's address is https://abc.def/hub/negotiate , "myurl" should be https://abc.def/hub

**Comment by andrekiba** [comment]
not the hub url (the hub url is already known using the azure signalr binding and it is specified in a function app settings (local.settings.json if you test in local)). As you said this must be the url where you can find the negotiate function...and it is
https://docs.microsoft.com/it-it/azure/azure-functions/functions-bindings-signalr-service

**Comment by realwanpengli** [comment]
What I mean is https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config#configuring-a-client-connection . But it is great if you are sure you know the way to connect signalr service. 

Could you tell me :
* the speed of connecting - how many signalr clients is trying to establish connections to signalr service? 
* total connections and the duration when the error occured?

Could email me your azure subscription and signalr service instance name? I would check the log first.

**Comment by andrekiba** [comment]
I investigated the problem more in depth and it seems related to the **System.IO.Pipelines** package.
If I reference only the **Microsoft.AspNetCore.SignalR.Client** package then I have this error:

> Could not load type of field 'Microsoft.AspNetCore.Http.Connections.Client.HttpConnection:_transport' (11) due to: Could not load file or assembly 'System.IO.Pipelines, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

If I try to install directly the last version of **System.IO.Pipelines** nuget package then I have the previous error:

> Unable to connect to the server with any of the available transports

As already said this happens only for Android, iOS works great.
I'll send you an email with the requested info, thank you!

**Comment by andrekiba** [comment]
the other strange thing is that **System.IO.Pipelines** seems to start from version 4.5.0 in nuget...

**Comment by realwanpengli** [comment]
Hi @andrekiba  I didn't receive your email, and if I only referenced `Microsoft.AspNetCore.SignalR.Client` for version `1.1.0`, but I couldn't reproduce the error. All things works well in my Xamarin.Forms Android app. Could you provide app server log and more information like your azure signalr service name?

**Comment by realwanpengli** [comment]
Did you installed the `System.IO.Pipelines` package [here](https://www.nuget.org/packages/System.IO.Pipelines/)? The latest is `4.5.3` since 4 months ago.

**Comment by andrekiba** [comment]
Mail sent few minutes ago, sorry for the delay.
Yes I tried to install System.IO.Pipelines 4.5.3 but it doesn't work.

**Comment by realwanpengli** [comment]
Got it. Thanks. I cannot see any connection in your azure signalr service in May. Could you double check that you provide the correct signalr service resource name?

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
