### ISSUE TITLE
Unable to connect Azure SignalR service (keep getting 500 and 429 - too many requests)

### ISSUE THREAD

**Issue by majum** [Azure/azure-signalr#536]
I have been using SignalR working/serving on my local computer (self-hosted) for months without any problem. I need to go production and decided to use Azure's SignalR service.

There is no source/documentation/stackoverflow topic/github samples left I have not checked. I keep getting "500 - internal server error" and "(429) too many requests". I don't know which is occurred when.

Tried on local and publishing project to AppService but none worked so far.

I am using SignalR Free tier and also tried with a Standard tier but no difference observed. Project I am trying to connect from is an Asp.Net MVC API (.net framework) project.

This is the code I am using (Startup.cs/Configuration):

```
app.UseCors(CorsOptions.AllowAll); // Also not working without this.
app.MapAzureSignalR(
    GetType().FullName,
    "<my connection string goes here>"
);
```

I am using a tiny website (can be found here: [https://gist.github.com/thecopy/5874375](https://gist.github.com/thecopy/5874375) - please note that I updated jquery.js and signalr.js files to the latest ones after download) to connect to my IIS hosted local API (signalr) project from `http://192.168.1.33:50069/signalr` and getting `https://XXX.service.signalr.net/aspnetclient/negotiate?clientProtocol=2.0&connectionData=%5B%5D&_=1558122682786` result with `429` http status code (observing from google chrome console). When I go to this link I get `Connection count reaches limit.` message.

As no client is connected to this signalr service I am unsure why I am getting this http status. I assume this is because of the number of connection attempts, then I restart the signalr service to reset all connections and confirm zero connections from the `Connection (max)` graph.

"Connection (max)" graph shows "server 20, client 0" even though I try connecting only once (one connection attempt with the tiny website client I shared above). I am not sure what causes signalr service to show 20 servers. The graph, sometimes, shows 30 servers even though I am on "SignalR Free" tier. I thought there can be maximum 20 servers and am unable to exceed. Can you tell me how is this server number counted and why I sometimes see more than 20 on free tier?

I downloaded [ChatRoom](https://github.com/aspnet/AzureSignalR-samples/tree/master/aspnet-samples/ChatRoom) sample and created a new signalr service on Azure. Chat application worked without any problem. However, when old signalr service is used, chat application is unable to connect and getting the same error (429). I tried using freshly created signalr service (that succeeded for ChatRoom app) on my project and surprisingly it didn't work.

I have also tried all `Service Mode`s (Default, Serverless, Classic). None of them made any difference.

I am using the latest SignalR packages installed from NuGet (signalr version 2.4.1).

Why am I constantly getting 429 and 500 http status codes and how do I solve this? Is this a bug?

**Comment by vicancy** [comment]
How many hubs do you have? SDK side initiates `(N hub count + 1) * ServiceOptions.ConnectionCount` server connections to the Azure Service when app starts, refer to [Server Connections](https://github.com/Azure/azure-signalr/blob/dev/docs/internal.md#server-connections) for details. The connection limitation counts for `client connection + server connection`. You can try set `ConnectionCount` to 1 to see if it can work:
```cs
app.MapAzureSignalR(
    GetType().FullName,
    options => {
        options.ConnectionCount = 1;
        options.ConnectionString = "<your connection string>";
    }
);

```
```

**Comment by majum** [comment]
I have 3 hubs.

Everything started working today without me doing anything. However, on [iOS SignalR Client](https://github.com/AutosoftDMS/SignalR-Swift) I am still getting `ResponseValidationFailureReason` with http `400`. Is there any way to see detailed reason on server side if client is misdoing/misinterpreting something (might be a version issue) so I can confirm blame client?

**Comment by vicancy** [comment]
client first negotiate with your app server, so may be you can log something you are interested from the incoming client request.

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
