### ISSUE TITLE
Orphaned connection

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#539]
For some reasons, rarely the Hub doesn't get notified about a client disconnect. Today it happened related to some issues ( I don't know if they are network or server related) that caused several disconnects (10-20 times) between 09:30 - 11:00 UTC aprox.

Are there any means to know that a specific connection is no longer active?

**Comment by vicancy** [comment]
One related bug https://github.com/Azure/azure-signalr/issues/416

**Comment by vicancy** [comment]
We beleive 1.0.12 fixed the issue. Please reopen it if you still encounter such issue. Thanks for your support.
