### ISSUE TITLE
Regular client disconnects using REST API

### ISSUE THREAD

**Issue by rstropek** [Azure/azure-signalr#540]
## Description

I have written a demo app in Go that uses the [Azure SignalR REST API](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md) to broadcast messages to JavaScript clients regularly (e.g. every second). The app's code is available [here](https://github.com/rstropek/golang-samples/tree/master/azure-signalr-server).

## Problem

Every approx. 15 seconds, the JavaScript clients get disconnected with the following error message: *Server returned an error on close: No app server is currently connected to the Azure service.*. I have to reconnect to continue receiving messages.

## Expected behavior

The Websocket connection should be stable.

## Repro

* Build Go code (link see above)
* Run it
* Open *http://localhost:8081* in a browser and see disconnect logs in the browser's console

**Comment by rstropek** [comment]
The [documentation](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-internals) says: *These connections [to clients] will remain connected to the SignalR Service all the time. If a server connection is disconnected for network issue, all clients that are served by this server connection disconnect...*. I guess this is the reason for the behavior I am seeing.

Guess my question is: How to deal with a scenario where there is no server connection? I only have a server that uses SignalR's REST API.

**Comment by realwanpengli** [comment]
Hi @rstropek , could you tell me what's the service mode of your signalr service (In `Azure_Portal/Your_SignalR_Service_Page/Settings`)? Your scenario is serverless, the service mode should be `Serverless`.

**Comment by rstropek** [comment]
Thank your for pointing that out. Will check and get back to you.

**Comment by rstropek** [comment]
Good point. The setting was indeed on *Default* instead of *Serverless*. I switched it to *Serverless* now. Here is the current setting in the Azure portal:

![image](https://user-images.githubusercontent.com/2341573/58181259-c2be1600-7cab-11e9-8fea-5edc3b4a1bdb.png)

Unfortunately, the behavior is still the same. Here is a screenshot of the browser's console window showing the error that occurs every 15 seconds:

![image](https://user-images.githubusercontent.com/2341573/58181206-a4f0b100-7cab-11e9-87e5-b5205904368b.png)

Greetings,
Rainer.

**Comment by rstropek** [comment]
Ok, I simply wasn't patient enough 😂🤣. I created a brand new service and it worked. Then I switched back to the old one - and it work there now, too. So I guess the change of the setting took a while until it became active. Now the Go sample works as expected. Thank you for reminding me on having to change that flag.

Greetings,
Rainer.
