### ISSUE TITLE
[DOC] Can't find sharding.md in dev branch

### ISSUE THREAD

**Issue by tebeco** [Azure/azure-signalr#546]
Hello,

We are trying to check our software resiliency and i found this PR : #359
It was merged on march the 4th
![image](https://user-images.githubusercontent.com/2266487/58307060-cbbefc80-7dfd-11e9-9224-8ff7d9271689.png)

it contains [the file sharding.md](https://github.com/vicancy/azure-signalr/blob/dd84de02a66c6d197cf8d3845ded3319ab761bb4/docs/sharding.md) but i can't find it in `dev` branch, is that intended ?

Has the docs fully moved to `https://docs.microsoft...` website ?

**Comment by vicancy** [comment]
https://github.com/Azure/azure-signalr/blob/dev/docs/sharding.md

**Comment by tebeco** [comment]
my bad the navigation took me to your account fork.
I'm not sure how i did not see that
