### ISSUE TITLE
Every night around 01:11 UTC clients receive errors when sending data

### ISSUE THREAD

**Issue by alexiordan** [Azure/azure-signalr#556]
Every night around 01:11 UTC clients that send data to server encounter following error:

```
The server closed the connection with the following error: Internal server error.
```
The stack is this:
```
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)   
```
In the server side log of the appservice I did not find any errors. 
It happens every day at that time. Is this some planned restart of the SignalR Service?

**Comment by vicancy** [comment]
No there is no planned restart for SignalR Service. Is it possible that Web App has planned restarts?

**Comment by alexiordan** [comment]
I just looked in Azure under "Diagnose and solve problems" - "Web App Restarted" and I haven't seen any restart there.
For 2 days now it seems that time is no longer 01:11 UTC, but 01:50 UTC.

**Comment by vicancy** [comment]
Any server side log during that period? You can also email me the affect instance name for me to check if there were anything abnormal from service side.

**Comment by alexiordan** [comment]
I believe it was something about the ISP infrastructure that caused such behavior. I'll close it for now.
