### ISSUE TITLE
WebSocket connection ttl for serverless mode

### ISSUE THREAD

**Issue by myarotskaya** [Azure/azure-signalr#558]
According to the documentation the client will be receiving Ping messages from the SignalR service after successful HandshakeRequest. How long lives a connection in case when client would'n send any Ping requests to the server?

**Comment by realwanpengli** [comment]
Hi @myarotskaya , for [signalr client (version >= 1.1.0)](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.1.0), signalr client always send ping.

**Comment by myarotskaya** [comment]
@realwanpengli thanks for the reply! But my question is about the case when I'm not using SignalR client. Does SignalR service close a connection if it doesn't receive any Ping messages from client?

**Comment by myarotskaya** [comment]
hey @realwanpengli any updates on this?

**Comment by realwanpengli** [comment]
@myarotskaya  Sorry for the delay. The connection timeout is 30 seconds without receiving Ping messages.

**Comment by myarotskaya** [comment]
But I tried to connect to the SignalR service without sending Ping messages from the client side and the web socket connection was alive during at least 6 hours (the server haven't closed it)

**Comment by albertxavier100** [comment]
You said you don't use SignalR client, so how do you establish the connection?

**Comment by myarotskaya** [comment]
@albertxavier100 you can connect to Azure SignalR service without SignalR client using the following url: `wss://[signalRServiceName]/client?hub=[hubName]&accessToken=[accessToken]` and after that send [Handshake request](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#overview). In browser it looks like: 
```
var connection = new WebSocket('wss://[signalRServiceName]/client?hub=[hubName]&accessToken=[accessToken]');

socket.onopen = function (event) {
    console.log('Connected to: ' + event.currentTarget.url);
    socket.send('{"protocol":"json","version":1}');
};
```

**Comment by realwanpengli** [comment]
@myarotskaya Sorry , I checked the ping message timeout for server connection instead of client connection. There is no timeout for client connection.

**Comment by BrennanConroy** [comment]
@myarotskaya In SignalR 1.0.0 clients didn't send pings to the server and the server didn't timeout clients for not pinging regularly. In 1.1.0 the clients start sending pings and to preserve back-compat the server would only start observing timing out clients if they sent a ping in the first place.

So in your case because you never send a ping, the server wont start the timeout logic.

**Comment by myarotskaya** [comment]
@BrennanConroy Ok, I get it. Thank you for the reply! But how long will live a connection in case if client starts to send ping messages and then stops to do it? After which period of time the server supposed to terminate this connection?

**Comment by BrennanConroy** [comment]
~30 seconds

**Comment by myarotskaya** [comment]
Hmm I just tried to send Ping message from a client side - the established connection wasn't closed after 30 seconds 🤔 
![image](https://user-images.githubusercontent.com/3490828/59236747-1330ef80-8c2a-11e9-8773-31ab25b44858.png)

**Comment by BrennanConroy** [comment]
Whats the version of SignalR you're using on the server?

**Comment by myarotskaya** [comment]
I'm using Azure SignalR Service

**Comment by BrennanConroy** [comment]
Oh are you doing serverless? I don't know then. @vicancy

**Comment by vicancy** [comment]
@myarotskaya When using Azure SignalR Service, service does not terminate the connection even if the client starts to ping, for backward compatibility concerns. For now, ping messages from client are just ignored by the service.

cc @BrennanConroy

**Comment by myarotskaya** [comment]
@vicancy thanks for the reply! In this case, is there any plans to support Ping messages from the client and terminate a connection once the server stops to receive them?

**Comment by vicancy** [comment]
It's not yet in the plan. We can add the feature to the plan if there is a strong need for this. May I know your main scenario for this and your concern if this feature is not there?

**Comment by myarotskaya** [comment]
Actually I don't have a case right now but it's [a part of HubProtocol](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#ping-aka-keep-alive). Why it was designed like this in the first place? I mean why SignalR server supports Pings from the client? For which scenarios it might gonna need?

**Comment by myarotskaya** [comment]
@BrennanConroy maybe you could help me? I just want to have an idea why would I need to send pings from the client and why it doesn't make sense for Azure SignalR Service

**Comment by BrennanConroy** [comment]
It is so the server can better detect when a client is no longer connected. If the client never sends a ping and pulls the ethernet or power cable from their computer, then it can take many minutes for the server to know that the client is no longer there.

App developers like to know when clients are gone as soon as possible, so pings helps close that gap.

**Comment by myarotskaya** [comment]
@BrennanConroy thank you for the clarification! But why there are no plans to support pings from clients in Azure SignalR Service as well? @vicancy

**Comment by vicancy** [comment]
Thanks @BrennanConroy for the explanation. 

Hi @myarotskaya Yeah we should support that. Adding to backlog for triage.

**Comment by vicancy** [comment]
@myarotskaya As for serverless case, Azure SignalR maintains the lifetime of client connections. So for now, the only impact for lacking client ping timeout check is that Azure SignalR detect client connections later and thus consumes more resource to maintain already disposed client connections.

This feature can be useful when we allow OnDisconnect event hook (which is work in progress) with Serverless mode. cc @zackliu

**Comment by myarotskaya** [comment]
@vicancy thanks for the explanation and adding to the backlog! I have one more question (it's not related to Pings but still about connection lifetime): can client send `Close` message to the server? I see in the [documentation](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#overview) that `Close` message can be sent by Caller and Callee (`Sender` column) but `Description` column says that it can be sent only by the server:
> Sent by the server when a connection is closed.

**Comment by bbowman** [comment]
Any update on this now that the serverless disconnect work appears to be done (https://devblogs.microsoft.com/aspnet/azure-signalr-service-now-supports-event-grid/)?

**Comment by zackliu** [comment]
@bbowman Ping check in `Serverless` mode haven't been done still. But now, as the blog shows, you can leverage Event Grid to receive the `OnConnected` and `OnDisconnected` whenever service detects the client status changes.

**Comment by roy46** [comment]
+1 for using the pings to determine client connectivity in serverless mode.

We are trying to use this feature to determine if a client is connected to show an online / last seen status in a chat app. I noticed the long polling transport type follows the documented ConnectionTimeout of 110s so this is a possible solution. However I would be great if we could use websockets instead. 

As far as I can tell and from what I have read the websocket is only considered disconnected once the underlying TCP connection has timed out. From what I have seen this is anywhere between 2 - 30 minutes. I'm unsure if that is correct? but I might be worth clarifying for anyone else seeing this issue

It would also be beneficial to have some control over the ConnectionTimeout in serverless mode. As far as I can tell it's not configurable?

**Comment by danielkylewood** [comment]
+1, similar issue to @roy46 above.

Any update on this?

**Comment by sffamily** [comment]
Hi @myarotskaya @royston-c @danielkylewood , I'm the Product Manager of Azure SignalR Service. I found your previous communications on serverless scenarios with Azure SignalR Service. We have a new internal preview to support raw WebSocket in serverless scenarios, thinking you might be interested to try it out and offer us some feedback. If you are interested please ping me at zhshang at microsoft dot com so I can help you with a testing URL and sample codes to try it out.  Thanks. -Zhidi

**Comment by vicancy** [comment]
I am closing the issue because it should already be fixed. Please feel free to reopen it or leave your comment if you still have concerns about it.
