### ISSUE TITLE
Serverless Mode. Connected/Disconnected users

### ISSUE THREAD

**Issue by tbuha** [Azure/azure-signalr#559]
Hi there,

I'm going to use Azure Functions and Azure SignalR in Serverless Mode.
How to determine that user is connected to Azure SignalR? Is there any API to get connected users(with UserId) to Azure SignalR?

Thanks, Taras

**Comment by albertxavier100** [comment]
Hi @tbuha . All REST API can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md). No query api for connected users.

**Comment by realwanpengli** [comment]
Hi @tbuha All REST API can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md). No query api for connected users.

**Comment by tbuha** [comment]
@realwanpengli  thanks for the reply.

Does it mean that I cant do completely serverless approach?
And to get Connected/Disconnected Azure SignalR clients I still need to implement Hub in the App Service with 
public override Task OnConnectedAsync();
public override async Task OnDisconnectedAsync(Exception exception);

What will be the best approach?

**Comment by realwanpengli** [comment]
@tbuha , welcome. That's right.

**Comment by realwanpengli** [comment]
Close the issue since already resolved and over 1 week.

**Comment by vicancy** [comment]
Hi @tbuha, we are now working in progress to add EventGrid hook to serverless scenarios so that you can get notified with `Connect` and `Disconnect` events. 

It will be available for all regions around early July.

cc @realwanpengli  @zackliu

**Comment by PalashBorhan** [comment]
Hello @vicancy, It's good to have this. I have this reported [here in github](https://github.com/Azure/azure-functions-signalrservice-extension/issues/54) as well. Any thoughts if this can be done using Azure Functions binding?

**Comment by fjmejias** [comment]
> Hi @tbuha, we are now working in progress to add EventGrid hook to serverless scenarios so that you can get notified with `Connect` and `Disconnect` events.
> 
> It will be available for all regions around early July.
> 
> cc @realwanpengli @zackliu

It this EvenGridTrigger to serverless scenarios working for all regions?

**Comment by zackliu** [comment]
@fjmejias It works in all the regions and here's [the sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/EventGridIntegration) of Event Grid integration.
