### ISSUE TITLE
XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by marshall76963** [Azure/azure-signalr#561]
Hi

We are receiving the following error in the Firefox console when initiating a connection to SignalR:

```
XML Parsing Error: not well-formed
Location: https://<azure-server-instance>/aspnetclient/start?transport=webSockets&clientProtocol=2.1&<connection-data>...
Line Number 1, Column 1:
```

I am aware that this was known about in previous versions of SignalR as described here: https://github.com/aspnet/SignalR/issues/1106, however we are getting this with the latest `Microsoft.Azure.SignalR.AspNet` NuGet package (version 1.0.10) on Azure using ASP.Net.

Whilst as far as I can tell this does not cause any issues - it just messes up the console, I thought I would flag it as it has been detected previously, and that was caused when the `Content-Type` has not been set and is being parsed as XML in Firefox rather than JSON.

**Comment by vicancy** [comment]
Repro-ed with Firefox. Thanks for reporting it.

**Comment by vicancy** [comment]
We plan to fix this issue in the upcoming service update, which is planed on the end of June.

**Comment by vicancy** [comment]
Fixed
