### ISSUE TITLE
Is adding to groups persistent?

### ISSUE THREAD

**Issue by JontyMC** [Azure/azure-signalr#572]
I'm using serverless and adding users to groups via the REST API. Does group membership persist beyond connection closing? IE, do I need to register to the groups every time a user connects or only once? I can't find this information in the docs anywhere.

**Comment by vicancy** [comment]
Yes, when using serverless, we *guarantee* persistency of "users to group relationship" for **7 days**.

**Comment by bitcloud** [comment]
Where can I find that guarantee in the documentation? I would love to link to that page from our documentation.

**Comment by pnda489** [comment]
Any updates on this?

I am still looking for some kind of documentation.

**Comment by vicancy** [comment]
We have a swagger describing the usage of adding user to group, inside which we have a description for ttl as **Time to live in seconds for the user Id. Optional for live forever.** https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.json#L289
