### ISSUE TITLE
Sometimes my signalr .net client's InvokeAsync method works and sometimes it doesn't.

### ISSUE THREAD

**Issue by hodgezappa** [Azure/azure-signalr#581]
I have a .net core 2.2 project which has an Azure signalR service hub, in my startup.cs i have set it up like this:

```
services.AddSignalR(o => o.EnableDetailedErrors = true).AddAzureSignalR(connstring);

app.UseAzureSignalR(route =>
{
    route.MapHub<FooBarHub>("/foobarhub");
});
```

I have a .net client project which is a winform app (.net 4.6.1), it sets up the connection like :

```
connection = new HubConnectionBuilder().WithUrl($" 
{serviceHost}/AgentHub").Build();
```
when it starts up I call:

`await connection.StartAsync();`
and can see the state is Connected.

I then want to call a method on the hub from the client so i do this in the client:

```
string myIdString = await connection.InvokeAsync<string> 
("RegisterSignalRId", foobarId);
```
that should hit my method in my server hub:

```
public string RegisterSignalRId(string foobarId)
{
    myService.RegisterSignalRId(this.Context.ConnectionId, foobarId);
    return this.Context.ConnectionId;
}
```
My problem is that sometimes when I start the winform app, I get myIdString being set to null, it doesn't hit the breakpoint in the server hub method at all, and yet sometimes it does work and I get the real/correct value.

I can't consistently make it work or fail, it seems random. When it does fail i get no errors or exceptions.

**Comment by hodgezappa** [comment]
After some more digging i think this is because i'm using an Azure signalR service. I've added a new method which is sometimes hits successfully but sometimes fails with - HubException: Method does not exist.

**Comment by vicancy** [comment]
It occurs when you use Azure SignalR Service for different web apps with different application name, or web app with different versions, one web app contains the method however the other one not.

**Comment by hodgezappa** [comment]
hmm, i only have one web app and i'm running all this locally in dev mode with visual studio at the moment

**Comment by hodgezappa** [comment]
Actually, you've made me realize that other devs are using my service with their instances too, their instances don't have this new method in, so when it works it's hitting me code, when it fails it's hitting theirs! This is probably what's happening. Thanks

**Comment by hodgezappa** [comment]
Yep, i've set up a new service so i'm the only one calling that and there's no problems now. Thanks for pointing my brain in the right direction!
