### ISSUE TITLE
Implementing Hub Class

### ISSUE THREAD

**Issue by kwasak** [Azure/azure-signalr#582]
I'm using serverless with ASP.NET Core SignalR, and I'm wondering, how would I use my own hub implementation?

```
var serviceManager = new ServiceManagerBuilder()
                .WithOptions(option =>
                {
                    option.ConnectionString = signalRConnectionString;
                    option.ServiceTransportType = ServiceTransportType.Persistent;
                })
                .Build();

IServiceHubContext simpleChatHubContext = await 
serviceManager.CreateHubContextAsync("simplechat");
```
The Hub returned from ServiceManager builds is implmentated as an internal class of ServiceHubContext.
How would I implement and use my own Hub logic, similar to below, instead?

```
public class ChatHub : Hub
{
        public void BroadcastMessage(string name, string message)
        {
            Clients.All.SendAsync("broadcastMessage", name, message);
        }
}
```

It's worth noting, the documentation states [business logic should be in your hub classes](https://github.com/Azure/azure-signalr/blob/dev/docs/internal.md), which leads me to believe it may be possible.

**Comment by realwanpengli** [comment]
Hi @kwasak , the document for Management SDK can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md).

You can send messages like this:
```
simpleChatHubContext.Clients.All.SendAsync("broadcastMessage", name, message);
```

Quick start can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#quick-start).

Samples can be found [here](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management).

**Comment by kwasak** [comment]
Thank you @realwanpengli
