### ISSUE TITLE
Azure SignalR compatible with preview7

### ISSUE THREAD

**Issue by JialinXin** [Azure/azure-signalr#584]
Open a issue to track the potential compatibility issue in preview7.

**Comment by JialinXin** [comment]
cc @davidfowl @vijayrkn 
Let us know if you meet any problem in the coming release.

**Comment by davidfowl** [comment]
Yes there are breaking changes we need to react to, lets get a new build so we can start the reaction.

**Comment by JialinXin** [comment]
Thanks for reminding. Will work on this.

**Comment by JialinXin** [comment]
@vijayrkn @phil-allen-msft 
Package(version number >= [1.1.0-preview1-10442](https://www.myget.org/feed/azure-signalr-dev/package/nuget/Microsoft.Azure.SignalR/1.1.0-preview1-10442)) work for preview7 is available in **MyGet** for Visual Studio integration tests before AspNetCore 3.0 preview 7 releases. Please check.

> nuget.exe install Microsoft.Azure.SignalR -Version 1.1.0-preview1-10442 -Source https://www.myget.org/F/azure-signalr-dev/api/v3/index.json

**Comment by phil-allen-msft** [comment]
Checked; all appears to be well.

**Comment by JialinXin** [comment]
Pushed to Nuget(https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.1.0-preview1-10442) as well.
