### ISSUE TITLE
Endpoint status always Online

### ISSUE THREAD

**Issue by alarco-l** [Azure/azure-signalr#589]
Hi,

I'm trying to understand how SignalR and Azure SignalR resiliency works according [Resiliency and disaster recovery](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-disaster-recovery) and [Sharding.md](https://github.com/Azure/azure-signalr/blob/dev/docs/sharding.md).

I have created a very dummy custom router class to be able to check my primary endpoints and there status.
```csharp
 public class CustomRouter : EndpointRouterDecorator
{
    private readonly ILogger<CustomRouter> _logger;

    public CustomRouter(ILogger<CustomRouter> logger)
    {
        _logger = logger;
    }

    public override ServiceEndpoint GetNegotiateEndpoint(HttpContext context, IEnumerable<ServiceEndpoint> endpoints)
    {
        var onlinePrimaryEndpointsCount = endpoints.Where(s => s.Online && s.EndpointType == EndpointType.Primary).Count();
        _logger.LogInformation(onlinePrimaryEndpointsCount > 0 ? "Some Primary Online" : "No Primary Online");

        var endpoint = base.GetNegotiateEndpoint(context, endpoints);
        _logger.LogInformation($"Endpoint : {endpoint.ConnectionString}");
        return endpoint;
    }
}
```
 
When I delete my signalR service in azure portal and try to connect a signalR client, I was expected my endpoint to not be marked as `online` but it currently is.

Is there something I misunderstood ?

I'm using:
* ASP.NET Core v3.0-preview5
* Microsoft.Azure.SignalR v1.1.0-preview1-10420

**Comment by vicancy** [comment]
When you delete your service? Is it when the app server is already running or before the service is running? For backward compatibility concerns, the endpoint initial status is `online`, and it changes to `offline` after its first try of connecting to Azure SignalR.

**Comment by alarco-l** [comment]
Yes my app server is running, then I delete the signalR service.

So how the hub on app server running on azure can switch to my `secondary endpoint` if the status will not change to `offline` ?

**Comment by vicancy** [comment]
It should change. Could you try the latest one `Install-Package Microsoft.Azure.SignalR -Version 1.1.0-preview1-10435 -Source https://www.myget.org/F/azure-signalr-dev/api/v3/index.json`? We made several fixes to `endpoint` after `10420`.

**Comment by alarco-l** [comment]
I just edited my previous answer after some tests and I will no test with `1.1.0-preview1-10435` package.

Thanks

**Comment by vicancy** [comment]
1. Running my app server, connected to `ServiceEndpointA`(primary, online) and `ServiceEndpointB`(secondary, online)
2. Connect a signalR client, redirect to `ServiceEndpointA`
3. Delete my service `ServiceEndpointA`, 
~~Run a new app server~~ (no need to)
4. Connect a new signalR client, `ServiceEndpointA` should be offline now, and return `ServiceEndpointB`

**Comment by alarco-l** [comment]
Indeed with `1.1.0-preview1-10435` package, the dead enpoint is not marked as `online` anymore and the new signalR client is routing on the secondary enpoint.

With my understanding, the `1.1.x` package will be delivered synchronously with `netcoreapp3.0` and `aspnet core 3.0`, I'm not really sure about my assumptions.  

Can you share more details about this release and if it is  really related to `aspnet core 3.0` release ?

Thanks for yours answers.

**Comment by vicancy** [comment]
Thanks for the info. @alarco-l  We will release the `1.0.11` package for `netstandard2.0` in next release, which is planned in next week.

**Comment by alarco-l** [comment]
Great news ! Thanks for all your answers.
I’m closing the issue
