### ISSUE TITLE
[PORTAL] Deleting and Recreating a backplane show log from previous instance

### ISSUE THREAD

**Issue by tebeco** [Azure/azure-signalr#593]
Hello,

It seems that we see glitches in Azure Portal, when using an `azure signalr` backplane :
* Create an Azure SignalR backplane
* Use it for streaming
* Delete it
* Create  a blank new one with the same name/ region / resource group (not sure what how it matches)
* DO NOT use it
* go in `Activity log` in the portal

It will display logs from the previously existing instance.

It's a bit annoying in development when we tend to regenerate `azure service` on purpose, when trying to validate the ARM template to create our apps for example

For now, if we want clear logs, we have to generate "unique" name every time we re-generate it. So it also means we cannot pin it in the Dashboard

For example, this is an `Azure Signalr` that has just been create, and as we see it contains information from ~7h ago

![image](https://user-images.githubusercontent.com/2266487/60903751-39ba6880-a272-11e9-9ec6-f7cf1f41af4b.png)
![image](https://user-images.githubusercontent.com/2266487/60903786-4474fd80-a272-11e9-9c56-cce769bb5731.png)

**Comment by JialinXin** [comment]
It's by design. [Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/overview)(metrics and logs on Azure portal) recognize **ResourceId** (composed by subscriptionId, resource group name and resource name, which can be find under Properties) only and it is a common issue among all Azure resources.

**Comment by tebeco** [comment]
thx a lot I had no idea that behavior

it's weird that the Id could be reused like that, it feel both logic and sooooo bad
the logs will ends up with tons of false positive
will probably open a ticket to the Monitor team to see if it could at least have a boolean to erase logs while deleting a resource
