### ISSUE TITLE
[Question] Does Azure Signalr supports Ackable Message ?

### ISSUE THREAD

**Issue by alarco-l** [Azure/azure-signalr#594]
Hi,

I could see on [ServiceProtocol](https://github.com/Azure/azure-signalr/blob/dev/specs/ServiceProtocol.md) and in the source code of this sdk that there is a notion of acknowledgement for both `joinGroup` and `leaveGroup` actions.

There is also a [AckMessage class](https://github.com/Azure/azure-signalr/blob/b97db853f8e2460983ec49f659784e8d6c7a2a82/src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs#L134) available.

On my understanding it's only for internal purpose, am I right ?

Is there a way or maybe in the future to be able to send `AckMessage` over the `Hub` class ?
In order to do guaranteed delivery on specific messages.
 
I know I can achieve my own acknowledgement policy but I wonder if by any chance that it's already implemented or if it could be on your roadmap.

I do understand that SignalR it self does not provide such thing, as "signalr does not hold any state" (mainly for scalability purpose), but as long as `Azure SignalR Service` is design as a SaaS service backplane, this Sdk could contains Api to let the backplane handle the Acknowledgment based on a given policy (like `Poly`).

Thanks for your time.

**Comment by zackliu** [comment]
Now the ack-able operation only apply on `JoinGroup` and `LeaveGroup` as waiting for ack will definitely have a bad impact on performance and `JoinGroup` and `LeaveGroup` are not as frequent as other operations .
We don't have a clear road map about adding other ack-able actions. I know many customers have the necessary of guaranteed order or guaranteed delivery, and we're investigating a way to balance the functionality and performance.

**Comment by alarco-l** [comment]
@zackliu thanks for your answer.
I look forward to have the guaranteed delivery feature.
