### ISSUE TITLE
[QUESTION] Release Synchronization with AspNetCore ?

### ISSUE THREAD

**Issue by tebeco** [Azure/azure-signalr#597]
Hello @vicancy ,

I know this kind of question is usually hard to answer.
We plan to move from `aspnetcore2.2` to `aspnetcore3.0` + `azure signalr` at the same time.

We are currently wondering if the release of the `azure-signalr` `v1.1.x` (or maybe `v3.x`) will be aligned with the release date for both `netcoreapp3.0` / `aspnetcore3.0`, for september 2019

**Comment by vicancy** [comment]
Yes we are. cc @JialinXin

**Comment by tebeco** [comment]
oupsi, i forgot to close that one i guess
