### ISSUE TITLE
Server Connections remain open

### ISSUE THREAD

**Issue by ariosdev** [Azure/azure-signalr#614]
Hello, 

I am using Microsoft Azure SignalR Management library to create a single hub which connects to Azure SignalR Service which is set to Serverless mode, currently I have only one client, client connects to ASRS with no issues, does some work and then it calls hubConnection.stop() to close the connection, however I can see in Azure Portal that server connection count keeps getting higher up to the point to reach 20 server connections, at that point I am getting this error:

HTTP/1.1 429 Too Many Requests
Connection count reaches limit.

So I have to restart the ASRS to reset the server connection count to get it working again.

Shouldn't hubConnection.stop() take care of that or am I missing something?

Thank you!

**Comment by realwanpengli** [comment]
@ariosdev 

One server connection per `ServiceHubContext`, so you created 20 ServiceHubContext? Did you choose `AGGREGATION` to `MAX` in Metrics blade in Azure portal?

HubConnection.StopAsync() only stop client connections.

Call `IServiceHubContext.DisposeAsync()` to stop server connection.

FYI, Management SDK's [guide](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md) and [sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management).

**Comment by ariosdev** [comment]
@realwanpengli 

I opened the website in new tabs / browsers multiple times, I think that would translate to creating 20 or so ServiceHubContext, I tried calling IServiceHubContext.DisposeAsync() as suggested but it didn't help, I was still getting the same error, what helped was changing the ServiceTransportType back to Transient as I had it set to Persistent, everything seems to be working fine now.

Thank you.

**Comment by realwanpengli** [comment]
@ariosdev Could you tell me what tier and unit are you using? If it is free, the concurrent connections limit (20) is easy to reach. The pricing details acn be found [here](https://azure.microsoft.com/en-us/pricing/details/signalr-service/)

>  I tried calling IServiceHubContext.DisposeAsync() as suggested but it didn't help

Could you email me your SignalR service's resource ID, if it is true, it should be a bug, we would like to help to fix it.

**Comment by ariosdev** [comment]
@realwanpengli

Sure, 

Free Tier
Unit / Capacity: 1
Mode: Serverless

I will email you the resource id.
