### ISSUE TITLE
No clarity about thread safety at all. Finally, is ServiceHubContext thread-safe or not?

### ISSUE THREAD

**Issue by scale-tone** [Azure/azure-signalr#617]
All the examples of how to obtain and use IServiceHubContext instances do not go beyond a "Hello world" use case and therefore do not provide any answer on what is the recommended approach to it's instance lifecycle.
Can we have a singleton instance of it per process? If yes, will it be thread-safe? Will it automatically reconnect? What if it fails to?
If not, how costly are serviceManager.CreateHubContextAsync() calls?

The only doc I managed to find on this topic is for [Asp.Net Hub](https://docs.microsoft.com/en-us/previous-versions/aspnet/jj890869(v=vs.111)) class, which says its instance methods "are not guaranteed to be thread-safe" (hopefully it is just a boilerplate text and is not true in reality)…

All this uncertainty prevents people from using this package in production-ready environment.

**Comment by realwanpengli** [comment]
Hi @scale-tone Thanks for asking.


> do not provide any answer on what is the recommended approach to it's instance lifecycle

No global shared data, you can use it as static/non-static member. So no special recommendation.


> Can we have a singleton instance of it per process?

Both work.


> will it be thread-safe?

Yes, except for `ServiceHubContext` can be disposed only once.


>  Will it automatically reconnect? What if it fails to?

If it fails:
* Transient Mode: No actual connection
* Persistent Mode: No, it will not reconnect, user should handle it by himself/serself. Throw exception if disconnects unexpectly.

More information about these two modes can be found [here](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#transport-type).


> how costly are serviceManager.CreateHubContextAsync() calls?

The [document](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md#servicehubcontext-createhubcontextasyncstring-hubname-iloggerfactory-loggerfactory--null-cancellationtoken-cancellationtoken--default) alreadly talked about it.

* Transient Mode: Cost can be ignore -- Create an instance to call Azure SignalR's REST api to send messages.
* Persistent Mode: Main cost -- Establish Websockets connections to send messages.

**Comment by scale-tone** [comment]
Thanks @realwanpengli , much more clear now. Still more questions:

> Persistent Mode: No, it will not reconnect, user should handle it by himself/serself. Throw exception if disconnects unexpectly.

Did you mean that IClientProxy.SendCoreAsync() will start throwing exceptions in that case?

> The document alreadly talked about it.
Transient Mode: Cost can be ignore -- Create an instance to call Azure SignalR's REST api to send messages.
Persistent Mode: Main cost -- Establish Websockets connections to send messages.

I assume, ServiceTransportType.Transient is the default option, is that correct?

Are you saying that in this mode it will be establishing new HTTP connections to Azure SignalR Service REST API for each and every message to be sent? 
If yes, this mode seems to be pretty expensive!

I can also see they in [Azure Functions SignalR Extension](https://github.com/Azure/azure-functions-signalrservice-extension/blob/master/src/SignalRServiceExtension/Config/SignalRConfigProvider.cs) are using this mode (can be configured, but they do not advertise this option, probably, because the rest of the code is not ready for connection failures). They do use ServiceHubContexts as singletons but they do not use "Persistent Mode". Does that make sense? What would be the recommended approach for server-side scenarios like in Azure Functions?

**Comment by realwanpengli** [comment]
@scale-tone Thanks for mentioning Azure Function SignalR Extension! And sorry for the wrong answer. The Management SDK already have the logic to [reconnect](https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs#L205)

But we only have one websockets connection in persistent mode, if one drops, there's no other connections to send messages. We plan to add more connections, and randomly choose another available connection to send message event if part of the connections drop.

> Are you saying that in this mode it will be establishing new HTTP connections to Azure SignalR Service REST API for each and every message to be sent

Yes, the version 1.0.0 only has transient mode, so we plan to add persistent mode to send all messages in one websockets connection in improve performance.

The reason to set transient mode as default is to keep consistency to the previous versions.

**Comment by scale-tone** [comment]
> The Management SDK already have the logic to reconnect

Yes, but I don't see it working. [A bug on that](https://github.com/Azure/azure-signalr/issues/627).

**Comment by vicancy** [comment]
It is thread-safe.
