### ISSUE TITLE
[WebSocket] Unable to connect to server

### ISSUE THREAD

**Issue by Mittchel** [Azure/azure-signalr#620]
We've been trying to port our api's to .net core 2.2 and are experiencing issues with the Azure SignalR service and WebSockets.

For some reason we're experiencing a WebSocket exception: 'Unable to connect to the remote server'. The weird thing is that when we enable Long polling everything works fine. 
We've scattered the web and tried a bunch of things but nothing has been successful yet. 

I've attached a solution that reproduces the error with both a 'server' and client.
I hope someone call tell me what we're doing wrong here! Thanks in advance.
[SampleApplication.zip](https://github.com/Azure/azure-signalr/files/3458448/SampleApplication.zip)

**Comment by vicancy** [comment]
The sample code looks good to me.

Is it the client side experiencing the WebSocket exception? Could you follow https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#tips to get the details of the failed request?

**Comment by vicancy** [comment]
Details please refer to https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#troubleshooting-guide-2 #2

**Comment by Mittchel** [comment]
@vicancy thanks for taking the time to dig into this one. I've followed your advice and checked the request with Fiddler. There isn't much to see except a 404 that I'm getting which isn't really new sadly. (see attachment)

I've disabled SkipNegotiation before and did it again, that indeed works, but I'm not a 100% sure that it's using websockets then. The reason for that is that If I check the transport type in the api the value is null. Also if I check Fiddler it doesn't tell me that it's using websockets (see attachment 2).
![404_signalr](https://user-images.githubusercontent.com/1458641/62352120-ad653380-b507-11e9-8a02-cd6bca5e049b.png)
![signalr_transport](https://user-images.githubusercontent.com/1458641/62352123-af2ef700-b507-11e9-8b52-460f842dceff.png)

**Comment by Mittchel** [comment]
I feel like [this issue ](https://github.com/aspnet/SignalR/issues/2329)is related. It's an issue from a year ago though and doesn't supply a solution. 

Also when I'm not using Azure Signalr Service but I'm actually hosting my own by doing app.UseSignalr() it works over websockets (see attachment). So it looks like the connection to the Azure Signalr service isn't working via websockets. I know the connectionstring is correct since I can connect with longpolling.
![works_without_azure_signalrservice](https://user-images.githubusercontent.com/1458641/62352497-92df8a00-b508-11e9-955e-35e4f874a5eb.png)

**Comment by Mittchel** [comment]
Ooff @vicancy I think you're right on setting the SkipNegotiation to false. The first time I actually removed it entirely which worked but I didn't see the websocket request like I mentioned.

I've read the docs you provided and actually read your comment better and explicitly changed `SkipNegotiation = false` and I think it works now.

I'll do some more testing before I can close this issue.

**Comment by Mittchel** [comment]
So did some more testing and it works when putting `SkipNegotation = false` but I'm not 100% sure that its using WebSockets now. I can't find it anywhere in Fiddler actually and also when I try to retrieve the transport in the api by calling: `var transportType = Context.Features.Get<IHttpTransportFeature>()?.TransportType;` it actually returns null. 

When reading up on [the internals](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-internals) I can imagine I won't see the websocket connection between the api and azure signalr with fiddler. I can understand that I'll only see the negotiation, which I do. 

But why does the transporttype return null? And what are my other options to be 100% sure that I'm actually using websockets now?

![negotiate](https://user-images.githubusercontent.com/1458641/62355010-6d557f00-b50e-11e9-9912-48a2417f8637.png)

**Comment by Mittchel** [comment]
Did some more digging and it actually works. I actually found out I had it working before when I didn't supply `SkipNegotiating` at all. I just didn't know for sure if it was using WebSockets, now I do. I'll summarize it for further readers.

`SkipNegotation` has to be set to false or left out completely and it will work. The reason why we can't see in Fiddler that it's a WebSocket connection is because the Websocket connection is between the api and azure. You will only see the `negotiation` call.  Probably also the reason why `Context.Features.Get<IHttpTransportFeature>()?.TransportType;` returns null. 

So, to check if I'm actually using WebSockets I added some logging to both the client and the server.

**Clientside logging(Microsoft.Extensions.Logging.Debug nuget package)**

>             var connection = new HubConnectionBuilder()
>                     .WithUrl("https://localhost:44394//chat", options =>
>                     {
>                         options.Transports = HttpTransportType.WebSockets;
>                     })
>                     .ConfigureLogging(logging =>
>                     {
>                         logging.AddDebug();
> 
>                         // This will set ALL logging to Debug level
>                         logging.SetMinimumLevel(LogLevel.Debug);
>                     })
>                     .Build();

**Serverside**
https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2#server-side-logging

In the client and server logging I both can see the `Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport` coming back in the logging. So I am sure now that everything is working as intended and that we are actually using websockets. 

I do think this should be added to the documentation in one place, maybe more explanation under the 404 error descriptions at: https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#troubleshooting-guide-2

**Comment by vicancy** [comment]
Thanks for your detailed info @Mittchel.

From my side fiddler is able to capture the network between your localhost and azure SignalR. Is there any setting/filter preventing that from your side?
![image](https://user-images.githubusercontent.com/668244/62436336-eaccf980-b771-11e9-95c7-780fc4cd527b.png)

**Comment by Mittchel** [comment]
@vicancy no problem for the detailed info. Really hope this helps other people in the future as well!

I am not that familiar with fiddler to tell you which setting/filter is preventing me from seeing the network connection between localhost and Azure. 

Currently I'm using the default settings (clean install of fiddler). Are you able to tell me what settings I could check?

Thanks!
