### ISSUE TITLE
[Bug] Context.GetHttpContext().Connection.RemoteIpAddress returns null

### ISSUE THREAD

**Issue by ispysoftware** [Azure/azure-signalr#623]
It stopped working about 9 hours ago - it connects but doesn't relay any messages to the backend server.

I've restarted the service and even deployed a new instance of it with the same results. Something has crapped it's pants on Azure's side. This has been working for months.

**Comment by ispysoftware** [comment]
seems to only be an issue on Central US

**Comment by vicancy** [comment]
Resolved in 1.0.12

**Comment by ispysoftware** [comment]
This bug cost us a lot of money - in lost customers and site downtime. What kind of assurances do we have that it won't happen again?  Is there a way to specify an azure signalr server version to use? 

I'm extremely nervous that our platform will go down at any moment due to a botched push from your side that we have no control over and no notification that it's being "upgraded".
