### ISSUE TITLE
Group related options do not throw exceptions when message is lost

### ISSUE THREAD

**Issue by vicancy** [Azure/azure-signalr#632]
Since SDK 1.0.10 we changed the group related actions to wait for the ack messages from Service to guarantee group related message order and delivery. However, when the message is lost when for example, transport layer error, SDK does not throw exceptions to the caller. So there is still chance when the message is lost silently.

**Comment by zackliu** [comment]
#638

**Comment by vicancy** [comment]
Fixed in 1.0.13

**Comment by alexiordan** [comment]
If such an exception occurs, and I handle it to retry, if eventually does not succeed, should I call `await base.OnConnectedAsync()` anymore?

**Comment by vicancy** [comment]
@alexiordan  Hi Alex, I think `Hub.OnConnected` just returns `Task.CompleteTask`, you mean the group join action happens in your `OnConnected`?

**Comment by alexiordan** [comment]
Yes, the `await Groups.AddToGroupAsync(Context.ConnectionId, systemId);` takes place in `OnConnectedAsync`.
1. Is anything wrong with that?
2. So I will just call `await base.OnConnectedAsync();` at the end.

**Comment by vicancy** [comment]
Looks good to me, when `await Groups.AddToGroupAsync(Context.ConnectionId, systemId);` fails, it throws and user will fail to connect.
