### ISSUE TITLE
Azure SignalR service (serverless) triggers false disconnected event

### ISSUE THREAD

**Issue by PalashBorhan** [Azure/azure-signalr#642]
I'm using Azure SignalR Service, EventGrid trigger binding used to get the Connected/Disconnected events. I'm seeing a case where EventGrid triggering Disconnected but from the client end, I can see it still receiving SignalR ping messages and also if I try to send any message to that client it receives successfully which means the client is actually connected. Any thoughts for this case?

**Comment by PalashBorhan** [comment]
Also there is another case, the client is power off which means it's disconnected but SignalR service doesn't trigger disconnect event (Client is not properly stopped). Is there any configuration or something can be done in the service or client end to make sure the connected/disconnected events are correct?

**Comment by zackliu** [comment]
Right now, the service doesn't handle ping messages from clients in serverless mode. Which means service detects disconnection events only depends on the underlying TCP close. It can have significant delay before sending `OnDisconnected`. 
We have a tracking issue. #558

**Comment by PalashBorhan** [comment]
Thanks @zackliu, do you have any thoughts for the first case?

**Comment by zackliu** [comment]
Can you comfirm the Disconnected event has the same connectionId as the client you can still use?

**Comment by PalashBorhan** [comment]
Let me verify that. Will get back to you with that information.

**Comment by PalashBorhan** [comment]
Hello @zackliu, any update for the ttl issue?

**Comment by vicancy** [comment]
We made some improvements on the service that once client starts to send out ping, the service starts to track the lifetime of the connection. The feature will be available around the mid of April according to the deployment schedule.

**Comment by PalashBorhan** [comment]
Thanks for the update. Looking forward to it. I have a few questions, We are using [SignalR C++ client ](https://github.com/SignalR/SignalR-Client-Cpp) WebSocket to connect with Azure SignalR (serverless mode), any thoughts how that will work with the CPP client we are using? We are facing another issue that is critical and pushing us to decide whether we stick on using SignalR and other serverless things together or we should look for something else. Problem is, once the client gets connected, normally it receives a ping message every 10 seconds, in some cases, it doesn't receive any ping also it doesn't receive any messages pushed from the Function app through SIgnalR service. There is no disconnection event-grid event for these cases which makes it very unreliable and unstable. Please suggest.

**Comment by vicancy** [comment]
[SignalR C++ client](https://github.com/SignalR/SignalR-Client-Cpp) is the old ASP.NET SignalR. Azure SignalR Service serverless version and the REST API does not support the old ASP.NET SignalR protocol.
This one https://github.com/aspnet/SignalR-Client-Cpp is the one for the new ASPNETCore SignalR

**Comment by PalashBorhan** [comment]
Thanks for your quick update. Let us try that.

**Comment by palashanyconnect** [comment]
Hello, @vicancy is it already deployed?

**Comment by vicancy** [comment]
@palashanyconnect Thanks for the note, should be already deployed. 
I am closing the issue because it should already be fixed. Please feel free to reopen it or leave your comment if you still have concerns about it.
