### ISSUE TITLE
[ArgumentNullException: Value cannot be null. Parameter name: username]

### ISSUE THREAD

**Issue by escobar5** [Azure/azure-signalr#646]
I'm getting an ArgumentNullException in SignalR negotiate, 

> Request URL: http://localhost:1623/signalr/negotiate?clientProtocol=2.1&connectionData=%5B%7B%22name%22%3A%22notificationshub%22%7D%5D&_=1566915910789
> Request Method: GET
> Status Code: 500 Internal Server Error

It seems it has something to do with the claims I'm currently using in my project, I've tried setting a claimsprovider at initialization as the Troubleshooting Guide states:

```
services.MapAzureSignalR(GetType().FullName, options =>
            {
                // pick up necessary claims
                options.ClaimsProvider = (context) => context.Authentication?.User.Claims.Where(...);
            });
```

and filtering out all my claims, but the error persist.

here is the Callstack:

> System.Web.Util.SecUtility.CheckParameter(String& param, Boolean checkForNull, Boolean checkIfEmpty, Boolean checkForCommas, Int32 maxSize, String paramName) +161
>    System.Web.Security.SqlRoleProvider.GetRolesForUser(String username) +59
>    WebMatrix.WebData.SimpleRoleProvider.GetRolesForUser(String username) +54
>    System.Web.Security.RolePrincipal.GetRoles() +208
>    System.Web.Security.<get_Claims>d__4.MoveNext() +65
>    System.Security.Claims.<get_Claims>d__51.MoveNext() +247
>    System.Security.Claims.<get_Claims>d__37.MoveNext() +212
>    Microsoft.Azure.SignalR.<BuildJwtClaims>d__6.MoveNext() +1060
>    Microsoft.Azure.SignalR.AspNet.<BuildClaims>d__13.MoveNext() +372
>    System.Linq.<ConcatIterator>d__59`1.MoveNext() +193
>    System.Security.Claims.ClaimsIdentity.SafeAddClaims(IEnumerable`1 claims) +101
>    System.Security.Claims.ClaimsIdentity..ctor(IIdentity identity, IEnumerable`1 claims, String authenticationType, String nameType, String roleType, Boolean checkAuthType) +12675858
>    Microsoft.Azure.SignalR.AuthenticationHelper.GenerateJwtBearer(String issuer, String audience, IEnumerable`1 claims, Nullable`1 expires, String signingKey, String requestId) +185
>    Microsoft.Azure.SignalR.AuthenticationHelper.GenerateAccessToken(String signingKey, String audience, IEnumerable`1 claims, TimeSpan lifetime, String requestId) +122
>    Microsoft.Azure.SignalR.AspNet.ServiceEndpointProvider.GenerateClientAccessToken(String hubName, IEnumerable`1 claims, Nullable`1 lifetime, String requestId) +116
>    Microsoft.Azure.SignalR.AspNet.NegotiateMiddleware.ProcessNegotiationRequest(IOwinContext owinContext, HostContext context) +596
>    Microsoft.Azure.SignalR.AspNet.NegotiateMiddleware.Invoke(IOwinContext owinContext) +67
>    Microsoft.Owin.Infrastructure.OwinMiddlewareTransition.Invoke(IDictionary`2 environment) +46
>    Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +273
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +182
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +638
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +638
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +638
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +638
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +182
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +180
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
>    System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +483
>    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

**Comment by vicancy** [comment]
The callstack shows that `ArgumentNullException` throws from `WebMatrix.WebData.SimpleRoleProvider.GetRolesForUser`. 

When enumerating `User.Claims` to generate the jwt token, `GetRoles` is called however the `SimpleRoleProvider` throws. I wonder if this is similar to the one described here: http://www.lhotka.net/weblog/CallingRolesGetRolesForUserInAWCFService.aspx

To prevent the issue from blocking negotiate, you can try the following:
```cs
services.MapAzureSignalR(GetType().FullName, options =>
            {
                // specify the claim instead enumerate User.Claims
                options.ClaimsProvider = (context) => new Claim[]
                    {
                    new Claim("customClaim1", "value"),
                    };
            });
```

**Comment by escobar5** [comment]
I did try to set an empty list in ClaimsProvider to see if that was the case, but I still get the error.

**Comment by vicancy** [comment]
How you set an empty list? And what is the callstack of the error when you set an empty list?

**Comment by escobar5** [comment]
@vicancy You where right, I was setting an empty list but using `context.Authentication?.User.Claims.Where(...)` with a where clause that didn't return anything, I guess that line was the responsible of making the call to `WebMatrix.WebData.SimpleRoleProvider.GetRolesForUser`.

I changed it to `new Claim[]` as you suggested and it worked.

Thanks for your help
