### ISSUE TITLE
Potential memory leak related to SymmetricSecurityKey caching

### ISSUE THREAD

**Issue by vas6ili** [Azure/azure-signalr#647]
We've noticed a memory leak in our app after upgrading `Microsoft.IdentityModel.Tokens` to version 5.5.0. Analyzing memory dumps revealed a large number (~100K) of `SymmetricSignatureProvider` and `SymmetricSecurityKey` instances being retained by `Microsoft.IdentityModel.Tokens.CryptoProviderFactory` cache. All `SymmetricSecurityKey` objects had the same key which corresponded to Azure SignalR's access key from connection string (utf-8 encoded). 

Latest version 5.5.0 of `Microfost.IdentityModel.Tokens` enables signature provider caching by default ([release notes](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/5.5.0)) in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/f28d52f9c5455f470cfab8081b86f8e87261a3a0. 
The cache key used is derived from `SecurityKey.KeyId` or `SecurityKey.InternalId` if the former is null, `InternalId` being just a new guid for every instance of that object. Looking at https://github.com/Azure/azure-signalr/blob/986be83e05434b7058fab49a5d83e24912f8b02b/src/Microsoft.Azure.SignalR.Common/Utilities/AuthenticationHelper.cs#L71 a new `SymmetricSecurityKey` instance is created every time with the same key which will add a new cache entry unless a `KeyId` is specified. 

As a temporary fix, we'll disable signature provider caching.

Packages used in our app:
- Microsoft.Azure.SignalR.AspNet@1.0.0
- System.IdentityModel.Tokens.Jwt@5.5.0

**Comment by JialinXin** [comment]
Thank you @vas6ili for providing detailed investigation. The fix will be in the coming release.

**Comment by MZar2019** [comment]
> As a temporary fix, we'll disable signature provider caching.

How exactly do you do that?

I'm using Microsoft.IdentityModel.Tokens.Jwt 6.5.1 and it looks to me like that version has the same problem as described here.

**Comment by vas6ili** [comment]
> How exactly do you do that?

This worked for us at that time as a temporary measure. 

```
CryptoProviderFactory.DefaultCacheSignatureProviders = false;
CryptoProviderFactory.Default.CacheSignatureProviders = false;
```

This code was removed after upgrading to the latest package version, haven't noticed any memory leaks after, though.
