### ISSUE TITLE
Azure SignalR Service is not connected yet, please try again later.

### ISSUE THREAD

**Issue by shyamal890** [Azure/azure-signalr#663]
Here's my code. I am getting error as soon as I try and connect to server.

**Server code:**
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```
            app.UseCors(CorsOptions.AllowAll);
            var hubConfiguration = new HubConfiguration();
            hubConfiguration.EnableDetailedErrors = true;
            app.MapAzureSignalR(this.GetType().FullName, hubConfiguration);
```

**Client code:**

```
        //Getting the connection object
        this.connection = $.hubConnection(this.globals.webApiBaseUrl + 'signalr', { useDefaultPath: false });
        //Enable logging
        this.connection.logging = true;
        (<any>this.connection).EnableDetailedErrors = true;

        //Creating proxy
        this.storyHubProxy = this.connection.createHubProxy('storyHub');
        
        //Track events
        this.storyHubService.startTracking(this.storyHubProxy);

        //Starting connection
        this.connection.start().done( ()=> {
            //console.log("Connection succeeded");
            deferred.resolve();
        }).fail(function () {
            console.log("SignalR Connection failed");
            deferred.reject();
        });;

        this.connection.connectionSlow(() => {
            console.warn('We are currently experiencing difficulties with the connection.')
        });

        this.connection.error((error) => {
            console.error('SignalR error: Name- ' + error.name
                + "\nContext: " + JSON.stringify(error.context, null, 4)
                + "\nMessage: " + error.message
                + "\nTransport: " + error.transport)
        });
```

Error I am getting on client when it tries to connect to server: 
```
SignalR error: Name- Error
Context: {
    "readyState": 4,
    "responseText": "Azure SignalR Service is not connected yet, please try again later.",
    "status": 500,
    "statusText": "error"
}
Message: Error during negotiation request.
Transport: undefined
```

**Comment by shyamal890** [comment]
@realwanpengli @JialinXin

**Comment by vicancy** [comment]
Please follow https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#troubleshooting-guide-3 to see what's the error from the server side when connecting to Azure SignalR. If it can be reproed from localhost, local debugging following https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#troubleshooting-guide-1 also helps.

**Comment by shyamal890** [comment]
@vicancy Server side I am not getting any errors, its only showing the following as stated earlier in the client side: 

```
SignalR error: Name- Error
Context: {
    "readyState": 4,
    "responseText": "Azure SignalR Service is not connected yet, please try again later.",
    "status": 500,
    "statusText": "error"
}
Message: Error during negotiation request.
Transport: undefined
```

**Comment by vicancy** [comment]
The client side error indicates that the server failed to establish server connections with the Azure SignalR service. When app server starts, it tries to establish server connections with Azure SignalR Service, could you capture that server side traffic? For example, the below one is when I set the ConnectionString to an unexist Azure SignalR and 502 returns when I start my server side.

From console:
![image](https://user-images.githubusercontent.com/668244/65475195-2f8f2a00-deb1-11e9-97f6-05f8ef5f3835.png)


From fiddler:
![image](https://user-images.githubusercontent.com/668244/65475114-edfe7f00-deb0-11e9-80ed-5b529f25e5c0.png)

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
