### ISSUE TITLE
.NET Core 3 migration: Hub registration

### ISSUE THREAD

**Issue by Masuzu** [Azure/azure-signalr#676]
Hello,

Should we replace the `UseAzureSignalR` call:
```
app.UseAzureSignalR(routes =>
{
    routes.MapHub<Chat>("/chat");
});
```
with
```
app.UseEndpoints(endpoints =>
    {
        endpoints.MapHub<ChatHub>("/chat");
    });
```
in a similar way as SignalR (https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)?
Or do we still have to use the UseAzureSignalR method?

**Comment by JialinXin** [comment]
Both methods work under AspNetCore 3.0.

**Comment by davidfowl** [comment]
We recommend using UseEndPoints in 3.0 applications.

**Comment by Masuzu** [comment]
Thank you for the answers!
