### ISSUE TITLE
Hub connection re-opens automatically after dispose called

### ISSUE THREAD

**Issue by laurence-accurx** [Azure/azure-signalr#677]
I'm using the management SDK to call my hub from a functions project. The code effectively looks like this with the appropriate connection string and hub name.

```
public static class MyFunction
    {
        [FunctionName("MyFunction")]
        public static async Task Run([TimerTrigger("0 */10 * * * *")]TimerInfo myTimer, ILogger log, ExecutionContext executionContext)
        {
            var connectionString = "";

            var serviceManager = new ServiceManagerBuilder()
                .WithOptions(option =>
                {
                    option.ServiceTransportType = ServiceTransportType.Persistent;
                    option.ConnectionString = connectionString;
                })
                .Build();

            var hub = await serviceManager.CreateHubContextAsync("myhub");

            await hub.DisposeAsync();
        }
    }
```

When I use the persistent transport type, I can see server connections leaking on Azure. When I drill into an individual transaction I see that immediately after the dispose is called and the transport stopped, it opens again,

![image](https://user-images.githubusercontent.com/48315337/66295104-7aae3180-e8e2-11e9-86ba-593bce57350f.png)

I also see this behaviour locally with the above code.

**Comment by realwanpengli** [comment]
Thanks. I'm trouble shooting
