### ISSUE TITLE
Core 3.0 - Server Connections Count

### ISSUE THREAD

**Issue by aloji** [Azure/azure-signalr#678]
Hi,

I have implemented the service using core 3.0 and I see that the number of server connections does not follow the rule described in

https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-messages-and-connections#how-connections-are-counted

I have one application servers and define five hubs in the code.

(1 application servers * 5 hubs * 5 connections per hub) = 25 connections

![image](https://user-images.githubusercontent.com/7695703/66389327-69d7eb80-e9c8-11e9-8fdb-14aa2f814c66.png)

Why does the number of connections vary so much? 

In the last 12 hours the server connection number remains at 39, but never at 25

![image](https://user-images.githubusercontent.com/7695703/66465070-6f910800-ea80-11e9-845f-7860bbd0d7be.png)

Regards,

**Comment by vicancy** [comment]
Thanks for reporting the issue. The document is a bit out-of-date and we will have an update on that. The initial server connection count (when app server starts) is as the document illustrated 25 connections, and while the service is running, there will adjustment to server connections (for example, on-demand created connections or connection close) for better performance and service stability. The principle of server connection adjustment is to minimize the impact on connected client connections.

For your case, you can email me `lianwei@microsoft.com` your instance name to check the detailed reason for this server connection adjustment.

**Comment by aloji** [comment]
Hi @vicancy
Thank you for your response and email support.
Regards,
