### ISSUE TITLE
[QUESTION] Chaos monkey - Can I Restart Azure SignalR ?

### ISSUE THREAD

**Issue by tebeco** [Azure/azure-signalr#691]
Hello,

In an attempt to test our “resiliency and continuous deployment”, I’d love to be able to do the equivalent of the `Restart` button in the `Azure SignalR Service` in the Azure Portal.  

For example in an `Azure Function` so that is could b either a Timed one or a `POST`.
I guess the `Az CLI` would probably have something but not sure if it can be ran in a `Function`.  
I’m really curious on the `Auth` part especially
(It will run in the same situation subscription)

TBF I did not looked a lot, I’m wondering what’s your guidance on that ?

**Comment by juniwang** [comment]
Hi @tebeco,  as you said, Azure SignalR Service does have a `az signalr restart` command.  

For `Functions`, we don't have a specific guidance about how to manage SignalR service. However there is a general idea. You can think of Azure `Functions` as a ordinary `App Service`, that means you can config `Service Principal` (Client Id and Client Secret) in your `Functions` config, and inside your `Functions`, you are able to read them from config, and then authenticate Azure using the SP, and then manage Azure Resources including SignalR via Azure Management SDKs. 

Hope this helps.
