### ISSUE TITLE
Fix Blazor + SignalR

### ISSUE THREAD

**Issue by BrennanConroy** [Azure/azure-signalr#693]
Lets discuss how and when we want to fix the issue described in https://github.com/aspnet/AspNetCore/issues/15128.

There are a few options.
We can fix the issue in a 1.1.2 patch to the SDK by checking the list of protocols for "blazorpack" and excluding it from the list of serialized messages unless it is the only protocol on the list. (This works because blazor clears the list and adds only "blazorpack").

We can wait until SignalR 3.1 ships and apply part of the same change that is going into SignalR by pulling the `HubOptions` from DI and using the "SupportedProtocols" list to determine what protocols to serialize the message to.

I'm willing to help/make the changes if we agree on a solution.

@davidfowl @anurse @vicancy @halter73

**Comment by vicancy** [comment]
The impacted code is here https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs#L225

`ServiceLifetimeManager` is DI'ed in as a Singleton.

> (This works because blazor clears the list and adds only "blazorpack")
Is it that `IHubProtocolResolver.AllProtocols` only contains `blazorpack` when blazor is sending messages? Or there are more to change?

I'd prefer to fix it ASAP with a 1.1.2 patch.

**Comment by BrennanConroy** [comment]
> Is it that `IHubProtocolResolver.AllProtocols` only contains `blazorpack` when blazor is sending messages?

No, `AllProtocols` contains all protocols from DI. But we only want "blazorpack" to be used when it's the only configured protocol. So we can inject the huboptions and inspect the SupportProtocols list and exclude blazorpack except in the case that it's the only protocol listed.

**Comment by vicancy** [comment]
> inspect the SupportProtocols list and exclude `blazorpack` except in the case that it's the only protocol listed

Thanks Brennan, sounds acceptable to me.
