### ISSUE TITLE
Frequent disconnects on server side with Azure SignalR

### ISSUE THREAD

**Issue by ezyhaul** [Azure/azure-signalr#710]
We have a signalR hub hosted on Azure App Service.
The connection between the hub and the Azure SignalR service is often lost and requires us to restart the hub to re-establish the connection.

From app insights we are seeing errors such as,

- Error while sending message to the service, the connection carrying the traffic is dropped. Error detail: Connection ping timeout.
- Error while sending message to the service, the connection carrying the traffic is dropped. Error detail: The connection is not active, data cannot be sent to the service.
- Failed writing message. Aborting connection.
- Connection to the service was dropped, probably caused by network instability or service restart. Will try to reconnect after the back off period. Id: 00ac0013-ff40-489c-957a-65b5a15e9df9

These errors occur especially often on our production enivronment.
We do have a similar setup on our DEV and UAT environments but this does not occur as often or at all.

Load wise is not large, we have recorded a maximum of 48 clients.
Number of messages sent over signalR is also low - about 600 messages per day.

The Azure SignalR service is configured as below,
Pricing Tier - Standard
Unit count - 1
Service Mode - Classic

Recent time frame when these errors occured as below,
2019-10-29T08:10:04.3694968Z - 2019-10-29T08:11:07.2183378Z
2019-10-29T05:01:43.0808824Z - 2019-10-29T05:02:03.6247681Z
2019-10-29T03:53:50.8429272Z - 2019-10-29T03:55:41.8503502Z
2019-10-29T03:02:23.4362921Z - 2019-10-29T03:02:27.7938782Z
2019-10-29T02:21:17.8668271Z - 2019-10-29T02:21:19.8888377Z
2019-10-28T11:08:12.4584386Z - 2019-10-28T11:12:24.3007192Z
2019-10-28T06:54:13.5846495Z - 2019-10-28T06:54:25.6923649Z
2019-10-27T16:59:32.2125307Z - 2019-10-27T17:00:32.7662726Z

Please provide an email so that I may send you the resource name.

**Comment by vicancy** [comment]
SDK has "reconnect" logic, and there is no need to "restart the hub to re-establish the connection". 
For "connection ping timeout", what is the CPU usage of your app server during that period? Where is the app server hosted? Is the network between server and service stable?

Please email me `lianwei@microsoft.com` your instance for a further check.

**Comment by fofaria** [comment]
Hi @vicancy 

We have an application using Azure SignalR and very often we are getting an error:

> Failed to connect to '"(Primary)https://........service.signalr.net"', will retry after the back off period. Error detail: "Unable to connect to the remote server. Unable to connect to the remote server". Id: "......"

The last outage lasted for almost 4h and it's becoming too frequently. After this period it reconnects, but it's starting to reach numbers that are not acceptable for our application.

The Azure SignalR service is configured as below,
**Pricing Tier:** Standard
**Unit count:**  1
**Service Mode:** Classic

is anything we can do about this? thank you

**Comment by vicancy** [comment]
Here explains the cases when server connections can drop and reconnect: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#server-connection-drops
