### ISSUE TITLE
Service crashes very easily with a tiny load

### ISSUE THREAD

**Issue by bentmar** [Azure/azure-signalr#711]
Hi, im currently testing ASR running with 2 units in serverless mode. A function handles the negotiation.

Connecting 300-500 clients over 10 seconds takes the service down 99% of the time. And if it was to handle all connections, alla clients gets disconnected after a minute, when they reconnect they take it down again.

Im running a simple console app to create the connections.

The errors im getting are

"SignalR connection failed to connect: Unable to connect to the server with any of the available transports. (WebSockets failed: The server returned status code '404' when status code '101' was expected.) (ServerSentEvents failed: Response status code does not indicate success: 404 (Not Found).) (LongPolling failed: Response status code does not indicate success: 404 (Not Found).)"

and

"SignalR connection failed to connect: Response status code does not indicate success: 503 (Service Temporarily Unavailable)."

My Function that handles negotiations barely even raises its cpu, and responds instantly on all requests.

tell me what you need to investigate in this issue.

**Comment by bentmar** [comment]
To the left: My Console app
To The right: live from function that negotiates
![ASR](https://user-images.githubusercontent.com/10244000/67783016-e1e67e00-fa69-11e9-8bb4-03b71d9da1b2.gif)

**Comment by zackliu** [comment]
@bentmar Can you send me your ResourceId and the issue happening time via email? I can get more details for you.

**Comment by bentmar** [comment]
@zackliu thanks!

**Comment by zackliu** [comment]
Already discussed in email. Close the issue.

**Comment by mmulhearn** [comment]
It would be nice to know what the resolution to this was.

**Comment by maf1024** [comment]
This is the only google result for the error. I too think that it would be nice to know _something_ about the resolution.

**Comment by bentmar** [comment]
there was no resolution from what i remember. I ended up handling negotiations and publishing messages on an app hosted in an app service plan.
