### ISSUE TITLE
Azure Functions not Listing After Deployment

### ISSUE THREAD

**Issue by Bijus** [Azure/azure-signalr#718]
I have created the Azure Function with Azure Signal Service.

I have used following two functions

[FunctionName("negotiate")]
public static SignalRConnectionInfo GetSignalRInfo(
[HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
[SignalRConnectionInfo(HubName = "chat")] SignalRConnectionInfo connectionInfo)
{
return connectionInfo;
}
}

public static Task SendMessage(
[HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
[SignalR(HubName = "chat")] IAsyncCollector<SignalRMessage> signalRMessages)
{
return signalRMessages.AddAsync(
new SignalRMessage
{
Target = "newMessage",
Arguments = new[] { message }
});

}

After Deployment in Azure, no Function listed in the Azure Functions.

also getting the status, when I deploy the Function APP to Azure

Syncing 0 function triggers with payload size 2 bytes successful.

**Comment by JialinXin** [comment]
Hi @Bijus , would you take a look at [this](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-authenticate-azure-functions#deploy-to-azure-and-enable-authentication) about deployed steps for Azure Function to Azure? Please double check the deployment target and deployment logs.

**Comment by sffamily** [comment]
Hi @Bijus , I cannot find your contact so ping you here. I'm the Product Manager of Azure SignalR Service, and we have a new internal preview for supporting raw WebSocket in serverless scenarios, thinking you might be interested to try it out and offer us some feedback. If you are interested please ping me at zhshang at microsoft dot com.  Thanks. -Zhidi

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
