### ISSUE TITLE
sending to group with groupname ending with "2" is extremely unreliable

### ISSUE THREAD

**Issue by bentmar** [Azure/azure-signalr#720]
Very strange indeed.

-Console app sends to a specific group via servicemanager sdks (1.1.1), 
-Web app acts as negotiator. adding connected clients to groups
-Console app recieves signalr messages

IF the groupname ends with 2, the number of delivered messages are only around 50% and delivered very random.

I have also tried the same but sending with a function with Microsoft.Azure.WebJobs.Extensions.SignalRService v1.0.1 but the result are the same.

a working groupname is uat-full-001.
a probematic groupname is uat-full-002.

Im not sure if its the "2" being in the groupname or the "2" in the end.

our ASR i a Standard Tier.

Please loo into this ASAP!

Thanks!

**Comment by JialinXin** [comment]
Hi @bentmar, please email jixin[at]microsoft.com about your resource id and incident time. Better with your code snippet about sending group message. 
We don't have any logic on parsing groupnames except for length should smaller than 1kb.

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
