### ISSUE TITLE
How to debug EventGrid triggered function on a localhost in Azure SignalR Services context?

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-signalr#729]
[This article ](https://devblogs.microsoft.com/aspnet/azure-signalr-service-now-supports-event-grid/)explains how to leverage Event Grid in the scope of Azure SignalR Services. How one can use [ngrok](https://ngrok.com) and configure Event Grid Subscription to use ngrok as the webhook's end point? [The other article](https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-event-grid-trigger-local) does not help because "Events" menu is not available in the storage supporting the functions. So, apparently there is no way to be able to divert Azure traffic to a localhost machine running ngrok. Any suggestions?

**Comment by zackliu** [comment]
You can use ngrok to achieve this. We have a sample [here](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/EventGridIntegration#build-and-run-the-sample-locally), and I've already validated it.

**Comment by Arash-Sabet** [comment]
@zackliu Thanks for the reply. There is one issue though, when a function is deployed to azure by CI/CD, the function itself is marked as "read only" on azure portal and there is no way to be able to define EventGrid subscription. How can such a subscription be added when the function is in "read only" mode?
