### ISSUE TITLE
Using persistent connection with management SDK takes a lot of memory

### ISSUE THREAD

**Issue by laurence-accurx** [Azure/azure-signalr#733]
Hi,

I had a previous issue with the management SDK automatically re-connecting after calling `DisposeAsync()`

I upgraded to the latest package yesterday and have just tried it out. Now I find that in a simple Azure function which constructs a ServiceManager and calls `CreateHubContextAsync()` that my function app on Azure crashes and locally I find the create call takes about 30-40 seconds to return and sends my memory usage up from 35Mb to almost 1.6Gb. This currently makes it unusable. Any obvious reason what's going on? My code is pretty much as simple as:

```[FunctionName("Test")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequestMessage req)
        {
            var serviceManager = new ServiceManagerBuilder()
            .WithOptions(option =>
            {
                option.ServiceTransportType = ServiceTransportType.Persistent;
                option.ConnectionString = "CONNECTION_STRING";
            })
            .Build();

            await serviceManager.CreateHubContextAsync("testhub");
            return new OkResult();
        }

**Comment by realwanpengli** [comment]
You didn't call DisposeAsync. So there's memory leak.
And using the `IServiceHubContext` in function will create and destroy one websockets connection per http request. Please take a look at this [guide](https://github.com/Azure/azure-functions-signalrservice-extension/tree/wanl/update-doc#use-signalr-service-management-sdk-in-functions), it describes the best practice about using management sdk in Azure functions.

**Comment by laurence-accurx** [comment]
Sorry I should have clarified - in my production code I do call dispose async. This isn't to do with the dispose - as I said above, on calling createhubcontextasync my application hangs for 40 seconds and suddenly consumes over a 1GB of RAM.

**Comment by realwanpengli** [comment]
Could you pass`ILoggerFactory` to `CreateHubContextAsync ` to collect the log?
And what's the request frequency and is the signalr service free or standard tier?
Could you send me your signalr service's resource id and the collected log and memory dump?
My email address is wanl[at]microsoft.com

**Comment by laurence-accurx** [comment]
Emailing you now

**Comment by realwanpengli** [comment]
We found a package is referenced by our SDK and function app which cause the issue.  We are fixing it in #735

**Comment by vicancy** [comment]
Thanks for reporting the issue. It should be fixed in https://github.com/Azure/azure-signalr/releases/tag/v1.2.1

**Comment by oatsoda** [comment]
> You didn't call DisposeAsync. So there's memory leak. And using the `IServiceHubContext` in function will create and destroy one websockets connection per http request. Please take a look at this [guide](https://github.com/Azure/azure-functions-signalrservice-extension/tree/wanl/update-doc#use-signalr-service-management-sdk-in-functions), it describes the best practice about using management sdk in Azure functions.

Updated Link: https://github.com/Azure/azure-functions-signalrservice-extension/blob/wanl/update-doc/docs/use-signalr-binding.md#use-signalr-service-management-sdk-in-functions
