### ISSUE TITLE
Frequent connection drops due to "network instability"

### ISSUE THREAD

**Issue by dbrodie122** [Azure/azure-signalr#742]
Hi,

We're seeing logs on an almost daily basis like this:
 
`Connection to [our Azure SignalR Instance] was dropped, probably caused by network instability or service restart. Will try to reconnect after the back off period. Error detail: 9ce6b551-8cd8-4d1d-94bc-bf0e157bfa6a. Id: The remote party closed the WebSocket connection without completing the close handshake.`

17 instances this morning from: 21 Nov 2019 04:24:37.339 to 21 Nov 2019 04:25:07.284
19 instances this morning from: 21 Nov 2019 06:05:16.659 to  21 Nov 2019 06:14:00.965
18 instances this morning from: 21 Nov 2019 07:27:45.878 to 21 Nov 2019 07:28:27.339

The reconnect logic is in place and the service is never offline for very long, however the frequency of these outages is concerning.

@vicancy I've seen your replies/discussions in issues and I appreciate how on point you've been. Please let me know if you're able to check out the server side logs or if you need additional information =)

**Comment by JialinXin** [comment]
@dbrodie122 Thanks for reporting the issue. Would you email _jixin[at]microsoft.com_ to include your SignalR ResourceId. I'll help check your resource status during the time.

**Comment by dbrodie122** [comment]
@JialinXin Great!  Thank you so much!  I'll send the email.

**Comment by JialinXin** [comment]
@dbrodie122 Replied in the email. Please check and let me know if there's any further questions.

**Comment by dbrodie122** [comment]
Thanks so much!  @JialinXin 's response is below for anyone else with a similar issue:

"If I’m guessing right, your time zone is UTC-5 that matches the connection spike for your resource metric below. And with some investigation, the connection spikes exactly match the time our service restarts. All of the restarts are caused by dependent Redis service temporary unavailable, which will reset all existing server connections as well as related clients. I’ll help update your resource to using sharding Redis which is an improvement in our service in the recent month to mitigate this issue.

As you can observed, the switch time would be quick and back to service quite soon. Ideally, with reconnect logic applied, the impact would be minor. We’ll keep improving the service quality and feel free to create issues on Github when you find any problem. Hope these information helps and let me know if you have any concern."

**Comment by Greg15153** [comment]
Hey @JialinXin, Is this going to be a publicly available feature we can set ourselves anytime soon? We are having the same exact problems with our error logs being spammed with the same message in all our environments. We are also on UTC-5.

**Comment by JialinXin** [comment]
@Greg15153 How's frequency and down period you've experienced? Normally it should be quick and few. Would you send me email _jixin[at]microsoft.com_ for resourceId/time if you've met a lot and let me double check if there's other problems.
