### ISSUE TITLE
[Improvement] AckMessage not throw timeout if related connection is already closed

### ISSUE THREAD

**Issue by JialinXin** [Azure/azure-signalr#750]

**Comment by tebeco** [comment]
hello @JialinXin 

can you enlighten me a bit, does this means ?
* AckMessage SHOULD NOT throw timeout if related connection is already closed <== I suppose this make more sense
* AckMessage WILL NOW throw timeout if related connection is already closed

**Comment by JialinXin** [comment]
@tebeco, we're going to fix as this. 
> AckMessage should not throw timeout if related connection is already closed.

Normally Ack returns `NotFound` when connection close in early stage and there's chance that ASRS processes in the middle and connection closed and `Timeout` is returned to server. We fixed to do a re-check before return `Timeout` to make sure connection still exists. Otherwise, return `NotFound` as it is.

The fix is done in SignalR service side and will be deployed in the coming release, in 1~2 weeks.

**Comment by JialinXin** [comment]
Fixed in latest Azure SignalR Service release. Close the issue.

**Comment by tebeco** [comment]
thx a lot @JialinXin 
to benefits from it, do we need to recreate a new ASRS resource on azure (since products are versioned on azure) ?
I guess not but I'm just trying to be sure

**Comment by JialinXin** [comment]
@tebeco, not require to. We'll refresh the images on existing resources as well. So far, regions in US are updated. And rest would be rolling updated in this week, or up to early next week.
