### ISSUE TITLE
SignalR Azure Service - Python client can send messages but not receive them

### ISSUE THREAD

**Issue by La-Buse** [Azure/azure-signalr#751]
I have a python websocket client that was previously used to establish a connection to a SignalR service hosted on a Web App. Recently I have started using Azure SignalR Service.

`            services.AddSignalR(options =>
            {
                options.MaximumReceiveMessageSize = long.MaxValue;
            }).AddAzureSignalR();`

The python client can still send messages, but not receive them. Also, I don't see any error message either on the client console or on the server output. When using signalr as a javascript library in the browser, there are no problems either.

The python client uses websocket-client version 0.48.0. I am using .NET core 3.0. I am testing this locally with IIS Express in Visual Studio 2019

Any idea on what is causing that problem and how it can be fixed ?

**Comment by vicancy** [comment]
Could you try fiddler to capture the websocket traffic? As you mentioned, JavaScript client works well. Could you compare the traffic between python WebSocket client and JavaScript one to see if there is any difference? Here shares how to capture traffic: https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#tips

Also, I am interested in the python websocket client, as there is no official SignalR python client, are you implementing the SignalR protocol on python WebSocket client yourself including handshake and ping?

**Comment by La-Buse** [comment]
Hi @vicancy,

How can I capture the websocket traffic from the python client ? Your link shows how to capture it from the browser. As for how it is implemented, all I am doing is using the websocket-client python library and passing it the url mapped to the SignalR server app. Everytime I send a message from the python client to the SignalR host, I use the character '\x1e' which seems to be mandatory for the messages to be correctly received. I am not doing anything else for negotiation/handshake.

Also, I started getting these errors with the javascript client using SignalR hosted on my Web App (not using the SignalR Azure service). A few weeks ago I forced the client to use SSE instead of websockets because websockets was not reliable and kept encountering connection errors.

![image](https://user-images.githubusercontent.com/16738639/70465687-798ab380-1a8f-11ea-842c-7e9257dd774d.png)

From the Network tab in devtools, I also this error: 

![image](https://user-images.githubusercontent.com/16738639/70465760-a63ecb00-1a8f-11ea-98b2-c01c8e62d4bc.png)

**Comment by vicancy** [comment]
You can use [Fiddler](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#collect-a-network-trace-with-fiddler-preferred-option) to capture the network trace.

For SignalR, I am afraid a *websocket-client python* is not enough, it has it's own protocols:
1. [TransportProtocol](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/TransportProtocols.md#all-versions):
Specifically, for Azure SignalR to work, client needs to support redirect response: https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/TransportProtocols.md#all-versions
 
1. [HubProtocol](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md) which includes the format for handshake and ping messages.

**Comment by vicancy** [comment]
Please try this pretty full-featured python AspNetCore SignalR client github.com/mandrewcito/signalrcore 😄

**Comment by vicancy** [comment]
Closing the issue, please reopen it if you have any additional concerns.

**Comment by clovett** [comment]
Instead of closing the issue can the SignalR team provide an official SignalR client, I also want to be able to send and receive messages to my SignalR service...  I can do it in C#, why not python also?

**Comment by vicancy** [comment]
Hi @clovett Here is the issue for Python client FYI https://github.com/dotnet/aspnetcore/issues/5331#issuecomment-813911542
