### ISSUE TITLE
Unable to send to Groups with NewtonsoftJsonProtocol and Azure SignalR Service

### ISSUE THREAD

**Issue by thedeukalion** [Azure/azure-signalr#756]
Sending an event from API Controller to a Hub connected to Azure SignalR Service with NewtonsoftJsonProtcol as protcol throws an exception while sending messages to groups.

Error thrown:

> An unexpected error occurred invoking 'SendToGroup' on the server. ArgumentException: An item with the same key has already been added. Key: json

API Controller Code:
```
var groupId = Guid.NewGuid();

connection.On<Guid>(TestHub.SendToGroupEventName, receivedDatAId =>
{
    // Received data for group
    // Received when called with Clients.Caller.SendAsync(SendToGroupEventName, id);
    // Not received when called with Clients.Group(GetGroupId(id)).SendAsync(SendToGroupEventName, id);
});

await connection.InvokeAsync(TestHub.JoinMyGroupMethod, id, cancellationToken);
// throws an exception:
await connection.InvokeAsync(TestHub.SendToGroupMethod, id, cancellationToken);
// wait 2 seconds for assurance
await connection.InvokeAsync(TestHub.LeaveMyGroupMethod, id, cancellationToken);
```

Hub Code:
```
public class TestHub : Hub
{
    public TestHub()
    {

    }
    public static string GetGroupId(Guid id)
    {
        return $"group-{id}".ToLower();
    }

    public const string SendToGroupEventName = "test-event";
    public const string JoinMyGroupMethod = nameof(JoinMyGroup);
    public const string LeaveMyGroupMethod = nameof(LeaveMyGroup);
    public const string SendToGroupMethod = nameof(SendToGroup);

    public Task JoinMyGroup(Guid id)
    {
        return Groups.AddToGroupAsync(Context.ConnectionId, GetGroupId(id));
    }

    public Task LeaveMyGroup(Guid id)
    {
        return Groups.RemoveFromGroupAsync(Context.ConnectionId, GetGroupId(id));
    }

    public Task SendToGroup(Guid id)
    {
        return Clients.Group(GetGroupId(id)).SendAsync(SendToGroupEventName, id);
    }
}
```

Tried with and same result:
- Opened 2 connections (one receiver, one sender)
- Used IHubContext<TestHub> with: `(Hub.Clients.Group(TestHub.GetGroupId(id)).SendAsync(TestHub.SendToGroupEventName, id, cancellationToken);)`
- Created an entirely NEW SignalR Service from scratch that no one had connected to - still the same error!

This seems to be the error causing it:
```
services.AddSignalR()
.AddAzureSignalR(options =>
{
    options.ConnectionString = "<CONNECTION-STRING>";
})
.AddNewtonsoftJsonProtocol(options =>
{
    options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
});
```

Removing
```
.AddNewtonsoftJsonProtocol(options =>
{
    options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
});
```
or 
```
.AddAzureSignalR(options =>
{
    options.ConnectionString = "<CONNECTION-STRING>";
});
```

Fixes the issue. But since System.Text.Json is default now and we can't change that for Azure SignalR - what is the point of adding functionality to change protocols while it's obviously not working? If I change the order doesn't seem to matter either.

Stack traces
>    at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter`1.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)

The same code works previously but slightly different:
```
.AddJsonProtocol(options =>
{
    options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
});
``` 

Packages:
> Package: Microsoft.AspNetCore.SignalR" Version="1.1.0"
> Package: Microsoft.AspNetCore.SignalR.Client" Version="3.0.0"
> Package: Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="3.0.0"
> Package: Microsoft.Azure.SignalR" Version="1.2.1"
> Package: Newtonsoft.Json" Version="12.0.3"

**Comment by vicancy** [comment]
There is already a default "json" protocol, adding another "json" protocol leads to conflict.
Hi @BrennanConroy is there any recommendations from your side when user wants to override the existing "json" protocol?

**Comment by BrennanConroy** [comment]
In 3.0 duplicate entries will now override the previous entry. So multiple "json" protocols will only use the last one registered.

I'm not sure how this all interacts with the service and the mixture of 3.0.0 and 1.1.0 package versions.

**Comment by vicancy** [comment]
@BrennanConroy good to know, I will make the SDK side change to let it be consistent with this overridden behavior.

**Comment by jsheetzati** [comment]
Is there an ETA for a release of this change? This is a roadblock for our migration to .NET Core 3.1. With 2.2 EOL coming up, we would like to stay on a supported version.

**Comment by vicancy** [comment]
The next release is planned EOW  (13th Dec. 2019)
