### ISSUE TITLE
Error: SignalR Service is now in 'Default' service mode. Current mode works as a proxy that routes client traffic to the connected app servers. However app servers are not connected.

### ISSUE THREAD

**Issue by mbinggeli** [Azure/azure-signalr#791]
I am currently using SignalR in a multi-region scenario. I have a Primary EndPoint and a Secondary end-point.  

```
.AddAzureSignalR(options => options.Endpoints = new ServiceEndpoint[] {
                    new ServiceEndpoint(Configuration["SignalR:Connection:Primary"], EndpointType.Primary, "Central US"),
                    new ServiceEndpoint(Configuration["SignalR:Connection:Secondary"], EndpointType.Secondary, "South Central US"),
                });
```

I launch my web application which is an Angular app using '@microsoft/signalr';  

```
  async connect(hub: string, group: string) {
    this.connection = new HubConnectionBuilder()
      .withUrl(`${this.config.env.socket}/${hub}`)
      .withAutomaticReconnect()
      .build();

    await this.connection.start();

    if (group) {
      await this.connection.invoke('JoinGroup', group);
    }
  }
```

I want to test the failure over from the Primary to the Secondary end point and when I "fail" over the Primary (by restarting it in Azure), I get an error in my browsers console log:

**Error: SignalR Service is now in 'Default' service mode. Current mode works as a proxy that routes client traffic to the connected app servers. However app servers are not connected.**

Does anyone know what might be causing this?

**Comment by vicancy** [comment]
Failover requires `active-active` topology, details please refer to https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-disaster-recovery#high-available-architecture-for-signalr-service.

For your case, there are 2 regions, `Central US` and `South Central US`, and there is an app server instance running in `Central US` taking `Central US` Azure SignalR as primary and `South Central US` Azure SignalR as secondary. To make failover work, there should be another app server instance running in `South Central US` taking `South Central US` Azure SignalR as primary and `Central US` Azure SignalR as secondary.

![](https://docs.microsoft.com/en-us/azure/azure-signalr/media/signalr-concept-disaster-recovery/topology.png)

**Comment by mbinggeli** [comment]
Ok thank you very much for clarification!
