### ISSUE TITLE
REST APIs Check User Existence Always Returns Empty Body

### ISSUE THREAD

**Issue by kwasak** [Azure/azure-signalr#793]
The REST API that [Checks user existence in a group](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#check-user-existence-in-a-group) always returns an empty body.

This issue occurs in both of the _Check user existence in a group_ REST APIs:
- https://<instance-name>.service.signalr.net/api/v1/hubs/<hub-name>/users/<user-id>/groups/<group-name>
- https://<instance-name>.service.signalr.net/api/v1/hubs/<hub-name>/groups/<group-name>/users/<user-id>

Request sent:

> GET /api/v1/hubs/REMOVED/users/REMOVED/groups/REMOVED HTTP/1.1
> Host: REMOVED.service.signalr.net
> User-Agent: Paw/3.1.9 (Macintosh; OS X/10.14.6) URLSession/1575.19
> Content-Type: application/json
> Authorization: Bearer REMOVED

For the sake of clarity, the text "Removed" was added for privacy and not actually sent with request

Response received:

> HTTP/1.1 200 OK
> Content-Length: 0
> Server: nginx
> Date: Tue, 07 Jan 2020 18:19:18 GMT
> Connection: keep-alive

I confirmed the user is a member of the group by successfully sending and receiving  a message through the _[broadcast message to group endpoint](https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md#broadcast-message-to-a-group)_.

**Comment by vwxyzh** [comment]
This API is for serverless.
For in default mode:
* a group contains connections, i.e.: 0..n--0..n.
* a connection can belong to a user, i.e: 0..n--0..1.
* no relationship between user and group.

**Comment by Tharindu-Diluksha** [comment]
@kwasak @vwxyzh  I'm having the same problem. I have been working on SignalR service in serveless mode. I'm getting the same empty response when I check the wether my users are in a particular group using the rest API. Any update on this? Thanks

**Comment by Tharindu-Diluksha** [comment]
Okay, guys, it seems like if the user is in the group it's responding with status 200 with an empty body. If not status is 400.

**Comment by sffamily** [comment]
@Tharindu-Diluksha , Hi, I cannot find your contact so ping you here. I'm the Product Manager of Azure SignalR Service, and we have a new internal preview for supporting raw WebSocket in serverless scenarios, thinking you might be interested to try it out and offer us some feedback. If you are interested please ping me at zhshang at microsoft dot com.  Thanks. -Zhidi

**Comment by vwxyzh** [comment]
If a user in the group, it will return 200, otherwise, it will return 404.
Both are empty body.

**Comment by Tharindu-Diluksha** [comment]
@sffamily Hi, I would really love to test that. I have sent an email. I look forward for your reply. Thanks

**Comment by vicancy** [comment]
Closing the issue as Empty body is expected
