### ISSUE TITLE
NegotiateMatcherPolicy cache can keep growing unbounded

### ISSUE THREAD

**Issue by rynowak** [Azure/azure-signalr#794]
The design of `NegotiateMatcherPolicy` is pretty cool, but it's missing one detail. The collection of endpoints (and thus the endpoint instances used as keys in the cache) can change while the app is running. With the current design this can cause the matcher policy to cache an unbounded number of endpoints.

Some suggestions about how to improve this:

- Use the hub type from `HubMetadata` as the key - the set of `Type` objects doesn't change unless the user has written a plugin system
- Listen to the changes on `EndpointDataSource` and reset the cache when the set of endpoints change

Examples (can probably be simplified for your usage):

- https://github.com/dotnet/aspnetcore/blob/master/src/Http/Routing/src/DataSourceDependentCache.cs
- https://github.com/dotnet/aspnetcore/blob/0a1d68b8f375eb979c5722b8bedd57496749b1f8/src/Http/Routing/src/Matching/DataSourceDependentMatcher.cs#L23

Reach out to me or @davidfowl if you want more info

**Comment by JialinXin** [comment]
@rynowak Thanks for pointing this out and providing details.
