### ISSUE TITLE
Getting a response on the existence of a given connection

### ISSUE THREAD

**Issue by kapir** [Azure/azure-signalr#812]
Hi, I'm currently looking at using Azure SignalR as a centralized way for different services in a system to talk to connected clients. 😄 

### My current setup

Using this structure leads to the  services pushing messages to the clients do not know about my web app that sets up the actual hub. This seems to be working very well using the onConnect and onDisconnect hooks in the web app while the services send messages through the managment sdk. The exception is that I would want a simpler way to know if the connection is disconnected. I don't trust the onDisconnected hook as I'm worried that it will over time fail to notify the services about disconnects, especially when scaling to several instances for the web app and the services. I would also prefer that the web app doesn't have to store what clients listen to. I only want to send(and listen) to the events on the services if there are a client that wants this info, there will be a lot of not interesting events and I want to avoid listening to these if I dont have to.

### Feature requested

What I think would be beneficial would be one way to check if a connection is still alive through the managment sdk or the rest-api. I see that getting this kind of response on every send message call might not be beneficial, but a way to check if a connection is alive without having to create a "ping loop" or having to ask the web-app would be great.

I'm assuming that this issue will be classified as a feature-request as it seems that the managment-api does a fire and forget when sending messages to non existing clients, and the rest-api always returns 202 according to the swagger doc(and does not contain a specific client/connection endpoint). 
If i have missed some functionality or my problem could be solved on my end, please let me know 😛 

Thank you for the help! 😄

**Comment by vicancy** [comment]
Could you help me to understand your scenario a little bit more? Do you currently have clients stored? How you "send(and listen) to the events on the services if there are a client that wants this info"? Why "check if a connection is still alive" can help? As the check and the decision are not atomic, there will always be some cases that when check the connection is alive however when do the real stuff the connection dies.

**Comment by kapir** [comment]
Thank you for the response, sorry about my late reply:



> Do you currently have clients stored?

 
Yes, currently the application stores the connections in memory and also tells services that the clients want to listen to specific messages through message routing and parameters. The services also store this information about the connections. On disconnect this information will be updated both in the client and in the services

> How you "send(and listen) to the events on the services if there are a client that wants this info"? 


E.g a new object is created in a list service:Then the service will  send a message to all the clients that subscribes to this type of info.

> Why "check if a connection is still alive" can help? 

I have cases where I don't want the service to listen to anything if there are no clients that need this information. If the onDisconnect hook is not triggered for some reason the service will never stop listening to these events.

Currently my solution for this is a ping that the service needs to do, but this requires implementation in the client and it would be much easier if I could use the Managment sdk to get info about the connection status.

I see that checking if a connection is alive and getting an atomic answer would demand a lot of syncing, in my case there is no need for a very accurate response (as long as i never get "connection is not alive" when it is). The issue I'm trying to solve is to save resources over time by being able to clean up the connections that are disconnected.

**Comment by vicancy** [comment]
> it would be much easier if I could use the Managment sdk to get info about the connection status

Yes makes sense, we are adding the feature request to our plan. It might take one to two months to roll out the support as it includes Azure SignalR service side change and deployment as well as the management SDK updates.

**Comment by vicancy** [comment]
It is now supported, with both `GET` and `HEAD` methods

https://github.com/Azure/azure-signalr/blob/04faa1e8c358910dcd5e7b9dfc192ce0e83bbaf3/docs/swagger/v1.json#L189-L270
