### ISSUE TITLE
CurrentCulture changed to en-US 

### ISSUE THREAD

**Issue by sven5** [Azure/azure-signalr#813]
Hi,

I've already opened an issue [here ](https://github.com/dotnet/aspnetcore/issues/18508).
After establishing a Azure SignalR Connection within my Blazor App the culture is suddenly changed to en-US. 
Could you please look into this?
Is there any way to set set the culture for Azure SignalR service?

Thanks
Sven

**Comment by JialinXin** [comment]
@sven5 It seems I'm not able to repro this. Following your steps in the original issue. I could make it in `German` language both w/o Step2.
> Add Azure SignalR service (edit: this is optional)

Besides your steps, I've made German top language in my browser. Any further idea about how to repro your issue?

**Comment by JialinXin** [comment]
Sorry, it took some delay when connected to ASRS and could be reproduced. I'm looking into this.

**Comment by sven5** [comment]
@JialinXin  Ok thank you. Otherwise I would have created a small repro sample.

**Comment by JialinXin** [comment]
Hi @sven5, just an update that the fix should be in 1.4.0 targeting to release in recent week. Thanks for reporting the issue!

**Comment by sven5** [comment]
Hi @JialinXin 
Thank you for your fix. Looking forward for the update and testing in our environment.

**Comment by sven5** [comment]
@JialinXin 
I was able to update the package and test in our environment was successul.
Thank you! 😃

**Comment by SyedAunHaider** [comment]
@sven5  i had  facing same issue which you were facing, when try to change culture to danish , first time it comes correct then automatically shifted to en-US . Brother its really appreciated if you can help me on this.

**Comment by sven5** [comment]
@SyedAunHaider Hi, as you may have already read here, this issue is **already fixed** in **v1.4.0** of [Azure SignalR nuget package](https://www.nuget.org/packages/Microsoft.Azure.SignalR). 
If you are already using the correct nuget package version then you may face another issue.

**Comment by SyedAunHaider** [comment]
@sven5  Thanks brother I had 1.2.3 version that's why issue there. its now resolved . did you have any fix for attempting to reconnect  server issue of blazor server side.
