### ISSUE TITLE
[QUESTION] Can one azure signalr service instance be used by multiple web app services

### ISSUE THREAD

**Issue by Craig-TSS** [Azure/azure-signalr#825]
Hi, I have been scouring the documentation but have not been able to find any answers to my question.

Basically what I wanted to know is if Azure SignalR (with asp.net core) can handle having multiple separate web apps sharing the same Azure SignalR Service. Let's say I have 3 web apps (A, B, C) which are built from the same code (ie they provide the same service), but they are completely independent of one another, eg they have entirely separate databases and users, but all implement the same services/hubs. Since each server has its own unique URI (eg serverA.azurewebsites.net, serverB.azurewebsites.net) etc, could they all share the one instance of azure signalR. The clients will obviously connect(negotiate) directly to their desired server (A,B or C), and that server will route them to the azure signalr service, Am i guaranteed that the client will then be paired with the server that it negotiated with originally? (keep in mind all 3 servers have the same hub name/endpoints). Further to that, if server A gets scaled out at some point will that still correctly route to a scaled out instance of server A if the original negotiation occured via server A?

The reason I am asking is purely for cost saving reasons. We have a number of independant server instances that need Azure SignalR, however they don't use a lot of connections/messages per day, but they do use more than the free tier. So ideally i would be able to create a single azure signalR service instance on the standard tier and connect all the servers to that. If they eventually get to a point where they start needing more resources than the standard 1 unit tier provides, then i could just scale that up to 2 units. It would save me needing a separate standard 1 unit service instance for each server. 

Hope that makes sense. Thanks.

**Comment by davidfowl** [comment]
As long as the hub names don't overlap then yes.

**Comment by Craig-TSS** [comment]
Thanks for the quick answer. As the web apps are the same actual services (just different instances), the hub names would overlap as they will be the same on all servers. I was hoping that the client connection would get paired to the server negotiating the connection, but it sounds like this is not the case.

**Comment by terencefan** [comment]
```C#
public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR()
                    .AddAzureSignalR(options =>
                    {
                        options.ApplicationName = "app1";
                    }
                );
        }
```

You could specify an `ApplicationName` in the server SDK.

It will help your server generate access tokens like `......?hub=app1_<your_hub>` during negotiation to help our ASRS instances to differentiate connections coming from different server groups.

Sorry for not listing it in our docs. It will be updated later.

**Comment by Craig-TSS** [comment]
Great, thanks terencefan. That sounds like it could resolve the issue. 

Just to clarify though, do you know for sure that it will work or was it just a suggestion to try? ie if I have 3 identical servers (different uri's) with identical hub names with just a different ApplicationName configured for each, that clients are guaranteed to be paired with the server (or its scaled out instances) that they originally connected to (ie negotiation occurred with).

**Comment by vicancy** [comment]
> Just to clarify though, do you know for sure that it will work or was it just a suggestion to try
It should work. It is a feature.

**Comment by vdurante** [comment]
@terencefan sorry for commenting on such an old issue, but I am really lost and looking for some guidance.

Does using the ApplicationName also guarantees that each server will handle only their connections? So, let's suppose I have 2 servers running the exact same code, but one of them inits the ApplicationName as `app1` and the other as `app2`

If a client connects using `app1_your_hub`, then it attempts to invoke a method `MyHubMethod` that exists in both applications, is it guaranteed that it will always invoke the method by app1 instead of app2?

**Comment by vicancy** [comment]
> @terencefan sorry for commenting on such an old issue, but I am really lost and looking for some guidance.
> 
> Does using the ApplicationName also guarantees that each server will handle only their connections? So, let's suppose I have 2 servers running the exact same code, but one of them inits the ApplicationName as `app1` and the other as `app2`
> 
> If a client connects using `app1_your_hub`, then it attempts to invoke a method `MyHubMethod` that exists in both applications, is it guaranteed that it will always invoke the method by app1 instead of app2?

Hi @vdurante, I am not sure how your "client connects using `app1_your_hub`". Basically you don't need to worry about the generated hub, the SDK does this automatically when your client connects to the app server (SDK generates a redirect URL to the Azure SignalR service). If your client negotiates with `app1` app server, yes it is guaranteed that only app1 method `MyHubMethod` will be invoked. 

When ApplicationName is different, these two app servers are considered as different applications, and clients connects to one application (through Azure SignalR) will not be routed to another application.
