### ISSUE TITLE
Error thrown to server side even though broadcast and client connection is success

### ISSUE THREAD

**Issue by hoyanhan** [Azure/azure-signalr#833]
I'm having tons of error on server side as below:

`Failed to connect to '(Primary)https://XXX.service.signalr.net', will retry after the back off period. Error detail: Unable to connect to the remote server. Unable to connect to the remote server. Id: 3d03b4f6-2681-4b50-9f6f-f9b5ad2dce27
`

Even though all of my broadcast on server side and client connection seems to be fine, server is able to broadcast and client is able to receive it via Azure SignalR Service connection.

Please let me know if any additional information is required to assist in troubleshooting.
Thanks.

**Comment by vicancy** [comment]
These are false alarms and should not be shown. We will improve the logs, thanks for reporting the issue. In the meanwhile you can just ignore them .
