### ISSUE TITLE
Make DefaultKeepAliveInterval Configurable

### ISSUE THREAD

**Issue by emilroman** [Azure/azure-signalr#846]
Hi,

We're currently building a web app making use of SignalR. Our clients are devices that don't always have a reliable internet connection (ex: wearables) and resort to long polling as the preferred transport type. Because of this and given the resource limitations of the devices, the time interval between 2 long polling requests can be > 5 seconds. We would really like to use Azure SignalR Service, because of its scaling benefits, but to do so, we need to be able to configure the DefaultKeepAliveInterval.

Would it be possible to make this configurable?

**Comment by vicancy** [comment]
For AspNetCore SignalR it should be natively supported when using Azure SignalR Service. Are you using the old AspNet SignalR?

**Comment by emilroman** [comment]
Thank you very much for your reply @vicancy, we are using AspNetCore SignalR.
On our client devices, we are not able to leverage the existing SignalR client libraries and will build our own according to the specs (https://github.com/aspnet/SignalR/tree/master/specs).

The main issue we faced so far is that SignalR's "HttpConnectionManager.Scan()" method, removes inactive connections after 15 seconds, by default. In our use case, we might sometimes have > 15 seconds between 2 long polling requests, because of the nature of the devices.
After looking at the SignalR source code, we've found a way to get around this, by setting the value of the public "ConnectionOptionsSetup.DefaultDisconectTimeout" property to something else while mapping the hub endpoint:

"endpoints.MapHub<TestHub>("/test", opts =>
{
	ConnectionOptionsSetup.DefaultDisconectTimeout = TimeSpan.FromMinutes(2);
});"

However, this (arguably hack-ish) approach doesn't work when using Azure SignalR Service, which by default, seems to disconnect inactive connections after 5 seconds. After looking at the source code, I wonder if this is due to "ServiceConnectionBase.DefaultKeepAliveInterval" having a hardcoded value of 5 seconds?

**Comment by vicancy** [comment]
Thanks for the detailed explanation, yes you are right, we will look into it.

**Comment by emilroman** [comment]
Thank you very much for your help @vicancy . Looking forward to see if it will be possible to accommodate our scenario.
Just wanted to add that our SignalR clients will not be pinging the server (in order to preserve battery life), which should theoretically update the last seen timestamp, but even if they did, we would still face the same potential network lag issues between 2 consecutive requests (be it long polling or server pings).

**Comment by BrennanConroy** [comment]
FYI, the more recent spec is located at https://github.com/dotnet/aspnetcore/tree/master/src/SignalR/docs/specs. The aspnet/SignalR repo is archived and was moved to dotnet/aspnetcore.

**Comment by vicancy** [comment]
It requires changes from Azure SignalR service side and we are considering exposing the config in the portal. I will get you updated if there is any process on this feature.

**Comment by emilroman** [comment]
Sounds great! Thanks and looking forward to hearing from you

**Comment by vicancy** [comment]
Hi @emilroman , to double confirm
> have > 15 seconds between 2 long polling requests
In my understanding, when the previous long polling request ends, the next long polling request starts immediately. for `> 15 seconds` between 2 long polling requests, how you achieve this? Am I misunderstanding anything here?

**Comment by emilroman** [comment]
Hey @vicancy ,

In our case the devices are resource constrained, which makes them take a lot of time to open an http connection (can be more than 10-15 seconds). They can also occasionaly loose the internet conection and re-establish it again after a short while, which can add up to the time between the polling requests.

**Comment by vicancy** [comment]
It is now configurable through `ServiceOptions`' [MaxPollIntervalInSeconds](https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#maxpollintervalinseconds)
