### ISSUE TITLE
Code samples of using SignalR service with other programming languages like php

### ISSUE THREAD

**Issue by neuvee** [Azure/azure-signalr#862]
Hello,

I have a Laravel/php project and currently I am using PubNub to broadcast messages. PubNub implementation is simple. As soon as someone posts a message, through an ajax call, I get latest data from application server and broadcast to all using pubnub in my js file. I want to use SignalR Service instead of PubNub but I do not see any samples posted anywhere on how to implement it.

In Quickstart section at https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-rest-api , it says "You can choose any programming language" but on GitHub page https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md it says "Azure SignalR Service only supports REST API for ASP.NET CORE SignalR applications."

Will appreciate if someone can clarify if it can be used in similar way as PubNub in a php project or post a sample with PHP/JavaScript.

**Comment by JialinXin** [comment]
Yes, you can choose any language to implement Rest API call, but for client side receive message, only limited version of language is supported: .Net client, JavaScript and Java, see 
https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1.

Maybe you can refer to our Azure Function sample which use azure function to send message and js client to receive message: 
https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/simple-chat/content/index.html#L149

**Comment by JialinXin** [comment]
Generally Azure SignalR Service provides bi-direction real-time communications using WebSocket/Http. Sure your requirement can be achieved using Azure SignalR Service. You can refer to our azure function js version sample: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript. 
With azure function you don't need to implement negotiation yourself and Azure SignalR Service can ensure high availability and load balancing as well as flexible scalability.

**Comment by vicancy** [comment]
Closing the issue as the answer is provided, please feel free to reopen it if you have further concerns.
