### ISSUE TITLE
Azure SignalR Service - Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by erzki** [Azure/azure-signalr#864]
I can't for some reason our application to work with SignalR.

- Negotiate works
- Connect seems to return a 101 status code
- Start seems to work
- Then it tries to reconnect and gets 404

![image](https://user-images.githubusercontent.com/1607185/78263457-45397800-7502-11ea-8df1-46d03ae3066a.png)

This is the error message for the reconnects
`WebSocket connection to 'wss://bokio.service.signalr.net/aspnetclient/reconnect?transport=webSockets&clientProtocol=2.1...' failed: Error during WebSocket handshake: Unexpected response code: 404`

![image](https://user-images.githubusercontent.com/1607185/78263662-8d589a80-7502-11ea-9cbb-57552efb7d96.png)

Edit:
After enabling logging you can see that it closes the websocket connection directly after it says `Now monitoring keep alive...`
![image](https://user-images.githubusercontent.com/1607185/78291031-fd781800-7524-11ea-8fc9-a8a0037c3bee.png)

**Comment by vicancy** [comment]
Can you constantly repro the issue? It might be that your app server-side rejected the connection.
Could you:
1. Enable your server-side log to see if the connection is successfully connected? https://github.com/Azure/azure-signalr/blob/dev/docs/howto-tsg.md#add_logs_server_aspnet
2. You can also enable diagnostic in the portal https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-diagnostic-logs

**Comment by erzki** [comment]
I'm constantly getting this issue.

I think something is failing on your side here.
This is from the Azure SignalR Service logs:
![image](https://user-images.githubusercontent.com/1607185/78356637-36a99a00-75b0-11ea-85c3-96644151b246.png)

**Comment by vicancy** [comment]
"reason" is returned from your app server side, so your app server has some null reference.

**Comment by erzki** [comment]
I solved it. Thanks for your help.

The problem was some HttpContext that was null.
