### ISSUE TITLE
How to do the default SignalR AzureSignalR common use

### ISSUE THREAD

**Issue by yimogit** [Azure/azure-signalr#865]
I have a use netcoreapp3.0 SignalR project, 
 has been a Hub: / testhub using the default SignalR service, 
now want to add a Hub: /azurehub use SignalRAzure service. 
But testing found that after the introduction of SignalRAzure will original /testhub this hub also through Azure service connection 

example code is as follows

``` cs
 public void ConfigureServices(IServiceCollection services)
 {
           services.AddSignalR()
            .AddAzureSignalR();
}
public void Configure(IApplicationBuilder app)
{
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<TestHub>("/testhub");
            });
            app.UseAzureSignalR(endpoints =>
            {
                endpoints.MapHub<AzureHub>("/azurehub ");
            });
}
```

Is there a way to keep the two hubs from affecting each other?

**Comment by yimogit** [comment]
This is a diagram modified using the example
![image](https://user-images.githubusercontent.com/15975059/78331386-82f8d800-75b8-11ea-811d-4438fa41a82c.png)
![image](https://user-images.githubusercontent.com/15975059/78331408-8d1ad680-75b8-11ea-9652-5dfc9ab6061f.png)

**Comment by davidfowl** [comment]
Remove the UseAzureSignalR call, it no longer required in 3.x

**Comment by yimogit** [comment]
Thank you for your reply

But I want to use the original signalr service. When the azure service is not available, I can easily switch back to the original signalr service. Can it be done through rules or policies

**Comment by davidfowl** [comment]
Yes it can be done via configuration. In fact there’s vs tooling that wires it up on publish.

**Comment by yimogit** [comment]
> Yes it can be done via configuration. In fact there’s vs tooling that wires it up on publish.


I am very sorry, may I express has a problem, I am want to make two Hub and different Path using different SignalR service

```
endpoints.MapHub<Azure>("/azure"); //use azure service
endpoints.MapHub<Chat>("/chat");// user aws service or other
```

I should be how to deal with？

**Comment by JialinXin** [comment]
It's not supported to mix use local signalR and Azure SignalR Service in an App Server. Why you need to do this? Azure SignalR service have SLA to ensure availability and you don't need to worry about fallback for this case.

**Comment by yimogit** [comment]
I have to consider that the azure service is temporarily unavailable due to arrears and other reasons. So can service switching be supported in subsequent plans?

**Comment by davidfowl** [comment]
How would you use this feature? It the service goes down what would your code do? How does they affect your application state? 

The connections associated with the service would have to drop, then new ones would be local? 

This isn’t something we plan on doing as it’s both difficult to implement and difficult to reason about. 

Best to host different applications completely

**Comment by JialinXin** [comment]
No, we don't have the plan. Our daily tests show solid performance and you can contact us whenever you found any performance issues. For the temporary unavailable, service will be quickly recovered(in seconds) and app server/partial clients should do reconnect instead of switch to a different hub for minimum impact. However, if you choose to fallback to local SignalR, **ALL** server/clients should reconnect.

**Comment by yimogit** [comment]
OK, I see. Thank you for the answer
