### ISSUE TITLE
Unable to authenticate client app via Azure Functions or MSAL

### ISSUE THREAD

**Issue by flo-sch** [Azure/azure-signalr#866]
Hi,

I am having issues to authenticate SignalR Azure services from a JavaScript application (the client is a SPA written in JavaScript and will be hosted in Azure Storage)

I am the JS developer of the project, working together with a backend developer in charge of the SignalR // Azure config.

The tutorial we have tried to use as reference is the following:
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-authenticate-azure-functions

https://github.com/Azure-Samples/signalr-service-quickstart-serverless-chat/blob/2720a9a565e925db09ef972505e1c5a7a3765be4/docs/demo/chat-with-auth/index.html

We have a first issue with the binding functions not redirecting back to the application:
`{apiBaseUrl}/.auth/login/aad?post_login_redirect_url=${encodeURIComponent(window.location.href)}`
--> After logging in, I am redirected to `{apiBaseUrl}/.auth/login/done#token=[...]`

What is needed to be configured and/or added for that flow to redirect me back to my SPA?

The second issue is related to the `@microsoft/signalr` package.
I tried implementing MSAL.js directly instead, but have a hard time figuring out what is needed for the AccessTokenFactory: where as a frontend developer should I get that access_token from?

```
const connection = new HubConnectionBuilder()
  .withUrl('https://XXXXXX.azurewebsites.net/api', {
    accessTokenFactory: async () => {
      // what service am I supposed to call here?!
    }
  })
  .withAutomaticReconnect()
  .configureLogging(LogLevel.Information)
  .build();
```

I tried to use msal `acquireTokenSilent` // `acquireTokenRedirect`, but the response contains an `access_token` field which is `null`. Potentially, because the scopes I am using `['user.read']` are somehow invalid, but I have a really hard time figuring out what scope is needed for SignalR?

Related issues:
- https://github.com/Azure/azure-signalr/issues/583

**Comment by wanlwanl** [comment]
accessTokenFactory provider the accessToken for Azure SignalR, you can use a negotiate function to handle this, e.g. [sample](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/chat-with-auth/csharp/FunctionApp/Functions.cs#L21). You don't need to generate token in you client, otherwise you have to use the connection string in your client, which  might have security risk.

About the redirecting issue, you can use the login url like [this](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/chat-with-auth/content/scripts/auth.js#L21).

You can try our latest [sample](https://github.com/Azure/azure-functions-signalrservice-extension/tree/dev/samples/chat-with-auth). It contains online demo, deploy guide and detailed explanation.

**Comment by zackliu** [comment]
I think you mixed AAD token with SignalR client access token. You can not require an AAD token through MSAL.js to connect a client.

**Comment by flo-sch** [comment]
Hi, thank you for your responses and examples :)

Yes I have to say I am a bit confused between MSAL and SignalR authentication itself, quite a lot of concepts to learn for me who is totally new to Azure 😅 
We intend to use several Azure services (SignalR and serverless functions at first, backed by some IoT Hub in the backend), so what needs to be authenticated is unclear to me at the moment.

Regarding the redirection issue, this is what I have tried so far, my React authentication context function does +/-:

```
// This is my SPA route handling the post login callback, locally: https://localhost:3000/login/validate
const postLoginRedirectUrl = new URL('/login/validate', window.location.origin);
window.location.href = `https://{api-name}.azurewebsites.net/.auth/login/aad?post_login_redirect_url=${encodeURIComponent(postLoginRedirectUrl.href);
```

When I am working locally, `postLoginRedirectUrl` is `https://localhost:3000/login/validate`.
Once deployed on Azure Storage, it would be something like `https://{blob-name}.web.core.windows.net/login/validate`, and if we add a CDN later on and/or a custom domain it would be something else.

So far I faced 2 cases that I could not completely reproduce in a certain way, but I certainly never managed to get successfully redirected to my SPA:

1. (Most common one) the parameter is ignored: after a successful login, instead of getting redirected back to `https://localhost:3000/login/validate`, I am redirected back to:
`https://{api-name}.azurewebsites.net/.auth/login/done#token={the stringified token}`
(This seems to be the default Azure behaviour when I do not set the `post_login_redirect_url` parameter)

![azure-post-login-done-page](https://user-images.githubusercontent.com/1577155/78762737-8c04f300-7984-11ea-81fa-ab168d0502a2.png)

--> The "return to the website" link here targets `https://{api-name}.azurewebsites.net/`, which is a placeholder page for Azure function, not my application

2. (Sometimes, uncertain when nor why) the parameter is taken into account, but instead of getting redirected back to `https://localhost:3000/login/validate`, my SPA URL is concatenated as a page of the API, which of course is invalid and result in a 404:
`https://{api-name}.azurewebsites.net/.auth/login/aad/https%3A//localhost%3A3000/login/validate`

Is there anything that needs to be configured somewhere in Azure for that `post_login_redirect_url` to work, like whitelisting those URL somewhere?

I do not work on the backend // Azure configuration myself, but is there any kind of version we need to use on the binding `.auth` function to make that working?

Are there common environment-related issues that needs to be taken into account (... like the fact that I am using Brave Browser which natively prevents cross-site cookies? I have disabled those, but could that be an issue I - and more importantly the customers - need to be aware of?)

**Comment by wanlwanl** [comment]
> 1. Most common one) the parameter is ignored: after a successful login, instead of getting redirected back to https://localhost:3000/login/validate, I am redirected back to:
https://{api-name}.azurewebsites.net/.auth/login/done#token={the stringified token}
(This seems to be the default Azure behaviour when I do not set the post_login_redirect_url parameter)

Expected redirect is `https://{blob-name}.web.core.windows.net/login/validate`. I think you didn't use a function proxy, so the you can't be redirected to your azure storage. Try to setup proxy like [this](https://github.com/Azure/azure-functions-signalrservice-extension/blob/dev/samples/chat-with-auth/csharp/FunctionApp/proxies.json).

I strongly suggest try the [chat with auth SPA sample](https://github.com/Azure/azure-functions-signalrservice-extension/tree/dev/samples/chat-with-auth), all you need is to change the name in the scripts and use Azure CLI to deploy. The deployment should be simple. 

> 2. Sometimes, uncertain when nor why) the parameter is taken into account, but instead of getting redirected back to https://localhost:3000/login/validate, my SPA URL is concatenated as a page of the API, which of course is invalid and result in a 404:
https://{api-name}.azurewebsites.net/.auth/login/aad/https%3A//localhost%3A3000/login/validate

Could you share the minimal reproduce repo? I think the issue might be on SPA side.

**Comment by flo-sch** [comment]
Hi @wanlwanl , thanks for the explanation, indeed I had never heard of a that "functions proxy", I guess that was the missing part :)

I guess there is no way to have that working locally though?
(I mean for me to work on my SPA locally, while still calling the backend in Azure?)

**Comment by wanlwanl** [comment]
Hi @flo-sch The sample is setup with azure function authentication. For authentication part, you need to call the backend in Azure. But the function can be run locallly, you can call the API locally.

**Comment by flo-sch** [comment]
Okay, thanks for clarifying :)
Will close this for now, I think I have the answers I need!
