### ISSUE TITLE
JWT token has some additional claims in response to negotiate request

### ISSUE THREAD

**Issue by JakubSurfer** [Azure/azure-signalr#869]
Hi,

I'm establishing signalR connection using typescript client library: 

`const connection = new HubConnectionBuilder()
        .withUrl(url,
          {
            accessTokenFactory: () => token
          })
        .configureLogging(!environment.production ? LogLevel.Information : LogLevel.None)
        .build();`

According to docs : [ https://docs.microsoft.com/pl-pl/azure/azure-signalr/signalr-concept-internals#client-connections](url)

I expected to receive a JWT token the same that I used to establish connection. At least it had been the same before I switched to use azure signalr from hosted by ASP .net core app. What I have found out is that JWT token from negotiate's response has some additional claims. 
Why is it like that ?

**Comment by vicancy** [comment]
Azure SignalR SDK adds some claims for the Azure SignalR Service to leverage, https://github.com/Azure/azure-signalr/blob/dev/src/Microsoft.Azure.SignalR.Common/Utilities/ClaimsUtility.cs#L37

Do you have any concerns about these claims?

**Comment by JakubSurfer** [comment]
In the Hub I'm using in OnConnectedAsync() the token is re-used for some additional calls and due to it's changed I get an error. Is there a way to keep the token unchanged ?

**Comment by vicancy** [comment]
> In the Hub I'm using in OnConnectedAsync() the token is re-used 
How you get the token from `OnConnectedAsync()`?

**Comment by JakubSurfer** [comment]
from query string

**Comment by vicancy** [comment]
When using Azure SignalR, the workflow is:
1. client negotiate with your app server with the access_token generated by your `accessTokenFactory`
2. app server auth the client based on the token
3. app server generate **another** JWT token on the rules that Azure SignalR requires using the claims it gets from the authed client
4. app server sends the generated JWT token for **Azure SignalR** to client
5. client uses the token to negotiate with Azure SignalR
6. Azure SignalR auth the client and pass through the client along with the claims to app server

So the token client uses to connect to the app server is a totally different one from the one fetched from `OnConnectedAsync()`. 

If you'd reuse the client-generated token, one way is to preserve the token inside some other query string (not a secure way), one way is to re-sign the token when `OnConnectedAsync` using the claims ( more secure way).

**Comment by gustavodaquino** [comment]
@vicancy, on a JWT workflow, what information is used to identify the user registered? Any property included inside the JWT body? Can I choose one of them, for example sub or jti?

**Comment by vicancy** [comment]
@gustavodaquino You can implement your `IUserIdProvider` https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#IUserIdProvider to customize the user

**Comment by vicancy** [comment]
Closing the issue, please reopen it if you have any additional concerns.
