### ISSUE TITLE
Group add and removal should complete the task when the user is in the group

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-signalr#87]
Today we're not waiting for the connection to be added to the group before returning from the method. That's one of the SignalR contracts that isn't being respected right now by the service and sdk. It might require a protocol change to send ACKs back (like we do in redis).

**Comment by davidfowl** [comment]
@xscript @chenkennt we need to make sure this is the case before GA. No acks actually need to come back to the application. It can be done all on the service side itself.

**Comment by xscript** [comment]
Yeah, this is the next issue I plan to fix. But my fix requires a new message type to send ACK back to application. Let's sync offline about your idea.

**Comment by xscript** [comment]
Fixed in [the latest Service SDK](https://www.nuget.org/packages/Microsoft.Azure.SignalR/1.0.0-preview1-10200).
