### ISSUE TITLE
Seem to get frequent disconnects between application server and ASRS

### ISSUE THREAD

**Issue by laurence-accurx** [Azure/azure-signalr#888]
Hey,

We use both the REST API from the management SDK and also having an application server connected to our ASRS. During the day we have about 50k clients connected to ASRS. We seem to get quite frequent (much more than I would expect) disconnects. Over the last 7 days I've had 28k exceptions of ```Microsoft.Azure.SignalR.Common.ServiceConnectionNotActiveException```

on Application Insights logging.

![image](https://user-images.githubusercontent.com/48315337/80089240-83e8ae00-8555-11ea-8173-0fbbe5c83462.png)

Are we doing something wrong? In our start-up code we just call 
```
 services.AddSignalR().AddAzureSignalR();
```

so nothing fancy.

Have also had 147 logs saying 

Connection to '"(Primary)https://OURDOMAIN.service.signalr.net"' was dropped, probably caused by network instability or service restart. Will try to reconnect after the back off period. Error detail: "c17984f2-2d05-424a-934d-67f722d910cd". Id: "The remote party closed the WebSocket connection without completing the close handshake.. The remote party closed the WebSocket connection without completing the close handshake.".

And had 36 over last week saying 

Connection "GUID" received error message from service: "Service reloading, please reconnect."

We're on version 1.2.3 of the SDK.

**Comment by JialinXin** [comment]
@laurence-accurx , Thanks for reporting the issue. Would you email **jixin[at]microsoft.com** for some details about your ResourceId and more accurate incident time with time zone information. App Server side logs are also preferred if you have. 

Normally `service reload` means there's backend maintenance that should be quickly auto recovered in seconds and with reconnect logic in client side together with our service side graceful shutdown, clients would be rarely affected. We'd like to help take a further investigation in your case if it's working as expected.

**Comment by JialinXin** [comment]
@laurence-accurx Didn't receive any email related to this. Is this issue still repro? Do you need any further help on this?

**Comment by laurence-accurx** [comment]
Sorry for delay - will email you some details now.

**Comment by JialinXin** [comment]
@laurence-accurx Replied in email. Let me know if you have any further questions.

**Comment by lenhatnguyen** [comment]
I also had the same problem. Could you please guide me to solve your problem ?

**Comment by JialinXin** [comment]
@lenhatnguyen, you can enable [diagnostics logs](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-diagnostic-logs) for a rough check on the service connection logs, including connection close reasons. The issue for the original case is due to sharp connection drops triggers our connection rebalancing, and it doesn't have much impact.

If you are still not able to find out much information, feel free to send some details to jixin[at]microsoft.com, resourceId, incident time(UTC preferred).

**Comment by lenhatnguyen** [comment]
Thank, I will enable diagnostics logs to check the problem, if i can't resolvce it , i will send mail to you .
