### ISSUE TITLE
Application Insights telemetry correlation and Azure SignalR

### ISSUE THREAD

**Issue by dyskette** [Azure/azure-signalr#905]
Hello.

I have a Net Core 2.2 application using signalr and application insights. When I use it without Azure SignalR service, all telemetry is correlated to each other. 

![image](https://user-images.githubusercontent.com/6687927/81618099-4cc72900-93ac-11ea-9aae-289c7c432162.png)

However, when using Azure SignalR Service they don't correlate because none have details like operation id or parent id. This means I cannot group it into requests and dependencies.

Is this expected behaviour or it's something else? What could I do to fix it?

**Comment by vicancy** [comment]
> when using Azure SignalR Service they don't correlate because none have details like operation id or parent id

What event do you expect to correlate? When a client connection is connected or disconnected? Do you expect logs inside a Hub is correlated to something else?

**Comment by dyskette** [comment]
In this case, the request or event from when the client connection was created would be the parent, similar to regular SignalR where it sets the "GET /hub" request as the parent. The rest of the logs for that client connection would be associated to that parent.

```
- Client connection 1 created
    - Log 1
    - SQL dependency 1
    - Exception 1
    - HTTP dependency 1
- Client connection 2 created
    - Log 1
    - SQL dependency 1
    - HTTP dependency 1
    ...
```

I don't expect logs to be correlated to anything additional when I set `UseAzureSignalR()` than when I set `UseSignalR()`.

**Comment by JialinXin** [comment]
Hi @dyskette, sorry for the late notice. I'm looking into this and try to repro. Would you help explain your scenario a little more. What detail actions are you user Application Insights to track? It would be helpful if you could share some code snippet.

**Comment by JialinXin** [comment]
Hi @dyskette, I did some tests to compare the AI logs(requests) on our ChatSample working on local/Azure SignalR, it seems the results are same. May I know what code do you add to correlate the operations? Seems simply adding AI dependency, it will auto generate an operation_Id for each HTTP request.

**Comment by vicancy** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
