### ISSUE TITLE
EventGrid > Connected event ignoring overridden accesstoken

### ISSUE THREAD

**Issue by simonthebear** [Azure/azure-signalr#918]
During the negotiate function, I am overriding the accesstoken for SignalR Service (serverless) to add some additional claims.

```
var claims = new List<Claim>
{
    new Claim("SomeNewClaim", "somevalue")
};

var clientAccessToken = serviceManager.GenerateClientAccessToken(Constants.HubName, "12345", claims);

var connectionInfo = binder.Bind<SignalRConnectionInfo>(new SignalRConnectionInfoAttribute
{
    HubName = Environment.GetEnvironmentVariable("HubName"),
    UserId = "54321",
    ClaimTypeList = new [] { "SomeNewClaim" },
    IdToken = clientAccessToken
});

connectionInfo.AccessToken = clientAccessToken;
```

In the browser, this results in the websocket connection being requested and I can see my access token being sent in the access_token parameter.  Ignore the rubbish code above, as you can see I've been trying in all different ways to get this set correctly!

EventGrid publishes an event for the new connection but the SignalRConnectionInfo doesn't contain my access token.  Instead, it's a much shorter one, I suspect the one it would have used regardless.  Is it possible to have the access token which was supplied to the wss:// request?

Just to be clear, the negotiate azure function succeeds, the access token I setup is then sent to mydomain.service.signalr.net/client/?hub=myhub endpoint and subsequently the wss connection....  but even after that, the event fires from EventGrid and the SignalRConnectionInfo access token is just something else, not the one I supplied!

What am I doing wrong?

**Comment by zackliu** [comment]
In the current architecture with Event Grid, we doesn't pass the `claims` to Event Grid, so you cannot get claims you set from Event Grid's message. 
We're now releasing a new feature that can totally meet your requirement and get rid of Event Grid. The new feature that allow you send messages (including `OnConnected` but not only limit to that) from client to your serverless handler (e.g. Azure Function) proxied by SignalR Service. As all the messages are proxied by SignalR Service, you can get the `claims` you set in access token from all kinds of call from SignalR Service.

We have a full functionality sample in https://github.com/Azure/azure-functions-signalrservice-extension/tree/master/samples/bidirectional-chat. And the new version function binding can support the feature https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.SignalRService/1.2.0.

**Comment by simonthebear** [comment]
Thank you, that's good news, I needed to be able to invoke a method on the hub, great timing!

However, it doesn't fully solve my problem with the Connected/Disconnected events.  

When OnConnected fires from EventGrid, I need to then make a single API call and pass a token.  Likewise with OnDisconnected (we need to perform an action elsewhere when users connect/disconnect).

Up to now, I've got around this issue by placing the token I need in the UserId(!) during negotiation, like this:

```
var userId = ValidateMyToken(passedInTokenFromHeader);

var connectionInfo = await binder.BindAsync<SignalRConnectionInfo>(new 
    SignalRConnectionInfoAttribute
            {
                HubName = Constants.HubName,
                UserId = $"{userId}|{passedInTokenFromHeader}"
            });
```

Then, when EventGrid fires the connect/disconnect events, I can split the userId and token and use it.

However, hacking the UserId in this way this stopped me being able to send to a specific userId elsewhere of course, so I had to add each user to a group for that.  (Other parts of the system publish events which are handled by an EventGridTrigger that sends signalr messages to clients.)

Is there any other way I can get that token from the negotiate event injected into the connected/disconnected Event Grid message?

**Comment by zackliu** [comment]
The new function binding does not only can invoke methods, but also can get fired with Connected/Disconnected events **automatically** just like Event Grid. So, it can fully cover the functionality that the Event Grid can provide now. Besides, the newly Connected/Disconnected event (directly through new function binding rather than Event Grid) can carry all the claims you set in negotiate. I think that can fully resolve you problem.

Actually, the new function binding leverages a new feature called "Upstream" supported by SignalR Service. Basically, it can send messages and fire connected/disconnected events in Serverless mode. The feature is totally available but the detail documents are still on going. 
From sample's README, you can see there's a step to set upstream in SignalR Service. It can be only set through `az cli`.

**Comment by simonthebear** [comment]
Excellent, thank you!  I'll give it a try.

**Comment by simonthebear** [comment]
I can't seem to get SignalRTrigger OnConnected() to be executed after a successful websocket connection. :(

```
[FunctionName(nameof(OnConnected))]
public async Task OnConnected([SignalRTrigger]InvocationContext invocationContext, ILogger logger)
{
    await Clients.All.SendAsync("someClientMethodOnConnected", invocationContext.ConnectionId);            
    logger.LogInformation($"{invocationContext.ConnectionId} has connected");
}
```

I've also tried invoking a new hub method from a client to see if that works, but I get this response on the websocket:

`{"type":3,"invocationId":"0","error":"Invocation failed, status code 404"}`

The webhook defined in the upstream template appears to be reachable, returning 401 with the wrong key and 500 with a valid key.  I'm assume that gets a payload in real life.
`https://myapp.azurewebsites.net/runtime/webhooks/signalr?code=myKey`

I've added the ServerlessHub base class, referenced 1.2 for the function code and using v1.0.3 js client.  I've double-checked the keys, connection string, resourceId for SignalR

Negotiate works ok.

I'm going to try setting up the chat sample instead, but in the mean time if you see this and have any ideas I'd appreciate it. 👍

**Comment by simonthebear** [comment]
The bidirectional-chat sample works 100%.  

All I can think at the moment is that I set the sample up in westeurope whilst my own project is in northeurope.  I also published the sample using the CLI, but Visual Studio for my own project.  I'll find out why it's not happening and update here.

**Comment by zackliu** [comment]
Does the SignalR Service that hosing your own project is an old resource. The SignalR Serivce got a internal update to support the upstream feature, and if there's a chance that the resource updated failed, then it can not use upstream successfully. So, maybe you can try to create a new SignalR Service resource to have a try.

**Comment by simonthebear** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️

Just realised that I don't need to (and shouldn't be) using the binder or generating an access token, etc.  I still had that old code in the negotiate method.  It's all working now, the client can call hub methods, claims are working, OnConnected and OnDisconnected work.  

Thank you 👌
