### ISSUE TITLE
ServerlessHub - Clients.GroupExcept() not available yet?

### ISSUE THREAD

**Issue by simondupdr** [Azure/azure-signalr#933]
Attermpting to call Clients.GroupExcept() throws an exception with the message "Specified method is not supported.".

Are there any plans to implement this for the SignalR Service in Serverless mode?

**Comment by zackliu** [comment]
`GroupExcept` is not supported in REST APIs according to the spec https://github.com/Azure/azure-signalr/blob/dev/docs/rest-api.md 
We can consider to add it but we don't have a roadmap right now.

**Comment by vwxyzh** [comment]
Following should be supported:
* Group broadcast except: [api](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#broadcast-a-message-to-all-clients-within-the-target-group)
* Broadcast except: [api](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#post-broadcast-a-message-to-all-clients-connected-to-target-hub)

**Comment by vicancy** [comment]
REST API already contains `GroupExcept` https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#post-broadcast-a-message-to-all-clients-within-the-target-group., ManagementApi needs an update.

**Comment by AndreasFurster** [comment]
That feature is also not documented in the Microsoft docs:
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-rest-api#broadcast-to-everyone

**Comment by zwymer** [comment]
Please implement this functionality. It is horrible that we cannot use something so basic.
