### ISSUE TITLE
How to check if user is online in Azure SignalR serverless mode

### ISSUE THREAD

**Issue by jonx** [Azure/azure-signalr#935]
Hi,

My goal is to create a chat app that can save a message when the user is offline and distribute the message the next time the user comes back online.

The missing piece in my Azure Function is how to check if a user is online before sending him the message? Note that this question is not about dealing with the offline and distribution challenge. That's not a problem. Only how to find out somehow that I need to store my message and distribute later.

My code so far is very classic and works:
```
public static class Talk
    {
        [FunctionName("Talk")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(
                AuthorizationLevel.Anonymous,
                "post",
                Route = "talk")]
            HttpRequest req,
            [SignalR(HubName = "simplechat")]
            IAsyncCollector<SignalRMessage> questionR,
            ILogger log)
        {
            try
            {
                string json = await new StreamReader(req.Body).ReadToEndAsync();
                dynamic obj = JsonConvert.DeserializeObject(json);
                var jObject = new JObject(obj);

                req.Headers.TryGetValue("x-ms-client-principal-name", out var sender);

                var recipient = obj.recipient.ToString();

                await questionR.AddAsync(
                    new SignalRMessage()
                    {   
                        UserId = recipient,
                        Target = Constants.MessageName,
                        Arguments = new[] { jObject }
                    });
...
```
Is there a way to verify a user is online in there?

A way to see that the message was not delivered would also do the trick.

I tried using the following to get access to the missing pieces but this throws an exception. Can this be potentially used from inside an Azure Serverless Function?
```
var serviceHubContext = await StaticServiceHubContextStore.Get("AzureSignalRConnectionString").GetAsync("simplechat");
                    log.LogInformation("C# HTTP trigger function processed a request.");
                    await serviceHubContext.Clients.All.SendAsync("newMessage", "LOL!");
```

I prefer not to keep a user list myself through on/disconnect because it's not completely reliable and there must be an easier way, right?

Maybe using the rest api is an option but I have no idea how to do that in case someone has an exemple.

Thanks a bunch for your lights.

BTW: Can you mix ... : ServerlessHub stuff and static Azure Functions? Like for example using this to distribute the message:
```
public class SignalRTestHub : ServerlessHub
{
    [FunctionName("SignalRTest")]
    public async Task SendMessage([SignalRTrigger]InvocationContext invocationContext, string message, ILogger logger)
    {
        ...
    }
}
```
I tried but it seems only the code in there is ignored. 

If someone has an Azure ServerlessHub sample and Xamarin clients, please share.

Thanks.

**Comment by vicancy** [comment]
We do have REST API for checking if the user has any connected connections https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#get-check-if-there-are-any-client-connections-connected-for-the-given-user We haven't integrated this feature into the Mangement API yet (https://github.com/Azure/azure-signalr/issues/922), for now, you can have a REST API call to get the result. (cc @wanlwanl )

**Comment by jonx** [comment]
Thanks for your advice @vicancy much appreciated.

I've done that and it seems to be working quite nicely.

It would be really nice to get this feature added to the Management API. It's quite some code including non trivial code to generate the access token. This or some way to verify that my message was/can be delivered or not.

(Also an example of how to call the Management API from inside Azure Functions would be nice.)

If anyone is interested by the code. I used code from this sample https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Serverless

I added this method to ServerHandler.cs (+ some minor code adjustment IIRC)
```
public async Task<bool> IsUserOnline(string userId)
        {
            string url = GetSendToUserUrl(_hubName, userId);
            if (!string.IsNullOrEmpty(url))
            {
                Client.DefaultRequestHeaders.Authorization =
                   new AuthenticationHeaderValue("Bearer", _serviceUtils.GenerateAccessToken(url, _serverName));

                var response = await Client.GetAsync(url, HttpCompletionOption.ResponseHeadersRead);
                if (response.IsSuccessStatusCode)
                {
                    return true;
                }
            }

            return false;
        }
```
From inside my azure Function I call this like that:
```
var server = new ServerHandler(connectionString, "simplechat");
                if (await server.IsUserOnline(recipient))
                {
                    await SendMessageToClient(questionR, "Message delivered");
                }
                else
                {
                    await SendMessageToClient(questionR, $"User {recipient} is not online.");
                }
```
