### ISSUE TITLE
InvalidOperationException after upgrading to ASP.NET Core 3

### ISSUE THREAD

**Issue by Schaemelhout** [Azure/azure-signalr#940]
On ASP.NET Core 2, our configuration looked like this:

```csharp
services.AddSignalR().AddAzureSignalR(this.appSettings.SignalR.ConnectionString).AddJsonProtocol(options =>
{
    options.PayloadSerializerSettings.Converters.Add(new StringEnumConverter());
});
```
```csharp
app.UseAzureSignalR(routes =>
{
    routes.MapHub<GeneralHub>("/generalhub");
});
```

After upgrading to ASP.NET Core 3, we changed our configuration according to [this documentation](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core#add-azure-signalr-to-the-web-app).
Specifically:

> For ASP.NET Core 3+, replace the above code with:
> ```csharp
> app.UseFileServer();
> app.UseRouting();
> app.UseAuthorization();
> 
> app.UseEndpoints(routes =>
> {
>     routes.MapHub<Chat>("/chat");
> });
> ```

So we removed the call to `UseAzureSignalR` on `IApplicationBuilder`, but now we get the following error:

**`System.InvalidOperationException: 'AddAzureSignalR(...)' was called without a matching call to 'IApplicationBuilder.UseAzureSignalR(...)'.`**

Is there something missing in the documentation? Do we not need the call to `AddAzureSignalR` on `IServiceCollection` anymore? We need an `ISignalRBuilder` to be able to configure our `PayloadSerializerSettings`...

**Comment by vicancy** [comment]
Which SDK version are you using? Try the latest one for `.NET Core App 3.0`

Only `AddAzureSignaR` is needed for ASP.NET Core 3+. Here is a sample code for it https://github.com/Azure/azure-signalr/blob/dev/samples/ChatSample/ChatSample/Startup.cs#L18

**Comment by Schaemelhout** [comment]
Turns out I wasn't using the latest version of the SDK. Thanks!
