### ISSUE TITLE
Failed to connect to '(Primary)https://***-dev.service.signalr.net' - http status code 400

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-signalr#944]
### Describe the bug

I can see multiple repeating logs from my aspnet core application, indicating a problem connecting to azure signal-r.

Here are the logs that repeat in a cycle (most recent first)

>
Failed to connect to '(Primary)https://foo-dev.service.signalr.net', will retry after the back off period. Error detail: The server returned status code '400' when status code '101' was expected.. The server returned status code '400' when status code '101' was expected.. Id: 67e26bc1-103b-4ae0-95c3-f21293b2354c
29 Jun 2020 17:43:55.860
 Transport is stopping.
29 Jun 2020 17:43:55.803
 Starting transport. Transfer mode: Binary. Url: 'wss://foo-dev.service.signalr.net/server/?hub=43e1b6f6e3f14c31b4ddbccf011c9b0d_webnotificationhub&cid=67e26bc1-103b-4ae0-95c3-f21293b2354c'.

How do I work out why this is failing with an error 400? I can't see any further details in the log output.

My startup contains code like this which prefixes hub names:

```

 s.AddSignalR((o) =>
                {
                    o.EnableDetailedErrors = true;
                })
                .AddAzureSignalR((a) =>
                {
                    a.ApplicationName = context.Tenant.GetPartitionKey(); // segregate hubs by tenant.
                    a.ConnectionString = tenantConfig[signalRConnStringKey];
                });
```

The partition key returns a GUID formatted like so:

```
return tenant?.Guid.ToString("N");
```

It seems to work locally. I only see the above error logs in an azure app service for windows containers environment.

### Further technical details
- Your Azure SignalR SDK version
>         <PackageReference Include="Microsoft.Azure.SignalR" Version="1.*" />

- Your SignalR Client SDK version

>         <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.5" />

**Comment by vicancy** [comment]
Thanks for reporting the issue, the failed request, having `ApplicationName` starting with numbers which are not allowed, so 400 bad request returns. To quickly mitigate your issue, you can add a char prefix to the `ApplicationName` and avoid non-alphabetic chars inside the name, e.g. `a.ApplicationName = "app" + context.Tenant.GetPartitionKey();`

`ApplicatioName` should follow the same naming restriction as hub names however the SDK missed the validation. This is a bug we will fix in the next SDK release.
