### ISSUE TITLE
WebSocket connection to '' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by g7prakash** [Azure/azure-signalr#958]
### Describe the bug
i am unable to explain more clear, i configured my application with Azure SignalrR Service, after sometime i got error couldn't connect to server after resolving those,I got this in my console.

### To Reproduce
When we run our application and hold for 15-20 minutes its throws back

### Exceptions (if any)
![ErrorSignalR](https://user-images.githubusercontent.com/29399989/86943670-5bd81680-c164-11ea-8825-d3b0d952873c.png)

### Further technical details
- Your Azure SignalR SDK version - 2.4.1.0
- Your Server ASP.NET MVC version or Assembly version of `Microsoft.AspNetCore.SignalR` 
- Your SignalR Client SDK version

**Comment by vicancy** [comment]
`reconnect` `404` can happen when the connection no longer exists. please see https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#reconnect_404 for detailed explanation. If client implemented "reconnect" when connection drops, the connection can come back after 3 times of `reconnect`.

**Comment by g7prakash** [comment]
> `reconnect` `404` can happen when the connection no longer exists. please see https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#reconnect_404 for detailed explanation. If client implemented "reconnect" when connection drops, the connection can come back after 3 times of `reconnect`.

I do the same, in my application,
This occurs while we hold a page for a hour or mare than it, 
i see in network tab

![image](https://user-images.githubusercontent.com/29399989/87296002-b6d28a80-c523-11ea-9720-8ddba3a4d749.png)

Could you please brief me and help me out from the same, 
thanks in advance

**Comment by vicancy** [comment]
If it is always happening after one hour, it is probably caused by token expiration, please check here for details: https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#401_unauthorized_returned_for_client_requests

**Comment by g7prakash** [comment]
@vicancy 
When we click on any link we get first, have you ever get this type of error

https://dummy.service.signalr.net/aspnetclient/abort?transport=webSockets&clientProtocol=2.1&_=1594641185423&asrs_request_id=MJ%2FhZ%2BsCAAA%3D&asrs.op=%2Fsignalr&connectionToken=x6SJFw8ugQaGG6jkBQqwnwdf1ea6611&connectionData=%5B%7B%22name%22%3A%22myhub%22%7D%5D

status : cancelled

404 error occurs after a time, we will go for that next,
Thanks in advance for helping me

**Comment by vicancy** [comment]
`abort` canceled is the client logic that it cancels the request when it finds out that the connection is already disconnected and there is no need to send out the `abort` request.

What is the very first error when the connection is stopped? For example, inside the WebSocket frame, what is the last frame when the connection closes?

**Comment by vicancy** [comment]
Here are the possible 404 reasons: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-howto-troubleshoot-guide#404-returned-for-client-requests
