### ISSUE TITLE
Microsoft.Azure.SignalR.Management dependency on Newtonsoft System.IO.FileLoadException

### ISSUE THREAD

**Issue by sukesh-ak** [Azure/azure-signalr#965]
### Describe the bug
Azure SignalR Management sample fails with System.IO.FileLoadException while running on .NET Core 3.1

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
```
**Any reason why Newtonsoft.Json is still being used instead of System.Text.Json?**

![signalr-newtonsoft](https://user-images.githubusercontent.com/53081362/87428313-ca532380-c5ff-11ea-8070-1aa45e3e5b80.png)

### To Reproduce
[Link for the sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/Management/MessagePublisher)

### Exceptions (if any)
System.IO.FileLoadException

### Further technical details
Version details in the screenshot attached.
- Your Azure SignalR SDK version
- Your Server ASPNETCORE version or Assembly version of `Microsoft.AspNetCore.SignalR` 
- Your SignalR Client SDK version

**Comment by wanlwanl** [comment]
Hi @sukesh-ak , I can run the message publisher with `<TargetFramework>netcoreapp3.1</TargetFramework>`.
My dotnet version is 5.0.100-preview.5.20279.10. Could you tell me yours?
When you get this problem? On building the sample or running some function? Could you provide more details?

**Comment by wanlwanl** [comment]
My Newtonsoft.Json is v11.0.2, have you install other packages that reference Newtonsoft.Json 10.0.1 whichi cause the problem.

**Comment by sukesh-ak** [comment]
I am getting this error while running the app on .NET Core 3.1 and not on compile time.
If I add the NewtonSoft.Json package manually added to the project it works.

I would guess its time to move to System.Text.Json since that's the official route for .NET APIs

**Comment by wanlwanl** [comment]
I used the same version of Management SDK. But the inside Newtonsoft.Json is v11.0.2. I neve ad Newtonsoft.Json or other packages manually. 

@vicancy About System.Text.Json, what do you think?

**Comment by sukesh-ak** [comment]
If you look at the screenshot in the original post above the dependency is coming from
System.Identitymodel.Tokens.Jwt which has a version of 5.5.0
but the latest version on NuGet of Jwt is 6.7.1.

**Comment by vicancy** [comment]
> move to System.Text.Json
 
> the entire hierarchy of dependency needs an update for .NET Core 3.1 

agree to both
