### ISSUE TITLE
Azure SignalR - Failed to ping server.  Server responded with status code 401, stopping the connection

### ISSUE THREAD

**Issue by g7prakash** [Azure/azure-signalr#968]
### Describe the bug
Azure SignalR - Failed to ping server.  Server responded with status code 401, stopping the connection
Azure SignalR - Couldn't reconnect within the configured timeout of 5000 ms, disconnecting. -SL- 41966
Azure SignalR - Error during negotiation request.
We are getting on Production Server and a multilanguage site in staging and Production both

same code is deployed on English Staging and error is not occured
I dont have use long-pooling in my code

`public void ConfigureAuth(IAppBuilder app)

{
    GlobalHost.Configuration.ConnectionTimeout = TimeSpan.FromSeconds(60);
    GlobalHost.Configuration.DisconnectTimeout = TimeSpan.FromSeconds(30);
    GlobalHost.Configuration.KeepAlive = TimeSpan.FromSeconds(10);
    GlobalHost.Configuration.DefaultMessageBufferSize = 500;
    app.CreatePerOwinContext(ApplicationDbContext.Create);
    app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
    app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);
    app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
        LoginPath = new PathString("/Main/Login"),
        CookieName = typeof(Startup).FullName,
        Provider = new CookieAuthenticationProvider
        {
            OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser>(
                validateInterval: TimeSpan.FromMinutes(30),
                regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
        }
    });            
    app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
    app.UseTwoFactorSignInCookie(DefaultAuthenticationTypes.TwoFactorCookie, TimeSpan.FromMinutes(5));
    app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);
    app.MapAzureSignalR(this.GetType().FullName);
    app.Map("/DetailedErrors", map =>
    {
        HubConfiguration hubConfiguration = new HubConfiguration
        {
            EnableDetailedErrors = true,
            EnableJavaScriptProxies = false
        };
        map.MapAzureSignalR(this.GetType().FullName, hubConfiguration);
    });
}`

`$(document).ready(function () {

    // Defining a connection to the server hub.
    var myHub = $.connection.myHub;

    // Setting logging to true so that we can see whats happening in the browser console log. [OPTIONAL]
    window.hubReady = $.connection.hub.logging = true;

    // Start the hub
    window.hubReady = $.connection.hub.start();
    
    // Client method to broadcast the message
    myHub.client.hello = function (message) {
        if ($.connection.hub.lastError)
        {
            $.connection.hub.start();
        }`

`$.connection.hub.disconnected(function () {
    if ($.connection.hub.lastError) {
        $.post(WebSiteUrl() + "/Com/SignalErrorWrite", { errorMessage: $.connection.hub.lastError.message }, function (data, status) {
            if (data == 'Success') {
                setTimeout(function () {
                    $.connection.hub.start();
                }, 5000);// Restart connection after 5 seconds.
            }
            else if (data == 'UserNotLogin') {
            }
            else if (data == '') {
            }
        })
    }
});`
We will close this issue if:
- the repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
- if we will not be able to repro the behavior you're reporting
-->

### Further technical details
-Your Azure SignalR SDK version - 2.4.1.0
-Your Server ASP.NET MVC version or Assembly version of Microsoft.AspNetCore.SignalR
-Your SignalR Client SDK version

**Comment by vicancy** [comment]
401 is expected when 1 hour later JWT token's lifetime 1 hour expires. There is an `AccessTokenLifeTime` option https://github.com/Azure/azure-signalr/blob/dev/docs/use-signalr-service.md#accesstokenlifetime to extend the token life but we don't encourage doing that for security concerns, we suggest client re-negotiate with the server and reconnect to the service with a new token. Details please see  https://github.com/Azure/azure-signalr/blob/dev/docs/tsg.md#401_unauthorized_returned_for_client_requests

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have concerns about the issue.
