### ISSUE TITLE
Cannot get the userId in Hub in SignalR core

### ISSUE THREAD

**Issue by HaythamBS** [Azure/azure-signalr#982]
I added SignalR Core to my Asp.net Core 3 Web Api project an this web api communicates with my Android application , I am trying to send message back and forth between two client , and I don't want to use the connection_Id because when a user leaves an activity where the connection is made, the connection is lost and the connection_Id will change if the client reconnects , and in that case the communication between the two users will be lost , and the second user will be unable to communicate with the first user because the other's connectionId has changed , so I want to use the userName or the userId to send messages between users

PS : When I send message to all clients , or with connectionId the code works fine.

PS : I am using identity and JWT to authenticate and authorize users in my app.So I have this method In my Hub :

```
public async Task sendOffer(DeliveryOffer offer)
        {

            string name= Context.User.Identity.Name;
            Notifications notification = new Notifications();
            notification.deliveryOffer = offer;
            await Clients.User(name).SendAsync("sendOfferToClient", notification);
        }
```
and this is mycustomerUserIdProvider :

```
public class CustomUserIdProvider : IUserIdProvider
    {
        public virtual string GetUserId(HubConnectionContext connection)
        {

            return connection.User.Identity.Name;
        }
    }
```
In my startup class inside the configure method I addded signalR after adding Authentication like below :

```
app.UseAuthentication();
            app.UseAuthorization();
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSignalR(routes => {
                routes.MapHub<NotificationHub>("/myHub");
            });

and inside my configureServices method :

            services.AddSignalR();
            services.AddSingleton<IUserIdProvider, CustomUserProvider>();
```
But this instruction here always returns null:

string id = Context.User.Identity.Name; // Always null

And this is the method that generates the Token in my controller :

```
private TokenResponse generateToken(User user)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.ASCII.GetBytes(_jwtSettings.Secret);
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new System.Security.Claims.ClaimsIdentity(new[]
                {
                                new Claim(JwtRegisteredClaimNames.Aud, user.Email),
                                new Claim(JwtRegisteredClaimNames.Sub, user.Email),
                                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                                new Claim(JwtRegisteredClaimNames.Email, user.Email),
                                new Claim(JwtRegisteredClaimNames.UniqueName, user.UserName)
                            }),
                Expires = DateTime.UtcNow.AddMinutes(10),
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);

            TokenResponse response = new TokenResponse();
            response.token = tokenHandler.WriteToken(token);
            return response;
        }
```

**Comment by vicancy** [comment]
What insides `CustomUserProvider`? When `CustomUserProvider` is provided, `Context.User.Identity.Name` is the value returned from `CustomUserProvider`

**Comment by vicancy** [comment]
Please feel free to reopen it if you still have any concerns about it.
