### ISSUE TITLE
Visual Studio build error -  current .NET SDK does not support targeting .NET Core 2.1

### ISSUE THREAD

**Issue by felipecruz91** [Azure/azure-signalr#99]
Hi there!

I'd like to start contributing to this project so I have followed the [Developer Getting Started](https://github.com/Azure/azure-signalr#developer-getting-started) section.

The project seems to have been built correctly via the `build.cmd` command (click [here ](https://gist.github.com/felipecruz91/366407c7f64b7c415946b16538c64525) to see the output for more information.)

However, when building the `AzureSignalR` solution in Visual Studio version 15.7.1, I get the following error:

`The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.`

The current dotnet SDK version installed in my computer is 2.1.200.

Thank you!

**Comment by xscript** [comment]
Thanks @felipecruz91 for reporting the issue.
`build.cmd` will install the required SDK for you. You need to add the path of that SDK to the `PATH` environment variable so that Visual Studio can use it.
By default, it is installed at `c:\Users\<username>\.dotnet\x64`

**Comment by davidfowl** [comment]
We should be able to switch to the official 2.1 builds now.

**Comment by felipecruz91** [comment]
Thanks @xscript - After having added the env. variable to the `PATH`, the project now builds successfully.

However, when launching the `ChatSample` project locally, the following runtime exception is thrown:

`An unhandled exception of type 'System.IO.FileLoadException' occurred in System.Private.CoreLib.dll
Could not load file or assembly 'System.Memory, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`
